### ISSUE TITLE
Unable to Login in caldera web interface

### ISSUE THREAD

**Issue by alisp7** [mitre/caldera#1005]
hi
according to your offline caldera installation instruction i,ve installed the caldera and i could connect to its web user interface but default username and password doesn't work..??
![Screenshot from 2020-01-09 07-13-47](https://user-images.githubusercontent.com/35430014/72036311-a957f180-32af-11ea-8ff7-b00b88cc4b84.png)

**Comment by wbooth** [comment]
Try admin as the user name and admin as the password. You may need to clear your cache.

Alternatively you can bypass the login by using localhost instead of 0.0.0.0
