### ISSUE TITLE
Payloads are not deleted after completing operation

### ISSUE THREAD

**Issue by wietze** [mitre/caldera#1015]
The [ability wiki page](https://github.com/mitre/caldera/wiki/What-is-an-ability) states:
> Upon an operation completing, all payload files will be removed from the client (agent) computers.

This currently doesn't work for me, I have to delete them manually.

**Comment by privateducky** [comment]
Yeah-- that looks like a bug. We'll fix that.

**Comment by khyberspache** [comment]
https://github.com/mitre/sandcat/pull/280

**Comment by privateducky** [comment]
fixed in this PR: https://github.com/mitre/caldera/pull/1385/files
