### ISSUE TITLE
Run different phases on different agents

### ISSUE THREAD

**Issue by perra22** [mitre/caldera#1042]
Hi,
Is it possible to run phases of the same adversary on different agents?
Thanks!

**Comment by privateducky** [comment]
Do you mean run only phase 1 on one agent and only phase 2 on another agent? Or am I misunderstanding?

**Comment by privateducky** [comment]
If that’s what you mean - then no, that’s not currently supported. You would need to create 2 adversaries to do that... or... you could use our new potential links functionality. 

To use this, run an operation without selecting an adversary, and selecting the option to keep the operation open for max time. Then, while the operation is running, click ‘potential links’ to add specific abilities to any agent.

**Comment by perra22** [comment]
Yes, is that what I mean. I'll try links functionality.
Thanks for the support!
