### ISSUE TITLE
Server.py error in operation_svc ?

### ISSUE THREAD

**Issue by riccardosl** [mitre/caldera#105]
Hello friends, 
I'm trying to get up and running caldera server, installation was done on an Ubuntu Server 18.10 with mongodb: db version v3.6.3

The setup procedure went quite well until the last step, I have these messages and I'm not sure how to proceed :

1st attempt:
python3 server.py -E local
Traceback (most recent call last):
  File "server.py", line 87, in <module>
    operation_svc = OperationService(data_svc=data_svc, utility_svc=utility_svc, planner=config['planner'])
  File "/home/caldera/caldera/app/service/operation_svc.py", line 16, in __init__
    planning_module = import_module(planner)
  File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 941, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'plugins.stockpile.app'

2nd attempt:
python server.py -E local
  File "server.py", line 30
    async def background_tasks(app):

Is there an issue with some dependencies ?
Thanks a lot!
R

**Comment by privateducky** [comment]
Possibly- it looks like it’s retiring out while loading the planner, which is referenced in local.yml. Two things: 
1. Ensure you have a file called plugins/stockpile/app/sequential.py
2. If yes, ensure the planner in conf/local.yml references the full path to it as: plugins.stockpile.app.sequential

If these are good, my next thought would be your python path needs to include the root of caldera. We try to do this automatically at line 83 in server.py- but it may not apply to all distros.

Let me know if this does or doesn’t work!

**Comment by riccardosl** [comment]
> Possibly- it looks like it’s erroring out while loading the planner, which is referenced in local.yml. Two things:
> 
> 1. Ensure you have a file called plugins/stockpile/app/sequential.py
> 2. If yes, ensure the planner in conf/local.yml references the full path to it as: plugins.stockpile.app.sequential
> 
> If these are good, my next thought would be your python path needs to include the root of caldera. We try to do this automatically at line 83 in server.py- but it may not apply to all distros.
> 
> Let me know if this does or doesn’t work!

Good point, the folder stockpile seems empty even if I did
git clone https://github.com/mitre/caldera

**Comment by privateducky** [comment]
Ah yes, make sure you clone recursive. That should do the trick.

**Comment by privateducky** [comment]
@riccardosl feel free to reopen if that did not work. here's the full command you want to do:
git clone git@github.com:mitre/caldera.git --recursive

**Comment by riccardosl** [comment]
Thank you, it didn't work the recursive command for some reason give some errors, but I managed to do it manually in each plugin folder to get the file and seems starting the gui correctly.

**Comment by privateducky** [comment]
great! feel free to shoot me the error messages if you want a second set of eyes. offhand, i'm guessing it would be due to http vs ssh cloning (credentials cached vs needing to be plugged in for each repo).
