### ISSUE TITLE
server error (TypeError: 'int' object is not subscriptable)

### ISSUE THREAD

**Issue by MikeLim7** [mitre/caldera#110]
Unable to start server in Ubuntu LTS 18.04 with Caldera 2.0.0, 
Python 3.6.7 and MongoDB 3.6.3

`python3 ./server.py  -E local`
```
Traceback (most recent call last):
  File "./server.py", line 105, in <module>
    main(services=services, host=config['host'], port=config['port'], terminal_port=config['terminal_port'], users=config['users'])
  File "./server.py", line 64, in main
    loop.run_until_complete(init(host, port, services, users))
  File "/usr/lib/python3.6/asyncio/base_events.py", line 473, in run_until_complete
    return future.result()
  File "./server.py", line 56, in init
    await attach_plugins(app, services)
  File "./server.py", line 39, in attach_plugins
    await plugin(app, services)
  File "/root/caldera/plugins/stockpile/hook.py", line 10, in initialize
    abilities='plugins/stockpile/abilities')
  File "/root/caldera/app/service/data_svc.py", line 18, in reload_database
    await self.load_adversaries(config=adversaries)
  File "/root/caldera/app/service/data_svc.py", line 25, in load_adversaries
    await self.create_adversary(**adv)
  File "/root/caldera/app/service/data_svc.py", line 51, in create_adversary
    a = (dict(adversary_id=identifier, phase=ability['phase'], ability_id=ability['id']))
TypeError: 'int' object is not subscriptable
```

The plugin folders (stockpile, adversary, chain, gui, sandcat) are populated manually via git clone as I was unable to git clone recursively.

If I commented out stockpile in conf/local.yml, I am able to start but this does not seem correct

**Comment by privateducky** [comment]
@MikeLim7 the plugins are tied to the core code through commit hashes (git submodules). if you manually cloned the git repositories, you've likely got a mismatch between the core code and the plugin versions. to solve this, you have two good options:

1) Recursively clone. This is by far the easiest way. What errors did you receive attempting to clone recursively? Most common would be authentication-related issues: if you add a public SSH key to your GitHub profile, cloning via SSH should work fine (recommended). If you clone via HTTPS, you'll likely need to cache your GIT credentials before doing the recursive clone. 
2) If you want to use the 2.0.0 version, go to the GitHub releases page and download the ZIP, which will contain the full (core + plugins) code for the given version.

**Comment by MikeLim7** [comment]
@privateducky, will try recursively clone again.  

> 2. If you want to use the 2.0.0 version, go to the GitHub releases page
Did that. Both ZIP and tar archive have empty plugin folders.

**Comment by MikeLim7** [comment]
@privateducky, finally got recursive clone working and it works now.
