### ISSUE TITLE
caldera 2.5.1 - auto-installer.sh doesn't detect kali

### ISSUE THREAD

**Issue by JohnARivers** [mitre/caldera#1101]
Minor issue, the auto-installer.sh can't detect the Kali operating system. Potential fixes include adding the following 2 lines of code at/near line 137 (see below) or allowing user to specify the operating system through a command-line option. I appreciate your team's hard work, and I hope this is helpful.

elif [[ "$(lsb_release -d)" == *"Kali"* ]]; then
  ubuntu

**Comment by privateducky** [comment]
thanks!

if you submit this change as a PR, I'll merge.

**Comment by khyberspache** [comment]
PR in https://github.com/mitre/caldera/pull/1140.
