### ISSUE TITLE
server.py

### ISSUE THREAD

**Issue by rayhernandez** [mitre/caldera#122]
I'm trying to deploy Caldera with Docker and I get this error:

```
Traceback (most recent call last):
  File "server.py", line 98, in <module>
    operation_svc = OperationService(data_svc=data_svc, utility_svc=utility_svc, planner=config['planner'])
  File "/usr/src/app/app/service/operation_svc.py", line 15, in __init__
    self.log = Logger('operation')
  File "/usr/src/app/app/utility/logger.py", line 18, in __init__
    handler = logging.FileHandler('%s/%s' % ('.logs', name))
  File "/usr/local/lib/python3.7/logging/__init__.py", line 1092, in __init__
    StreamHandler.__init__(self, self._open())
  File "/usr/local/lib/python3.7/logging/__init__.py", line 1121, in _open
    return open(self.baseFilename, self.mode, encoding=self.encoding)
PermissionError: [Errno 13] Permission denied: '/usr/src/app/.logs/operation'
```

**Comment by scottctaylor12** [comment]
@rayhernandez can you verify what user is running the docker daemon on your system? When starting up CALDERA, a log file is created in the `.logs/` directory which means the user running the docker daemon will need permissions to create a file. 
In Linux, this can be verified by running `ps -edf` and checking what user is running the docker daemon. Then go to the local caldera directory and run `ls -lah` and ensure the files and directories are owned by the user running the docker daemon.

**Comment by privateducky** [comment]
closing this ticket as it's a local deployment issue. when deploying caldera (via docker or normally), the user will need permissions to create directories inside the caldera source code root.
