### ISSUE TITLE
Evals plugin is not supported in version 2.5.1

### ISSUE THREAD

**Issue by nevinhappy** [mitre/caldera#1279]
I get this project (https://github.com/mitre/evals.git ), and try to install it to version 2.5.1. From the errors I seen, it not supported in this version . 
So Eval will be shipped to this new version ?  or Eval should install to which version of caldera   ?

**Comment by connormagee** [comment]
Yup that repository has been archived and the plugin now lives at [Evals Plugin](https://github.com/mitre-attack/evals_caldera)
The plugin is currently being refactored to account for ATT&CK Evaluations Round 2 and will be updated when the results are finalized!

**Comment by nevinhappy** [comment]
Thank you for your reply. And Do you know which tag of Caldera will match the archived Evals ?

**Comment by privateducky** [comment]
@wbooth do you know? I want to say 2.4

**Comment by wbooth** [comment]
No idea, next best would thing would be to match up dates.

**Comment by nevinhappy** [comment]
From the code , I think 2.4.0 is not right .  2.3.X should be matched.

**Comment by privateducky** [comment]
yep, i see 2.3.2 in my notes as the caldera version we tied to the evals plugin. 

we are currently working on a way to tag non-default plugins (like Evals) to the version of the core code we developed it against. hopefully, you'll see this out in the near future.
