### ISSUE TITLE
RestAPI is not working properly from a remote host

### ISSUE THREAD

**Issue by super0xbad1dea** [mitre/caldera#1319]
Hey guys,

When you're on the Caldera server and run `curl -X POST http://localhost/api/rest -d '{"index":"operations"}'`, you get all operations in json - Perfect.

But when you replace localhost with the server IP and add your API key to the header, the result is `[]`

In addition, regarding to your API documentation. POST and operations (s at the end) should not exist regarding to your rest_api.py. But you get only results when you use operations. 
```
POST=dict(
                    operation_report=lambda d: self.rest_svc.display_operation_report(d),
                    result=lambda d: self.rest_svc.display_result(d),
                    contact=lambda d: self.rest_svc.download_contact_report(d),
                    configuration=lambda d: self.rest_svc.update_config(d),
                    link=lambda d: self.rest_svc.get_potential_links(**d),
                    operation=lambda d: self.rest_svc.update_operation(**d)
                )
```

**Comment by privateducky** [comment]
on the former, can you post your actual cURL request?

on the latter, i know it looks like "operations" wouldn't work-- but it's somewhat hidden. the key are the lines just below what you posted:
```
            if index not in options[request.method]:
                search = {**data, **access}
                return web.json_response(await self.rest_svc.display_objects(index, search))
```
Here, if there are no matches found (index=operations), we will run the display_objects by default. in here, we capture the queries that do basic search on c_object types (those in the app/objects directory, such as operations). Our front-end HTML pages (or, really, the JavaScript in them) uses this to retrieve adversaries, abilities, sources, operations, etc. 

I plan on extending our REST API documentation to put cURL examples for each possible REST request. It may be a few days before I get cycles for this-- so feel free to propose pull requests with these changes (all docs are in the docs/ directory) and I can review them quickly.

**Comment by super0xbad1dea** [comment]
Just for the correctness: When I use this command on my local caldera installation, I get all operations: `curl -X POST http://localhost:8888/api/rest -d '{"index":"operation"}'`
When I use the following command from a remote host, I get just the result `[]`:
curl -X POST -H "KEY:ADMIN123" http://192.168.92.135:8888/api/rest -d '{"index":"operations"}'

During both commands no error was shown in the console. So, where do you differentiate between a local and a remote connection?

**Comment by super0xbad1dea** [comment]
We've figured out when you do it from a remote host, curl needs the cookie API_SESSION. With this cookie it's possible to query the API from a remote host.

**Comment by khyberspache** [comment]
It would make sense that you need both the API_SESSION cookie and the KEY header value populated because we are using two different checks:
```Python
    async def check_permissions(self, group, request):
        """
        Check if a request is allowed based on the user permissions
        :param request:
        :return: None
        """
        try:
            if request.headers.get('KEY') == self.get_config('api_key'):
                return True
            elif self.bypass in request.host:
                return True
            await check_permission(request, group)
        except (HTTPUnauthorized, HTTPForbidden):
            raise web.HTTPFound('/login')
```
That is function our authorization decorator uses which checks against the header value and...
```Python
    async def apply(self, app, users):
        """
        Set up security on server boot
        :param app:
        :param users:
        :return: None
        """
        for group, u in users.items():
            self.log.debug('Created authentication group: %s' % group)
            for k, v in u.items():
                self.user_map[k] = self.User(k, v, (group, 'app'), )
        app.user_map = self.user_map
        fernet_key = fernet.Fernet.generate_key()
        secret_key = base64.urlsafe_b64decode(fernet_key)
        storage = EncryptedCookieStorage(secret_key, cookie_name='API_SESSION')
        setup_session(app, storage)
        policy = SessionIdentityPolicy()
        setup_security(app, policy, DictionaryAuthorizationPolicy(self.user_map))
```
that is where we set up aiohttp_security.

This isn't very well documented and we probably need to fix this so that the KEY can actually establish sessions without the API_SESSION cookie set.

**Comment by privateducky** [comment]
Ah- can someone propose a change to our documentation for this?

**Comment by khyberspache** [comment]
I think this was actually a permissions bug from the cutover to ACCESS based roles.

Think I fixed the issue in this PR:
https://github.com/mitre/caldera/pull/1331

**Comment by khyberspache** [comment]
@ super0xbad1dea I merged the fix (I think) on master.  If you try the API on master, you should be able to query w/o API_SESSION being set

**Comment by privateducky** [comment]
ah-- that's interesting. thanks.
