### ISSUE TITLE
Enable Atomic Red Team

### ISSUE THREAD

**Issue by gregkcarson** [mitre/caldera#1323]
I am trying to enable the Atomic plugin but during server start I see the following error:
Error enabling plugin=atomic, Command '['git', 'clone', '--depth', '1', 'https://github.com/redcanaryco/atomic-red-team.git', 'plugins/atomic/atomic-red-team/']' returned non-zero exit status 128.

Any ideas? Could this be SSL/Proxy related? I'm not sure what that exit code means or where to find out.

**Comment by privateducky** [comment]
Weird error code for sure. Is git installed on you caldera computer? What operating system are you using?

**Comment by privateducky** [comment]
And which python3 version?

**Comment by gregkcarson** [comment]
Python 3.7.6
Git 2.24.1

**Comment by gregkcarson** [comment]
During initial install I had SSL issues and had to run:
GIT_SSL_NO_VERIFY=true git clone --recursive --branch master https://www.github.com/mitre/caldera

This resulted in a 100% successful install but I'm thinking this status code 128 must also be SSL Related? Any idea what file I should modify to include a SSL bypass in the git command that pulls atomic down?

**Comment by khyberspache** [comment]
Are you trying to install on a corporate network or something with SSL Introspection & a proxy? That doesn't seem like a "caldera bug"

**Comment by gregkcarson** [comment]
I didn't say it was a Caldera bug - the initial issue is an odd error code that I was hoping someone might have some insight into. SSL issue is just speculation on my part.

**Comment by gregkcarson** [comment]
I'm going to play with https://github.com/mitre/atomic/blob/master/hook.py and see if I can resolve the issue.

**Comment by gregkcarson** [comment]
repo_dir = 'plugins/atomic/atomic-red-team/'
    if not os.path.exists(repo_dir) or not os.listdir(repo_dir):
        repo_url = 'https://github.com/redcanaryco/atomic-red-team.git'


This allows you to clone the repo and load the atomics locally. I did so and I now have them ingested so I think we can close this issue.
