### ISSUE TITLE
Operation Continuation Question

### ISSUE THREAD

**Issue by jbooz1** [mitre/caldera#1324]
When a new Agent is spawned in the middle of an operation, should the phases start over on that agent? 
For example a simple operation could enumerate all hosts running SSH, 
Phase 1: scan for IPs
Phase 2: start new agent over SSH

In this case, it would be beneficial for the new agent to scan for IPs in the case that it can route to subnets that previous agents could not. The behavior that I am seeing, the operation will stop after 1 iteration because no new facts can be used.   However, in my opinion, the operation should continue because there are new agents which have not executed all parts of the operation yet.

For more information, I am working off of release version 2.3.2. I didn't see this issue addressed in any of the updates.

I would like to make the change, so can you point me in the direction of where I should make the change so that the operation is run by all agents (even those that come into the operation halfway)?

**Comment by privateducky** [comment]
You are right in what we want to happen—what version of code are you using? We made a change the other day that may solve this but I haven’t tested specifically.

**Comment by privateducky** [comment]
If it’s still occurring, the fix would be in the c_operation.py module, specifically in the run function. I’d love to see a proposed solution!

**Comment by jbooz1** [comment]
I am working off an older version. Version 2.3. 
I just saw that you have made some major changes since I started looking a while ago. 
Unfortunately I am unable to update the version I am working with at this time. 

I got around this issue last night by making some changes to both the old operation_svc.py and the sequential planner. 
To summarize my changes:
- The operation gets a list of the current hosts (operation['host_group'] at the beginning of the operation 
- The operation now passes that list of hosts to the planner for each phase. 
- Before the operation ends, the planner will check if the list of hosts "now" (after all phases) is bigger than the list of hosts from the start of the operation. 
- If there are hosts that exist "now" that did not exist at the beginning, run the operation phases again only on those new hosts. 
- In this way, I keep a list of hosts that have already performed the operation, and a list of hosts who have not yet. 

I know this way of doing things is hacky at best, but it is a workaround for the moment :)

**Comment by privateducky** [comment]
hey-- if it works! i do believe this was resolved in the later version(s) of caldera. we made a big jump from 2.5 -> 2.6, with a lot of optimizations built in. same functional code but lots of improvements to the structure to help us grow more stable
