### ISSUE TITLE
Configuration of context path

### ISSUE THREAD

**Issue by com98** [mitre/caldera#1349]
Hi guys!

Just a little feature request from my side. Currently your configuration does not support specifying a context path (e.g. example.com/caldera) in order to be able to run Caldera in a subdirectory or behind a reverse proxy on the same domain. The paths in your templates are also specified as hard-coded absolute paths, therefore I'm not able to use Caldera within a sub path using nginx as reverse proxy at the moment. IMHO it would definetely make sense to add that feature :blush: 

Thanks!

**Comment by khyberspache** [comment]
We could probably add this.  I'll make as enhancement and try to add it if I have some free time this weekend...

**Comment by privateducky** [comment]
@unkempthenry didn't we post a doc page around this somewhere...? or support this case at some point in time?

**Comment by unkempthenry** [comment]
I think that this would be a great feature to have.  We did support it for a couple months, but it was introduced before the 2.0 release.   Basically, we need to change any absolute paths in the front-end to include the prefix that the proxy prepends to the path.  Finding out the right prefix can be done in a couple ways:

1) set the prefix in the caldera config file, and insert it when the pages are rendered (like @com98 suggested) 
2) have the reverse proxy tell us what the path should be in a header and use that when rendering responses
3) The purely front-end solution I came up with before where the web app inspects the path when the app loads, saves it, and uses it for future requests.  I'll send you and Alex a link to that code, but I think (1) is probably the best way to go.

**Comment by tomac** [comment]
+1 for this. I'd suggest the 1st option, where we can set up the prefix in the caldera config file. I've been able to have caldera running behind an nginx proxy in the /caldera directory playing with the nginx config, but this feature would make my life easier.

**Comment by khyberspache** [comment]
Bumping as this issue isn't stale.

**Comment by privateducky** [comment]
this is a feature add that isn't on our immediate roadmap. If anyone wants to do this, we'll happily include the PR but we're unlikely to circle on this in the near term
