### ISSUE TITLE
JSON Profiles from attack.mitre.org/groups don't display abilities in Adversary view

### ISSUE THREAD

**Issue by serracloud** [mitre/caldera#1364]
I am trying to troubleshoot why Caldera won't load abilities from the threat groups located on https://attack.mitre.org/groups. This worked in 2.5.1, but I don't know where to start troubleshooting why the abilities won't load in 2.6.3.

I tried re-downloading and installing the JSON files but that creates duplicate entries which i cannot seem to remove from the Adversary or Compass drop downs. It looks like these files are converten into yml files but not sure where. Happy to send logs & screenshots if someone can point me in the right direction. 

Pic with Super Spy shows a profile with abilities properly loading. 
Other Pics show the JSONs loaded and what they all look like when selected.

![Default Abilities Loading](https://user-images.githubusercontent.com/27729001/76169914-0f93b000-614b-11ea-9b69-a75817ce6bcf.JPG)
![Empty Adversary](https://user-images.githubusercontent.com/27729001/76169915-0f93b000-614b-11ea-9d23-608bcb2353c2.JPG)
![Loaded Menus](https://user-images.githubusercontent.com/27729001/76169916-102c4680-614b-11ea-9286-b92da39d1f76.JPG)

**Comment by serracloud** [comment]
It looks like when I upload the JSON that has all the technique numbers, these never get translated into the generated yml files that live in ../caldera/data/adversaries/. The phases are blank when I open the ymls. I tried browsing the code to find the file that's supposed to be doing this but no luck at the time of this comment.

**Comment by khyberspache** [comment]
We are taking a look at this today

**Comment by khyberspache** [comment]
@wbooth

**Comment by wbooth** [comment]
@serracloud looks like there were some breaking changes to the plugin recently. I'll take a look and clean them up. In the mean time-- check that the score for each technique is a positive number.

**Comment by serracloud** [comment]
> @serracloud looks like there were some breaking changes to the plugin recently. I'll take a look and clean them up. In the mean time-- check that the score for each technique is a positive number.

Thanks @wbooth. I can confirm the scores are definitely 1 in absolute value.

**Comment by privateducky** [comment]
@wbooth closing this issue as your fix should have solved this. re-open if the problem persists.

**Comment by serracloud** [comment]
Took me a while to get to this, but the updates did not fix the issue. Let me know if you would like a new ticket number or if you prefer to reopen this.
