### ISSUE TITLE
Name Reports after Operation Name

### ISSUE THREAD

**Issue by serracloud** [mitre/caldera#1373]
Enhancement Request: Change report names of an operation to the name of your Operation as opposed to naming them all operation_report. 

![Caldera Improvements](https://user-images.githubusercontent.com/27729001/76350497-e05f7900-62d9-11ea-8729-b1679f8ee898.JPG)

**Comment by khyberspache** [comment]
This has been bothering me for a while, I'll modify it today or tomorrow

**Comment by privateducky** [comment]
because i couldn't figure out what was taking @khyberspache so long ;), i went ahead and did this:
https://github.com/mitre/caldera/pull/1377
