### ISSUE TITLE
Red Canary Atomic Tests not processing

### ISSUE THREAD

**Issue by xenoscr** [mitre/caldera#1374]
I have cloned release 2.6.4 into a fresh directory and am trying to enable the "atomic" plugin but it is not processing tests properly. I added some debug logging and managed to track it down two issues:

1. Processing command and cleanup_commands, if they are blank seems to cause issues. Should add a check to see if the keys exist before processing them.
2. The call to the Abilities object, where Varation() is called throws 'NoneType' errors when attempting to iterate the results.

Without modification the logging simply states:
'Ingested 0 abilities from Atomic plugin'

**Comment by privateducky** [comment]
1. we're currently not loading all atomic tests but just those which are "cleanly" imported. this is around ~130 tests i believe. we'll be working on writing exceptions around the other tests to import them, like you point out, things like missing commands don't import. this will be a little lower on our priority list though, as we have a good bulk of atomic tests ported in to work with for the time being. but if you append to this code, i'll happily look at a PR :) 

2. yesterday i merged in a fix to the variations bug. here's the issue that was opened around that: https://github.com/mitre/atomic/issues/5. I don't believe this is in the 2.6.4 release that we just cut, so it'll get into the next one.
