### ISSUE TITLE
Multiple Adversary Profiles - multiple saves & no obvious Delete option

### ISSUE THREAD

**Issue by serracloud** [mitre/caldera#1375]
This ticket has two issues that I've identified. Let me know if you want me to open a separate ticket for it. 

In 2.6.3, if I want to adjust an adversary profile with modified abilities, a new profile is generated in the drop-down menu with the same name after I save. This adds to confusion because I now have multiple adversary profiles with the same name that does not populate the correct ability list that I am trying to run in the operations menu. 

In order to reduce confusion, I want to delete a duplicate adversary in the drop down, but there is no obvious method to do so. 

Please reference the pic to see 3 versions of my custom Going Loud in the profile drop-down menu. Each has a separate set of abilities and I have to click on each one in the adversary menu to ensure I am running the right set of abilities which is not conducive to rapid testing.

![MultipleAdversaryProfs](https://user-images.githubusercontent.com/27729001/76457081-1bc77980-63a6-11ea-9abe-5a057567afcf.JPG)

**Comment by privateducky** [comment]
let's look at the first part:

if you want to update an existing adversary, you select it from the drop-down, add/delete abilities then click save. this should overwrite the existing YML file for that adversary on the backend. You can validate this by checking the adversary profile in plugins/stockpile/data/adversaries/*. The contents should be different after you updated the profile from the GUI.

alternatively, if you want to build a new adversary, you would toggle the view/add button so "add" is visible. then you would add your phases/abilities. if you select the same name as an existing adversary, you'll end up with two different adversaries with the same name (which is the process I'm guess you took?). To avoid this, I would simply give your new adversary a different name.

**Comment by privateducky** [comment]
per your 2nd item, i just spent a few min adding a delete adversary button. this will get merged in just a few minutes but here is the PR: https://github.com/mitre/caldera/pull/1376
