### ISSUE TITLE
Docker-Compose Broken

### ISSUE THREAD

**Issue by DigitalAftermath** [mitre/caldera#142]
When using docker compose, everything seems to execute without error, but the WebUI for Caldera in inaccessible despite modifying the respective configuration file. This is on Ubuntu 18.04.

**Comment by scottctaylor12** [comment]
@DigitalAftermath to make the WebUI accessible to the host machine, ensure that the `conf/local.yml` file is configured with the following settings:
```
host: 0.0.0.0
port: 8888
terminal_host: 0.0.0.0
terminal_port: 8880
```
If you are accessing the CALDERA from outside of the host machine, ensure that the host firewall allows port 8888 for the WebUI. 

Also, try deleting and re-cloning the git repository, `git clone https://github.com/mitre/caldera.git --recursive`. Once cloned and with the proper local.yml settings configured, start the container by running `docker-compose up -d` from the root of the caldera directory. To see what is happening at startup, run `docker container logs <container name>` to see the startup logs. 
If you see errors in the logs please post them here.

**Comment by privateducky** [comment]
@scottctaylor12  has the correct answer. to view the UI, you can do so locally using the default 127.0.0.1 address (in the local.yml file). otherwise,  you would need to serve CALDERA on all interfaces (0.0.0.0) to view the GUI on a remote server.
