### ISSUE TITLE
Disabling exfiled files encryption

### ISSUE THREAD

**Issue by xToad** [mitre/caldera#1436]
Hello guys, 

Is there any way do disable exfiled files encryption? I have looked around the documentation and didn't find any answers.
I am able to track the file, however it seems that the file is encrypted. I'm also able to capture the incoming traffic, and reassemble the TCP sequence and the files seems not corrupted.

Thank you.

**Comment by khyberspache** [comment]
Uploaded files aren't encrypted by the core serve unless specifically done so by the ability that is exfiling the data.  Which ability are you using to exile? What file type is it?  zip? tar.gz?

**Comment by mrengstrom** [comment]
currently there is not a way to outright disable encryption, you can set `self.encryptor` to `None` in the code here and run caldera and that should disable all encryption:
https://github.com/mitre/caldera/blob/master/app/service/file_svc.py#L22

we can add an encryption flag into the config if this is a needed feature and use that for controlling the response of `_get_encryptor()`

**Comment by khyberspache** [comment]
Oh would you look at that, @mrengstrom added file encryption back in February! I completely missed that haha

**Comment by xToad** [comment]
I have set the `self.encryptor`  to `None` as pointed out by @mrengstrom. 

```
    def __init__(self):
        self.log = self.add_service('file_svc', self)
        self.data_svc = self.get_service('data_svc')
        self.special_payloads = dict()
        self.encryptor = None
```


However now it seems like the server wont start, showing out this output, when `python server.py` is issued:

```
2020-03-25 14:11:55 DEBUG    Using selector: EpollSelector
Traceback (most recent call last):
  File "server.py", line 88, in <module>
    run_tasks(services=app_svc.get_services())
  File "server.py", line 49, in run_tasks
    loop.run_until_complete(data_svc.restore_state())
  File "/usr/lib/python3.6/asyncio/base_events.py", line 484, in run_until_complete
    return future.result()
  File "/home/toad/caldera/app/service/data_svc.py", line 63, in restore_state
    ram = pickle.loads(store)
_pickle.UnpicklingError: invalid load key, '%'.
```
If you could make this configurable, through the default.yml file, it would be really great.

**Comment by mrengstrom** [comment]
yea, you are going to want to run with the `--fresh` flag, as your prior caldera state was saved as an encrypted object, so the server is having issues re-loading it without the loaded encryption key.
https://github.com/mitre/caldera/blob/master/app/service/data_svc.py#L53

if you need to re-load your prior state and still want to test out not encrypting files that are saved to disk, you can also just edit `_save` and comment out the first two lines (make sure to revert the prior change to `self.encryptor` as we will need it).  This will now never encrypt anything on save, but will allow you to decrypt previously encrypted files with `_read`

And yea, I'll toss up a small PR for the disabling of encryption and a discussion can be had on there as to that.

**Comment by mrengstrom** [comment]
https://github.com/mitre/caldera/pull/1440
