### ISSUE TITLE
Unable to view/search stockpile through UI

### ISSUE THREAD

**Issue by taschultz** [mitre/caldera#1458]
The Stockpile UI does not allow for search/display of abilities. It simply shows stats on how many abilities/adversaries are loaded. Currently, to view abilities one has do some command line wizardry to view contents of the YML files that are descriptively named in the /caldera/plugins/stockpile/data/abilities folders. 

![stockpile](https://user-images.githubusercontent.com/12669524/78078758-6c604000-7370-11ea-9232-7677e9936a7f.jpg)

**Comment by wbooth** [comment]
You should also be able to see abilities through creating an adversary. Might be a good interim solution
