### ISSUE TITLE
Request Documentation to integrate HA Proxy with SSL Plugin

### ISSUE THREAD

**Issue by serracloud** [mitre/caldera#1459]
I have a requirement to ensure all my callbacks from the agent are encrypted, but simply having HA proxy installed is not as straightforward as it should be. Documentation for a quickstart to get the SSL plugin like it should, particularly with non-standard framework configs (custom callback ports) would be helpful for admins who may have never used HAProxy before or are waddling into TLS/SSL administration for the first time.

**Comment by khyberspache** [comment]
It should just work out of the box - what issue did you encounter?

**Comment by khyberspache** [comment]
Side note - we haven't updated SSL in a while so it's possibly things aren't working as intended.

**Comment by privateducky** [comment]
@serracloud I have updated the docs on the SSL plugin README: 

https://github.com/mitre/ssl

In general, you shouldn't have to muck with TLS/SSL or any kind of changes to HAProxy itself. As long as you have HAProxy installed, you can add the SSL plugin to default.yml and it will automatically configure itself for use. 

Let me know if there is any other documentation which would be helpful to add.
