### ISSUE TITLE
[Question] Mock Plugin Enabled: HTTPhandle_heartbeat: Incoming http beacon from

### ISSUE THREAD

**Issue by Cyb3rWard0g** [mitre/caldera#1481]
Good evening Caldera team,

I was testing the Mock plugin using a similar config like the one you guys provide as the default one:

https://github.com/mitre/caldera/blob/master/conf/default.yml

However, when launching the Caldera server, I get the following DEBUG logs when there are not endpoints beaconing to the Caldera server. I only have my browser open and with the Caldera Interface open.

```2020-04-05 05:56:54 - DEBUG (contact_svc.py:47 handle_heartbeat) Incoming http beacon from 1234
2020-04-05 05:56:54 - DEBUG (contact_svc.py:47 handle_heartbeat) Incoming http beacon from 4321
2020-04-05 05:56:54 - DEBUG (contact_svc.py:47 handle_heartbeat) Incoming http beacon from 5521
2020-04-05 05:56:54 - DEBUG (contact_svc.py:47 handle_heartbeat) Incoming http beacon from 6511
2020-04-05 05:56:54 - DEBUG (contact_svc.py:47 handle_heartbeat) Incoming http beacon from 9231
```
After reading the docs, I can see that `app.contact.http`: the http location you want HTTP agents (like Sandcat) to connect to

https://github.com/mitre/caldera/blob/master/conf/default.yml#L6

and 

`port` : the port you serve CALDERA on
https://github.com/mitre/caldera/blob/master/conf/default.yml#L20

are set to port `8888` 

I know that the

```
The mock plugin adds simulated agents to CALDERA, which can be used in normal operations. These simulated agents use mock responses, which can be added for any ability.
```
However, I wasn't sure if that's the default behavior right after enabling the Mock plugin. Thank you in advance for your time to answer this question.

Thank you!

**Comment by privateducky** [comment]
Good question- that is the right behavior. Once you enable the Mock plugin, on the next server reboot, a set of "simulated" agents will start immediately and beacon back (via the HTTP contact point) to the server.

in plugins/mock/conf/agents.yml, you can adjust the beaconing agents. 

these agents are designed to start up immediately, so you can run operations and test out various attack scenarios before you deploy "real" agents (sandcat, rag doll, Manx, etc.).

**Comment by Cyb3rWard0g** [comment]
Awesome thank you @privateducky :)
