### ISSUE TITLE
[Server.py] local.yml config file not being processed 

### ISSUE THREAD

**Issue by Cyb3rWard0g** [mitre/caldera#1483]
I am testing my own local.yml config to add some new plugins that are not defined in the [default.yml](https://github.com/mitre/caldera/blob/master/server.py) config. However, even when I run the [server.py](https://github.com/mitre/caldera/blob/master/server.py) script with the `-E` parameter set to local (not needed since it is the default, but I tried) it is still using the `default.ym` file.

I fixed it with the following PR: https://github.com/mitre/caldera/pull/1482

On March 24th , there was a MERGE which removed the open call for the config file (5b18d18) . However:default.yml was hardcoded on the BaseWorld.strip_yml method to read the config file as shown in here (https://github.com/mitre/caldera/blob/master/server.py#L74) . Even though one runs python server.py -E local, the parameter does not get passed to the Baseworld.strip_yml method. It is evaluated properly by the conditional to handle the args.environment parameter (https://github.com/mitre/caldera/blob/master/server.py#L73) and stores the value in the variable config (https://github.com/mitre/caldera/blob/master/server.py#L73), but it is never used.

**Comment by privateducky** [comment]
Merged your change - thanks!
https://github.com/mitre/caldera/pull/1482
