### ISSUE TITLE
Bad handling of multiline commands 

### ISSUE THREAD

**Issue by zaphodef** [mitre/caldera#1486]
First of, I've only been using caldera for a few days, so apologies if what I say is actually nonsense :)

When trying to execute a command over multiple lines in version 2.6.6, it gets reduced into one, causing the command to fail or resulting in strange behaviors.

One example to reproduce this:
- take any ability and use the following command:
```
echo 'test line 1' > test1
echo 'test line 2' > test2
```
- launch an operation on a Linux-based system, and look at the (unexpected) result (it is actually this output for `echo 'test line 1' > test1echo 'test line 2' > test2`)
```
0      test1echo
4.0K test2
```

The problem is caused by the replacement of newlines `'\n'` by the empty string `''`, in
- https://github.com/mitre/caldera/blob/master/app/utility/base_world.py#L43
- https://github.com/mitre/caldera/blob/master/app/objects/c_agent.py#L148
- https://github.com/mitre/caldera/blob/master/app/objects/c_ability.py#L93 (not a 100% sure about this last one, but it should be involved too)

The ability is correctly stored on multiple lines in the database.

I'm guessing these `replace('\n', '')` methods are serving a specific purpose, but I'm not sure what purpose (at first I thought it was for sending the payload over TCP, but we already use base64 encoding for that).

I'd be glad to help and/or make a PR if I can understand what those `replace('\n', '')`  are here for.

**Comment by privateducky** [comment]
makes perfect sense-- and you're spot on. 

you have two options when creating a new ability:

1. use a semi-colon to separate your lines in the command field of the YML file. you'll see a bunch of examples like this. when the command gets interpreted, it'll be read as a single line, but the semi-colon works to separate it appropriately when executed. 
2. if you're command is more than a handful of lines, storing it in the YML file may be ugly (imagine 500+ lines!). in these cases, you can put your code into a file and store it as a "payload".

**Comment by zaphodef** [comment]
OK! I'll use semicolon for mitre/atomic/pull/7. Maybe it's also worth adding a parser, that converts new lines to semicolons when entering multiline commands from the WebUI? I'll make another PR.
