### ISSUE TITLE
Operations stuck at 99% not cleaning up, error in logs

### ISSUE THREAD

**Issue by Meow-ops** [mitre/caldera#1496]
Most operations start well and perform, but they get stuck at 99%, None of the cleanup operations are done afterwards.
The only thing I can see in the logs is this error :

```
future: <Task finished name='Task-72' coro=<LearningService.learn() done, defined at caldera/app/service/learning_svc.py:41> exception=UnicodeDecodeError('utf-8', b'Copy-Item : L\'acc\x8as au chemin d\'acc\x8as \'C:\\Users\\Public\\eicar.com\' ...
Traceback (most recent call last):
  File "caldera/app/service/learning_svc.py", line 42, in learn
    decoded_blob = b64decode(blob).decode('utf-8')
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8a in position 17: invalid start byte

```

**Comment by Meow-ops** [comment]
Error or not, the operation stays stuck actually

**Comment by Meow-ops** [comment]
If I manually "finish" the operation and restarts it, the decision is taken and the cleanup is actually done for some reason

**Comment by Meow-ops** [comment]
For the error from above, I simply replaced the utf-8 codec by utf-16, it seems to work perfectly, still stuck at 99% though

**Comment by privateducky** [comment]
when you start an operation, you get two choices (under 'Basic Options') for how you'd like to stop your operation. by default it will select 'Keep open forever' which means the operation will run the adversary profile -- then stay open forever. you could alternatively select 'auto close', which will do just that once the adversary is unable to run any additional actions. 

you'd choose 'keep open forever' for a few reasons:
1. you have some long running abilities that may require the user to do something on the computer - eventually - to unlock other abilities in the adversary. 
2. you want to utilize the '+ potential links' on the operation page - which allow you to keep an operation open indefinitely but task agents in the operation with any TTP from the database

**Comment by privateducky** [comment]
your UTF-8/16 issue is something separate. 

that was a development bug in bleeding-edge, if i recall correctly, from just a week or two ago. if you use the latest tagged release (2.6.6) you shouldn't see that. i fixed that last week i believe in the bleeding-edge (latest master) code.

**Comment by Meow-ops** [comment]
Okay, thanks for the explanations!
