### ISSUE TITLE
Error on starting an operation : get_links() got an unexpected keyword argument 'phase'

### ISSUE THREAD

**Issue by Meow-ops** [mitre/caldera#1507]
I updated caldera to the newest commit on the master branch, on starting an operation I got the following error:

```
Traceback (most recent call last):
  File "/home/sarcarx/vm_readonly/developpement/analid/caldera/app/objects/c_operation.py", line 231, in run
    await self._run(planner)
  File "/home/sarcarx/vm_readonly/developpement/analid/caldera/app/objects/c_operation.py", line 249, in _run
    await planner.execute(ability_set_format.index(ability))
  File "/home/sarcarx/vm_readonly/developpement/analid/caldera/plugins/stockpile/app/sequential.py", line 10, in execute
    for link in await self.planning_svc.get_links(operation=self.operation, phase=phase,
TypeError: get_links() got an unexpected keyword argument 'phase'

```

**Comment by zaphodef** [comment]
You need to update the submodules too. `git submodule update --recursive --remote` should do the trick.

**Comment by Meow-ops** [comment]
Ok, after updating the submodules, the windows agent seems to crash:
```
Started sandcat in verbose mode.
server=http://192.168.250.1:8888
group=my_group
privilege=User
initial delay=0
c2 channel=HTTP
Beacon API=/beacon
[+] beacon: ALIVE
[*] Running instruction task-987515
panic: interface conversion: interface {} is nil, not string

goroutine 1 [running]:
_/Users/davidhunt/Desktop/toolbox/caldera/plugins/sandcat/gocat/core.runAgent(0x7b55a0, 0x9c4b70, 0xc0000b9710)
        /Users/davidhunt/Desktop/toolbox/caldera/plugins/sandcat/gocat/core/core.go:58 +0x8cc
_/Users/davidhunt/Desktop/toolbox/caldera/plugins/sandcat/gocat/core.Core(0xc0000103c0, 0x19, 0xc00000a0f8, 0x8, 0x0, 0x
0, 0x0, 0x0, 0xc0000b96e0, 0x430100)
        /Users/davidhunt/Desktop/toolbox/caldera/plugins/sandcat/gocat/core/core.go:143 +0x539
main.main()
        /Users/davidhunt/Desktop/toolbox/caldera/plugins/sandcat/gocat/sandcat.go:35 +0x458
```

I tried re installing the agent, it didn't work

**Comment by Meow-ops** [comment]
And after the submodule update, seems like the phase error still occurs

**Comment by privateducky** [comment]
two separate issues here:

1. the phase error. just last night, we pushed a big update to bleeding-edge code to remove phases and replace them with a dynamic ordering option, which will aid us in our automated intelligence in the future. if you're seeing an error there, one of your plugins (likely stockpile) is likely not up to date. the easiest approach is to re-clone entirely. 
2. the interface/panic issue when starting the agent. this is one of 2 things: either the plugins are out of sync (same as above) or your CALDERA server doesn't have a modern version of GoLang installed. If it is the latter, you'd want to either re-run the install.sh script - or manually upgrade your GoLang version.

**Comment by privateducky** [comment]
as a general note, we currently operate using the GitHub "flow", which means our master branch is our bleeding-edge version, whereas our tagged releases are our stable (fully tested) versions. depending on how much stability you're looking for (versus latest features) you may want to opt for a release version.

**Comment by Meow-ops** [comment]
Ok, I see, I will try with the latest tagged release and close the issue if it works, thanks for your answers
