### ISSUE TITLE
Ability duplication

### ISSUE THREAD

**Issue by zaphodef** [mitre/caldera#1524]
Changing an ability's platform from the WebUI leads to a duplication of the ability (with the two platforms). The incorrect one is stored through `data_svc`, and is saved in `data/object_store` when exiting the server. Removing the file removes the wrong duplicate.

Steps to reproduce (e0d5098):
* `python server.py --fresh`
* login as red
* go to campaigns > adversaries > add ability
* eg. chose collection > T1047 > WMIC Process Enumeration
* change platform
* save ability
* logout then login
* go to this ability again, it got duplicated

**Comment by privateducky** [comment]
yeah that is odd behavior. I went ahead and patched it here, by removing and re-inserting the persisted ability:
https://github.com/mitre/caldera/pull/1531
