### ISSUE TITLE
C2 abilities are not always agents

### ISSUE THREAD

**Issue by zaphodef** [mitre/caldera#1532]
Currently, all abilities in the "command-and-control" tactic [are considered agents](https://github.com/mitre/caldera/blob/1b8853bc60fa530a54893872fff7906ccb6eeb87/app/api/packs/campaign.py#L30). This is probably too wide, because some tests may be conducted in order to test resilience to C2, without installing an agent.

For instance, [this test from Atomic Red Team](https://github.com/redcanaryco/atomic-red-team/blob/11c5096b0e64939b47b826dcb0f07e2689e9a077/atomics/T1065/T1065.yaml), which can be imported in Caldera and only contact google.com on a specific port, is considered an agent if registered under the "command-and-control" tactic (while [this is the correct phase for this technique](https://attack.mitre.org/techniques/T1065/)).

**Comment by privateducky** [comment]
Yeah, I was wondering when the first time we'd hit this would be. 

Do you have any suggestions on a remediation? I originally thought about adjusting the ability YML files to "tag" them as an agent. However, I don't necessarily like the idea of modifying YML files with non-uniform properties like this.

**Comment by privateducky** [comment]
@zaphodef I've decided to go with adding deployment abilities to the agents.yml file:
https://github.com/mitre/caldera/pull/1634
