### ISSUE TITLE
Pin version of dirhash library (new release with breaking changes)

### ISSUE THREAD

**Issue by andhus** [mitre/caldera#1551]
Hi! Glad to see that you found the use of my `dirhash` library :) 

Please note that there is a new release (0.2.0) of the library soon to be published on PyPI. This has several changes *and obtained hashes will differ from those computed with < 0.2.0*. This is because the implementation is now based on the "Dirhash Standard", which has now taken over the repo https://github.com/andhus/dirhash where the python lib was previously maintained. The python lib has moved to https://github.com/andhus/dirhash-python.

For further details, please see the respective changelog:  
https://github.com/andhus/dirhash/blob/master/CHANGELOG.md
https://github.com/andhus/dirhash-python/blob/master/CHANGELOG.md

For `caldera` I suggest that you upgrade to 0.2.0 or at least pin the version to 0.1.1 in `requirements.txt` to avoid problems.

The intention is to avoid any future breaking changes, the whole purpose of the Dirhash Standard is to provide a formal and stable protocol. Let me know if you have any questions! And please consider star:ing the repos and spread the word of well-defined directory hashing :)

**Comment by privateducky** [comment]
nice- we will do! 

we were prototyping the other day (myself and @mrengstrom) and found dirhash seemed to give the best results for including/excluding files when directory hashing. 

we just started using this last week, as we've been piloting using directory hashes to verify application versions of cloned code. this seems to be working pretty well. 

I'll put definitely put together a shout-out for dirhash.

**Comment by andhus** [comment]
Oh, and the `-m`/`--match` and `-i`/`--ignore` args for the CLI should now be a list of strings (instead of one string with space-separated patterns) which affects https://github.com/mitre/caldera/blob/adbcf4582d260e0745e19bda73e2d2e01a0c98bb/release.sh#L11
...I should add this to the change log.

**Comment by andhus** [comment]
If you'd like I'll make a PR for you before publishing 0.2.0.

**Comment by privateducky** [comment]
sweet. that'd be nice to see. for now, I went ahead and pinned dirhash in this PR:

https://github.com/mitre/caldera/pull/1553
