### ISSUE TITLE
ModuleNotFoundError: No module named 'plugins.manx.app'

### ISSUE THREAD

**Issue by nov3mb3r** [mitre/caldera#1552]
Tried the docker deployment as stated by readthedocs. The following error appears:
```
sudo docker run -p 7010:7010 -p 7011:7011 -p 7012:7012 -p 8888:8888 caldera:server

Traceback (most recent call last):
  File "server.py", line 10, in <module>
    from app.api.rest_api import RestApi
  File "/usr/src/app/app/api/rest_api.py", line 14, in <module>
    from app.service.app_svc import Error
  File "/usr/src/app/app/service/app_svc.py", line 16, in <module>
    from app.contacts.contact_tcp import Tcp
  File "/usr/src/app/app/contacts/contact_tcp.py", line 7, in <module>
    from plugins.manx.app.c_session import Session
ModuleNotFoundError: No module named 'plugins.manx.app'
```
Docker version 19.03.6, build 369ce74
Python 3.8.2

**Comment by privateducky** [comment]
@scottctaylor12 do you know offhand?

**Comment by scottctaylor12** [comment]
This error happens when the multiple plugins/* folders appear, but the content inside is not populated. This happens when the `--recursive` flag is not used when cloning CALDERA. So the error isn't actually Docker related, but I'll have to check how readthedocs sets up the container.

**Comment by scottctaylor12** [comment]
@nov3mb3r I am assuming you cloned CALDERA from GitHub and then built your container by running `docker build . -t caldera:server` according to the docs. As mentioned previously, you might have missed the `--recursive` flag when doing the initial clone of CALDERA from GitHub.
If I am correct, you'll see multiple folders in the plugins/ directory **but** all of them will be empty if you look inside. To remediate the problem, re-clone from GitHub by running `git clone https://github.com/mitre/caldera.git --recursive`

**Comment by nov3mb3r** [comment]
--recursive did the trick
