### ISSUE TITLE
API Queries for Operations created via API return empty brackets

### ISSUE THREAD

**Issue by jetbennett** [mitre/caldera#1577]
When an operation is created via the GUI, users can query its status with an API call such as:
`curl -X POST http://localhost:8888/api/rest -d '{"index":"operations","id":"12345"}'`

This does not work if the operation was created via API. 

For example, if the operation is created via the API call:
`curl -X http://localhost:8888/api/rest -d '{"index":"operations","name":"ExampleOP","group":"red","adversary_id":"...","state":"running","planner":"sequential","autonomous":"1","atomic_enabled":"1","obfuscator":"base64","auto_close":"1","jitter":"4/8","source":"Alice Filters","visibility":"50"}'`

The API call:
`curl -X POST http://localhost:8888/api/rest -d '{"index":"operations","id":"54321"}'`
will return:
`[]`

But the more general API call:
`curl -X POST http://localhost:8888/api/rest -d '{"index":"operations"}`
will return information about the operation 54321 in addition to any operations created via the GUI.

**Comment by khyberspache** [comment]
@jetbennett Operation ID's are integers, not strings.  Use this to properly query your operation:
```Bash
curl -X POST -H "KEY:ADMIN123" http://localhost:8888/api/rest -d '{"index":"operations","id":54321}'
```

**Comment by jetbennett** [comment]
Ah that solved it. Thanks!

Interestingly, op_id works both quoted or unquoted.
`curl -X POST -H "KEY:ADMIN" http://localhost:8888/api/rest -d '{"index":"operation_report","op_id":"54321","agent_output":0}'`
and
`curl -X POST -H "KEY:ADMIN" http://localhost:8888/api/rest -d '{"index":"operation_report","op_id":944734,"agent_output":0}'`
return identical output.
