### ISSUE TITLE
No Agents selectable in Campaigns > Agents

### ISSUE THREAD

**Issue by Zeik0s** [mitre/caldera#1580]
I cloned the repo (commit 6426caddb99d4821e8fe785bc8452eed9708d215), ran the install script with root user, entered the virtualenv and started the server. Accessing the Dashboard was possible, but when i wanted to deploy an Agent via Campaigns > Agents i couldn't select any agent version. 

Analyzing this with the developer Console in Chrome, the Rest API Call is successfull, but the Response for index: "assets" is empty. 

I didn't change any config for this. I am currently on Kali Rolling 2020.2 (up-to-date), with XFCE, on VmWare Workstation. 

If any further info about the setup environment/logs is necessary, i will provide that.

**Comment by khyberspache** [comment]
@Zeik0s I just pulled down the latest Master on a 2020.2 Kali variant and had no issues.  Can you provide any additional steps to reproduce?

**Comment by Zeik0s** [comment]
Ok, i am not sure what fixed it. Most likely i messed something up with the repo before. But i updated also the packages today (around 52 new Packages). And although commit 5cb070d33a934e129d0b7e5837e208e39b6ac549 is the particular part of Website, it doesn't change anything to the logic. So i will close this one.
