### ISSUE TITLE
Operation created from the API does not appear in the UI

### ISSUE THREAD

**Issue by rcaroncd** [mitre/caldera#1599]
Hello,

I have checked that if you make a request to the API to create an operation, I do not know why, not the operation does not appears in the UI part, but it is created correctly.  The request returns data to me as when it is made from the UI, that is to say, that it has been made correctly.

I attach the function I have to perform the operation and you can check that the values I send are correct:

![create_operation_function](https://user-images.githubusercontent.com/62614400/80575803-68bde880-8a04-11ea-9c93-61aa1b27bdf9.png)

In case you want to check it or something.

A greeting

**Comment by khyberspache** [comment]
@rcaroncd I've seen this before - the operation is showing up on the "blue-side" of Caldera due to some API KEY access issues.  (Yes there is a Blue/automated incident response version of caldera in case you didn't know!).

We are aware of this issue and will address it ASAP.

**Comment by khyberspache** [comment]
@privateducky @wbooth

**Comment by rcaroncd** [comment]
Oh, okay, perfect. Yeah, I knew blue's profile, which I didn't see appearing there. I'm standing by.

**Comment by privateducky** [comment]
I kicked off a RED operation using the red key (ADMIN123) and it showed up fine under the operation GUI (for red):
```
curl -X PUT -H "KEY:ADMIN123" http://127.0.0.1:8888/api/rest -d '{"index":"operations","name":"testoperation1"}'
```

I did the same thing with the blue key (BLUEADMIN123) and it showed up only under the blue GUI page. I'm doing this against latest master code-- are you doing this against a release version or latest master?
