### ISSUE TITLE
Problem with adversaries and API

### ISSUE THREAD

**Issue by rcaroncd** [mitre/caldera#1602]
Hello,

Sorry for opening up so many issues (I'm just testing the framework thoroughly). I have a problem with the adversary query via API REST. Theoretically, if I make the following request

```
curl 'http://192.168.1.2:8888/api/rest' -H 'Host: localhost:8888' -H 'Content-Type: application/json' -d '{"index":"adversaries","adversary_id":"958d42b6-b7c2-4cbc-8606-b1714ab5fce3"}' -H 'KEY: ADMIN123'
```

I should get all the existing adversaries. The problem is that, if I make the request using the KEY API in the http header (as in the previous example), it doesn't return the same results, as if I use the session COOKIE that I extract from the web when I login with the red user. I attach a screenshot that shows the problem:

![caldera_adversary_bug](https://user-images.githubusercontent.com/62614400/80621521-b576e300-8a47-11ea-9c68-0ca85c0214a1.png)

The data I expect is the one from the request with the COOKIE, but... theoretically, it should return the same, right?

A greeting and I hope you can solve it and understand the explanation

**Comment by khyberspache** [comment]
This is the same issue as https://github.com/mitre/caldera/issues/1599. 

Our back-end authentication/authorization via the API isn't responding with the correct data for the correct keys (your first query got all of Blue Defender profiles, vice the second getting the Red Adversary profiles).  This will be fix when we address the API issues.

**Comment by khyberspache** [comment]
@privateducky @wbooth

**Comment by wbooth** [comment]
Cool we’ll get this resolved, thanks

**Comment by privateducky** [comment]
I updated the docs to show how to do this correctly: https://github.com/mitre/caldera/pull/1668 

here's a quick example.

we have a blue adversary, with ID=f61e3fc0-43d8-4b36-b5d3-710610b92974. When I request this adversary using the red key (ADMIN123), nothing comes back.
```
curl 'http://localhost:8888/api/rest' -H 'Content-Type: application/json' -d '{"index":"adversaries","adversary_id":"f61e3fc0-43d8-4b36-b5d3-710610b92974"}' -H 'KEY: ADMIN123'
```

If I only swap the key for the blue key (BLUEADMIN123) I get all abilities for this adversary.
```
curl 'http://localhost:8888/api/rest' -H 'Content-Type: application/json' -d '{"index":"adversaries","adversary_id":"f61e3fc0-43d8-4b36-b5d3-710610b92974"}' -H 'KEY: BLUEADMIN123'
```
