### ISSUE TITLE
Can't start sandcat on Win 10

### ISSUE THREAD

**Issue by pstnslv** [mitre/caldera#1606]
Hello,

I ran caldera docker [image ](https://hub.docker.com/r/mitre/caldera) v.2.6.65 and trying to download and start sandcat agent on my Win 10 workstation by PowerShell commands from [there](https://github.com/mitre/caldera/wiki/Plugins-sandcat) and from my CALDERA server (change 0.0.0.0 to localhost):

```$server="http://0.0.0.0:8888";$url="$server/file/download";$wc=New-Object System.Net.WebClient;$wc.Headers.add("platform","windows");$wc.Headers.add("file","sandcat.go");$data=$wc.DownloadData($url);$name=$wc.ResponseHeaders["Content-Disposition"].Substring($wc.ResponseHeaders["Content-Disposition"].IndexOf("filename=")+9).Replace("`"","");get-process | ? {$_.modules.filename -like "C:\Users\Public\$name.exe"} | stop-process -f;rm -force "C:\Users\Public\$name.exe" -ea ignore;[io.file]::WriteAllBytes("C:\Users\Public\$name.exe",$data) | Out-Null;Start-Process -FilePath C:\Users\Public\$name.exe -ArgumentList "-server $server -group red" -WindowStyle hidden;```

But in both variants sandcat closed right after start:
```
Started sandcat in verbose mode.
server=http://localhost:8888
group=my_group
privilege=User
initial delay=0
c2 channel=HTTP
Beacon API=/beacon
[+] beacon: ALIVE
[*] Running instruction task-596278
panic: interface conversion: interface {} is nil, not string

goroutine 1 [running]:
_/Users/davidhunt/Desktop/toolbox/caldera/plugins/sandcat/gocat/core.runAgent(0x7b55a0, 0x9c4b70, 0xc0000ddb60)
        /Users/davidhunt/Desktop/toolbox/caldera/plugins/sandcat/gocat/core/core.go:58 +0x8cc
_/Users/davidhunt/Desktop/toolbox/caldera/plugins/sandcat/gocat/core.Core(0xc000010380, 0x15, 0xc00000a0f0, 0x8, 0x0, 0x0, 0x0, 0x0, 0xc0000ddb30, 0x430100)
        /Users/davidhunt/Desktop/toolbox/caldera/plugins/sandcat/gocat/core/core.go:143 +0x539
main.main()
        /Users/davidhunt/Desktop/toolbox/caldera/plugins/sandcat/gocat/sandcat.go:35 +0x458
```

The docker logs are: 
```
2020-05-01 16:24:25 - DEBUG (sand_svc.py:123 _compile_new_agent) Dynamically compiling sandcat.go

2020-05-01 16:24:25 - WARNING (file_svc.py:133 compile_go) Problem building golang executable sandcat.go: Command '['go', 'build', '-ldflags', '-s -w -X main.key=BV0C8T6LU91U0BX50S95RPFJR4WUPF ', '-o', '/usr/src/app/plugins/sandcat/payloads/sandcat.go-windows', 'sandcat.go']' returned non-zero exit status 1.

2020-05-01 16:24:25 - DEBUG (app_svc.py:109 retrieve_compiled_file) sandcat.go downloaded with hash=a98ed4833c64ff96ad74f1a76358b1fb947c7bc61502e51624afe6944982ec93 and name=splunkd

2020-05-01 16:24:26 - DEBUG (contact_svc.py:55 handle_heartbeat) First time http beacon from yfpgth```

Is it right that server cant compile correct sandcat image for my host and that's why agent don't ran? 
How to resolve this ?

Thank you for interesting project. I will be appreciate for any help.

**Comment by privateducky** [comment]
@scottctaylor12 I know we don't test our docker container often, but do you know if it installs latest GoLang?

@pstnslv the error message you posted is good: this usually indicates that the computer running the server (in your case, the docker container) does not have a high-enough GoLang version installed.

**Comment by khyberspache** [comment]
@privateducky This is definitely a case of the server/docker not having `go` available in PATH. @pstnslv You will need to install Golang-Go on the host your running your dockers on.

**Comment by pstnslv** [comment]
@privateducky, thanks, but it seems like I already have golang in my container (from original docker image):
```root@7a53be12a98c:/usr/src/app# go version
go version go1.10.4 linux/amd64
```
and there is $PATH
```root@7a53be12a98c:/usr/src/app# whereis go
go: /usr/bin/go /usr/lib/go /usr/share/go
root@7a53be12a98c:/usr/src/app# echo $PATH
/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
```

**Comment by khyberspache** [comment]
@pstnslv Your go version is too low. I think the absolute minimum we can support is 1.11, but we test/deploy 1.13.  Upgrade go on your system and you're good to go (pun intended!).

**Comment by pstnslv** [comment]
@khyberspache Thanks a lot! Yes, it works after I update golang in my image to 1.13.10. I think it will be great to update Dockerfile, but I don't know right way to do it.
