### ISSUE TITLE
virtualenv not working + calderaenv not created

### ISSUE THREAD

**Issue by a6n1** [mitre/caldera#1615]
Hi,

I tried installing caldera on two OSes (Kali 2020, and Ubuntu 16.04) but I get the same error when I did ./install.sh --ubuntu and ./install.sh --kali. Here's the output of the file:

[-] Setting up Python venv
[+] Python virtualenv installed
PermissionError: [Errno 13] Permission denied: '/root/caldera/calderaenv'
[x] Caldera python venv FAILED to install
1
-su: /root/caldera/calderaenv/bin/pip: Permission denied
[x] Caldera python requirements FAILED to install
1
[-] Building documentation
-su: /root/caldera/calderaenv/bin/sphinx-build: Permission denied
[x] sphinx documentation FAILED to install
[x] Caldera installer FAILED to install critical components
[x] See install_log.txt for details

When i checked install_log.txt this is the output:

[x] Caldera python venv FAILED to install
 - command: virtualenv -q -p python3 /root/caldera/calderaenv
[x] Caldera python requirements FAILED to install
 - command: /root/caldera/calderaenv/bin/pip -q install -r /root/caldera/requirements.txt
[x] sphinx documentation FAILED to install
 - command: /root/caldera/calderaenv/bin/sphinx-build -b html /root/caldera/docs /root/caldera/docs/_build

I tried doing virtualenv -q -p python3 /root/caldera/calderaenv manually but it says that it is already using interpreter /sur/bin/python3.

Any ideas on how to make this work? Thanks.

**Comment by khyberspache** [comment]
Try running the installation with `sudo` from a non-root account and see if it works for you.

**Comment by a6n1** [comment]
I tried using my normal account, then used sudo, but it still has an error:

[-] Setting up Python venv
[+] Python virtualenv installed
usage: virtualenv [--version] [--with-traceback] [-v | -q] [--app-data APP_DATA] [--clear-app-data] [--discovery {builtin}] [-p py] [--creator {builtin,cpython3-posix,venv}] [--seeder {app-data,pip}] [--no-seed]
                  [--activators comma_sep_list] [--clear] [--system-site-packages] [--symlinks | --copies] [--no-download | --download] [--extra-search-dir d [d ...]] [--pip version] [--setuptools version] [--wheel version] [--no-pip]
                  [--no-setuptools] [--no-wheel] [--symlink-app-data] [--prompt prompt] [-h]
                  dest
virtualenv: error: argument dest: the destination . is not write-able at /opt/caldera
[x] Caldera python venv FAILED to install
1
-su: /opt/caldera/calderaenv/bin/pip: No such file or directory
[x] Caldera python requirements FAILED to install
1
[-] Building documentation
-su: /opt/caldera/calderaenv/bin/sphinx-build: No such file or directory
[x] sphinx documentation FAILED to install
[x] Caldera installer FAILED to install critical components
[x] See install_log.txt for details
a6n1@ubuntu:/opt/caldera$ 

it still has that same error in the install_log.txt:

[+] Python virtualenv installed
[x] Caldera python venv FAILED to install
 - command: virtualenv -q -p python3 /opt/caldera/calderaenv
[x] Caldera python requirements FAILED to install
 - command: /opt/caldera/calderaenv/bin/pip -q install -r /opt/caldera/requirements.txt
[x] sphinx documentation FAILED to install
 - command: /opt/caldera/calderaenv/bin/sphinx-build -b html /opt/caldera/docs /opt/caldera/docs/_build

**Comment by a6n1** [comment]
the install.sh does not create the calderaenv directory

**Comment by khyberspache** [comment]
Reopened - I'll try to replicate

**Comment by privateducky** [comment]
the install.sh script is not working on all operating systems right now (several side-cases stopping it from doing so). we'll be working on making this more robust-- but in the meantime, you should just follow the "normal" install instructions on GitHub:

Clone repo
Pip install requirements

**Comment by privateducky** [comment]
in latest master, I have removed references to using the install.sh script. this has been plaguing us for awhile, where we tried to add a helper script to install some dependencies for making the CALDERA server more powerful. 

we'll be revisiting more robust ways to do this in the future-- but in the meantime, I have updated the README documentation for installation, using the normal approach.
