### ISSUE TITLE
Question about modifying abilities

### ISSUE THREAD

**Issue by a6n1** [mitre/caldera#1638]
I'm not sure if this is a bug or not. But If so, I would like to ask if there are work arounds for it.

When you add an ability on a profile, Ex. Exfiltration > T1002 > compress staged directory, and you removed the clean up on Linux (rm #{host.dir.staged}.tar.gz) and save it. Then you created a new profile and add the same ability, the clean up for Linux  shows that it is empty. The abilities doesn't return to default once you have modified and added it in a profile. Is there a fix for this? 

There are also times where you can't delete or add the abilities you edited in a certain attack. Let's use the same example T1002. I removed all windows and saved it, when I get back to check the abilities tab, all windows attacks are still there. Any ideas on how to fix this?

**Comment by mrengstrom** [comment]
For the first question, modifying an ability when adding to an adversary edits the ability in memory, so all future references to it will be modified as well.  The way around that would be to have a set of abilities we copy from, then if those are to be saved or persisted they would need to get new IDs.

For the second question I will try and reproduce that issue, as that sounds like a bug with updating an ability, which obviously works elsewhere in the UI as the first question proves.

**Comment by a6n1** [comment]
I see, I tried copying the IDs and they seem to work, but I would like to ask how do you delete the other attacks in case of duplicates?

**Comment by mrengstrom** [comment]
so, are you saying, that if you create a new ability from an existing ability (so it gets a new id), and then you delete cleanup actions on it, or not change it at all, how do you find equivalent ability commands and clean them up?
As there is no built in functionality for that to my knowledge besides checking source control for the locally added files and removing them.

**Comment by a6n1** [comment]
Yes, you I mean I need to delete it here? https://github.com/mitre/stockpile/tree/6580bd7d97e9d91441377c9a3b3a6a7467dbf241/data/abilities

**Comment by privateducky** [comment]
I'm not sure if I quite get this question, but let me try answering in a round about way:

1. There is exactly 1 ability with a given ID (UUID) at any given time. If this ability exists in two adversary profiles, they are references to the ability, not copies. Which means, if you modify the ability (such as removing the cleanup), it will affect both profiles. 
2. If you want to avoid this and instead only change the ability for a single profile, you'll need to create a new ability and attach it to the profile. You can copy an existing ability by opening the ability (campaigns -> adversaries -> +add ability) and clicking 'generate new ID' and saving. you may also want to give your ability a new name, to not confuse the two.

let me know if this clears it up.
