### ISSUE TITLE
Docker not starting on Ubuntu 18.04

### ISSUE THREAD

**Issue by maraboutingermany** [mitre/caldera#1639]
When trying to run Caldera via Docker I received the following error message:

  File "server.py", line 9, in <module>
    from app.api.rest_api import RestApi
  File "/usr/src/app/app/api/rest_api.py", line 14, in <module>
    from app.service.app_svc import Error
  File "/usr/src/app/app/service/app_svc.py", line 16, in <module>
    from app.contacts.contact_tcp import Tcp
  File "/usr/src/app/app/contacts/contact_tcp.py", line 7, in <module>
    from plugins.manx.app.c_session import Session
ModuleNotFoundError: No module named 'plugins.manx.app'

I followed the caldera documentation on using docker

**Comment by rcaroncd** [comment]
Have you done the recursive git clone of the submodules?

Try again cloning caldera with:
`git clone https://github.com/mitre/caldera.git --recursive --branch x.x.x`

**Comment by khyberspache** [comment]
@maraboutingermany - @rcaroncd has the right answer.
