### ISSUE TITLE
Error while installing caldera WRNING:failed to import module 'rest_api'

### ISSUE THREAD

**Issue by mdevaips** [mitre/caldera#1648]
reading sources... [100%] index
WARNING: autodoc: failed to import module 'rest_api' from module 'app.api'; the following exception was raised:
No module named 'plugins.manx.app'
WARNING: autodoc: failed to import module 'contact_tcp' from module 'app.contacts'; the following exception was raised:
No module named 'plugins.manx.app'
WARNING: autodoc: failed to import module 'app_svc' from module 'app.service'; the following exception was raised:
No module named 'plugins.manx.app'
/home/caldera/caldera/app/service/planning_svc.py:docstring of app.service.planning_svc.PlanningService.check_stopping_conditions:5: WARNING: Field list ends without a blank line; unexpected unindent.
/home/caldera/caldera/app/service/planning_svc.py:docstring of app.service.planning_svc.PlanningService.execute_planner:3: WARNING: Unexpected indentation.
looking for now-outdated files... none found
pickling environment... done
checking consistency... done
preparing documents... done
writing output... [100%] index
/home/caldera/caldera/docs/Common-problems.md:26: WARNING: None:any reference target not found: What-is-an-ability
/home/caldera/caldera/docs/Server-configuration.md:37: WARNING: None:any reference target not found: What-is-a-plugin
/home/caldera/caldera/docs/The-REST-API.md:77: WARNING: None:any reference target not found: What-is-an-ability
/home/caldera/caldera/docs/The-REST-API.md:79: WARNING: None:any reference target not found: Plugins-sandcat
generating indices...  genindex py-modindexdone
writing additional pages...  search/home/caldera/caldera/calderaenv/lib/python3.6/site-packages/sphinx_rtd_theme/search.html:20: RemovedInSphinx30Warning: To modify script_files in the theme is deprecated. Please insert a <script> tag directly in your theme instead.
  {{ super() }}
done
copying static files... ... done
copying extra files... done
dumping search index in English (code: en)... done
dumping object inventory... done
build succeeded, 9 warnings.

**Comment by privateducky** [comment]
what is this stack trace from?

1. did you recursively clone? 
2. were you able to complete: "pip install -r requirements.txt" ?

**Comment by privateducky** [comment]
I updated the docs to reflect how we'd like people to perform the installation moving forward, as we were hitting issues with the install.sh script. Check GitHub for the more simplistic way to do this.
