### ISSUE TITLE
Install on Kali 2020.2 works, but Caldera shows No Version and other warnings in page

### ISSUE THREAD

**Issue by jacobhargrave** [mitre/caldera#1661]
Attached are the install log which used sudo ./install.sh --kali on Kali 2020.2 in Hyper-V and a screenshot of the warnings / errors found in the Caldera webpage related to No Version.
[install_log.txt](https://github.com/mitre/caldera/files/4639249/install_log.txt)

The screenshot can be seen here:

https://imgur.com/JLWuBdq.png

I'm not sure, but this may be related to some other issues I'm having and will post later in reply to this post.

**Comment by privateducky** [comment]
you'll get 'no version' if you are using bleeding-edge code (i.e., latest master). 

to use a stable version of caldera, you'll want to clone the last stable build/version.

**Comment by jacobhargrave** [comment]
> you'll get 'no version' if you are using bleeding-edge code (i.e., latest master).
> 
> to use a stable version of caldera, you'll want to clone the last stable build/version.

I'm a little new to github, so I'm sorry if this is a stupid question, but how can I tell which release is the "stable" version?

**Comment by privateducky** [comment]
no problem-- on GitHub you'll see a "releases" link on a project page: https://github.com/mitre/caldera/releases

to use the stable version of caldera, you'll want to follow the first step of installation exactly:
```
Start by cloning this repository recursively, passing the desired version/release in x.x.x format. This will pull in all available plugins. If you clone master - or any non-release branch - you may experience bugs.

git clone https://github.com/mitre/caldera.git --recursive --branch x.x.x 
```
So your command would turn into:
```
git clone https://github.com/mitre/caldera.git --recursive --branch 2.6.5
```
