### ISSUE TITLE
Error for Human Plugin

### ISSUE THREAD

**Issue by Zeik0s** [mitre/caldera#1682]
I get the following error Message on Kali for enabling the Human Plugin and restarting the Server: 

`2020-05-19 18:39:28 - ERROR (human_svc.py:48 _load_workflow_module) Error loading extension=plugins.human.pyhuman.app.workflows.__pycache__.spawn_shell, No module named 'plugins.human.pyhuman.app.workflows.__pycache__.spawn_shell'
2020-05-19 18:39:28 - ERROR (human_svc.py:48 _load_workflow_module) Error loading extension=plugins.human.pyhuman.app.workflows.__pycache__.browse_web, No module named 'plugins.human.pyhuman.app.workflows.__pycache__.browse_web'
2020-05-19 18:39:28 - ERROR (human_svc.py:48 _load_workflow_module) Error loading extension=plugins.human.pyhuman.app.workflows.__pycache__.search_web, No module named 'plugins.human.pyhuman.app.workflows.__pycache__.search_web'`

The requirements from the .txt are fullfilled.

**Comment by khyberspache** [comment]
I replicated and patched this:
https://github.com/mitre/human/pull/3

**Comment by Zeik0s** [comment]
Will try, thanks a lot.

**Comment by Zeik0s** [comment]
Works. But it's really confusing, that configuring the Human Plugin is only visible for the Blue Team. Because i would expect creating Noise is a Task that Red-Team would do in order to confuse the Blue Team.

**Comment by khyberspache** [comment]
That's a really easy change to make - @privateducky would be the one to make the decision on that

**Comment by privateducky** [comment]
ha, yeah that's a tricky one. I originally figured the human would be used as a blue-team tool for adding noise into a test environment to supply a more realistic test. however, your point is solid. I will update this to be both.

**Comment by Zeik0s** [comment]
Thx. I didn't have a look, where it is configured, but may be also a good hint in the Docs. :)

**Comment by Zeik0s** [comment]
I still have this error, everytime after the next restart. I thought this might be related to the virtualenv, but also with it, the error occurs.
