### ISSUE TITLE
Question on training plugin "Create adversary" step

### ISSUE THREAD

**Issue by manoj30** [mitre/caldera#1687]
Hello,
I am new to caldera and till now I have created 54nd547 (sandcat) agents, profiles and run operations. Forgive me for any incorrect question.

I am going through the caldera `training `plugin (https://caldera.readthedocs.io/en/latest/Plugin-library.html#training). 
It has step to create "Certificate" adversary with at least 3 phases.

There is no option available in operations GUI to add **phases** while creating adversary profile..

Are phases removed from the latest branch 2.6.65.

**Comment by privateducky** [comment]
ah-- good catch actually.

phases were in fact removed around the 2.6.x time period. it's possible the training wording may be off related to that. it should read "at least 3 abilities".

this has been reflected in the 2.7.0 release we cut yesterday.

**Comment by manoj30** [comment]
Thank you very much.
