### ISSUE TITLE
Issue with training plugin "Blue Operation" step

### ISSUE THREAD

**Issue by triznut** [mitre/caldera#1700]
I'm not sure what this step is looking for as an end-result for completion of the task, but I have setup the Blue agent operation as described for the task (including netcat listeners on both a Linux and Windows system running under the Blue group), however I can't get the system to give me credit for task completion.

The operation does kill the netcat listener on my Linux system via the "Find unauthorized processes/Kill rogue process" ability, but I cannot get an operation to kill the listener on the Windows system, which I have a hunch needs to happen via the "Find atypical open ports" ability to get credit. Reviewing the output from the operation of that ability reveals an error message regarding the "pidToPort" (see below).

Error Message:
"function getFullList($portList){ $final = @(); foreach ($p in $portList) { if ($p -like "*-*") { $minmax = $p.Split("-"); for ($i = ($minmax[0] -as [int]); $i -lt ($minmax[1] -as [int]); $i++) { $final += ($i -as [string]); }; } else { $final += $p; }; }; return $final;};$basePorts = @("135","139","389","445","636","1000-5000","9389","49152-65535");$allPorts = getFullList $basePorts;$pidToPort = @();foreach ($port in (Get-NetTCPConnection -RemoteAddress 0.0.0.0 -state Listen)){ if ($allPorts -notcontains $port.LocalPort){ pidToPort += , @{pid=$port.OwningProcess;port=$port.LocalPort}; }};$pidToPort | ConvertTo-Json;

pidToPort : The term 'pidToPort' is not recognized as the name of a cmdlet, function, script file, or operable 
program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:631
+ ... if ($allPorts -notcontains $port.LocalPort){        pidToPort += , @{ ...
+                                                         ~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (pidToPort:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException
 
pidToPort : The term 'pidToPort' is not recognized as the name of a cmdlet, function, script file, or operable 
program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:631
+ ... if ($allPorts -notcontains $port.LocalPort){        pidToPort += , @{ ...
+                                                         ~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (pidToPort:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException"

Has anyone else ran into this issue on release 2.7.0?

**Comment by privateducky** [comment]
it looks like we have two abilities which can detect malicious port activity:
- 3b4640bc-eacb-407a-a997-105e39788781
- 1b4aa8d5-ba97-4b9b-92a3-eaaaffbfdf0a

For your case, you're hitting an error on the latter one (my guess is PowerShell version but we can check on this). Are you getting any response from the first ability (it is named 'Find unauthorized processes')?

**Comment by triznut** [comment]
On the Windows agent, I receive the following response from the 'Find unauthorized processes' ability - (Get-NetTCPConnection : No MSFT_NetTCPConnection objects found with property 'RemotePort' equal to '7011'). However, that ability does work (kills netcat) against the Linux agent.

For reference, I've tried this operation against two different style Windows 10 eval images that were recently pulled from MS sites.

**Comment by triznut** [comment]
Setup the netcat differently on the Win blue agent from what I thought it was asking in the task (thought it was just looking for a local listener on port 7011. Seem to be looking for a connection to a remote host on port 7011), and got it to successfully kill the running netcat process, however still not getting credit for completing of the task. Not sure what I'm missing at this point.

Find unauthorized process output:
Get-NetTCPConnection -RemotePort "7011" | where-object { write-host $_.OwningProcess }
4168

Kill rouge process output:
Stop-Process -Id 4168 -Force

**Comment by privateducky** [comment]
@scottctaylor12 @garunagiri since you guys have been going hard on the blue/response development-- can one of y'all test this out?

**Comment by garunagiri** [comment]
Thank you for bringing that to attention. The wording should require connecting to a remote port, that's been fixed now.

I'll be looking into the error with the "Find atypical open ports" ability.

As far as the training flag, I was able to get it to verify by creating a tcpclient that connected to a listener on port 7011. I wasn't able to reproduce the issue there. Did the "Incident Responder" operation both detect the unauthorized process connecting to port 7011 and kill it automatically?

**Comment by garunagiri** [comment]
There was a small error with the "Find atypical open ports" ability. It should be fixed now. https://github.com/mitre/response/pull/35

**Comment by triznut** [comment]
Correct. "Incident Responder" both detected the unauthorized process (netcat in my case) and killed it.

**Comment by garunagiri** [comment]
I attempted this again on a fresh install of release 2.7.0 and was able to complete those challenges successfully. Can you attempt to redo this challenge please? 
Try deleting the (all?) existing blue operation by using the 'Delete' button on the front end, and then start a new blue operation with the flag's conditions set up. Let me know if that fixes things for you.

**Comment by triznut** [comment]
After deleting all my previous attempts, and then running a fresh blue operation, it worked. It gave me credit for completing the challenge.
Appreciate all the help on this.
Thank you.
