### ISSUE TITLE
cmd executor (cmd.go) is not available in latest Caldera releases

### ISSUE THREAD

**Issue by EnJohnGee** [mitre/caldera#1708]
Hi,

If I'm not wrong, I have observed that since the 2.6.6 release the cmd executor is not present anymore in plugins/sandcat/gocat/execute/shells (I know the structure under gocat plugin has changed a lot since the previous releases but now I cannot see the cmd.go executor file included anywhere).

I have created some abilities before that used the cmd executor only that doesn't have a psh executor option and they are failing to execute now with the "Executor not Available" error message.

To replicate this issue with the current Caldera 2.7.0 release:
- create an adversary including only the "Account Discovery (all)" ability (https://github.com/mitre/stockpile/blob/eee7447db5c6c558f5cad216d58f096b11eabdf6/data/abilities/discovery/c7ec57cd-933e-42b6-99a4-e852a9e57a33.yml) a
- try to run an operation using this adversary

As a result, the ability will fail with the same error message described above, like in the following snapshot:
![image](https://user-images.githubusercontent.com/22646707/82954785-4d41f100-9f62-11ea-9a64-3fecb51369df.png)

By the way, I have fixed this issue in my local installation by copying the old cmd.go file to the new location and fixing the import function. After this I'm able to run abilities that uses cmd executor without issues:
![image](https://user-images.githubusercontent.com/22646707/83077467-50091880-a02c-11ea-94f9-a8e9ca55e7b3.png)

I'm wondering if this a bug or if you are planning to remove the cmd executor in the future?

Hope this helps,

Thanks!

**Comment by privateducky** [comment]
no, that may be a bug. it should not be removed -- but it is possible it was dropped when we transitioned repos a few weeks back.

I'll track down an answer here.

**Comment by privateducky** [comment]
OK answer here: to utilize the cmd executor, you'll need to ask for the cmd extension when you download the agent. check the new docs on this here:

https://caldera.readthedocs.io/en/latest/Plugin-library.html#sandcat-54ndc47

**Comment by EnJohnGee** [comment]
Awesome, thanks!
