### ISSUE TITLE
Question about modifying abilities through yml files

### ISSUE THREAD

**Issue by alexgumo7** [mitre/caldera#1713]
Hello,

I am having an issue modifying abilities. Specifically, I am modifying the `command` and `timeout` parameters. I have several abilities stored in `data/abilities/`, when I need to update them I stop the docker container, I modify the `.yml` and I start again the container in order to load them. 

If I check the ability when caldera is running I can see two different behaviours (I don't know when happens one or the other):
- The parameters related to the first executor are not updated.
- Same behaviour than the previous, but in addition, the `timeout` of the rest of the executors is not updated.

As a workaround to make tests I check the ability in the GUI and I update the `command` of the first executor, however, it is not possible to change the `timeout` of the abilities from the GUI and I would like this to be updated only through the ymls.

Thanks in advance

**Comment by privateducky** [comment]
I just merged in a change set that I think solves both of your problems:

1. You can now update the timeout field for abilities via the GUI
2. There is a new background process which runs every 60s, looking for any ability YML file updates. If found, it will update the ability.

https://github.com/mitre/caldera/pull/1716

**Comment by alexgumo7** [comment]
Hi,
Now the abilities are not loading at all. The abilities that I am creating in `data/abilities/' follow the format specified in https://github.com/mitre/caldera/wiki/What-is-an-ability.

**Comment by privateducky** [comment]
Ah that’s the problem: that documentation should be removed.

Use the docs that are in your caldera version itself: nav bar -> docs.

**Comment by privateducky** [comment]
I have now purged that wiki documentation. Let me know if you have any questions after following the docs located inside your caldera version itself (accessible via the nav bar).
