### ISSUE TITLE
Sandcat Agent problems

### ISSUE THREAD

**Issue by P4T12ICK** [mitre/caldera#1719]
Hello,

I'm using the release version 2.6.65 and the sandcat agent is running on a Windows Server 2016. Unfortunately, the sandcat agent is not working anymore for me. I got the following error message:
`````
Started sandcat in verbose mode.
server=http://10.0.1.12:8888
group=my_group
privilege=Elevated
initial delay=0
c2 channel=HTTP
Beacon API=/beacon
[+] beacon: ALIVE
[*] Running instruction task-402341
panic: interface conversion: interface {} is nil, not string

goroutine 1 [running]:
_/Users/davidhunt/Desktop/toolbox/caldera/plugins/sandcat/gocat/core.runAgent(0x7b55a0, 0x9c4b70, 0xc0000d1f20)
        /Users/davidhunt/Desktop/toolbox/caldera/plugins/sandcat/gocat/core/core.go:58 +0x8cc
_/Users/davidhunt/Desktop/toolbox/caldera/plugins/sandcat/gocat/core.Core(0xc00000c380, 0x15, 0xc00000a100, 0x8, 0x0, 0x0, 0x0, 0x0, 0xc0000d1ef0, 0x430100)
        /Users/davidhunt/Desktop/toolbox/caldera/plugins/sandcat/gocat/core/core.go:143 +0x539
main.main()
        /Users/davidhunt/Desktop/toolbox/caldera/plugins/sandcat/gocat/sandcat.go:35 +0x458
`````

I reviewed similar issues, but in their case, the problem was an old version of golang. In my case, I have a recent version of Golang:
`````
go version go1.13.11 linux/amd64
`````

Thank you for your help.

**Comment by privateducky** [comment]
yep-- this is always 1 of 2 things:

1) pre-1.13 version of GoLang installed on the CALDERA server
2) the CALDERA server code you are using is a different version than your agent. This could be because.. 

a) you changed some code locally, which is throwing something off... 
b) you think you have a version but in fact do not... 
c) you have version 2.6.5 of the server - but you're using an agent from a previous build

**Comment by P4T12ICK** [comment]
thank you for your fast response. 

1)
`````
root@ip-10-0-1-12:/var/_caldera/caldera# go version
go version go1.13.11 linux/amd64
`````

2) I use the powershell code from the wiki to download the sandcat agent from the caldera server, see version here:
`````
root@ip-10-0-1-12:/var/_caldera/caldera# cat VERSION.txt
2.6.65-82dc613d8037687eaaaac097edfe5a86
`````

a) I didn't change any code locally. I'm only use a local.yml config.
b) see 2
c) see 2

do you have an idea, what else it could be?

**Comment by privateducky** [comment]
the VERSION.txt file reports what version the server should be-- but if the code changes around it (say you modify any source code file) the VERSION.txt file won't know about it. 

from your description, most likely C (above) is your problem: "you have version 2.6.5 of the server - but you're using an agent from a previous build". if you had a previous instance of caldera and then upgraded to 2.6.65, this could definitely happen. lots of possible reasons: server code didn't update properly, an old copy of the agent file (sandcat.exe) was already present on the target system, etc.

the quickest solution would be to reinstall CALDERA, using version 2.7.0. in this version, we provide a new "startup errors" list, which will help identify any problem areas of your build.

**Comment by P4T12ICK** [comment]
I tried it with version 2.7.0 and you are right the output is more verbose. I got the following error message:
`````
can't load package: package github.com/google/go-github/github: cannot find package "github.com/google/go-github/github" in any of:
	/usr/local/go/src/github.com/google/go-github/github (from $GOROOT)
	/usr/local/go/bin/go/src/github.com/google/go-github/github (from $GOPATH)
2020-06-02 11:17:37 - ERROR (sand_svc.py:87 load_sandcat_extension_modules) Failed to fulfill dependencies for module <plugins.sandcat.app.extensions.contact.gist.GIST object at 0x7fd5c1246e80>
`````

I don't understand where this path comes from? my GOPATH is /usr/local/go/bin/go.

**Comment by privateducky** [comment]
cool-- that stack trace is on the server-side (vs the one you posted initially, which is client-side). I believe you can safely ignore this error.. does everything work normally?

**Comment by P4T12ICK** [comment]
yes the stack trace is on the server with go version 1.13.11 installed. Unfortunately, I still have the same problem. In this thread, the first code snippet was from a windows server, all other code snippets are from the caldera server on Ubuntu 18.04. 

There were no changes in the code and I never update because this is for the project Attack Range and we build the whole lab always completely new. I assume the problem depends on the last error message.

I'm working in the moment on this branch, in case you have some time to take a closer look into the issue and you can easily reproduce it by running the build command:
https://github.com/splunk/attack_range/pull/274

Thank you for your support.

**Comment by privateducky** [comment]
@P4T12ICK let me know if you're still facing the error above. I looked at the branch (above) but I may have been late to the party ;) as it looks like it got merged in.

**Comment by P4T12ICK** [comment]
Hi, the problem still exists and I still need your help. Yes it was merged because of some other features. I would be very happy if we can schedule a short trouble shooting meeting. Can you reach out to me on twitter: @bareiss_patrick 
Thank you very much.

**Comment by aaron-dadum** [comment]
Same here, the newest install of Caldera (2.7) Go lang 1.14 and the same problem. There is something wrong there. 

Also more informative error on the sandcat side would be a blessing.

**Comment by aaron-dadum** [comment]
Ok, so i resolved my problem. 
So, if you download a newer version of the server, make sure that on the client computer you delete splunkd.exe sandcat binary from c:/users/public, even though the ps script should download a new binary each time it's invoked. 
Maybe somebody would find it useful. 

Thanks.

**Comment by privateducky** [comment]
thanks!
