### ISSUE TITLE
Cannot start the server in insecure mode after starting it in default mode

### ISSUE THREAD

**Issue by b-u-g-s** [mitre/caldera#1735]
Hi,

I am new to this tool and have just started testing it. So my apologies is what I am reporting here is a dumb issue!

- Did a fresh cloning of the master branch on an updated Kali distribution.
- installed all the requirements with pip
- started the server using: python3 server.py
- Everything works... but then I decided I didn't need the complex password in a test environment
- Killed the server (control-C on the command line used to start it)
- started the server again with: python3 server.py --insecure
- I then get a lot of errors and the server does not want to start, it is complaining about some cryptography issues. 
- To fix it, I took the nuclear option to delete the git clone, reclone it, and then start with python3 server.py --insecure, and it works. 

This looks like a bug...  maybe some settings/config files are setup when running it in default/secure mode that then prevent the server to be started again in the insecure mode?
Am I not terminating my server the right way? (control-C)

Thanks.
B.

**Comment by privateducky** [comment]
Nah, CTL-C is the "normal" way to kill the server for most of us. 

Your steps are normal and should work OK (in fact, I swap between secure/insecure as well). 

I believe the one thing you're likely missing is including the --fresh flag on start-up. This flag wipes out the in-memory database between reboots, and if you're changing authentication configurations, you'll need to use it when you do the swap.

**Comment by b-u-g-s** [comment]
Didn't know about the --fresh flag! it does the trick!
Thanks for that :)

**Comment by privateducky** [comment]
great!
