### ISSUE TITLE
The agent is not setup with my server IP address

### ISSUE THREAD

**Issue by b-u-g-s** [mitre/caldera#1736]
Hi,

Again, new to this as stated in the previous issue.
I hope I am posting this in the right place!

From a fresh install from master, logging in as red.
I go to deploy an agent and the code uses "http://0.0.0.0" and not the ip address of the server.
Everything works, I just need to change the 0.0.0.0 to the server IP address.

But the question is:
Why doesn't it offer the IP address of the server by default? 
it would make it so much easier to just copy and paste.
Asking this because I just watched a demo on 2.4.0 and it looked like the guy doing the demo had his server IP address by default.

Might be a config file to change, but just feels like it should be enabled by default/in the GUI.

Thanks,
B.

**Comment by privateducky** [comment]
CALDERA server offers "contact points" for agents to utilize to communicate with it. The most common one, is the HTTP contact point, which agents can send beacons to and which will return a set of instructions for the agent. 

Most contact points have a configuration (available in default.yml):
```
app.contact.html: /weather
app.contact.http: http://0.0.0.0:8888
app.contact.tcp: 0.0.0.0:7010
app.contact.udp: 0.0.0.0:7011
app.contact.websocket: 0.0.0.0:7012
```
These values can either be changed in the file itself - or you can change them via the Advanced tab from the UI.

When you choose an agent via the "Click here to deploy a new agent" button, CALDERA server locates the ability YML file for the agent, then swaps out the contact point variable for the address listed in the config file. For example, here is the Linux command for Sandcat:
```
server="#{app.contact.http}";
curl -s -X POST -H "file:sandcat.go" -H "platform:linux" $server/file/download > sandcat.go;
chmod +x sandcat.go;
./sandcat.go -server $server -group red -v
```

In older versions of CALDERA, we simply took the address listed in the browser and swapped the variable there. However, in almost every realistic red-team event, we deploy CALDERA behind proxies, making it inaccurate. In addition, there are cases for wanting an agent to connect via various interfaces (maybe the IP address, maybe the FQDN, etc.). 

To cover these cases, I designed the contact points, each with a configurable address value. That value can be changed on the fly - to anything - then when you re-open the agent deployment module, the command will be accurate. No more cases of mis-typing or forgetting to change one value in a longer command, etc.

**Comment by b-u-g-s** [comment]
Thanks for the explanation, it make sense and I will just edit the YML file going forward.
