### ISSUE TITLE
Custom Ability - Operations Failed but working

### ISSUE THREAD

**Issue by b4b857f6ee** [mitre/caldera#1741]
Hello,

Caldera 2.7.0 on Ubuntu 18.04.

I have create a custom Ability with a regsrv32 sct download execution etc... with other powershell session...
When i run the Operations, even if in real this is working i have a red mark for failure because he has no return.
How to run this command, let the command run x time and after launch de clear command and get the success mark. I have to return something?

My error message is [Errno 11] Resource temporarily unavailable for my first command how launch my regsrv32 in powershell.

Thank you in advance.

**Comment by privateducky** [comment]
questions:
1. if you run an operation using an existing adversary (say Hunter) does everything work normally? 
2. are you using the 54ndc47 agent or a different one?
3. the error message you posted, is that appearing on the agent or server side?

**Comment by Michealpool** [comment]
Hello,

 i am also getting the same error, by using my custom adversary and existing adversary (discovery) . The agent i am using is "myujio" and "54ndc47".

Kindly guide.

**Comment by b4b857f6ee** [comment]
No don't remove it xD.
Same as Michaelpool,
It's on the server side, even if the command is running on the client.
