### ISSUE TITLE
Troubleshoot Operations

### ISSUE THREAD

**Issue by Zeik0s** [mitre/caldera#1742]
When i'm creating Operations, sometimes it stays at zero Percent and never does a thing. Do you have some tips for troubleshooting? It happens on Kali as well as Ubuntu. 
It seems to me, that it happens when i'm selecting ttps for Windows and the Commands run on an Ubuntu Machine, but i thought this was Os-agnostic?

**Comment by privateducky** [comment]
This isn't just you-- this has been annoying me for a little while actually.

The percentage complete bar is a little tricky to compute, as it can be done a few different ways. As in, before an operation, we really don't know what 100% means, as new agents could join the operation, or not be able to complete specific abilities, or have abilities that can repeat, etc. 

If you want to take a look, the operations.html page contains the logic (JavaScript function called changeProgress) to compute the progress bar. I'm definitely open to a better computation!

**Comment by Zeik0s** [comment]
oh sorry, i noticed that, but didn't refer to. Because there are scenarios, where ttps are executed on the agents, but in this particular scenario they aren't. So they also don't show up below the progress bar. In my case there was nothing executed.

**Comment by privateducky** [comment]
ah- gotcha. for that type of issue, it's likely your adversary profile has TTPs that your agent(s) in the operation cannot execute. 

download the operation report and it should contain reasons why each TTP was skipped.
