### ISSUE TITLE
sandcat_extension_modules loading issue

### ISSUE THREAD

**Issue by Michealpool** [mitre/caldera#1745]
Hello,
 i am new to Caldera. after complete installation everything working perfect, i can login and run operations but cant see any progress in percentage on Bar. It always show zero. When i run server.py file i am getting below error. kindly guide.

============================================
ERROR (sand_svc.py:87 load_sandcat_extension_modules) Failed to fulfill dependencies for module <plugins.sandcat.app.extensions.contact.gist.GIST object at 0x7fe88327d438>

**Comment by privateducky** [comment]
ah yes- that progress bar has been broken for a hot minute. would love someone to patch it by the way (it is on the operations.html page if you have an interest ;))

**Comment by privateducky** [comment]
per the GIST error: that's one you can disregard. that (should be) fixed in the latest 2.7.0 version.
