### ISSUE TITLE
Question about agents

### ISSUE THREAD

**Issue by RalucaPreda** [mitre/caldera#1754]
Hello,

I have a question about the Sandcat agent and specifically about the connection security between server and agents. I am using version 2.5.0 and have noticed the agent use a random port to connect to the server. One of the older types of agents required a certificate for connection.
Thank you!

**Comment by privateducky** [comment]
the agent, even on v2.5.0 should use port 8888 to connect to the server. it uses HTTP by default (no cert) but you can load the SSL plugin and convert your agent to using a certificate (https). 

https://caldera.readthedocs.io/en/latest/Plugin-library.html#ssl

that plugin contains a self-signed certificate - but we give instructions on how to swap to your own cert:
