### ISSUE TITLE
[Security] Cross Site Scripting in the operation name value

### ISSUE THREAD

**Issue by Dfte** [mitre/caldera#1755]
Hello,

I was playing with your framework when i came across a XSS in the Operation Name box:
payload: <script>alert()</script>

![image](https://user-images.githubusercontent.com/23189983/84663443-7af4d700-af1d-11ea-962c-7b1e33c35d65.png)

I have no idea if you guys are interested in that type of vulnerability but i thought it would be nice to inform you anyway :) !

Have a good day,
Defte

**Comment by privateducky** [comment]
thanks! 

because caldera is designed as a single-user application, we tend not to prioritize things like this. but -- it's a great find -- and we'd love to fix it. I'll keep this issue open until either we, you or another person in the community pushes a fix. just so it stays in mind.

**Comment by Dfte** [comment]
Okay! Thanks for responding :)
