### ISSUE TITLE
[Agent] - Proxy system proxy

### ISSUE THREAD

**Issue by b4b857f6ee** [mitre/caldera#1758]
Hello,

I don't know if i miss it in the documentation but i can't find if we can ask to the agent to use the system proxy to work on a target using a proxy.

Thank you :)

**Comment by privateducky** [comment]
https://caldera.readthedocs.io/en/latest/Plugin-library.html

check this doc page out, specifically on the 54ndc47 plugin area, related to proxies.

let me know if this helps.

**Comment by b4b857f6ee** [comment]
Ok thank you!

I will try it.

**Comment by b4b857f6ee** [comment]
@privateducky 
I manage to modify the powershell script to include the proxy_http but this is change nothing..
![image](https://user-images.githubusercontent.com/36012515/85513022-dfd5be80-b5fa-11ea-8e1f-ff7ff870507a.png)

This is the debug on the server side (Download the payload but the payload don't use the proxy):
![image](https://user-images.githubusercontent.com/36012515/85513136-fe3bba00-b5fa-11ea-84c0-19cf5189b4d8.png)

**Comment by b4b857f6ee** [comment]
No idea? :/

**Comment by b4b857f6ee** [comment]
I upgrade the golang from 1.10.4 to 1.14.2 but nothing change :/

**Comment by b4b857f6ee** [comment]
On the server side : 
![image](https://user-images.githubusercontent.com/36012515/89042287-faf8c400-d346-11ea-9206-584efbcfe01a.png)

**Comment by unkempthenry** [comment]
Hi @b4b857f6ee , 

I think we didn't read your question correctly the first time -- the *_proxy agent extensions are for enabling chaining the C2 through multiple agents.

To have your agent connect to caldera through an http proxy, you should be able to set the `HTTP_PROXY` environment variable for the agent.  In the powershell session before launching sandcat: ```$env:HTTP_PROXY = 'http://proxyhost:proxyport'```

Hope this helps!

**Comment by DaveTheKiller** [comment]
Hello, I have the same problem, but it doesn't work for me. Maybe because I have a proxy with authentication. 

I tried to put proxy settings in .NEt webclient, but nothing.

Do you have any idea?

Thanks!
