### ISSUE TITLE
Caldera stuck after running few abilities

### ISSUE THREAD

**Issue by RK101** [mitre/caldera#1764]
Hi , 
I have created a new profile with different abilities from APT3 group techniques. The profile has about 22 abilities but when I run the profile , it runs about 10 of them and then it gets stuck. It is not failing, not stopping.. 
I am running the operation against Windows 10 VM. The agent I am using is Sandcat. 

How can I debug/figure out why it is not moving ahead ?

Thanks much in advance

**Comment by privateducky** [comment]
when you run the operation, you can decide whether to "stay open forever" or stop when complete. by default, it does the former. this is to allow you (the operator) to add "potential links" to the operation at any time, including after the adversary has completed. 

to determine why only 10 abilities are running, you would need to download the operation report. this should give a reason for each skipped ability. it is likely either the operating system/executor doesn't match, or the ability has variables which are not available.
