### ISSUE TITLE
Caldera Operations not working

### ISSUE THREAD

**Issue by bcn428** [mitre/caldera#1769]
I have installed caldera on my ubuntu machine and deployed the sandcat agent in two other ubuntu machines. I can see the agents active in Caldera browser. However, when i am trying to perform any operation using existing profile or by creating new profile there is no results. 
The progess bar remains at 0% ( with gray color code i.e queued ) for long time(~30 mins) . 
In the Caldera VM , below messages is displayed:
  2020-06-29 18:45:37 - DEBUG (planning_svc.py:158 get_links) Generated 0 usable links
2020-06-29 18:45:37 - DEBUG (planning_svc.py:158 get_links) Generated 0 usable links
2020-06-29 18:45:56 - DEBUG (planning_svc.py:158 get_links) Generated 0 usable links
2020-06-29 18:45:56 - DEBUG (planning_svc.py:158 get_links) Generated 0 usable links
<img width="1268" alt="Screen Shot 2020-06-29 at 10 52 37 PM" src="https://user-images.githubusercontent.com/66545827/86081711-956d9b00-ba5b-11ea-9098-d904eebf063d.png">

Can someone please help me to troubleshoot the issue.

**Comment by tootsierollpop81** [comment]
I'm new to Caldera myself, but I believe that I read somewhere that each adversary profile, like Hunter, Nosy Neighbor, etc, has a certain OS that it works with.  You may want to look at each Adversary profile and make sure it matches up with the type of host you want to attack.  You have to have agents loaded before hand to do anything in here.  If you look at your screenshot, it doesn't show agents loaded.  Also of note, if you set it to Keep it open forever in the Basic Options, you can manually select commands to run by clicking on potential links in your picture and selecting them from a list of abilities.   Of course, this may've been old information, so don't quote me on that.

**Comment by wbooth** [comment]
This is expected behavior though we will add an exhausted abilities alert to show there are no more abilities that the adversary can run. you can download the operation report to see why abilities were skipped.
