### ISSUE TITLE
Deployed agents become untrusted

### ISSUE THREAD

**Issue by alexgumo7** [mitre/caldera#1771]
Hello,

I am having an issue with deployed agents, in release 2.7.0. I am deploying the 54ndc47 agent to a Windows machine. Caldera recognises the new agent the first time:

```
caldera_1                    | 2020-06-30 08:20:29 - DEBUG (contact_svc.py:56 handle_heartbeat) First time http beacon from ytoluc
```

But then it doesn't receive more beacons and after 151 seconds, the agent becomes untrusted.

```
caldera_1                    | 2020-06-30 08:23:00 - DEBUG (app_svc.py:49 start_sniffer_untrusted_agents) Agent (ytoluc) now untrusted. Last seen 151 sec ago
```

Is there any solution for this behaviour?

Update:
I come from using the release 2.6.6 to the 2.7.0. I've tried the following solution: https://github.com/mitre/caldera/issues/1719#issuecomment-646574584 but it does not work.

Moreover, I am deploying caldera with docker in linux. Logs at start are the following:
```
caldera_1                    | 2020-06-30 11:59:03 - ERROR (base_world.py:147 check_requirement) FileNotFoundError(2, 'No such file or directory')                                            
caldera_1                    | 2020-06-30 11:59:03 - ERROR (app_svc.py:134 validate_requirement) go does not meet the minimum version of 1.11                                                 
caldera_1                    | 2020-06-30 11:59:03 - DEBUG (data_svc.py:62 restore_state) There are 0 jobs in the scheduler
caldera_1                    | 2020-06-30 11:59:03 - DEBUG (contact_svc.py:34 register) Registered contact: http
caldera_1                    | 2020-06-30 11:59:03 - DEBUG (contact_svc.py:34 register) Registered contact: udp
caldera_1                    | 2020-06-30 11:59:03 - DEBUG (contact_svc.py:34 register) Registered contact: tcp
caldera_1                    | 2020-06-30 11:59:03 - DEBUG (contact_svc.py:34 register) Registered contact: websocket
caldera_1                    | 2020-06-30 11:59:03 - DEBUG (contact_svc.py:34 register) Registered contact: html
caldera_1                    | 2020-06-30 11:59:03 - DEBUG (contact_svc.py:34 register) Registered contact: gist
caldera_1                    | /bin/sh: 1: go: not found
caldera_1                    | 2020-06-30 11:59:03 - ERROR (sand_svc.py:87 load_sandcat_extension_modules) Failed to fulfill dependencies for module <plugins.sandcat.app.extensions.contact.g
ist.GIST object at 0x7f991bef8df0>
```

I have the same problem than in https://github.com/mitre/caldera/issues/1719#issuecomment-637503766 where it's explained that this error can be safely ignored.  I've checked the go version in my linux and it is `go1.13.4`.

Thanks in advance.

**Comment by alexgumo7** [comment]
Hello,

I've been testing this behaviour with docker. At first I thought that go didn't meet the version requirements as stated in the error log. Checking the version of golang that would be installed with ubuntu:bionic that is specified in the Dockerfile I can see that it would install the version 1.10. However, entering in the bash of the docker container if I check the version of go with `go version` it doesn't find go at all, like if it's not installed.
Then, checking the `docker-compose.yml` I've seen that it isn't using the Dockerfile but using a `python:3` image. The Dockerfile is being used? Is go really being installed?

SOLUTION:
To solve the problem the `docker-compose.yml` has to be modified, the command has to include the installation of golang:
```
command: /bin/bash -c "apt update && apt install golang -y && pip install --no-cache-dir -r requirements.txt && python server.py --fresh --insecure"
```

**Comment by ciphrbrkr** [comment]
One of the multiple issues I experienced with version 2.7.0. I reverted to using 2.6.6. Did not find a solution.
