### ISSUE TITLE
Question About Customizing Victim Host

### ISSUE THREAD

**Issue by michael-hahn** [mitre/caldera#1779]
Hello:

I am wondering if it is possible to customize the victim host to e.g., add an EDR in the host?
I wasn't able to find any documentation on setting up a victim host. Can you provide some pointers?

Thank you!

**Comment by wbooth** [comment]
Though caldera isn't focused around environment builds -- You may want to start a blue agent and install the edr as an ability/adversary.
Otherwise you may want to use some config mgmt tool to achieve this.
