### ISSUE TITLE
Exfiltration folder encrypted

### ISSUE THREAD

**Issue by nrenou** [mitre/caldera#1786]
Hello, 
I have a problem with with decrypting the exfiltration folder ( .zip) . 
The exfiltration file is encrypted on the /tmp folder, I used the script file_decryptor.py to decrypt it  but i have this error : 

![image](https://user-images.githubusercontent.com/59913568/87672696-a1539f80-c773-11ea-8376-7bbd2a2b8856.png)

I tried using all the different option for this script but I always have the same error.

**Comment by wbooth** [comment]
Ensure you are using the correct encryption key: https://github.com/mitre/caldera/blob/master/conf/default.yml#L11
if you generated a config you will need to use the key from that one instead of from the default.yml
