### ISSUE TITLE
README says to use python instead of python3

### ISSUE THREAD

**Issue by anon8675309** [mitre/caldera#1787]
As a new user, I wanted to install and try out Caldera.  I started with a fresh Debian 10 installation and found that `pip install -r requirements.txt` failed to find any of the required packages, and `python server.py --insecure` failed to run the web server.

I'm attaching a log of all the commands I ran so it's clear where new users will run into problems, to provide the perspective of a new user.

The fix is simply to use pip3 and python3 and I'll submit a pull request to update the documentation so new users have a smoother on-boarding experience.

[install.log](https://github.com/mitre/caldera/files/4932050/install.log)

**Comment by privateducky** [comment]
Thanks @anon8675309; we reference needing Python 3.6.1+ in the README but have the start up command listed as "python server.py" as you reference. This is intended to be generic, as the executable name could either be Python3 or Python, depending on the system used. We opted for the generic term -- but I can see where that could be confusing. I'll update the readme to have a note in that area for this.
