### ISSUE TITLE
Operations uses bad colors for color-blind people

### ISSUE THREAD

**Issue by GanbaruTobi** [mitre/caldera#1791]
Hi,

the Operations-Tab uses green for success and red for failure.
This cant be seen for many ppl as different colors.

I suggest using colors seen in this article bottom:
[davidmathlogic.com/colorblind](https://davidmathlogic.com/colorblind/#%23D81B60-%231E88E5-%23FFC107-%23004D40)

Tell me if you like the idea, and if you need help implementing.

Tobi

**Comment by wbooth** [comment]
Thanks Tobi, absolutely -- we're happy to make a change like this. if you have the implementation in mind please feel free to put up a PR.

**Comment by GanbaruTobi** [comment]
![image](https://user-images.githubusercontent.com/15239745/87934461-6319f100-ca8f-11ea-831f-ff250b809eb3.png)

This is what my color schema would look like in the app. It is a combination from figure 3 and 4 from this artikel:

[paul tol's schema](https://personal.sron.nl/~pault/)

Personaly, I would go for one color-schema to use instead of an more advanced solution like a change button in the config tab. But if there is no generaly accepted schema i would implement three to choose from.

Right now I got feedback from one colorblind person, so if anybody reads this with colorblindness, please tell me if you can see the differences. 

This is what the timeline looks like (did only catch success, failure and queue yet):
![image](https://user-images.githubusercontent.com/15239745/87936093-8b571f00-ca92-11ea-8a50-4d82dfd530f3.png)

**Comment by GanbaruTobi** [comment]
Created Pull-Request #1827

**Comment by wbooth** [comment]
thank you! merged.
