### ISSUE TITLE
Scoping variables not working as expected

### ISSUE THREAD

**Issue by alexgumo7** [mitre/caldera#1794]
Hello,

I have noticed a behaviour that I did not expect regarding scoping variables (explained in https://github.com/mitre/caldera/issues/843#issuecomment-560486955), using release 2.7.0. I will focus on the example that I have been using to test this behaviour:

Operation with two agents.
Adversary with two abilites:
- *Find files* ability (ID: 90c2efaa-8205-480d-8bb6-61d90dbaf81b)
- Custom ability that simply echoes the generated fact by the previous ability, that uses the following command: `echo #{host.file.path}`.

The first ability finds files and generates facts (with trait `host.file.path`) containing these files. Then the following ability should  use the facts only in the hosts that collected the facts. However, **all the facts with that trait are being used on all the agents although the facts are generated with the trait beggining with `host`**.

To be clear, in the example I have two agents: tfenaf and jslzxk. The first link generates a fact collected by tfenaf, the link of agent jslzxk does not generate any fact.

![image](https://user-images.githubusercontent.com/23341546/87950487-a1bba580-caa7-11ea-9b31-54badeb9b0ce.png)

Then in the next ability, as the only host that has generated a fact is tfenaf, it should only generate a link for tfenaf. However, there is also a link generated for jslzxk using the same fact as tfenaf:

![image](https://user-images.githubusercontent.com/23341546/87950530-b0a25800-caa7-11ea-92ef-587581cd58c7.png)

The example uses atomic planner, although I have also tested it with a custom planner based on buckets and the behaviour is the same.

This behaviour didn't happen when I tested it in release 2.6.6, I wonder if something has changed regarding scoping variables.

Thanks in advance

**Comment by alexgumo7** [comment]
Any update on this issue?

**Comment by elegantmoose** [comment]
Hi @alexgumo7, apologies for the delayed response, we have been busy on other fronts.

You are correct, currently we are not enforcing that scoping of facts in that manner but it is a natural policy that should be available to enforce, especially given you stated it was at least appearing to be enforced in older versions. The fact scoping policy is in need of some thought as in your case the fact is not wanted to be used across all agents but in other cases the opposite is desired.

At the moment, we do not have an immediate fix but this is on our radar and we will be looking into.

**Comment by alexgumo7** [comment]
Thanks for the response. In my case it's really necessary the scoping of facts. Could you indicate how could I add this behaviour to my version of caldera? At least the functions that were used in past versions to enforce the scoping of facts.

Thanks in advance.

**Comment by b17zr** [comment]
The `trim_links()` method in https://github.com/mitre/caldera/blob/master/app/utility/base_planning_svc.py uses `operation.all_facts()` to define the facts which will be passed to the command. It should be possible to re-create this method's functionality in a custom planner and use `[fact for fact in operation.facts if fact.collected_by == agent.paw]` (untested) in its place. Or modify `base_planning_svc.py` itself.

**Comment by wbooth** [comment]
@alexgumo7 We've gone back and forth on this in the past. Variables are working as expected. We are currently keeping them less restricted. As @b17zr suggests, the best option is to implement a custom planner. We are happy to help you with this if you have questions.
