### ISSUE TITLE
Cannot Add a new Adversary

### ISSUE THREAD

**Issue by adimenia** [mitre/caldera#1799]
Hello
i've installed Caldera official release 2.7.0 on Ubuntu 20.04 LTS. I'm using chrome Version 84.0.4147.89 (Official Build) (64-bit)
when starting up Caldera and trying to add a new ability to a new adversary I'm getting the following errors 
when inspecting the HTTP 
![image](https://user-images.githubusercontent.com/5006200/88167677-e1a69800-cc21-11ea-853a-3e4386ed2624.png)

**Comment by fuckup1337** [comment]
Have u swiped the slider from view to add? 
![add](https://user-images.githubusercontent.com/31011703/88289879-33205700-ccf6-11ea-8453-b585ed5956b3.png)

**Comment by adimenia** [comment]
embarrassing :) thanks for pointing that out
