### ISSUE TITLE
Blue is not Detecting 

### ISSUE THREAD

**Issue by tombuttler12** [mitre/caldera#1804]
When I run Gameboard, the blue side never catches anything that the red side is doing. The only time there is ever anything caught is when I use batch planner on the blue side operation. The only thing that is being caught however, is the netcat I'm running which I understand is necessary to run a blue operation.

What am I doing wrong?

Thank you.

**Comment by wbooth** [comment]
Please ensure that the blue agent is running, then check the auto-collect operation that is started and that should have a step for each red step that was taken. Please also ensure that you are logged in as the blue user in order view the actions properly
