### ISSUE TITLE
Sandcat on Windows becomes untrusted

### ISSUE THREAD

**Issue by tombuttler12** [mitre/caldera#1806]
For some reason, the sandcat agent on the windows machine becomes untrusted. I am not sure what is causing this. What am I doing wrong?

Thank you.

**Comment by alexgumo7** [comment]
Hi, check this https://github.com/mitre/caldera/issues/1771#issuecomment-652360582, it's probably a problem of golang. If this doesn't solve the error, can you show the server log?

**Comment by tombuttler12** [comment]
Hi @alexgumo7 , 

I am using the most up to date version of golang, but I think you are onto something. I might be doing something incorrectly here. I am not using docker however. I am not sure that #1771 is applicable. I have looked at #1719  and simply deleting the already existing sandcat binary does not seem to work either. 

I am getting errors that say:

ERROR (baseworld.py:147 check_requirements) FineNotFoundError(2, "No such file or directory: 'go'")
ERROR (app_svc.py:134 validate_requirements) go does not meet the minimum version of 1.11

There is an error stating that sandcat is not able to fulfill dependencies further down the server log. 

I am using go1.14.6. This is confirmed when I type 'go version'. go is also in my PATH.
