### ISSUE TITLE
Question to Training: Operations

### ISSUE THREAD

**Issue by fuckup1337** [mitre/caldera#1811]
Hi flag0 for Operations is "Run a new operation, using the Hunter profile and select any group of agents".
If I do that the Challenge is not solved for me. The operation runs through until finished (if i choose to end automatically). I tried many different options for the Operation. Is there something I maybe missing?

Thanks!

**Comment by b17zr** [comment]
Sounds like the operation closed error was solved by https://github.com/mitre/caldera/pull/1809/commits/56c5ad6cb78e3225eb364ae4390aee9612120420 . Feel free to close the issue.

**Comment by fuckup1337** [comment]
Thanks for the help !
