### ISSUE TITLE
Atomic: plugin code is not a release version

### ISSUE THREAD

**Issue by HarveyVega** [mitre/caldera#1815]
I am walking through the training plugin and am working on Flag 26. In the configuration tab all Plugins show a version of 2.7.0 with the exception of atomic which shows a version of None. 

caldera/plugins/atomics/VERSION.txt shows
2.7.0-3f66bafae19b7ef1484ca0e4775ca8c9

Also, when I spin up server.py there is an error that is thrown after enabling the atomic plugin:
ERROR (c_plugin.py:71 enable) Error enabling plugin=atomic, 'NoneType' object is not iterable

**Comment by wbooth** [comment]
Thanks, this issue has been addressed in the latest version of caldera and there will be a new release shortly.

**Comment by vbastomp** [comment]
@wbooth has this issue been resolved and in what release? thank you
