### ISSUE TITLE
Sphinx-Build, Stockpile and Sandcat ERRORS

### ISSUE THREAD

**Issue by AppGuard** [mitre/caldera#1817]
Environment:

- Kali Linux 64-bit VMware pre-created virtual machine obtained from Offensive Security download page and imported into VMWare Workstation Pro 15.5.
- Kali Linux 64-bit _**fully updated and upgraded**_.
![JEFFKALI](https://user-images.githubusercontent.com/65809607/88921048-d6fc8c00-d23b-11ea-8d3f-bb2ec39888e2.PNG)
- GoLang _**installed from the Kali Linux repo**_.
```
set GOPATH
export GOROOT=/usr/lib/go
export GOPATH=$HOME/go
export PATH=$GOPATH/bin:$GOROOT/bin:$PATH
```
- go version go.1.14.4 linux/amd64
- python3 version 3.8.5 (with PIP3)
- Caldera 2.7.0 installed to /caldera

Upon executing the Caldera server in /caldera using "python3 server.py --insecure" the following errors are returned every single time (and they're being reported by others):

![CALDERAERRORS](https://user-images.githubusercontent.com/65809607/88917086-2ee3c480-d235-11ea-8de2-d27cd7a0a445.PNG)

Are these error messages an indicator of actual problems or breakages in Caldera 2.7.0 ?

**Comment by prashantvidja** [comment]
I am also getting same error for version 2.7.0!

**Comment by AppGuard** [comment]
Reply from Caldera contributors or maintainers ?

**Comment by bademidov** [comment]
I am also getting the same errors on 2.7.0 and 2.6.65 (Ubuntu 18.04.4)

**Comment by elegantmoose** [comment]
Hi @AppGuard , @prashantvidja , @bademidov. Apologies for delay, we've been a little busy.

Regarding the sphinx-build (i.e. docs compiling) error, we also get those depending on what platforms we run on. It's on our TODO, but it is not at all a critical error.

Regarding the sandcat error, a fix was pushed for that, but it is in the bleeding edge (master branch) not 2.7.0. So you will have to re-pull, apologies for inconvenience.

**Comment by AppGuard** [comment]
A big "Thank you" shoutout to the contributors and maintainers.

**Comment by unkempthenry** [comment]
@AppGuard , thanks for providing so much detail in your initial report -- it definitely made it easy to reproduce the docs issue you ran into. 

Currently, fieldmanual calls the `sphinx-build` binary to build the docs -- however it looks like depending on the OS, `sphinx-build` doesn't always wind up on the PATH when it is installed with pip and in this case the result is the "No such file or directory error" you saw. 

**(long term fix)** I think I figured out a good way to call sphinx directly without needing to look up the binary on the PATH, but that solution still needs to make it through our review process (see https://github.com/mitre/fieldmanual/pull/20 ). 


**(simple fix)** The immediate fix is to get it on your path -- when I tested this on a new Kali vmware image, it wound up in `~/.local/bin`, so adding this directory to your PATH variable should allow the docs to build (I'd double check that `sphinx-build` wound up there for you).  


**(virtualenv fix)** Another workaround is to install sphinx and the other caldera dependencies into a Python virtualenvironment (this is actually a good practice to use in general when you're running multiple Python applications in the same environment as it avoids dependency conflicts).  Virtual environments manage a lot of the python-related environment variables and should make sure that pip-installed binaries are accessible.  This does add a little complexity to the process though, so totally understandable for folks wanting to stick to the simple installation procedure in the readme.  If you're interested here are the commands to get set up with a virtualenv: 

```
# make sure venv is present as it doesn't come with Python by default on debian downstreams
sudo apt-get install python3-venv

# create a venv to store caldera's dependencies in your home dir
python3 -m venv ~/caldera_venv

# activate the venv -- any call to pip / python in this shell will go through this isolated environment (this command needs to be executed once for every new shell / session that launches caldera)
source ~/caldera_venv/bin/activate

# cd to caldera dir, install requirements and start caldera 
cd /path/to/caldera
pip install -r requirements.txt
python server.py  --insecure
 ```

**Comment by wbooth** [comment]
This issue should be addressed. Thank you for brining this up and the detailed ticket. If it persists or have further questions please re-open this ticket or feel free to open a new one!

**Comment by AppGuard** [comment]
So what is the fix ?

Where is the step-by-step how-to ?

On my KALI system, I had to install Caldera to /Caldera and also I had to change all directory and subdirectory\objects to rwxrwxrwx - which is documented nowhere in the Caldera documentation.

From your short term fix description, it is not clear at all what is supposed to be added to PATH. What - the entire /usr/local/bin directory ? That doesn't seem correct.

All of us out here in user land (from Level 1s right up through Level 3s) would surely appreciate detailed step-by-step how-to instructions.

Thank you

**Comment by AppGuard** [comment]
I do not know what you mean by pulling anything. I do not use Git. I don't know it. And I don't have time to research it.

I don't understand what fieldmanual has to do with the issue reported here. It isn't clear from what you are saying.

What is a pin ?

I don't want to use Master due to MITRE saying there is all kinds of bugs. I want to use only stable.

I added ~/.local/bin to PATH as instructed and now there are additional errors and the Caldera server cannot bind to the VM ip address.

![Cap1](https://user-images.githubusercontent.com/65809607/95908107-8bea1380-0d6a-11eb-9ed3-48c5ea2d15ff.PNG)

![Cap2](https://user-images.githubusercontent.com/65809607/95908225-c18efc80-0d6a-11eb-9546-2b8748cb2cf6.PNG)

**Comment by AppGuard** [comment]
After adding ~/.local/bin to PATH as instructed and a KALI reboot, Caldera is borked:

![Cap3](https://user-images.githubusercontent.com/65809607/95909011-d0c27a00-0d6b-11eb-8b32-15490a5a8fc9.PNG)

**Comment by AppGuard** [comment]
Please use only a fully updated and upgraded KALI VM. Using an old unpatched, unupdated VM is not going to reveal the issues reported above. I keep all the VMs fully up to date all the time.

**Comment by AppGuard** [comment]
OK here are the fixes...

1. Install Caldera 2.8.1 on a clean KALI Linux VM fully updated & fully upgraded
2. To add ~/.local/bin to PATH, add the following lines to ~/.bashrc (NOTE: adding the lines to ~/.profile should work, but it does not):
![Cap2](https://user-images.githubusercontent.com/65809607/95921688-beead200-0d7f-11eb-88de-fcad9973c179.PNG)
3. Voila !
![Cap3](https://user-images.githubusercontent.com/65809607/95921813-f8bbd880-0d7f-11eb-99b6-24e2102f0ac1.PNG)

**Comment by AppGuard** [comment]
What is the easiest way to upgrade Caldera without using the MASTER repo ?

Just delete ~/caldera and then reinstall by issuing command “sudo git clone https://github.com/mitre/caldera.git --recursive --branch x.x.x” where x.x.x = current Caldera "stable" ?

I'd prefer not to dive into the Git stuff just yet.

Thanks all. Sorry for prior confusion.

**Comment by unkempthenry** [comment]
So, I just tested this out. 

My VM (same as yours): 

```shell
kali@kali:~$ grep VERSION /etc/os-release 
VERSION="2020.3"
VERSION_ID="2020.3"
VERSION_CODENAME="kali-rolling"
kali@kali:~$ uname -a
Linux kali 5.7.0-kali1-amd64 #1 SMP Debian 5.7.6-1kali2 (2020-07-01) x86_64 GNU/Linux
```

**Test installing to `/caldera` and running with sudo (use sudo for everything) :** 

Note: caldera expects to be able to write to its directory, therefore if you want to run it as a non-root user, you'll need to make sure that the user that runs caldera has write-access to the files. I'll typically install it under a local user's home directory (e.g. /home/kali ), if you prefer it to live under `/caldera` you'll need to do some fiddling with permissions.  

(python3, python3-pip, golang, already installed in this example)

```shell
sudo git clone https://github.com/mitre/caldera.git --recursive --branch 2.8.1 /caldera
cd /caldera
sudo pip3 install -r requirements.txt 
sudo python3 server.py --insecure
```

The above works for me: 

```
kali@kali:/caldera$ sudo python3 server.py --insecure
2020-10-13 17:53:22 - WARNING (server.py:83 <module>) --insecure flag set. Caldera will use the default.yml config file.
2020-10-13 17:53:22 - INFO  (server.py:90 <module>) Using main config from conf/default.yml
2020-10-13 17:53:23 - INFO  (app_svc.py:107 load) Enabled plugin: sandcat
2020-10-13 17:53:23 - INFO  (app_svc.py:107 load) Enabled plugin: fieldmanual
2020-10-13 17:53:23 - INFO  (app_svc.py:107 load) Enabled plugin: response
2020-10-13 17:53:23 - INFO  (app_svc.py:107 load) Enabled plugin: access
2020-10-13 17:53:23 - INFO  (app_svc.py:107 load) Enabled plugin: atomic
2020-10-13 17:53:23 - INFO  (app_svc.py:107 load) Enabled plugin: training
2020-10-13 17:53:23 - INFO  (app_svc.py:107 load) Enabled plugin: gameboard
2020-10-13 17:53:23 - INFO  (app_svc.py:107 load) Enabled plugin: compass
2020-10-13 17:53:23 - INFO  (app_svc.py:107 load) Enabled plugin: manx
2020-10-13 17:53:23 - INFO  (app_svc.py:107 load) Enabled plugin: debrief
2020-10-13 17:53:23 - INFO  (app_svc.py:107 load) Enabled plugin: stockpile
2020-10-13 17:53:26 - INFO  (server.py:58 run_tasks) All systems ready.
```

Note that installing the python dependencies with sudo'ing pip resulted in `sphinx-build` being on the path of both the root and kali users: 

```
kali@kali:~$ which sphinx-build
/usr/local/bin/sphinx-build
kali@kali:/caldera$ sudo which sphinx-build 
/usr/local/bin/sphinx-build

``` 

Also, `sphinx-build` is only required to build and serve the documentation locally.  It's the same content that is available at https://caldera.readthedocs.io/en/latest/ , so it can also be viewed there.  

**Errno 99 Error**

Unsure what is going on here.  My first thought was that it meant that a process was already using the port with that IP address, however in my testing that case resulted in an Errno 98. 

It's worth confirming to see if anything is bound to the `8888`  port: 

```
ss -lp | grep 8888
```

If it is, confirm that it's nothing you care about and kill the process. 

**yaml.scanner.ScannerError**

This is raised because the config file is not valid YAML.  I'd check out `/caldera/conf/default.yml` and see if there is any misformatting in there -- the error message gives you a line and column to start with, but FYI yaml error messages sometimes point to misleading lines of the file. 

If you would like to revert your config file to the same state it was when it was first cloned you can: 

```
cd /path/to/caldera/dir
git checkout -- conf/default.yml
```

**Comment by unkempthenry** [comment]
@AppGuard , whoops, was typing up my response and didn't notice you had figured it out.

**Comment by unkempthenry** [comment]
> What is the easiest way to upgrade Caldera without using the MASTER repo ?

> Just delete ~/caldera and then reinstall by issuing command “sudo git clone https://github.com/mitre/caldera.git --recursive --branch x.x.x” where x.x.x = current Caldera "stable" ?

Yes, that will be the most thorough, simplest, and surefire way to do it 👍 . 

Note, if you're at all concerned about losing any customizations or previous data when upgrading, instead of deleting `/caldera` you could just rename it `mv /caldera /caldera.old`


--- 

If you'd like to do it without deleting the folder and using git commands you can do: 

```
git fetch
git checkout x.x.x
git submodule update --recursive --force
```

If you run into problems restarting the server after the git upgrade you can try these commands: 

```
# reset all local changes and config file(s) 
git reset --hard HEAD 
rm conf/local.yml 

# clear out all old data from caldera with the fresh flag-- will result in loss of prior operation data and modifications
python3 server.py --insecure --fresh
```
