### ISSUE TITLE
Ability icons

### ISSUE THREAD

**Issue by florent-fauvin** [mitre/caldera#1820]
Hello,

At the bottom of each ability there are 4 types of icons:
- padlock
- trash can
- key
- dollar

I don't understand the meaning of these icons in the documentation, except for the "padlock" (_Look at each ability command. If there is a variable inside - shown by # {} syntax - the ability will need to be “unlocked” by another ability, in a prior phase, before it can run_).

Do you know where I can find their meaning ?

(Some abilities don't execute. Is this related to a licensing issue or something like that ?)

![ability](https://user-images.githubusercontent.com/12167121/88946948-22d92080-d290-11ea-9ba9-44b5a5a120df.png)

Best Regards,

Florent

**Comment by ArtificialErmine** [comment]
I don't think we've got this information written down anywhere, but the general idea is that the icons indicate noteworthy side-effects of each ability, which can be a shortcut when building adversaries. Keys indicate credentials, for example, and I'm fairly certain the moneybag indicates a "successful" and "valuable" objective, i.e. moving laterally. I'm not entirely certain what the trashcan icon is off the top of my head, though, and I don't want to potentially mislead you. 

As for why some abilities don't execute, that isn't a licensing issue. Some abilities are tied to specific OS's, some are tied to specific execution agents (shell vs powershell, etc.), and some have pre-requisites that need to be met prior to being run. Hopefully that clears things up a bit.

**Comment by wbooth** [comment]
Thanks we'll add tooltips for those icons

**Comment by wbooth** [comment]
Thanks, @florent-fauvin , this has been addressed.
