### ISSUE TITLE
Path of the folders that doesn't exist or hidden

### ISSUE THREAD

**Issue by SeanTsaoFr** [mitre/caldera#1821]
Hello,
I ran into some problems when I was trying to modify one of the plugin of Caldera on my PC by calling the Python Shell in the JS code like you did using the ajax function in the following code:
`$.ajax({
         type: 'POST',
         url: '/plugin/compass/adversary',
         data: fd,
         processData: false,
         contentType: false`

But I couldn't find the path in the url. Wherever I put my Python Shell code and add path after the url, there's always the 404 error in the terminal of browser , such paths exist in other code files too. The path is clearly not in the root directory of Caldera.
So could you help me by specifying where I can find the path?
Thank you very much.
Best regards.

**Comment by ArtificialErmine** [comment]
If I understand what your end goal is, you're trying to run the compass code from another python script or program. If this is indeed the case, you should be aware the URLs are arbitrarily mounted according to a methodology, and not literal paths to resources. If you want access to what would be under `/plugin/compass/adversary`, you can find this by locating the mounting command (https://github.com/mitre/compass/blob/bd4a6f1c17ea1bca5d46588b0872db82af2493cd/hook.py#L13), and seeing where it points (https://github.com/mitre/compass/blob/bd4a6f1c17ea1bca5d46588b0872db82af2493cd/app/compass_svc.py#L116). 

Hopefully this helps, but if I'm misunderstood what's going on, please let us know and we'll try to dig in further.

**Comment by SeanTsaoFr** [comment]
Thank you very much for your help @ArtificialErmine! That solved my problem perfectly!
