### ISSUE TITLE
ModuleNotFoundError: No module named 'aiohttp_jinja2'

### ISSUE THREAD

**Issue by pawp81** [mitre/caldera#1822]
When trying to start Caldera server with:
`sudo python3 server.py --insecure`
I am receiving following error:
```
Traceback (most recent call last):
  File "server.py", line 9, in <module>
    from app.api.rest_api import RestApi
  File "/home/sysagent/caldera/app/api/rest_api.py", line 9, in <module>
    from aiohttp_jinja2 import template, render_template
ModuleNotFoundError: No module named 'aiohttp_jinja2'
```
When re-installing the requirement i see that it is already satisfied
```
pip3 install -r requirements.txt
Requirement already satisfied: aiohttp-jinja2==1.2.0 in /home/sysagent/.local/lib/python3.8/site-packages (from -r requirements.txt (line 1)) (1.2.0)
```

**Comment by clenk** [comment]
Do you have a need to run the server with `sudo`? Try running the server without `sudo`. `sudo python3` can't find the packages installed by non-sudo `pip3 install`, but you really shouldn't `sudo pip3 install`.

**Comment by pawp81** [comment]
Right. Thx! Running python3 server.py --insecure resolved the problem.
