### ISSUE TITLE
Question on creating abilities and adversaries

### ISSUE THREAD

**Issue by a6n1** [mitre/caldera#1829]
Hi,

I was trying to create a custom ability and adversary by creating .yml files in plugins/stockpile/data/abilities and plugins/stockpile/data/adversaries. I would like to ask how do i generate their UUID if I am creating them outside of the GUI?

**Comment by mrengstrom** [comment]
you can just use `uuidgen` from a bash prompt on mac or linux to create one.

**Comment by wbooth** [comment]
I prefer the option @mrengstrom gave, but another option too https://www.uuidgenerator.net
