### ISSUE TITLE
Which branch are you guys using? and startup error from branch 2.7.0

### ISSUE THREAD

**Issue by a6n1** [mitre/caldera#1831]
Hi,

I would like to ask which branch is the most stable? I still use the old 2.6.5 but there are now bugs when I tried creating a planner. 

Then I used the branch 2.7.0 from a fresh Kali install with go installed:

root@kali:/home/kali# go version
go version go1.14.7 linux/amd64
root@kali:/home/kali# which go
/usr/bin/go

I tried running python3 server.py --insecure but I have this error:

can't load package: package github.com/google/go-github/github: cannot find package "github.com/google/go-github/github" in any of:
        /usr/lib/go-1.14/src/github.com/google/go-github/github (from $GOROOT)
        /root/go/src/github.com/google/go-github/github (from $GOPATH)
2020-08-19 10:52:00 - ERROR (sand_svc.py:87 load_sandcat_extension_modules) Failed to fulfill dependencies for module <plugins.sandcat.app.extensions.contact.gist.GIST object at 0x7f45522e5df0>

I even tried putting 
/usr/lib/go-1.14/src/github.com/google/go-github/github to $GOROOT and /root/go/src/github.com/google/go-github/github to $GOPATH but nothing happened.

Any ideas on why is this happening and how can I resolve this to make it run smoothly?

**Comment by elegantmoose** [comment]
@a6n1 - I think the sandcat plugin submodule just needs to be re-pinned to caldera repo. As looks like there has been few commits since it was last pinned.

@wbooth - can you confirm/re-pin?

@a6n1 - after it gets re-pinned, you would to clone the bleeding version of caldera (i.e. master)

**Comment by wbooth** [comment]
can you try with 2.8.0 and see if you are still having this issue?
