### ISSUE TITLE
python-pip3 vs python3-pip

### ISSUE THREAD

**Issue by clr2of8** [mitre/caldera#1835]
The readme says to run this to install pip3
sudo apt install -y python-pip3

but on Ubuntu 18, I had to put the 3 after python like this:
sudo apt install -y python3-pip

Is that just a typo that needs corrected?

**Comment by unkempthenry** [comment]
Good catch @clr2of8 , 

AFAIK, it's a typo (I can't recall seeing pip ever referenced as `python-pip3` before. 

We'll get the README updated soon: https://github.com/mitre/caldera/pull/1836

**Comment by wbooth** [comment]
Fixed
