### ISSUE TITLE
Plugin (Evals) - Pending Issues

### ISSUE THREAD

**Issue by leegengyu** [mitre/caldera#1843]
Hello,

I understand that the [Evals plugin for CALDERA](https://github.com/mitre-attack/evals_caldera) falls into another repository under mitre-attack instead, but this was the closest place that I could find to ask this question (since the said repository has been inactive).

I am encountering the same issues (also encountered by Cyb3rWard0g who opened those issues on the repository) using the plugin in most of the phases that he had opened an issue on. However, there have not been any replies or updates to any of the opened issues (except the very first one).

Could I ask if there is any way that I could write in to enquire about those issues (details will be provided), or is the plugin no longer supported altogether?

Thank you!

**Comment by wbooth** [comment]
Thanks for the heads up @leegengyu it's a separate team but I can bug them about it :)

**Comment by wbooth** [comment]
looks like it's been superseded by the attack-arsenal which you can find here: https://github.com/mitre-attack/attack-arsenal/tree/master/adversary_emulation/APT29/CALDERA_DIY/evals

**Comment by leegengyu** [comment]
Thank you @wbooth for helping to check on this! :)
