### ISSUE TITLE
Docs link gives 404 Not Found

### ISSUE THREAD

**Issue by clr2of8** [mitre/caldera#1853]
In version 2.7 when I click on the Docs link it returns 404 Not Found

![image](https://user-images.githubusercontent.com/22311332/92289301-40bc2580-eecd-11ea-9af6-ac3e527cd399.png)

![image](https://user-images.githubusercontent.com/22311332/92289282-2f731900-eecd-11ea-8434-8e523abd2313.png)

**Comment by wbooth** [comment]
Hi Carrie, it worked for me on a fresh install of 2.7.0
I also see that the version number in the screenshot is in red, which means that some files might have been altered. Can you pull fresh on 2.7 and see if you are still seeing the issue?

**Comment by clr2of8** [comment]
I'm not on v2.7 any more but the same issue is seen on v2.8 as noted here https://github.com/mitre/caldera/issues/1883
