### ISSUE TITLE
v2.8 ImportError: cannot import name 'PyAsn1UnicodeDecodeError' from 'pyasn1.error'

### ISSUE THREAD

**Issue by clr2of8** [mitre/caldera#1854]
I just upgraded from version 2.7 to 2.8 and after `pip3 install -r requirements.txt` was getting this error when trying to start the server:

`ImportError: cannot import name 'PyAsn1UnicodeDecodeError' from 'pyasn1.error'`

my pyasn1 version was 0.4.2, I had to add this line to requirements.txt and reinstall requirements to get past this:

`pyasn1==0.4.8`

Server starts up now

**Comment by christophert** [comment]
Looks like it'll be taken care of by pinning a higher version of LDAP. Should be fixed next release, thanks!
