### ISSUE TITLE
Agent Untrusted

### ISSUE THREAD

**Issue by ashrafoon** [mitre/caldera#1856]
I'm facing an issue when running a operation. 
The job fails and the reason "Agent untrusted". 
any help

**Comment by Zeik0s** [comment]
Had the same Issue, at least for Sandcat. In the directory plugins/sandcat/ running update-agents.sh did it for me. Ensure that Caldera has installed a Go Version.

**Comment by wbooth** [comment]
Yes, please ensure that you have Go installed and it should be fixed. Please re-open the issue if that is not the case
