### ISSUE TITLE
Is there a solution for MITRE ATT&CK ICS?

### ISSUE THREAD

**Issue by KyyB** [mitre/caldera#1858]
Since it was launched earlier this year, is their a solution for the MITRE ATT&CK in ICS?

**Comment by wbooth** [comment]
The abilities can be tagged with any tactic/(sub)technique within ATT&CK. We do not validate what is in the ability. If you add ability for ICS you can tag with att&ck for ICS as appropriate.

**Comment by KyyB** [comment]
I see, but isn't ICS ATT&CK different then IT related one? I don't understand how it can be linked
