### ISSUE TITLE
Not deleting sources

### ISSUE THREAD

**Issue by alexgumo7** [mitre/caldera#1862]
Hello,

I would like to delete sources, I've tried with DELETE method using the following request:

```
{"index":"sources","id":source_id}
```

It's not working. Then, checking if this is possible in https://github.com/mitre/caldera/blob/master/app/api/rest_api.py I can't see that the delete of sources is implemented.

Is there a reason why this functionality is not implemented?

**Comment by wbooth** [comment]
Yes, sources are not deleted because they are depended upon for operation reports and historical information. Deleting a source may cause some unintended consequences.
