### ISSUE TITLE
Logging problem (wrong credentials?)

### ISSUE THREAD

**Issue by kont45** [mitre/caldera#1863]
Some problem with log in with red/admin credentials:

```
2020-09-09 06:03:31 - INFO  (server.py:57 run_tasks) All systems ready.
2020-09-09 06:03:50 - DEBUG (auth_svc.py:96 login_user) red failed login attempt: 
```

What is the correct login and password to Caldera dashboard?

**Comment by alexgumo7** [comment]
You can find the credentials for `red` and `blue` users in the file `caldera/conf/local.yml`.

**Comment by wbooth** [comment]
If you want to use the default credentials (admin/admin or blue/admin) , please use the `--insecure` arg
