### ISSUE TITLE
Select Technique number and name from a list

### ISSUE THREAD

**Issue by clr2of8** [mitre/caldera#1871]
When creating an ability it is weird to see two line items called "technique". Should one be called "technique number" and one "technique name"? Also, could we pick these values from a pre-populated list instead of free form text input? Thx

![image](https://user-images.githubusercontent.com/22311332/93689711-6a10b000-fa8e-11ea-8349-01b2c8ca3dc3.png)

**Comment by wbooth** [comment]
Correct, it should be technique id, I've updated that part. 

As to the repopulated list, gone back and forth on this one. A list of existing ids would be something we could add, but  if someone wanted to extend techniques with something that fits their own use case that they'd be able to.

**Comment by clr2of8** [comment]
got it, thx
