### ISSUE TITLE
The trashcan icon is black on a black background and therefore not visible

### ISSUE THREAD

**Issue by clr2of8** [mitre/caldera#1872]
Garbage can icon is between the lock and the key here but not visible.

![image](https://user-images.githubusercontent.com/22311332/93689735-92001380-fa8e-11ea-9c01-5fbe3e77ea81.png)

**Comment by wbooth** [comment]
What browser are you using?

**Comment by clr2of8** [comment]
chrome, it is also black on black in IE but not firefox

**Comment by wbooth** [comment]
https://github.com/mitre/caldera/pull/1924 this should fix the viewing of unicode characters

**Comment by wbooth** [comment]
it'll make it more viewable, if it's still unviewable it'll require updating unicode icons to svg icons. If that's the case, feel free to re-open this issue or a new one. thanks
