### ISSUE TITLE
server.py - ModuleNotFoundError

### ISSUE THREAD

**Issue by ohmygord** [mitre/caldera#188]

**Comment by ohmygord** [comment]
Hi,
I'm getting an error when I run server.py on Window10. I have followed all steps and this is when running server.py as the final step:

```
c:\caldera-master>python server.py
Traceback (most recent call last):
  File "server.py", line 10, in <module>
    import aiomonitor
ModuleNotFoundError: No module named 'aiomonitor'
```

This is with the 213 branch. With the current Master I was getting a different module error.

```
c:\caldera-master>python server.py
Traceback (most recent call last):
  File "server.py", line 19, in <module>
    from app.service.file_svc import FileSvc
  File "c:\caldera-master\app\service\file_svc.py", line 6, in <module>
    from app.utility.logger import Logger
  File "c:\caldera-master\app\utility\logger.py", line 3, in <module>
    from termcolor import colored
ModuleNotFoundError: No module named 'termcolor'

```

**Comment by rayhernandez** [comment]
You are missing two modules:
termcolor 1.1.0:  https://pypi.org/project/termcolor/
aiomonitor 0.4.4:  https://pypi.org/project/aiomonitor/

pyfiglet was also removed from requirements.txt, so it may or may not be needed.
pyfiglet 0.8.post1: https://pypi.org/project/pyfiglet/

You can modify requirements.txt and rerun pip install -r requirements.txt to install the missing modules:
https://github.com/mitre/caldera/commit/b8c4497c5e1c0f9133b955d15a4b778f3fb539e9#diff-b4ef698db8ca845e5845c4618278f29a

**Comment by privateducky** [comment]
thanks @ohmygord - it looks like we had a rouge import statement that should have been cleaned up from an experimental feature (termcolor). That has since been removed, so if you 'git pull' it should be back to normal.

**Comment by ohmygord** [comment]
@privateducky Thank you!!!
