### ISSUE TITLE
v2.8 can't set app.contact.tcp IP to caldera server IP

### ISSUE THREAD

**Issue by clr2of8** [mitre/caldera#1881]
If I change the app.contact.tcp IP from 0.0.0.0 to the IP of my Caldera Server and restart the server I get

OSError: [Errno 99] error while attempting to bind on address ('_**<caldera server ip>**_', 7010): cannot assign requested address

**Comment by wbooth** [comment]
hi @clr2of8 , here is where the host:port for the tcp connection is set: https://github.com/mitre/caldera/blob/master/app/contacts/contact_tcp.py#L21-L22

based on your error message I'm assuming that the public ip of your caldera server isn't an available interface on the box. 
have you checked `ifconfig` to see that it is available?

**Comment by clr2of8** [comment]
![image](https://user-images.githubusercontent.com/22311332/96203718-c8ab3b80-0f1f-11eb-92c2-fb43c82fc18a.png)

But since I'm reaching the CALDERA web interface from a remote machine via http://104.41.148.145:8888 doesn't that mean that the interface is available?

**Comment by unkempthenry** [comment]
@clr2of8 , if you can, please double check the formatting of `app.tcp.contact` in your config file.  I was able to successfully modify the setting in one of my VMs just now: 

```
app.contact.tcp: 192.168.131.193:7010
```

Caldera started without errors.  I confirmed that Caldera had bound to the port: 

```
testuser@ubuntu:~$ nc -v 192.168.131.193 7010
Connection to 192.168.131.193 7010 port [tcp/*] succeeded!

testuser@ubuntu:~$ ss -lp | grep 7010
tcp    LISTEN  0       100                                      192.168.131.193:7010                                                 0.0.0.0:*                   users:(("python",pid=47295,fd=11))   
```

This part of your error message ` ('', 7010)` suggests that there might be an issue with the formatting in the config file -- it's trying to bind to an empty IP address. Totally possible something else is going on here, but that's the first place I'd look.

**Comment by clr2of8** [comment]
![image](https://user-images.githubusercontent.com/22311332/96323217-6747a300-0fd9-11eb-85ef-3e2640f29a2d.png)

![image](https://user-images.githubusercontent.com/22311332/96323246-80505400-0fd9-11eb-83f7-a847389404d8.png)

![image](https://user-images.githubusercontent.com/22311332/96323298-c2799580-0fd9-11eb-80f0-cc7631492c3d.png)
