### ISSUE TITLE
At blue user interface, some agents are not set to be in blue group

### ISSUE THREAD

**Issue by alshaboti** [mitre/caldera#1888]
I login in as a blue user, and commands to deploy 54ndc47 for Linux, and windows show `group red` instead of `group blue`.

I am using caldera version `2.8.0-909597268607e7cbca77bd22c462fb22`

**Comment by wbooth** [comment]
Thanks, the commands are static. There is a command provided in order to run a blue agent: 
![image](https://user-images.githubusercontent.com/18699738/94136072-64bab900-fe32-11ea-85e4-5ec52a4641b2.png)

**Comment by GlennHD** [comment]
This doesn't seem to be functioning properly. Seems this would be an easy switcheroo right? Otherwise you just have Mac/Linux blue agents and no Windows blue agents. For 54ndc47, you just change "-group red" to "-group blue" then it works. Otherwise you're sending elevated agents to the red team.
