### ISSUE TITLE
Report data shows up as null when attempting to add agent output

### ISSUE THREAD

**Issue by fried213** [mitre/caldera#1891]
Report data shows up as null when attempting to add agent output. Below are the server side errors

![image](https://user-images.githubusercontent.com/2389185/94296626-21933f80-ff31-11ea-9027-7f77df5d688d.png)

**Comment by wbooth** [comment]
I was unable to reproduce this, is it possible that a file was deleted?

**Comment by fried213** [comment]
it's possible,, but it was a pretty recent install. should I do another git pull?

**Comment by wbooth** [comment]
I'd first try restarting caldera and ensure that the current database is cleared ```--fresh``` can ensure that log level is set at debug ```-l DEBUG``` if that doesn't work then, yes. I'd delete and reclone. if the issue persists please re-open this ticket.
