### ISSUE TITLE
2.8.0 compass plugin: an error occurred when trying to "Upload Adversary Layer"

### ISSUE THREAD

**Issue by shiracamus** [mitre/caldera#1892]
When I uploaded a json file created by ATT&CK navigator with "Upload adversary layer", the following error message was displayed in the console.

error message:

```text
'>' not supported between instances of 'NoneType' and 'int'
```

The error was caused by the following source code

app/compass_svc.py: line 83

```python
            if technique.get('score') > 0:
```

After making the following changes, the error no longer occurs.

```python
            if technique.get('score', 0) > 0:
```

Steps to replicate the issue:

1. select the compass in the navigate menu
2. pull down the "multi selection" menu in the selection controlls of the MITRE ATT&CK Navigator sub-window
3. select any thret groups (e.g. APT1)
4. pull down the "background color" menu in the technique controlls and select red color
5. click on the "download layer as json" menu in the layer controlls (it will be saved as "layer.json")
6. click on the "Upload Adversary Layer" button, select "layer.json" file and click the "Open" button
7. check the error message on the terminal that ran MITRE CALDERA

Versions are:

OS: Ubuntu 20.04
Python: 3.8.2
Web Browser: Chromium 85.0.4183.121
MITRE CALDERA: 2.8.0
Compass plugin: 2.8.0-2781156cfa6d4711e306cc4cca72f9a5

**Comment by wbooth** [comment]
thanks updated: https://github.com/mitre/compass/pull/34
