### ISSUE TITLE
How are changes to Techniques updated in Caldera and the Red Atomic plugin ?

### ISSUE THREAD

**Issue by AppGuard** [mitre/caldera#1895]
From the MITRE blog regarding the ATT&CK upgrade from 6.3 to 7.0, it states that

"seven key types of changes:

1. Remains Technique
2. Became a Sub-Technique
3. Multiple Techniques Became New Sub-Technique
4. One or More Techniques Became New Technique
5. Merged into Existing Technique
6. Deprecated
7. Became Multiple Sub-Techniques"

- So how are the changes in the ATT&CK technique numbers as well as the technique implementations (Abilities) updated in
   Caldera ?

- Are all the updates automatically updated in the background or by major Caldera version number - requiring the user to keep
   on top of ATT&CK changes made by MITRE and update Caldera manually when a new version that supports the new version of
   ATT&CK ?

- Does Caldera contributors and maintainers update the Techniques in Caldera on a regular basis ?

- What about the Techniques that are imported by the Red Atomic plugin ?

- What I am trying to figure out is if I run a test in Caldera 2.8.0, say for T1050, do the test results apply to all the sub-techniques
   in ATT&CK  version 7 ?

- It appears that the Technique numbers in Caldera (2.7.0) are not automatically nor regularly updated and probably map to
   ATT&CK version 6.3 or older.

For example, the command lines for T1050 have been dropped in ATT&CK version 7.0 because T1050 has been deprecated and split into sub-techniques T1543.a.b.c.

New command lines have been created for T1543.a.b.c to correspond to the changes in ATT&CK version 7.

Caldera 2.7.0 is still using the ATT&CK 6.3 command lines for T1050.

If you update to Caldera 2.8.0, then the T1050 has been "re-mapped" to T1543.a.b.c.

?????

**Comment by aapplebaum** [comment]
Happy to try to answer some of these.

> So how are the changes in the ATT&CK technique numbers as well as the technique implementations (Abilities) updated in
Caldera ?

All changes related to ATT&CK in CALDERA are done manually. As a team, we periodically check to see if select abilities still have parity with ATT&CK, but we do not have a fixed schedule for when we check. We strive to do our best to make sure each ability is correctly mapped to ATT&CK, but it's definitely possible a few will slip under our radar.

> Are all the updates automatically updated in the background or by major Caldera version number - requiring the user to keep
on top of ATT&CK changes made by MITRE and update Caldera manually when a new version that supports the new version of
ATT&CK ?

At this time we do not push CALDERA updates to users. We encourage our users to check the GitHub repo for changes to see if they need to make updates. When you do update via GitHub, changes are made automatically in the background.

When it comes to updates of ATT&CK and CALDERA, coordination between the two is a manual process. When we -- the CALDERA team -- notice big ATT&CK changes, we try to go through things in CALDERA to make sure we're still at parity with them.

> Does Caldera contributors and maintainers update the Techniques in Caldera on a regular basis ?

We periodically add new abilities to CALDERA, but often only do so as-needed based on internal usage/testing. We strongly encourage users to add in their own abilities to either a local plugin or push them to the stockpile plugin for everyone to use.

> What about the Techniques that are imported by the Red Atomic plugin ?

The atomic plugin only scans for the Atomic Red Team repo and converts the tests there into CALDERA's ability format -- it does not perform any checking as to the accuracy of the technique maps.

> What I am trying to figure out is if I run a test in Caldera 2.8.0, say for T1050, do the test results apply to all the sub-techniques
in ATT&CK version 7 ?

This is a good question, and I unfortunately don't have a clear-cut answer: ultimately it depends on the ability, and also how you use ATT&CK. My gut instinct would be to answer "no", as T1050 has been revamped to a specific sub-technique, so I think marking coverage for the other techniques would be inaccurate.

"Coverage" for techniques and sub-techniques is to some extent left to the user: if you cover technique "A" which has sub-techniques A.1, A.2, A.3, ..., then whether you want to mark A.1 and the others as covered is ultimately left to how you choose to do scoring. Similarly, if you have coverage of A.1, A.2, A.3, ..., whether you have "coverage" of "A" itself is also left to your scoring mechanism.

I'd also add -- if you do find abilities in the latest version of CALDERA mapping to deprecated or revoked techniques, feel free to flag them and we can take a look.

> It appears that the Technique numbers in Caldera (2.7.0) are not automatically nor regularly updated and probably map to
ATT&CK version 6.3 or older.

Yes; 2.7.0 is not going to maintained moving forward, and as the project grows will likely fall out of parity with plugins as they're updated. We'd encourage users to update to 2.8.0.

**Comment by AppGuard** [comment]
Andy, thank you for your detailed reply.

I searched the documentation on the MITRE recommended method to upgrade Caldera, but didn't find anything.

Does Caldera support upgrade in-place, or is the preferred method to uninstall current-install upgrade versions ?

**Comment by aapplebaum** [comment]
Sure, happy to help.

We don't have any recommended upgrade strategies; depending on the scenario, the best route is either:

1. Run a git pull from master on core + each plugin so CALDERA updates in-place, letting "git" resolve and handle any conflicts you might have.
2. Create a fresh clone of the latest version of CALDERA.

In the case of #2, this would result in you needing to copy over any changes you've made to CALDERA over to the new clone. In the case of #1, for many changes such as added abilities/adversaries git should allow them to remain, although they may no longer be compatible with the latest code.

One thing I'd note is uninstalling CALDERA is as simple as deleting the CALDERA folder from your computer; there is no formal install.

**Comment by AppGuard** [comment]
**1. Run a git pull from master on core + each plugin so CALDERA updates in-place, letting "git" resolve and handle any conflicts you might have.**

Executing the command

git clone https://github.com/mitre/caldera.git --recursive --branch x.x.x 

and following the entire Caldera install sequence as outlined on the Caldera GitHub page will accomplish option # 1 above ?

**Comment by wbooth** [comment]
This command will forcibly set the repo and submodules to master
`git reset --hard origin/master && git checkout master && git reset --hard origin/master && git pull && git submodule foreach git checkout master && git submodule foreach git pull`

additionally, you can clear non tracked files using `git clean -f`

**Comment by AppGuard** [comment]
Level 1 here and don't know Git.

I see this warning on the Caldera front-page:

Start by cloning this repository recursively, passing the desired version/release in x.x.x format. This will pull in all available plugins. **If you clone master - or any non-release branch - you may experience bugs.**

So problems must be of a high enough incidence to make the above admonition.

Do I have to run that command in a particular directory or is the command global if run on any open terminal ?

**Comment by wbooth** [comment]
the command `git reset --hard origin/master && git checkout master && git reset --hard origin/master && git pull && git submodule foreach git checkout master && git submodule foreach git pull` can be run in an existing caldera directory. this will forcibly pull all the latest code and the latest for each plugin (submodule). 

If you have not downloaded caldera or deleted the caldera directory, then you can run `git clone https://github.com/mitre/caldera.git --recursive` in the directory that you want caldera to be in. As you did the first time.
