### ISSUE TITLE
Possible issue with facts in regards to worm related adversary profiles

### ISSUE THREAD

**Issue by slickjitz** [mitre/caldera#1906]
I want to preface by stating I have checked past issue and looked at issue #860 and this did not seem to help as someone on there stated you can change fact sources in plugins/stockpile/data/facts although there does not seem to be in fact(s) dir in /data at least on v2.7.0. 

I seem to have an issue with any of the Windows Worms adversary profiles not completing all abilities. Specifically on 'Windows Worm #3' caldera will successfully complete the first ability (Collect ARP details), but then stop the operation. All the worm related adversaries and only worm related adversaries behave this way. I looked into the json report and see that it has a section on "skipped abilities" with all subsequent abilities after 'Collect ARP details' listed. The reason being "Fact dependency not fulfilled". I have been attempting the operation with basic facts. I understand what facts are, but I am a bit unclear how caldera collects and uses them. I have read the section on "How CALDERA makes decisions" in the docs but they are quite minimal. Thanks in advance!

"skipped_abilities": [ { "cfgvca": [ { "reason": "Fact dependency not fulfilled", "reason_id": 2, "ability_id": "fa4ed735-7006-4451-a578-b516f80e559f", "ability_name": "Reverse nslookup IP" }, { "reason": "Fact dependency not fulfilled", "reason_id": 2, "ability_id": "deeac480-5c2a-42b5-90bb-41675ee53c7e", "ability_name": "View remote shares" }, { "reason": "Fact dependency not fulfilled", "reason_id": 2, "ability_id": "65048ec1-f7ca-49d3-9410-10813e472b30", "ability_name": "Copy 54ndc47 (SMB)" }, { "reason": "Fact dependency not fulfilled", "reason_id": 2, "ability_id": "41bb2b7a-75af-49fd-bd15-6c827df25921", "ability_name": "Start Agent (WinRM)"

**Comment by wbooth** [comment]
The first command arp -a is below:
https://github.com/mitre/stockpile/blob/master/data/abilities/discovery/85341c8c-4ecb-4579-8f53-43e3e91d7617.yml
the parser is specified that will extract the information and save to the fact: #{remote.host.ip}

We can see that is used in the following ability: https://github.com/mitre/stockpile/blob/master/data/abilities/discovery/fa4ed735-7006-4451-a578-b516f80e559f.yml
and in turn a parser is set there to learn and parse more information. 

Sometimes there are facts required that aren't provided in a previous ability: In the windows worm 3 ability Start Agent (WinRM) https://github.com/mitre/stockpile/blob/master/data/abilities/lateral-movement/41bb2b7a-75af-49fd-bd15-6c827df25921.yml
there are some facts like #{domain.user.name} that aren't parsed from a prior ability. In this case they needed to be provided in the fact source

Here's a sample of what preseeding a fact source looks like: https://github.com/mitre/stockpile/blob/master/data/sources/ed32b9c3-9593-4c33-b0db-e2007315096b.yml

----

Sometimes there is an issue parsing the response of an ability that may leave the rest of the adversary unable to complete. Ensure that steps are parsing information in the UI by checking for the gold star:
![image](https://user-images.githubusercontent.com/18699738/95406113-9f6b2980-08e7-11eb-8270-c2580f120fec.png)

**Comment by wbooth** [comment]
Hopefully, this answered your question. If not please re-open or open a new issue.

**Comment by kingszhe9664** [comment]
i use Advanced Thief via GitHub Gist   Adversary 。 
find operation  list has no records   get record json file  。find  “Fact dependency not fulfilled”   
there is json content：

```
{
  "name": "Payload (2022/7/8 13:55:15)",
  "host_group": [
    {
      "paw": "vflzak",
      "sleep_min": 30,
      "ppid": 10528,
      "created": "2022-07-08T03:20:11Z",
      "username": "root",
      "deadman_enabled": true,
      "watchdog": 0,
      "proxy_chain": [],
      "exe_name": "splunkd",
      "available_contacts": [
        "HTTP"
      ],
      "group": "red",
      "sleep_max": 60,
      "location": "/root/splunkd",
      "architecture": "amd64",
      "host": "host185",
      "upstream_dest": "http://10.239.50.180:8888",
      "pid": 104313,
      "origin_link_id": "",
      "contact": "HTTP",
      "last_seen": "2022-07-08T06:02:17Z",
      "display_name": "host185$root",
      "pending_contact": "HTTP",
      "executors": [
        "proc",
        "sh"
      ],
      "platform": "linux",
      "privilege": "Elevated",
      "host_ip_addrs": [
        "10.239.50.185",
        "172.17.0.1"
      ],
      "trusted": true,
      "proxy_receivers": {},
      "server": "http://10.239.50.180:8888",
      "links": []
    }
  ],
  "start": "2022-07-08T06:02:45Z",
  "steps": {
    "vflzak": {
      "steps": []
    }
  },
  "finish": null,
  "planner": "atomic",
  "adversary": {
    "has_repeatable_abilities": false,
    "objective": "495a9828-cab1-44dd-a0ca-66e58177d8cc",
    "plugin": "stockpile",
    "adversary_id": "e89a10d3-004f-4c15-b0eb-d1ba76a4b67f",
    "description": "Exfil a compressed archive to a GitHub Gist (Base64 Encoded)",
    "name": "Advanced Thief via GitHub Gist",
    "atomic_ordering": [
      "10fad81e-3f68-47be-83b6-fbee7711c6a9",
      "30a8cf10-73dc-497c-8261-a64cc9e91505",
      "0582dc26-e0cf-4645-88cf-f37a02279976"
    ],
    "tags": []
  },
  "jitter": "2/8",
  "objectives": {
    "percentage": 0,
    "goals": [
      {
        "operator": "==",
        "value": "complete",
        "count": 1048576,
        "target": "exhaustion",
        "achieved": false
      }
    ],
    "description": "This is a default objective that runs forever.",
    "name": "default",
    "id": "495a9828-cab1-44dd-a0ca-66e58177d8cc"
  },
  "facts": [],
  "skipped_abilities": [
    {
      "vflzak": [
        {
          "reason": "Fact dependency not fulfilled",
          "reason_id": 2,
          "ability_id": "10fad81e-3f68-47be-83b6-fbee7711c6a9",
          "ability_name": "Advanced File Search and Stager"
        },
        {
          "reason": "Fact dependency not fulfilled",
          "reason_id": 2,
          "ability_id": "30a8cf10-73dc-497c-8261-a64cc9e91505",
          "ability_name": "Compress staged directory (Password Protected)"
        },
        {
          "reason": "Fact dependency not fulfilled",
          "reason_id": 2,
          "ability_id": "0582dc26-e0cf-4645-88cf-f37a02279976",
          "ability_name": "Exfil Compressed Archive to Github Gist"
        }
      ]
    }
  ]
}
```

**Comment by clenk** [comment]
Hi @kingszhe9664, please read wbooth's response above. Facts must either be parsed from a previous ability or provided by a fact source. If you need more help please open a new issue.

**Comment by robin-wei** [comment]
Hi, I have been meeting same issue, log shows "Fact dependency not fulfilled" for running nslookup after running arp -a when I tried windows worm #1. But if I just run nslookup {remote.host.ip}, it works. May I query who has really solved this issue? Thanks

**Comment by robin-wei** [comment]
> 

Is that possible to because of language of OS?  I can see the error from caldera back end is about uft8 error.

**Comment by clenk** [comment]
Hi @robin-wei, that is certainly possible. Can you please post the utf8 error you are seeing, as a new GitHub issue? Thank you.

**Comment by robin-wei** [comment]
Hi Chris,
I have soved this issue, utf8 is the reason. After I changed the language from Chinese to English, issue disappeared. 🙂 Thanks for your help.


Robin

________________________________
发件人: Chris Lenk ***@***.***>
发送时间: 2023年7月8日 2:35
收件人: mitre/caldera ***@***.***>
抄送: Robin Wei ***@***.***>; Mention ***@***.***>
主题: Re: [mitre/caldera] Possible issue with facts in regards to worm related adversary profiles (#1906)


Hi @robin-wei<https://github.com/robin-wei>, that is certainly possible. Can you please post the utf8 error you are seeing, as a new GitHub issue? Thank you.
