### ISSUE TITLE
Untrusted agents on long operations

### ISSUE THREAD

**Issue by alexgumo7** [mitre/caldera#1929]
**Describe the bug**
[Using release 2.7.0] I'm trying a custom buckets planner that is intended to perform an operation during several days. The problem should not be related to the planner because using it in its fast version is working as expected. The problem is that one day after starting the operation, **all** caldera agents are marked as **untrusted**, then the operation cannot continue and ends up finishing without executing new links. It is the first time that this behaviour is happening. The agents are still alive, however, they are still marked as untrusted.

**To Reproduce**
1. Run a long operation. (For instance, adding sleeps inside a planner)

**Expected behavior**
The expected behavior is that all the agents are not marked as untrusted and the operation can follow its usual flow.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Linux
 - Version 2.7.0

**Comment by b17zr** [comment]
Are you using `asyncio.sleep` in the planner or `time.sleep`?
Is the agent trusted timer set high?
Is there any debug output from https://github.com/mitre/caldera/blob/master/app/service/app_svc.py#L49?

**Comment by alexgumo7** [comment]
- I'm using `asyncio.sleep` to wait several hours.
- The trusted timer specified in the field `untrusted_timer` of `conf/agents.yml` is set to 90, the default value. I haven't changed it as I don't really know if it will affect other things.
- Yes, there was a 'Agent (%s) now untrusted. Last seen %s sec ago' for each untrusted agent.

**Comment by b17zr** [comment]
For now, maybe set the untrusted timer to something very high. I'll try to replicate agents becoming untrusted after a day.
