### ISSUE TITLE
Exfiltrated Compressed Directory Corrupted

### ISSUE THREAD

**Issue by sminky226** [mitre/caldera#1933]
**Describe the bug**
When exfiltrating files - in this case a .csv file - the agent will successfully compress the staged directory with the .csv file as expected. When extracted on the origin - the target machine - the archive will inflate correctly without errors. When extraction is attempted on the Caldera server, the archive appears to be corrupted, and an error stating "" 'staged.zip': not an archive "" is received.

**To Reproduce**
1. Deploy a 54ndc47 or Manx agent on a Windows 10 target that has a .csv file contained.
2. Update the Basic Facts source to include:   trait:file.sensitive.extension  value:csv
3. Update the Basic Facts rules to include:    trait:file.sensitive.extension    match:csv   action:ALLOW
4. Run the "Thief" operation on the target:
	Basic Options:
		<agent group>
		Thief
		Keep open forever
		Run immediately
	Autonomous
		Run autonomously
		Usee atomic planner
		Use basic facts
	Stealth
		N/a
	Schedule
		N/a
5. On the target machine, check the running directory of the agent for the staged.zip directory, and inflate it. The decompression succeeds.
6. On Caldera, check the exfiltrated staged.zip directory, and inflate it. The decompression fails.

**Expected behavior**
The compressed staged.zip directory should inflate successfully on both the target and Caldera server.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Caldera Server: Ubuntu 18.04.5 LTS (5.4.0-48-generic)
		Windows 10: Windows 10 Enterprise Evaluation 10.0.17763 N/A Build 17763 x64-based PC
				Hotfixes:
			 [01]: KB4486553
             [02]: KB4462930
             [03]: KB4470788
             [04]: KB4480056
             [05]: KB4489907
             [06]: KB4489899
 - Browser: Chrome 85.0.4183.121 (Official Build) (64-bit)
 - Caldera Version 2.8.0-909597268607e7cbca77bd22c462fb22
 - 54ndc47 Version 2.8.0-6ac972e9aa48ec57397e0e2bf94625db
 - Manx Version 2.8.0-96557f9a8fc594cf68ad2eb83c95627f

**Additional context**
This is being done in a virtual lab, not a cloud or physical environment. Previous exfiltration and file transfers have successfully demonstrated transmission of compressed directories/binaries.

![Not an archive](https://user-images.githubusercontent.com/73407140/97095223-c38a7280-162a-11eb-9593-22e159d2aa74.png)
![Not an archive2](https://user-images.githubusercontent.com/73407140/97095225-c5543600-162a-11eb-9c37-66e1dc5299db.png)
![Not an archive](https://user-images.githubusercontent.com/73407140/97095227-d13ff800-162a-11eb-986a-bba98fa0da74.png)
![Not an archive2](https://user-images.githubusercontent.com/73407140/97095228-d13ff800-162a-11eb-8af2-3eeee40ac7d3.png)
![Not an archive3](https://user-images.githubusercontent.com/73407140/97095229-d13ff800-162a-11eb-9cb0-31f5185afa96.png)
![op1](https://user-images.githubusercontent.com/73407140/97095230-d1d88e80-162a-11eb-94de-d4db401c9c8b.png)
![op2](https://user-images.githubusercontent.com/73407140/97095231-d1d88e80-162a-11eb-84e6-42269d309529.png)
![target decomp1](https://user-images.githubusercontent.com/73407140/97095232-d1d88e80-162a-11eb-8d38-5cea7f52b559.png)
![target decomp2](https://user-images.githubusercontent.com/73407140/97095233-d1d88e80-162a-11eb-9a08-7a7ef3892aae.png)
![target decomp3](https://user-images.githubusercontent.com/73407140/97095234-d1d88e80-162a-11eb-8018-f7a894c887a0.png)

**Comment by wbooth** [comment]
Thanks I will check on this, files are encrypted at rest. Can you check if the file is encrypted, decryptor is available here as a utility script https://github.com/mitre/caldera/blob/master/app/utility/file_decryptor.py
