### ISSUE TITLE
Enable SSL Plugin Not Working

### ISSUE THREAD

**Issue by jcleary47** [mitre/caldera#1937]
I've ensured Caldera is fully installed and up to date, and I have haproxy installed as well. 

When I click the green "Enable" button next to the SSL plugin, I get a message that the bottom that states _"You enabled a new plugin! Bummer that it is not available until your next server restart."_

Upon restarting the service, SSL is still not enabled and I am only able to connect using http://<server>:8888 and not https. 

The green enable button is also still present next to the SSL plugin in the Advanced Configuration menu.

Is there a way to manually force SSL enablement on the back-end? It seems like it is not taking the change through the web interface.

**Comment by wbooth** [comment]
Thanks, you can stop the server and edit conf/default.yml or conf/local.yml (if present) and add under the plugins

**Comment by jcleary47** [comment]
Hello William,

Thank you for reaching out. Looks like it's still not happy. I just noticed
some alerts however, may be related to haproxy. Could this be the cause. I
also noticed that it looks like my RHEL box has a GO version running < 1.11
after all. Not sure if that could contribute as well...

[ALERT] 302/110519 (53106) : parsing [plugins/ssl/templates/haproxy.conf:4]
: unknown keyword 'nbthread' in 'global' section
[ALERT] 302/110519 (53106) : parsing [plugins/ssl/templates/haproxy.conf:6]
: unknown option 'ssl-min-ver' on global statement
'ssl-default-bind-options'.
[ALERT] 302/110519 (53106) : Error(s) found in configuration file :
plugins/ssl/templates/haproxy.conf

**Comment by wbooth** [comment]
Hi @jcleary47 , while we look into your issue further, our friends at Black Hills wrote a nice blog about installing SSL with caldera that may be helpful: https://www.blackhillsinfosec.com/how-to-install-mitre-caldera-and-configure-your-ssl-certificate/

**Comment by ThisNerdyGuy** [comment]
Hi all, 
This is my first github comment on an open issue and I know github, like StackExchange, can roast when things aren't done "according to procedures" so preemptive apologies for any faux paux I may commit and may the sins be forever held by my ancestors. 

With that out of the way, I wanted to add to this -
It was the BHIS blog that got me wanting to try to enable SSL but, like @jcleary47, the WebUI doesn't save the changes. My behavior is exactly the same as he reports - it will say it's saved pending a reboot and, upon a reboot, the settings are all reverted - including the http IP change recommended by BHIS (and not in readthedocs). 

However, editing local.yml and forcing the -ssl plugin did work. I returned to the WebUI and changed the app.contact.http value to https://0.0.0.0:8443 and saved the changed. I noticed these changes are still not saving so I'll need to edit this in local.yml, too. 

I just wanted to add this in case it helps with debugging! 

Thanks for the project! It rocks!

**Comment by jcleary47** [comment]
Sorry for the delay in providing an update - I did manage to get haproxy started, but I had to comment these lines out of the haproxy.conf in the templates folder for the SSL plugin:

global
    maxconn 20000
    **#nbproc 1
    #nbthread 4
    #ssl-default-bind-ciphers ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SH$
    #ssl-default-bind-options ssl-min-ver TLSv1.1 no-tls-tickets**

Not sure if this is an acceptable workaround in terms of functionality, but it did get SSL working for us. 

**The only issue I'm seeing now, and I can't tell if it's actually causing a problem or not, is the following in the log:**

2020-11-04 11:21:21 - ERROR (base_events.py:1285 default_exception_handler) Task exception was never retrieved
future: <Task finished coro=<build_docs() done, defined at /root/caldera/plugins/fieldmanual/hook.py:24> exception=FileNotFoundError(2, "No such file or directory: 'sphinx-build'")>
Traceback (most recent call last):
  File "/root/caldera/plugins/fieldmanual/hook.py", line 27, in build_docs
    stdout=asyncio.subprocess.PIPE, stderr=asyncio.subprocess.PIPE)
  File "/usr/lib64/python3.6/asyncio/subprocess.py", line 225, in create_subprocess_exec
    stderr=stderr, **kwds)
  File "/usr/lib64/python3.6/asyncio/base_events.py", line 1211, in subprocess_exec
    bufsize, **kwargs)
  File "/usr/lib64/python3.6/asyncio/unix_events.py", line 200, in _make_subprocess_transport
    **kwargs)
  File "/usr/lib64/python3.6/asyncio/base_subprocess.py", line 39, in __init__
    stderr=stderr, bufsize=bufsize, **kwargs)
  File "/usr/lib64/python3.6/asyncio/unix_events.py", line 706, in _start
    universal_newlines=False, bufsize=bufsize, **kwargs)
  File "/usr/lib64/python3.6/subprocess.py", line 729, in __init__
    restore_signals, start_new_session)
  File "/usr/lib64/python3.6/subprocess.py", line 1364, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'sphinx-build': 'sphinx-build'

**Comment by wbooth** [comment]
Thanks yes, that sphinx-build issue has been addressed within the field manual plugin

**Comment by cyber-yinzer** [comment]
Be sure you install HAproxy, reboot, load Caldera, enable the plugin + IP, and reboot once more. The next caldera load will respond on hxxps://IP:8443.

Here's the next oddity...

From /caldera, I run grep -Hrn 8888 and grep -Hrn 8443 to check the plugin and config yml's to see it's all referencing 8888. Shouldn't the agents reflec the new 8443 request?

**Comment by grisno** [comment]
Hi,

This problem happens when using a haproxy version lower than v1.8. You can check the installed version using the command: 
```
haproxy -v
```

Disabling the minimal version of cypher is a very high security risk
```
#ssl-default-bind-ciphers ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SH$
#ssl-default-bind-options ssl-min-ver TLSv1.1 no-tls-tickets
```
In some Linux distributions the official repositories contain a lower than v1.8

Example:

CentOS 7.9 - Oficial Repo - haproxy 1.5
```
sudo yum install -y haproxy
```
CentOS 7.9 - SCL Repo - haproxy 1.8
```
sudo yum install -y centos-release-scl
sudo yum install -y rh-haproxy18-haproxy rh-haproxy18-haproxy-syspaths
ln -s /opt/rh/rh-haproxy18/root/usr/sbin/haproxy /usr/sbin/haproxy
```
