### ISSUE TITLE
Sandcat cannot establish a normal connection with the Caldera server

### ISSUE THREAD

**Issue by BoneCARD** [mitre/caldera#1951]
**Describe the bug**
When sandcat was used to connect to the caldera server on Win10, the connection was closed after the first connection was made and an error was displayed

**Expected behavior**
1. When I launch Caldera's server and run the download sandcat command provided by Caldera on Win10, the command line reports the following questions:

> `#` runtime/internal/sys
> /usr/local/go/src/runtime/internal/sys/intrinsics_common.go:28:5: ntz8tab redeclared in this block
>         previous declaration at /usr/local/go/src/runtime/internal/sys/intrinsics.go:58:5
> /usr/local/go/src/runtime/internal/sys/intrinsics_common.go:108:7: deBruijn64 redeclared in this block
>         previous declaration at /usr/local/go/src/runtime/internal/sys/intrinsics.go:11:20
> `#` runtime/internal/atomic
> /usr/local/go/src/runtime/internal/atomic/atomic_amd64x.go:18:6: Load redeclared in this block
>         previous declaration at /usr/local/go/src/runtime/internal/atomic/atomic_amd64.go:16:24
> /usr/local/go/src/runtime/internal/atomic/atomic_amd64x.go:24:6: Loadp redeclared in this block
>         previous declaration at /usr/local/go/src/runtime/internal/atomic/atomic_amd64.go:22:32
> /usr/local/go/src/runtime/internal/atomic/atomic_amd64x.go:30:6: Load64 redeclared in this block
>         previous declaration at /usr/local/go/src/runtime/internal/atomic/atomic_amd64.go:28:26
> /usr/local/go/src/runtime/internal/atomic/atomic_amd64x.go:36:6: LoadAcq redeclared in this block
>         previous declaration at /usr/local/go/src/runtime/internal/atomic/atomic_amd64.go:34:27
> /usr/local/go/src/runtime/internal/atomic/atomic_amd64x.go:41:6: Xadd redeclared in this block
>         previous declaration at /usr/local/go/src/runtime/internal/atomic/atomic_amd64.go:39:37
> /usr/local/go/src/runtime/internal/atomic/atomic_amd64x.go:44:6: Xadd64 redeclared in this block
>         previous declaration at /usr/local/go/src/runtime/internal/atomic/atomic_amd64.go:42:39
> /usr/local/go/src/runtime/internal/atomic/atomic_amd64x.go:47:6: Xadduintptr redeclared in this block
>         previous declaration at /usr/local/go/src/runtime/internal/atomic/atomic_amd64.go:45:47
> /usr/local/go/src/runtime/internal/atomic/atomic_amd64x.go:50:6: Xchg redeclared in this block
>         previous declaration at /usr/local/go/src/runtime/internal/atomic/atomic_amd64.go:48:36
> /usr/local/go/src/runtime/internal/atomic/atomic_amd64x.go:53:6: Xchg64 redeclared in this block
>         previous declaration at /usr/local/go/src/runtime/internal/atomic/atomic_amd64.go:51:38
> /usr/local/go/src/runtime/internal/atomic/atomic_amd64x.go:56:6: Xchguintptr redeclared in this block
>         previous declaration at /usr/local/go/src/runtime/internal/atomic/atomic_amd64.go:54:45
> /usr/local/go/src/runtime/internal/atomic/atomic_amd64x.go:56:6: too many errors
> 2020-11-22 20:30:23 - WARNING (file_svc.py:133 compile_go) Problem building golang executable sandcat.go: Co                                                                                               mmand '['go', 'build', '-ldflags', '-s -w -X main.key=NGKWKN137EV4IG4CMT3Z7VPH3BOL05 ', '-o', '/home/b0ne/De                                                                                               sktop/git/caldera/plugins/sandcat/payloads/sandcat.go-windows', 'sandcat.go']' returned non-zero exit status                                                                                                2.

2.You can find that splunkd.exe has been downloaded successfully under the C:\Users\Public path, but the startup process is not executing effectively. I try to execute the command 'C: \ Users \ Public \ splunkd exe - server http://10.100.17.201:8888 - group blue -v', but Win10 command line shows the error:

> Started sandcat in verbose mode.
> server=http://10.100.17.201:8888
> group=blue
> privilege=User
> initial delay=0
> c2 channel=HTTP
> Beacon API=/beacon
> [+] beacon: ALIVE
> [*] Running instruction 165479
> panic: interface conversion: interface {} is nil, not string
> 
> goroutine 1 [running]:
> _/Users/davidhunt/Desktop/toolbox/caldera/plugins/sandcat/gocat/core.runAgent(0x7b55a0, 0x9c4b70, 0xc0000d8a50)
>         /Users/davidhunt/Desktop/toolbox/caldera/plugins/sandcat/gocat/core/core.go:58 +0x8cc
> _/Users/davidhunt/Desktop/toolbox/caldera/plugins/sandcat/gocat/core.Core(0xc00000c3c0, 0x19, 0xc00000a100, 0x4, 0x0, 0x0, 0x0, 0x0, 0xc0000d8a20, 0x430100)
>         /Users/davidhunt/Desktop/toolbox/caldera/plugins/sandcat/gocat/core/core.go:143 +0x539
> main.main()
>         /Users/davidhunt/Desktop/toolbox/caldera/plugins/sandcat/gocat/sandcat.go:35 +0x458

**environment**
- Caldera version 2.8.1
- go version go1.13.8 linux/amd64
- OS kali 2020
- python 3.6.5

**Comment by wbooth** [comment]
looks like the binary didn't build for some reason and is using the default from the payloads directory which looks out of date. I just updated them so you can try again with the latest payloads. I'll check on kali and see if there is any weird build issues and get back to you

**Comment by uruwhy** [comment]
I was able to successfully compile a sandcat executable on Kali and have that new executable run on a Windows 10 target. Like @wbooth mentioned, the default sandcat.go-windows executable from the payloads directory in the sandcat plugin is out of date and won't work. Compiling a new payload with the 2.8.1 sandcat plugin version will fix the issue.

Kali version info: `Linux mykalihostname 5.6.0-kali2-amd64 #1 SMP Debian 5.6.14-1kali1 (2020-05-25) x86_64 GNU/Linux`
golang version: `go1.13.8 linux/amd64`
Python 3.8.6
