### ISSUE TITLE
Why caldera does not load /data by default

### ISSUE THREAD

**Issue by H4ckd4ddy** [mitre/caldera#1955]
Hi 👋

First thanks you for your work 👍 

Then, I don't understand why custom abilities, adversaries... are stored in `data` folder, but are not loaded after a restart of caldera.

I found that the data folder is only used when no other plugins exist, I'm write ?

https://github.com/mitre/caldera/blob/9ced90be8ee261730b15ccf0b2d8afb3af6ebdf2/app/service/data_svc.py#L164-L166

So how to load custom abilities, adversaries... at startup without changing the code ?

Thanks by advance
Best regards

**Comment by Phoenix1017** [comment]
蓝队为什么登陆不了锕？？？？？

**Comment by privateducky** [comment]
@H4ckd4ddy this looks like a valid bug. 

In version 2.6.2, we were handling this a little differently, by executing this line on server.py when Caldera started up:
```
loop.run_until_complete(data_svc.load_data([Plugin(data_dir='data')]))
```
This looks to be removed in later versions of the server. You can re-add that line to server.py, which should do the trick.

One of the tough things I (admittedly) wrote into Caldera is the complexity around managing TTPs, between the ones you pull in from open-source repos/plugins and the ones you write yourself.

I'm now supporting a new (free) C2 platform called Operator. In this platform, we're handling local data the same as remote. Every time you open Operator, the TTPs are updated and stored in a single directory on disk. If you get a chance to toy with that, let me know.

**Comment by jcleary47** [comment]
> @H4ckd4ddy this looks like a valid bug.
> 
> In version 2.6.2, we were handling this a little differently, by executing this line on server.py when Caldera started up:
> 
> ```
> loop.run_until_complete(data_svc.load_data([Plugin(data_dir='data')]))
> ```
> 
> This looks to be removed in later versions of the server. You can re-add that line to server.py, which should do the trick.
> 
> One of the tough things I (admittedly) wrote into Caldera is the complexity around managing TTPs, between the ones you pull in from open-source repos/plugins and the ones you write yourself.
> 
> I'm now supporting a new (free) C2 platform called Operator. In this platform, we're handling local data the same as remote. Every time you open Operator, the TTPs are updated and stored in a single directory on disk. If you get a chance to toy with that, let me know.

Where in server.py should that line go? **loop.run_until_complete(data_svc.load_data([Plugin(data_dir='data')]))**

I added it under **def run_tasks(services):** but I get this error when trying to start the server:

```
Traceback (most recent call last):
  File "server.py", line 108, in <module>
    run_tasks(services=app_svc.get_services())
  File "server.py", line 52, in run_tasks
    loop.run_until_complete(data_svc.load_data([Plugin(data_dir='data')]))
NameError: name 'Plugin' is not defined
```

**Comment by domainicus** [comment]
Hi @jcleary47, could you try pulling the `reload-data` branch, or manually patching the `app/service/data_svc.py` file with the edit from https://github.com/mitre/caldera/pull/1984/files ?

**Comment by jcleary47** [comment]
> Hi @jcleary47, could you try pulling the `reload-data` branch, or manually patching the `app/service/data_svc.py` file with the edit from https://github.com/mitre/caldera/pull/1984/files ?

Cheers, adding that line to the data_svc.py file appears to have resolved the issue. It loaded an adversary I had stored in /data/ successfully upon restart.
