### ISSUE TITLE
Operations do not run 

### ISSUE THREAD

**Issue by Jack-sudo-svg** [mitre/caldera#1956]
**Describe the bug**
Operations do not complete (agent issues)

**To Reproduce**
I am using a fresh install of 2.8.1, I reinstalled following the README this morning. I am trying to run any operation on any remote agent. If I leave the default untrusted timer (90) then the agents become untrusted after this 90 seconds and the operation will not run (if i start the operation before the agent becomes untrusted it will start the first 2 abilities but once the agent is untrusted it goes no further. If I change the untrusted timer to something very high so that agents cannot become untrusted the operation still does not run and just gets stuck at running. 

I am using the supplied agent code from the GUI

When I start the server I get the below errors:

ERROR (baseworld.py:147 check_requirements) FineNotFoundError(2, "No such file or directory: 'go'")
ERROR (app_svc.py:134 validate_requirements) go does not meet the minimum version of 1.11

but i am running go version 1.15
![image](https://user-images.githubusercontent.com/71085634/100617212-1a622680-3312-11eb-803f-ba2a88b7911d.png)

**Expected behavior**
I expected (from previous testing) that I would be able to run operations on agents that I have deployed to remote machines. 
**Screenshots**

**Desktop (please complete the following information):**
 - OS: kali
 - Browser chrome
 - Version 2.8.1

**Comment by unkempthenry** [comment]
One possibility is that `go` isn't available in the shell environment that caldera is running under (looks like you ran the `go version` command from the directory where the go executables.  One way to test that is from the same terminal and directory that you use to run caldera under, run the `which go` command.  If go isn't found there, then you can add the go directory to your path with `export PATH=$PATH:/usr/local/go` (to permanently add it, you'll want to add the export command to your ~/.bashrc or ~/.bash_profile).

**Comment by Jack-sudo-svg** [comment]
Thank you very much, Henry. 

That has sorted it. All working now. To confirm, Go was not added to PATH properly. I had to run-  export PATH=$PATH:/usr/local/go/bin - before it would run.
