### ISSUE TITLE
docker-compose on Windows

### ISSUE THREAD

**Issue by Hach0u** [mitre/caldera#196]
Hi,

I have the following error while running docker-compose on Windows (with Visual Studio Code):
```
PS C:\XX\Caldera\caldera2\caldera> docker-compose up -d
WARNING: The PWD variable is not set. Defaulting to a blank string.
Creating caldera_caldera_1 ... error

ERROR: for caldera_caldera_1  Cannot create container for service caldera: invalid volume specification: '/host_mnt/usr/src/app:rw'

ERROR: for caldera  Cannot create container for service caldera: invalid volume specification: '/host_mnt/usr/src/app:rw'
ERROR: Encountered errors while bringing up the project.
```
Before I've used the following commands:
```
. "C:\Program Files\Git\cmd\git.exe" clone https://github.com/mitre/caldera.git --recursive
cd caldera
```
Based on the documentation, it seems only this is required. Do you have any issues while it's not working ? Thanks.

**Comment by privateducky** [comment]
@scottctaylor12 do you know offhand? I just ran "docker-compose" from my OSX machine and had no issues.

**Comment by scottctaylor12** [comment]
@Hach0u, I was running this on a Linux system when developing the docker compose file. I am guessing that the docker-compose.yml file line 14 is what is causing a problem:

`      - $PWD:/usr/src/app`

Windows may not understand this variable. Try changing `$PWD:/usr/src/app` to `./:/usr/src/app`

I also saw a stack exchange thread mentioning windows users needing to place a c:\ before the mount location inside of the container.
https://superuser.com/questions/1051520/docker-windows-container-how-to-mount-a-host-folder-as-data-volume-on-windows

Give that a try and let me know if that helps.

**Comment by Hach0u** [comment]
Thanks @scottctaylor12 & @privateducky. I had another issue that was preventing this to be working properly. I have replaced as you suggested which solved the issue. Thank you.

**Comment by mrrobot304** [comment]
@privateducky @Hach0u @scottctaylor12  I would like to use the docker file to set up the C2 server as container , locally on my windows 10 station.
I cloned the repository as @Hach0u did above, but there is no docker-compose.yml file in the caldera repository. 
am I missing  something?

Thanks
