### ISSUE TITLE
Cmd Executor Not Working 

### ISSUE THREAD

**Issue by DefSecSentinel** [mitre/caldera#1974]
I'm running into an issue with Caldera not executing tests in my lab with the cmd executor. All other executors work fine but when I try to run any test with cmd nothing happens. Would disabling UAC cause this problem or have you seen it before? I'm running the golang agent on an up to date Windows10 box with Defender disabled. I am also running the Shutup10 program with a custom config. Again the Powershell executor works fine, I have an agent checking in but as soon as I change to or run the cmd executor my operation finishes immediately without having run the test. 

![image](https://user-images.githubusercontent.com/48036388/102654735-b1164c00-4136-11eb-94a0-494c10a8eb6b.png)

**Comment by DefSecSentinel** [comment]
<img width="1190" alt="Screen Shot 2020-12-18 at 1 53 48 PM" src="https://user-images.githubusercontent.com/48036388/102655764-77dedb80-4138-11eb-84a6-e2da9fc24b24.png">

As you can see the Powershell executor with the same test worked fine.

**Comment by DefSecSentinel** [comment]
Looks like according to the operation json output and agent details that the cmd executor is not available. Any idea why it might not be getting picked up?

**Comment by privateducky** [comment]
@DefSecSentinel I may be crazy ;) but flipping through the available shells in Sandcat (sandcat/gocat/execute/shells/*) I see bash and PowerShell (sh, psh) but not Windows command line prompt. 

Personally, I'd update my local sandcat code to version 2.6.2, which does a super easy-to-read implementation of picking a shell:
```
func buildCommandStatement(executor string, platform string, command string) *exec.Cmd {
	switch executor {
	case "psh":
		return exec.Command("powershell.exe", "-ExecutionPolicy", "Bypass", "-C", command)
	case "cmd":
		return exec.Command("cmd.exe", "/C", command)
	case "pwsh":
		if platform == "windows" {
			return exec.Command("pwsh.exe", "-c", command)
		} else {
			return exec.Command("pwsh", "-c", command)
		}
	case "osa" :
		return exec.Command("osascript", "-e", command)
	default:
		return exec.Command("sh", "-c", command)
	}
}
```
You could make that patch pretty easily.  

Alternatively, someone from the team would have to run through why the current AvailableExecutors() isn't picking up on Windows command prompt (cmd). It looks like the shells_shared.go should be capable of accepting an arbitrary file path to a shell executable -- something that would be passed cmd.exe or pwsh.exe (not to be confused with PowerShell.exe, which is covered).

**Comment by macmiranda** [comment]
I had a similar issue with 3.0.0, operations just remain stuck in RUNNING but none of the abilities are started
![image](https://user-images.githubusercontent.com/17923899/112331261-0d01eb00-8cb9-11eb-8a94-a2dd15646242.png)
Updated sandcat to `master` but still the same issue... no errors in the console.
Any help would be appreciated.

**Comment by b17zr** [comment]
Is this still an issue if gocat is updated to master as well?

**Comment by macmiranda** [comment]
`2021-03-25 08:41:50 - ERROR (contact_http.py:37 _beacon) Malformed beacon: {'host_ip_addrs': ['Unknown field.']}
2021-03-25 08:42:05 - ERROR (contact_http.py:37 _beacon) Malformed beacon: {'host_ip_addrs': ['Unknown field.']}
2021-03-25 08:42:20 - ERROR (contact_http.py:37 _beacon) Malformed beacon: {'host_ip_addrs': ['Unknown field.']}
2021-03-25 08:42:36 - ERROR (contact_http.py:37 _beacon) Malformed beacon: {'host_ip_addrs': ['Unknown field.']}
2021-03-25 08:42:51 - ERROR (contact_http.py:37 _beacon) Malformed beacon: {'host_ip_addrs': ['Unknown field.']}
2021-03-25 08:43:06 - ERROR (contact_http.py:37 _beacon) Malformed beacon: {'host_ip_addrs': ['Unknown field.']}
2021-03-25 08:43:22 - ERROR (contact_http.py:37 _beacon) Malformed beacon: {'host_ip_addrs': ['Unknown field.']}
2021-03-25 08:43:37 - ERROR (contact_http.py:37 _beacon) Malformed beacon: {'host_ip_addrs': ['Unknown field.']}
2021-03-25 08:43:48 - ERROR (contact_http.py:37 _beacon) Malformed beacon: {'host_ip_addrs': ['Unknown field.']}
2021-03-25 08:44:03 - ERROR (contact_http.py:37 _beacon) Malformed beacon: {'host_ip_addrs': ['Unknown field.']}
2021-03-25 08:44:18 - ERROR (contact_http.py:37 _beacon) Malformed beacon: {'host_ip_addrs': ['Unknown field.']}
`

**Comment by b17zr** [comment]
Ah, I see. Master is too far ahead. It looks like the version of gocat pinned in 3.0.0 is behind and missing the cmd executor update. https://github.com/mitre/sandcat/tree/30c0d78b4443faabb0b3ff4ce6d7b49301681875 should have the correct reference to the gocat commit.

**Comment by macmiranda** [comment]
Thanks @b17zr
Are you guys gonna release a 3.0.1 with such small fixes?

**Comment by jcleary47** [comment]
> 
> 
> Ah, I see. Master is too far ahead. It looks like the version of gocat pinned in 3.0.0 is behind and missing the cmd executor update. https://github.com/mitre/sandcat/tree/30c0d78b4443faabb0b3ff4ce6d7b49301681875 should have the correct reference to the gocat commit.

I'm getting this "executor not available" error in 3.0.0 as well - some stuff runs OK but a lot of them are giving me "executor not available" and are not even loading up into an operation.

I downloaded gocat from here: https://github.com/mitre/gocat/tree/1b4b19cd96627eedea00792d27c8d77a6abb4a7b 

And replaced plugins/sandcat/gocat with it, but still the same issue. There something else we might be missing on this?

**Comment by b17zr** [comment]
I've double-checked that https://github.com/mitre/sandcat/tree/30c0d78b4443faabb0b3ff4ce6d7b49301681875 works with the cmd executor. CALDERA master is working as well. Working on getting an updated release.

**Comment by jcleary47** [comment]
> 
> 
> I've double-checked that https://github.com/mitre/sandcat/tree/30c0d78b4443faabb0b3ff4ce6d7b49301681875 works with the cmd executor. CALDERA master is working as well. Working on getting an updated release.

Hmm interesting, OK I will pull down and try to update. Maybe my issue is unrelated... We have a bunch of adversary profiles we built, anywhere from 12-20 abilities. When I try to run the operation, it will load up 2 or 3 and the others just give an error that "executor is not available" - it doesn't even load them into the operations page when I start the operation. But oddly, the default adversary profiles seem to run OK so not sure what the issue might really be.

**Comment by macmiranda** [comment]
@jcleary47 did you rebuild the agents after checking out the gocat ref?

**Comment by jcleary47** [comment]
> 
> 
> @jcleary47 did you rebuild the agents after checking out the gocat ref?

Just did, and it seems to be fixed now. One odd thing I realized was when I downloaded the sandcat folder from https://github.com/mitre/sandcat/tree/30c0d78b4443faabb0b3ff4ce6d7b49301681875 it looks like the gocat folder it downloaded was empty, so I went into it within GitHub and downloaded the gocat folder separately.

![gocat_empty](https://user-images.githubusercontent.com/73623067/114078298-c4c8f800-9876-11eb-8e0b-c65228ab0956.PNG)

**Comment by macmiranda** [comment]
That does seem odd. In general I only use `git` commands. Makes my life easier

**Comment by b17zr** [comment]
Gocat is a sub-module of sandcat, so the git clone would need to be recursive.

**Comment by macmiranda** [comment]
I guess what @jcleary47 is talking about is hitting the download button on github. In that case the gocat folder is just a pointer to another repo's ref, isn't it?

**Comment by jcleary47** [comment]
> 
> 
> I guess what @jcleary47 is talking about is hitting the download button on github. In that case the gocat folder is just a pointer to another repo's ref, isn't it?

Yeah, I hit the "download" button to download the entire Sandcat folder. All of the subfolders appear to have downloaded with their contents except the gocat one. That one I had to go into separately and download and then merge it together. I should have probably used git commands but thought I'd point it out in case anyone else uses the Download button and perhaps is missing the contents of the gocat folder.
