### ISSUE TITLE
Conf.yml on docker-compose running Caldera

### ISSUE THREAD

**Issue by tek911** [mitre/caldera#198]
Issue #70 I believe is related but closed prematurely. Caldera running in docker-compose does not appear to generate a conf.yml file. To recreate this simply run the docker-compose up version of caldera. When you attempt to navigate to the 'https://my-caldera-server:8888/conf.yml' or in my case 'https://[my servers IP]:8888/conf.yml you are met with a 404 not found error. I've exec'd into a bash shell within teh running container image via 'sudo docker exec -it caldera_caldera_1 bash', performed a find from the /usr/src/app directory and grep'd for yml there is no conf.yml leading me to believe some step is being missed and it not generating in the docker version of running the server. 

I am going to be doing another just straight to server install however, I wanted to outline this in the interest of the project (and for validation for soph2 that opened up #70 , lol. ;) 

Seriously though, thanks to all project contributors, its easier to outline problems than to fix them. Thank you guys.

**Comment by privateducky** [comment]
thanks for the support! the docker-compose.yml is (currently) not configured to work with the adversary mode plugin. this plugin requires a few extra dependencies (biggest one being a MongoDB) which we haven't built into the docker-compose. 

we probably won't make a concerted effort to support that, as we're moving most future development into the chain mode plugin. I think it would be pretty easy to append the MongoDB and adversary mode PIP dependencies, if you did want to try it.

**Comment by tek911** [comment]
private, cycles are always fleeting but I definitely would like to contribute to projects I respect. I'll give it a run. Do you guys have any out of band communication paths for questions if anything comes up I needed to tap someone for a quick answer on (slack, email, otherwise)?

**Comment by privateducky** [comment]
@tek911 - yes - you can reach us at caldera@mitre.org. this address goes to all the devs, so it's the best way to get us.
