### ISSUE TITLE
How do I maintain training plugin progress between restarts?

### ISSUE THREAD

**Issue by JED15EN71NEL** [mitre/caldera#1983]
I was progressing through the excellent user training plugin within the GUI and was instructed to create a new user by editing the local.yml and an alert that I would need to restart the server for that change to take effect.

The steps I performed were:
- Stop the caldera.service
- - sudo systemctl stop caldera.service
- Edit the local.yml file and add user test:test
- - vim /var/_caldera/caldera/conf/local.yml
- Restart the the caldera.service (assuming this is how you restart CALDERA because restart instructions are not in DOCS)
- - sudo systemctl start caldera.service (my service appears to launch /var/_caldera/caldera/server.py -E local)
- Logged in with new user test:test

Issue:
Training progress has reset.

I don't know if this is a bug or user error on my part.

Related:
I also cannot get the Mock plugin to start. It requires restart as well after clicking enable in GUI but it never loads. I feel like something in the start service operation is ignoring some necessary local files that contain these changes. If this needs to be a separate issue, please advise.

**Comment by domainicus** [comment]
How have you installed CALDERA?

I can't think of a reason CALDERA would delete data when not starting the server with the `--fresh` flag, unless the process is being terminated ungracefully.

**Comment by JED15EN71NEL** [comment]
I'm using CALDERA installed via Splunk Attack Range (https://github.com/splunk/attack_range/blob/develop/ansible/roles/caldera/tasks/caldera.yml)

I immediately notice now that the version of CALDERA being used by the range is 2.8.1 and imagine that my issue could have been resolved in the latest CALDERA. I guess my question now is can I just update my installation locally on the server running CALDERA 2.8.1? Otherwise, I'll look through the range ansible file and see if I can update it to pull the latest CALDERA.

I understand if this is now outside your support but also appreciate any direction you can provide. Thanks.

**Comment by domainicus** [comment]
I see. Thanks for sharing that. Can you try adding the following line to the `[Service]` section of `/lib/systemd/system/caldera.service`? (from https://github.com/splunk/attack_range/blob/develop/ansible/roles/caldera/templates/systemd-caldera.service.j2)

```
KillSignal=SIGINT
```

Creating a test adversary or operation, stopping the service, starting the service should show that the operation/adversary persists (same would go for the training plugin data).

**Comment by JED15EN71NEL** [comment]
Excellent! That worked! Training progress is persisting through restarts and Mock plugin successfully created new agents. Thank you so much! Merry Christmas!

**Comment by JED15EN71NEL** [comment]
Still new at GitHub. How do I provide this change to the attack_repo guys so it can be fixed for others?

**Comment by domainicus** [comment]
It looks like they have contribution guidelines at https://github.com/splunk/attack_range/blob/develop/docs/CONTRIBUTING.md

You could report the issue on their repo, or create a PR for their team to review (see the Pull Requests section, they break down the steps). I'd recommend trying the PR since it's a common way to contribute to projects and a good way to get involved.
