### ISSUE TITLE
List of Abilities with Name / Tactic/ Technique # 

### ISSUE THREAD

**Issue by jcleary47** [mitre/caldera#1986]
Not an issue, but was wondering if you guys had a list of all of the Ability ID's in Caldera that also have the MITRE ID/Technique Name.

I'm hoping to build out a spreadsheet that has all of them listed for an easier visual representation and reference document for building customer adversary profiles via .yml instead of going through the GUI. 

Not a big deal if you don't, just would save some time going through the yml files and pulling out that data manually. :)

**Comment by aapplebaum** [comment]
Snuck in a little under the radar, but we do! We recently added a feature to our documentation that allows you to dump all abilities loaded into CALDERA; our public documentation has them listed here (https://caldera.readthedocs.io/en/latest/resources.html#ability-list), but if you load up CALDERA with the fieldmanual plugin you can also put these together locally and track custom TTPs you've added.

**Comment by jcleary47** [comment]
Just what I was looking for! Thank you!
