### ISSUE TITLE
Broken Regex Parser in 2.9

### ISSUE THREAD

**Issue by Someniak** [mitre/caldera#1992]
Hi, It looks like this is broken in version 2.9. Any idea on what changes might have introduced this behavior? (I'm a colleague of 0xThiebaut)

_Originally posted by @Someniak in https://github.com/mitre/caldera/issues/1265#issuecomment-754614709_

**Comment by domainicus** [comment]
It sounds like you're updating a custom parser. Happy to help if you have a specific question or can share the parser, otherwise the steps here are appropriate: https://github.com/mitre/caldera/issues/1265#issuecomment-754621581

**Comment by domainicus** [comment]
Closing this issue. Feel free to reach out again if you require support.
