### ISSUE TITLE
Custom Abilities are not returned in API 

### ISSUE THREAD

**Issue by w0rk3r** [mitre/caldera#1997]
**Describe the bug**
Custom abilities are not returned when querying access plugin via API

**To Reproduce**
1. Add custom ability file to plugins/access/data/abilities/
2. Start caldera
3. curl -X POST -H "key:ADMIN123" http://0.0.0.0:8888/plugin/access/abilities -d '{"paw":$paw}'

**Expected behavior**
Custom abilities should be returned in the json respnse

**Desktop (please complete the following information):**
 - OS: Linux, Windows
 - 2.9.0

**Comment by domainicus** [comment]
I am unable to replicate this -- I can see the custom ability. A couple things to note:

- The ability should be created under a directory in `plugins/access/data/abilities/` named after the technique. Ex: `plugins/access/data/abilities/discovery/`. You can make sure it's properly loaded on the adversary page.
- The ability needs an executor that the agent is capable of using. Ex: `psh` if a Windows agent.

**Comment by w0rk3r** [comment]
Hey @domainicus ,

Turns out this issue was caused after a modification in dir permissions...

Just working fine after clean install.

Thank you!
