### ISSUE TITLE
I can‘t find Crater when I install server

### ISSUE THREAD

**Issue by J4son** [mitre/caldera#2]
Install CraterMain.exe
The CraterMain.exe binary needs to be accessible to CALDERA. It should be placed in: caldera/dep/crater/crater/CraterMain.exe on the computer that the CALDERA server is installed on.

I saw this description in installation. I install server on Ubuntu 14.04. But I can't find Crater. Could you help me?

**Comment by hf-mitre** [comment]
We ran into a some delays posting a couple of the dependencies.  We we're working to get those other repositories along with documentation (including installation instructions) set up today.  

Sorry for the inconvenience!

**Comment by dm-mitre** [comment]
Binaries and source for crater and caldera-agent are now available:
https://github.com/mitre/caldera-crater/releases
https://github.com/mitre/caldera-agent/releases
