### ISSUE TITLE
Create Adversary via API

### ISSUE THREAD

**Issue by nicpalmer** [mitre/caldera#2010]
Is there a way to programmatically create Adversaries via the API? 

The [docs](https://caldera.readthedocs.io/en/latest/The-REST-API.html#adversaries) don't seem to show it as possible, but it looks like the endpoint will support a PUT 

https://github.com/mitre/caldera/blob/b874da9bf24ec9025a1016305642298143daaa8e/app/api/rest_api.py#L82

I've written a script that allows me to copy locally developed abilities into the `./data/abilities/$TACTIC` directory, and for particular groups, I'd like to be able to share the adversary file, so that users can run operations simply. 

I've tried simply dropping my adversary file (example below) into the `./data/adversaries` directory, but Caldera doesn't seem to ever see it, hence the ask around the API. I suspect I need to update an index somewhere...

```
---

id: f5ccb24b-1314-485a-8bfc-234bf7b21760
name: APT28
description: APT28 First Pass
atomic_ordering:
  - a4cedb35-5425-4dd8-b95b-22bd42b1b4d8
  - af1a51d8-5068-4e46-9035-af27296a8181
  - d4df3433-4828-4cba-a213-0f2f2ce2e162
  - 85341c8c-4ecb-4579-8f53-43e3e91d7617
  - 643fc9ef-1418-4b98-8467-b62c8f2e3b93
  - e42084fc-0a87-4089-90d9-7fb321e17f3b
objective: 495a9828-cab1-44dd-a0ca-66e58177d8cc
```

Thanks

**Comment by nicpalmer** [comment]
I've got a small workaround to this via a different avenue, dropping things into the stockpile data directories is working for now.

**Comment by domainicus** [comment]
Which version are you running? It's possible that https://github.com/mitre/caldera/pull/1984 fixes the issue with loading from `data/adversaries`.

**Comment by nicpalmer** [comment]
I'm on 2.9.0 - I'll try a build from master when I get a chance - this looks like it could be the issue. Thanks

**Comment by OscarJoverWalsh** [comment]
>>>> Looks like your first issue -- we aim to respond to issues as quickly as possible. In the meantime, check out our documentation here: http://caldera.readthedocs.io/

Hi, I am trying to do something similar, however, any query I do to the API returns the following result "302: Found". Is there something I'm doing wrong?

Thank you very much in advance.

**Comment by OscarJoverWalsh** [comment]
> I've got a small workaround to this via a different avenue, dropping things into the stockpile data directories is working for now.

Hi, I am trying to do something similar, however, any query I do to the API returns the following result "302: Found". Is there something I'm doing wrong?

Thank you very much in advance.

**Comment by OscarJoverWalsh** [comment]
Hi, I am trying to do something similar, however, any query I do to the API returns the following result "302: Found". Is there something I'm doing wrong?

I am using UBUNTU 20.04 on VirtualBox

Thank you very much in advance.

**Comment by OscarJoverWalsh** [comment]
> Is there a way to programmatically create Adversaries via the API?
> 
> The [docs](https://caldera.readthedocs.io/en/latest/The-REST-API.html#adversaries) don't seem to show it as possible, but it looks like the endpoint will support a PUT
> 
> https://github.com/mitre/caldera/blob/b874da9bf24ec9025a1016305642298143daaa8e/app/api/rest_api.py#L82
> 
> I've written a script that allows me to copy locally developed abilities into the `./data/abilities/$TACTIC` directory, and for particular groups, I'd like to be able to share the adversary file, so that users can run operations simply.
> 
> I've tried simply dropping my adversary file (example below) into the `./data/adversaries` directory, but Caldera doesn't seem to ever see it, hence the ask around the API. I suspect I need to update an index somewhere...
> 
> ```
> ---
> 
> id: f5ccb24b-1314-485a-8bfc-234bf7b21760
> name: APT28
> description: APT28 First Pass
> atomic_ordering:
>   - a4cedb35-5425-4dd8-b95b-22bd42b1b4d8
>   - af1a51d8-5068-4e46-9035-af27296a8181
>   - d4df3433-4828-4cba-a213-0f2f2ce2e162
>   - 85341c8c-4ecb-4579-8f53-43e3e91d7617
>   - 643fc9ef-1418-4b98-8467-b62c8f2e3b93
>   - e42084fc-0a87-4089-90d9-7fb321e17f3b
> objective: 495a9828-cab1-44dd-a0ca-66e58177d8cc
> ```
> 
> Thanks

Hi nicpalmer!

I'm trying to do something very similar, creating a program that generates the opponent files automatically, like you do. However, when I try to upload them to CALDERA through the REST API, they don't appear. Did you manage to solve the problem?

Thank you very much. Best regards.
Oscar.

**Comment by OscarJoverWalsh** [comment]
> Is there a way to programmatically create Adversaries via the API?
> 
> The [docs](https://caldera.readthedocs.io/en/latest/The-REST-API.html#adversaries) don't seem to show it as possible, but it looks like the endpoint will support a PUT
> 
> https://github.com/mitre/caldera/blob/b874da9bf24ec9025a1016305642298143daaa8e/app/api/rest_api.py#L82
> 
> I've written a script that allows me to copy locally developed abilities into the `./data/abilities/$TACTIC` directory, and for particular groups, I'd like to be able to share the adversary file, so that users can run operations simply.
> 
> I've tried simply dropping my adversary file (example below) into the `./data/adversaries` directory, but Caldera doesn't seem to ever see it, hence the ask around the API. I suspect I need to update an index somewhere...
> 
> ```
> ---
> 
> id: f5ccb24b-1314-485a-8bfc-234bf7b21760
> name: APT28
> description: APT28 First Pass
> atomic_ordering:
>   - a4cedb35-5425-4dd8-b95b-22bd42b1b4d8
>   - af1a51d8-5068-4e46-9035-af27296a8181
>   - d4df3433-4828-4cba-a213-0f2f2ce2e162
>   - 85341c8c-4ecb-4579-8f53-43e3e91d7617
>   - 643fc9ef-1418-4b98-8467-b62c8f2e3b93
>   - e42084fc-0a87-4089-90d9-7fb321e17f3b
> objective: 495a9828-cab1-44dd-a0ca-66e58177d8cc
> ```
> 
> Thanks

Hi nicpalmer!

I'm trying to do something very similar, creating a program that generates the adversary files automatically, like you do. However, when I try to upload them to CALDERA through the REST API, they don't appear. Did you manage to solve the problem?

Thank you very much. Best regards.
Oscar.
