### ISSUE TITLE
Python 3.9.1 requirements installation fails with CFLAGS="-Wno-error=implicit-function-declaration"

### ISSUE THREAD

**Issue by khyberspache** [mitre/caldera#2026]
**Describe the bug**
On OS  X 10.15+, using python 3.9.1, pip installation of the requirements fails due to `reportlab`. It will fail with:
```
  src/rl_addons/renderPM/gt1/gt1-namecontext.c:102:3: note: include the header <string.h> or explicitly provide a declaration for 'memcpy'
  src/rl_addons/renderPM/gt1/gt1-namecontext.c:172:10: error: implicitly declaring library function 'strcmp' with type 'int (const char *, const char *)' [-Werror,-Wimplicit-function-declaration]
      if (!strcmp (nc->table[i & mask].name, name))
           ^
  src/rl_addons/renderPM/gt1/gt1-namecontext.c:172:10: note: include the header <string.h> or explicitly provide a declaration for 'strcmp'
  3 errors generated.
  error: command '/usr/bin/clang' failed with exit code 1
  ```

**To Reproduce**
1. Create new virtual environment.
2. `pip uninstall reportlab` (make sure you rebuild it)
3. Run `pip install -r requirements.txt`.

**Expected behavior**
Requirements install properly.

**Screenshots**
<img width="1826" alt="image" src="https://user-images.githubusercontent.com/43142871/106399893-56386b80-63e9-11eb-8588-764930b9aa8a.png">

**Desktop (please complete the following information):**
 - OS: Mac 10.15+
 - Browser: N/A
 - Version: Master

**Additional context/Work-around**
You can work around this by making the reportlab install not fail during implicit-function-declaration errors with:
`CFLAGS="-Wno-error=implicit-function-declaration" pip install -r requirements.txt`

[error_log.txt](https://github.com/mitre/caldera/files/5900833/error_log.txt)

**Comment by wbooth** [comment]
thanks, looks like v3.9 isn't in our tests so will add that too

**Comment by wbooth** [comment]
bumped report lab to 3.5.59 which fixed the install issue testing locally. If you see it still happening please re-open. Thanks!

**Comment by khyberspache** [comment]
@wbooth confirming it's fixed, thanks!
