### ISSUE TITLE
Copy 54ndc47 (SMB)

### ISSUE THREAD

**Issue by veslo94** [mitre/caldera#2039]
Explain to me please. This is due to lateral movement tactics. I am using the caldera 2.9.0 GUI. I have a virtual network of several virtual machines. If I run the 54ndc47 agent on a win8 virtual machine, how can I use Copy 54ndc47 (SMB) to start the agent on the next virtual machine for example win10, only with win8. Team:
path = "sandcat.go-windows"; $ drive = "\\ # {remote.host.fqdn} \ C $"; Copy-Item -v -Path $ path -Destination $ drive "\ Users \ Public \ s4ndc4t. exe ";

what parameters do I need to enter in place # {remote.host.fqdn}?

**Comment by veslo94** [comment]
I did not find the answer to my question there

**Comment by blackwidow0616** [comment]
The parameter you need for #{remote.host.fqdn} is the Fully Qualified Domain Name, hostname, or IP address of the remote system. Keep in mind that, in addition to the remote.host.fqdn fact, this ability has additional requirements (in the form of specific edges) that must be supplied before it can run. These edges can be added manually via the sources gui or automatically via an ability that adds them as well as the remote.host.fqdn fact (i.e. - deeac480-5c2a-42b5-90bb-41675ee53c7e). 
To manually add it, you need to create a fact "remote.host.fqdn" with the parameter of the fqdn, hostname, or ip address and give it an edge called "has_share".

**Comment by wbooth** [comment]
Hopefully this addresses your question, if not please feel free to re-open this ticket or start a new one -- Thanks!
