### ISSUE TITLE
Plugin Debrief : Internal Server Error when trying to download PDF

### ISSUE THREAD

**Issue by t0-git** [mitre/caldera#2066]
**Describe the bug**

When I try to download a report after an operation in PDF in the Debrief plugin, I have an error message in the footer Internal Server Error.  This happens only with custom adversaries, not built in ones.

![image](https://user-images.githubusercontent.com/52962854/109805358-a3477180-7c23-11eb-8e02-6ca02dffbd9e.png)

If I try to download it in JSON, I don't have any problem. 

Problem is that, if I check the logs files, there isn't any information about that.
I have a docker environment, and checked the log file in /var/lib/docker/containers/<container_id>/<container_id>-json.log

![image](https://user-images.githubusercontent.com/52962854/109805551-e1dd2c00-7c23-11eb-8f1e-11252333b18e.png)

**To Reproduce**
1. Create a custom adversary
2. Launch an operation related to it.
3. When it's done, go to plugin Debrief, Select the operation and download PDF

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04
 - Browser Chrome
 - Version 2.9.0

**Comment by mchan143** [comment]
Can you say exactly what abilities you were running? 

I discovered a typo that I'll be putting a fix in for shortly, as well as a bug created by Facts with extremely long Values causing the Fact table in the PDF to not generate properly. However, based on the information provided, I'm unsure if these are related to the bug you are reporting.

**Comment by t0-git** [comment]
It fails for both of this two adversaries :
First one : 
- 02e7f222362610730e8f5fbe495a4518                                                                                                                                                                                                           - 8764d6c964901b9a56ca3ffe5e5a004a                                                                                                                                                                                                           - 422526ec-27e9-429a-995b-c686a29561a4                                                                                                                                                                                                       - 85341c8c-4ecb-4579-8f53-43e3e91d7617                                                                                                                                                                                                       - 10681f2f-be03-44af-858d-f2b0812df185                                                                                                                                                                                                       - 5b48201167bde1cc2b7970c6213559fb                                                                                                                                                                                                           - 73524c3b606097cdb22097f7cc3a1e94                                                                                                                                                                                                           - 4b6b44ffc4b462901addfcc484f4db3b                                                                                                                                                                                                           - add2c8586afedd07182459351a5874e5

Second one : 
- 9a30740d-3aa8-4c23-8efa-d51215e8a5b9                                                                                                                                                                                                       - e8017c46-acb8-400c-a4b5-b3362b5b5baa                                                                                                                                                                                                       - a0676fe1-cd52-482e-8dde-349b73f9aa69                                                                                                                                                                                                       - ac9dce33-2acc-4b34-94ce-2596409ce8f0                                                                                                                                                                                                       - b6f545ef-f802-4537-b59d-2cb19831c8ed                                                                                                                                                                                                       - 14a21534-350f-4d83-9dd7-3c56b93a0c17                                                                                                                                                                                                       - 56d6dc2628d8f8c7ceec54f8641d21bf                                                                                                                                                                                                           - 2b4e2a7be6ebda89812fe2d2f39f6173                                                                                                                                                                                                           - 9b5a0a6644a9cccc3dc3aa8be490430e                                                                                                                                                                                                           - 71b3d2945679566b9d94d8cb11df4b70                                                                                                                                                                                                           - 1d46ffd997d1722c5b26b7b1db282454                                                                                                                                                                                                           - d0f5eefa3f39b4e585e0947e0c16a0fe                                                                                                                                                                                                           - 7d8ee68f0e9731db82964f558f614608                                                                                                                                                                                                           - d4aa13cd6322080455d334e6fc2d5972                                                                                                                                                                                                           - 335cea7b-bec0-48c6-adfb-6066070f5f68                                                                                                                                                                                                       - 8adf02e8-6e71-4244-886c-98c402857404                                                                                                                                                                                                       - 4d9b079c-9ede-4116-8b14-72ad3a5533af                                                                                                                                                                                                       - 5a39d7ed-45c9-4a79-b581-e5fb99e24f65                                                                                                                                                                                                       - 0093c0e0-68b6-4cab-b0d4-2b40b3c78f71                                                                                                                                                                                                       - 0bff4ee7-42a4-4bde-b09a-9d79d8b9edd7                                                                                                                                                                                                       - 05cda6f6-2b1b-462e-bff1-845af94343f7                                                                                                                                                                                                       - 3b5db901-2cb8-4df7-8043-c4628a6a5d5a                                                                                                                                                                                                       - 453b8d81c6118310308fb5b22de12235                                                                                                                                                                                                           - f8de05d1741dcc468f772ab0ff4dac72                                                                                                                                                                                                           - c438dbdcf58c8c0e9abb4407a5a0a29b                                                                                                                                                                                                           - 1b47e726716362f535e47c9cd1051c6b                                                                                                                                                                                                           - c1cd6388-3ced-48c7-a511-0434c6ba8f48                                                                                                                                                                                                       - feaced8f-f43f-452a-9500-a5219488abb8                                                                                                                                                                                                       - 26d3702887944abcc64b406baf8f8e43                                                                                                                                                                                                           - a5631e2fe3fe023f592c348d72954b1c                                                                                                                                                                                                           - 1d5411f110766f97b4ba3e217df6c535                                                                                                                                                                                                           - 2925ed908da3eeb96197e0de710568c1                                                                                                                                                                                                           - 4b7c0cbdba2d136adcfd24ff34376883                                                                                                                                                                                                           - 1f11dae222a4189209a8b7cad49d4a57                                                                                                                                                                                                           - e528524d6a3cddaaddc89fcc719e2a3f                                                                                                                                                                                                           - ede4cb2a7ade401fbec1565155ba4cf2                                                                                                                                                                                                           - 68a0a328719faa26fff5b92e18108b3f                                                                                                                                                                                                           - 086125442162d8dcf8478ee9453135c8                                                                                                                                                                                                           - 22aff9c7cec7271f857fbea7db3df858                                                                                                                                                                                                           - c6607391-d02c-44b5-9b13-d3492ca58599                                                                                                                                                                                                       - 9d03c91bdae5a80f17f89c987942b5a8                                                                                                                                                                                                           - d6bb2a19da7246731ed9c44831b135f8                                                                                                                                                                                                           - bb089bbf58ca394664e8109340fcc1a7                                                                                                                                                                                                           - a1ee301b0508747b468d578a14e5c1a5                                                                                                                                                                                                           - 89955f55-529d-4d58-bed4-fed9e42515ec                                                                                                                                                                                                       - 02de522f-7e0a-4544-8afc-0c195f400f5f                                                                                                                                                                                                       - d69e8660-62c9-431e-87eb-8cf6bd4e35cf                                                                                                                                                                                                       - 1f7ff232-ebf8-42bf-a3c4-657855794cfe                                                                                                                                                                                                       - 90c2efaa-8205-480d-8bb6-61d90dbaf81b                                                                                                                                                                                                       - 0ef4cc7b-611c-4237-b20b-db36b6906554                                                                                                                                                                                                       - baac2c6d-4652-4b7e-ab0a-f1bf246edd12                                                                                                                                                                                                       - 7049e3ec-b822-4fdf-a4ac-18190f9b66d1                                                                                                                                                                                                       - 35d92515122effdd73801c6ac3021da7                                                                                                                                                                                                           - d3a25550397b3d791495d41fe6af084c                                                                                                                                                                                                           - 03526668cc55b6544244b107feadaf22                                                                                                                                                                                                           - 7251076ee95386d5292126583ea118d9                                                                                                                                                                                                           - 1b4c6a9df63d154d92c0ad6cb3f42f9d                                                                                                                                                                                                           - bd7780db67f42278033b765eb1c5de55                                                                                                                                                                                                           - 702aa3668648edd588e00c08705cde4e                                                                                                                                                                                                           - 6f86405303018df37b12518dbce0c83b                                                                                                                                                                                                           - deeac480-5c2a-42b5-90bb-41675ee53c7e                                                                                                                                                                                                       - 530e47c6-8592-42bf-91df-c59ffbd8541b                                                                                                                                                                                                       - 3fd81e7ee14b1a354fb9fd9fca1dc910                                                                                                                                                                                                           - 91b056f47bc449f84c52bbd4799289cd                                                                                                                                                                                                           - 397b85c37a87dd8925659f268abe7d90                                                                                                                                                                                                           - f247309a5f934b32f2e510eb50409d3b                                                                                                                                                                                                           - 743517fa2f3b55455ac00bf5278dfb67                                                                                                                                                                                                           - 638fb6bb-ba39-4285-93d1-7e4775b033a8                                                                                                                                                                                                       - 613e0ffb-e6e8-4e86-b35d-10edd232679d                                                                                                                                                                                                       - eedb50b1eb8283215bcf4d9b0531ba01                                                                                                                                                                                                           - 8ed60dceb98746f1da6214f4f6af7164                                                                                                                                                                                                           - c668e2597e8c0ebf1709f85d253995ab                                                                                                                                                                                                           - a14392d713dffba6a397682ff83259a0                                                                                                                                                                                                           - 7c3ba7cadff7e670bb6597174db69b32                                                                                                                                                                                                           - 0c7c18db582bff4d0da4b4f8fdb2be49                                                                                                                                                                                                           - 7121cdf93b951311be9d7078c602efdc                                                                                                                                                                                                           - 344e7eaf650763e0d3e9f02e62c1cf4b                                                                                                                                                                                                           - 2a3209689a6452c07f869f45414cbb4c                                                                                                                                                                                                           - 5f2a68667604f0e3f8188d2a083fbcc5

**Comment by mchan143** [comment]
Was your error resolved with the fix referenced above?

**Comment by t0-git** [comment]
Nope, same error.

**Comment by mchan143** [comment]
Can you clarify whether you were able to pull down the fix mentioned above? It might be easiest to checkout the `master` branch of the Debrief plugin since this fix is not in CALDERA 3.0.

From the list of abilities IDs provided, it appears you may be using custom abilities. Without further information on what is being run, it isn't clear what could be causing the error. I was able to identify and test three of the abilities listed (Dump history, Collect ARP details, Weak executable files) and I'm not finding any issues with generating a PDF for an operation running these abilities.

**Comment by t0-git** [comment]
Well, I checked out the master branch of the debrief plugin, now I'm able to download the PDF for the abilities reported, but I have an error when I try to open it.
All the abilities listed are not custom ones, they are all built-in.

![image](https://user-images.githubusercontent.com/52962854/112136162-e9627600-8bce-11eb-8afe-856eaeea716f.png)

**Comment by mchan143** [comment]
Thank you for the screenshots. Can you pull down the above fix to see if it resolves your issue?

**Comment by t0-git** [comment]
It seems it's not merged in the master branch for the debrief plugin : 

![image](https://user-images.githubusercontent.com/52962854/113850198-7d6d3980-979a-11eb-9d0f-64ad5ab79069.png)

**Comment by mchan143** [comment]
Have you tried running `git pull` to pull down the most recent changes?

**Comment by t0-git** [comment]
Sorry, I don't know why I forgot that yesterday ...
I stopped the container, `git pull origin master`, verified with git log :

![image](https://user-images.githubusercontent.com/52962854/114001806-8fafac00-985c-11eb-9296-1885cbab315e.png)


I restarted the container, launched the operation, and tried to download the pdf with the debrief plugin. Same problem happen. I'm able to download the PDF for the abilities reported, but I have an error when I try to open it.
I tried to find which report sections reproduced the error, and here there are :

![image](https://user-images.githubusercontent.com/52962854/114001591-6000a400-985c-11eb-9ddf-247c4f7889bc.png)

**Comment by mchan143** [comment]
You could try rebuilding to see if that resolves your issue. Are you able to see the graphs displayed in the Debrief GUI? Could you also try clearing your browser cache to ensure the newest scripts are in use?

**Comment by t0-git** [comment]
It seems it's mandatory to rebuild the docker image after pulling updates. Now I'm able to download the PDF and read it.
But the some graphs are empty : 
![image](https://user-images.githubusercontent.com/52962854/114521789-0aa10a00-9c43-11eb-92d4-393a0e924be7.png)

![image](https://user-images.githubusercontent.com/52962854/114521815-0f65be00-9c43-11eb-8afc-8b26cad91c49.png)

![image](https://user-images.githubusercontent.com/52962854/114521841-155b9f00-9c43-11eb-8bc6-00a983bd05cd.png)

![image](https://user-images.githubusercontent.com/52962854/114521870-1ab8e980-9c43-11eb-80d2-0146d64717ca.png)

And so are they on the Caldera's GUI.

![image](https://user-images.githubusercontent.com/52962854/114522013-39b77b80-9c43-11eb-9060-21963baac2b3.png)


![image](https://user-images.githubusercontent.com/52962854/114522039-41772000-9c43-11eb-912f-16796f0ec7f9.png)


![image](https://user-images.githubusercontent.com/52962854/114522065-476d0100-9c43-11eb-8bab-8d4dc9486e3c.png)


![image](https://user-images.githubusercontent.com/52962854/114522104-50f66900-9c43-11eb-8929-f08ab1d33192.png)

**Comment by mchan143** [comment]
Thank you for the screenshots, are you able to see any debug information in the output of the server by any chance?

**Comment by mchan143** [comment]
There may be some mismatching versioning issues introduced due to CALDERA v2.9.0 being used with a newer version of Debrief, is it possible for you to pull down the latest tagged release, 3.1.0, and see if the issues persist?

From your existing `caldera` directory:
```
git checkout tags/3.1.0
git submodule update --recursive
```

Based on the above, you may need to rebuild the docker image before proceeding.
