### ISSUE TITLE
Adversary Mode in CALDERA 2.1.0

### ISSUE THREAD

**Issue by wyc7** [mitre/caldera#2068]
Hello, CALDERA's Contributors!
I am interested in the planning aspect of CALDERA, so I am exploring the adversary mode of CALDERA. I have installed CADERA 2.1.0 and run it with the command ‘python3 -u server.py’.
Screenshot
![image](https://user-images.githubusercontent.com/48666541/109981510-f3b1f280-7d3b-11eb-8b32-870f0e8200a6.png)

Now, I use Google Chrome to log in to CALDERA's webgui with 'https://localhost:8888' or 'https://127.0.0.1:8888'. I tried many times but couldn't access this webpage.
Screenshot
![image](https://user-images.githubusercontent.com/48666541/109982936-56f05480-7d3d-11eb-9ca0-578dddf36342.png)

Why? Can you help me?
Thanks in advance！

**Comment by aapplebaum** [comment]
Hiya -- 2.1.0 is a bit older so my memory is hazy, but can you confirm that the GUI plugin is loaded in the local.conf YAML? I think that version still had GUI as a dedicated plugin and might tell you it's serving the 8888 frontend even if it's not actually doing so.

Another quick question -- can you confirm that port is open and the server is listening? I think "netstat -nat" will show you which ports are open (+ feel free to put in a screenshot)

**Comment by wbooth** [comment]
Hi @wyc7 there is an issue with that version (https://github.com/mitre/caldera/releases/tag/2.1.0) you'll need to use 2.3.0 or later. I highly recommend switching to v3 as you'll see many more features and many less bugs than before

**Comment by wyc7** [comment]
Hello @aapplebaum.I confirm that the GUI plugin is loaded in the local.conf YAML.
Screenshot:
![image](https://user-images.githubusercontent.com/48666541/110117629-169fdd80-7df4-11eb-871f-726be1422b26.png)
I confirm that port is open and the server is listening.
Screenshot:
![image](https://user-images.githubusercontent.com/48666541/110117723-3b945080-7df4-11eb-9e01-232afd7b9c95.png)
I am now trying to follow @wbooth ’s suggestion to install CALDERA 2.3.0 to see the effect.

**Comment by wyc7** [comment]
hello, I have installed CALDERA 2.3.0, and use the command ‘python3 server.py’ to start the service.But still can't access the GUI.
Screenshot:
![image](https://user-images.githubusercontent.com/48666541/110242586-bc3c8380-7f91-11eb-975b-3a988540de7d.png)
![image](https://user-images.githubusercontent.com/48666541/110242595-c52d5500-7f91-11eb-866b-f8036aac889f.png)
Why?

**Comment by wbooth** [comment]
Hi @wyc7, if you are open to using a new version will you try 3.0.0?
