### ISSUE TITLE
Red Hat installation issues

### ISSUE THREAD

**Issue by red-hat-newbie** [mitre/caldera#2084]
Hi!
I have problem with 
1.github cloning - it stops at the plugins/sandcat stage:

"remote: Total 2439 (delta 114), reused 198 (delta 79), pack-reused 2179
Receiving objects: 100% (2439/2439), 1.31 MiB | 2.19 MiB/s, done.
Resolving deltas: 100% (1377/1377), done.
Submodule path 'plugins/training': checked out '5ea20b96d905da367f11607bce0f7995f35db2d9'
Failed to recurse into submodule path 'plugins/sandcat'"

2.pip3 installation:

Collecting cryptography>=3.2 (from -r requirements.txt (line 7))
  Using cached https://files.pythonhosted.org/packages/fa/2d/2154d8cb773064570f48ec0b60258a4522490fcb115a6c7c9423482ca993/cryptography-3.4.6.tar.gz
    Complete output from command python setup.py egg_info:
    
            =============================DEBUG ASSISTANCE==========================
            If you are seeing an error here please try the following to
            successfully install cryptography:
    
            Upgrade to the latest pip and try again. This will fix errors for most
            users. See: https://pip.pypa.io/en/stable/installing/#upgrading-pip
            =============================DEBUG ASSISTANCE==========================
    
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-_jrm2oek/cryptography/setup.py", line 14, in <module>
        from setuptools_rust import RustExtension
    ModuleNotFoundError: No module named 'setuptools_rust'

I use Red Hat Server 7.8/7.9. What should I do (install/correct)? RedHat is my only option

**Comment by wbooth** [comment]
@red-hat-newbie please re-open this issue if Chris' comment didn't resolve your issue, thanks!
