### ISSUE TITLE
SSL Plugin with Manx: 

### ISSUE THREAD

**Issue by initstring** [mitre/caldera#2089]
**Describe the bug**

Thanks Caldera team for such a cool tool!!!

I have configured the SSL plugin per the documentation, and am currently using a LetsEncrypt certificate. This works, and I can access the management console over HTTPS and successfully deploy agents.

However, when I try to use the interactive terminal with the Manx agent, I can type a command but as soon as I press the "enter" key I see the following error at the bottom of my web browser:

```Check your JavaScript console. Uncaught SecurityError: Failed to construct 'WebSocket': An insecure WebSocket connection may not be initiated from a page loaded over HTTPS.```

The Chrome console has the following error:

```Mixed Content: The page at 'https://[REDACTED]:8443/' was loaded over HTTPS, but attempted to connect to the insecure WebSocket endpoint 'ws://https//[REDACTED]/manx/953010'. This request has been blocked; this endpoint must be available over WSS.```

I've left the IP:port defaults in local.conf as follows:

```
app.contact.http: http://0.0.0.0:8888
app.contact.tcp: 0.0.0.0:7010
app.contact.udp: 0.0.0.0:7011
app.contact.websocket: 0.0.0.0:7012
```

**To Reproduce**
1. Follow the documentation to enable the SSL plugin
2. Deploy a Manx agent
3. Inside Caldera, browse to plugins -> Manx
4. Select the active agent
5. Type any command in the terminal

**Expected behavior**
Interactive terminal should return command output

**Desktop (please complete the following information):**
 - OS: Kubuntu 20.10
 - Browser: Chromium, Firefox
 - Version: 3.0.0

**Additional context**

**Comment by alexanderkent** [comment]
Thanks for reporting. The current implementation serves websockets using the ws:\\\ protocol only, but
we are looking to add secure websocket wss:\\\ support and hope to have a PR soon.

https://github.com/mitre/caldera/tree/secure_websockets
