### ISSUE TITLE
data_svc.py:349 _verify_adversary_profiiles

### ISSUE THREAD

**Issue by cyber-yinzer** [mitre/caldera#2097]
Running v3 of caldera on Ubuntu 18 LTS. When running "python3 server.py &", the service will appropriately load but I am seeing the following messages verbose:

> 2021-03-29 21:51:41 - INFO  (app_svc.py:103 load) Enabled plugin: atomic
> 2021-03-29 21:51:41 - INFO  (app_svc.py:103 load) Enabled plugin: compass
> 2021-03-29 21:51:41 - INFO  (app_svc.py:103 load) Enabled plugin: training
> 2021-03-29 21:51:42 - INFO  (app_svc.py:103 load) Enabled plugin: fieldmanual
> 2021-03-29 21:51:42 - INFO  (app_svc.py:103 load) Enabled plugin: sandcat
> 2021-03-29 21:51:42 - INFO  (app_svc.py:103 load) Enabled plugin: access
> 2021-03-29 21:51:42 - INFO  (app_svc.py:103 load) Enabled plugin: response
> 2021-03-29 21:51:42 - INFO  (app_svc.py:103 load) Enabled plugin: gameboard
> 2021-03-29 21:51:42 - INFO  (app_svc.py:103 load) Enabled plugin: debrief
> 2021-03-29 21:51:42 - INFO  (app_svc.py:103 load) Enabled plugin: manx
> 2021-03-29 21:51:42 - INFO  (app_svc.py:103 load) Enabled plugin: stockpile
> 2021-03-29 21:51:42 - INFO  (app_svc.py:103 load) Enabled plugin: pathfinder
> 2021-03-29 21:51:49 - WARNING (data_svc.py:349 _verify_adversary_profiles) Ability referenced in 5fc84e89-8ec2-4c38-9805-9603687920b9 but not found: 74c90223-5b3c-4f0f-856a-f43a7b582da8
> 2021-03-29 21:51:49 - WARNING (data_svc.py:349 _verify_adversary_profiles) Ability referenced in 5fc84e89-8ec2-4c38-9805-9603687920b9 but not found: a7168191-0ca7-4182-b89c-51680343d64d
> 2021-03-29 21:51:49 - WARNING (data_svc.py:349 _verify_adversary_profiles) Ability referenced in 5fc84e89-8ec2-4c38-9805-9603687920b9 but not found: 17768461-dad1-4edc-ac51-b5aa256cd5de
> 2021-03-29 21:51:49 - WARNING (data_svc.py:349 _verify_adversary_profiles) Ability referenced in 5fc84e89-8ec2-4c38-9805-9603687920b9 but not found: 1b6a6641-c3c2-4d00-8fb6-5595730830bc
> 2021-03-29 21:51:49 - WARNING (data_svc.py:349 _verify_adversary_profiles) Ability referenced in 5fc84e89-8ec2-4c38-9805-9603687920b9 but not found: 846985f1-5885-4ac6-a0d2-63f1ca7269a0
> 2021-03-29 21:51:49 - WARNING (data_svc.py:349 _verify_adversary_profiles) Ability referenced in 5fc84e89-8ec2-4c38-9805-9603687920b9 but not found: 0c49069f-8847-40c9-bb3b-fda19528d7a3
> 2021-03-29 21:51:49 - WARNING (data_svc.py:349 _verify_adversary_profiles) Ability referenced in 5fc84e89-8ec2-4c38-9805-9603687920b9 but not found: f90fe187-0455-41ce-8b21-914bb39fac30
> 2021-03-29 21:51:49 - WARNING (data_svc.py:349 _verify_adversary_profiles) Ability referenced in 5fc84e89-8ec2-4c38-9805-9603687920b9 but not found: 14ba8c94-d127-40fb-a909-b805d744d46f
> 2021-03-29 21:51:49 - WARNING (data_svc.py:349 _verify_adversary_profiles) Ability referenced in 5fc84e89-8ec2-4c38-9805-9603687920b9 but not found: 85d5d630-271b-4af3-9595-2bb9a16cf7b2
> 2021-03-29 21:51:49 - WARNING (data_svc.py:349 _verify_adversary_profiles) Ability referenced in 5fc84e89-8ec2-4c38-9805-9603687920b9 but not found: 45f2e05e-78a9-45ea-ae5f-c50be5409f02
> 2021-03-29 21:51:49 - WARNING (data_svc.py:349 _verify_adversary_profiles) Ability referenced in 5fc84e89-8ec2-4c38-9805-9603687920b9 but not found: 7e119981-b921-457e-9f2c-06851cc8246c
> 2021-03-29 21:51:49 - WARNING (data_svc.py:349 _verify_adversary_profiles) Ability referenced in 5fc84e89-8ec2-4c38-9805-9603687920b9 but not found: 9179709f-23f6-482f-9a1e-025cea20bd6e
> 2021-03-29 21:51:49 - WARNING (data_svc.py:349 _verify_adversary_profiles) Ability referenced in 5fc84e89-8ec2-4c38-9805-9603687920b9 but not found: ed8fbef4-1963-4c3b-951c-eac02b38809d
> 2021-03-29 21:51:49 - INFO  (hook.py:58 build_docs) Docs built successfully.
> 2021-03-29 21:51:49 - INFO  (server.py:58 run_tasks) All systems ready.

What am I missing?

**Comment by wbooth** [comment]
Hi @cyber-yinzer, those abilities should not be referenced and will be removed, thank you!
@mrengstrom will update with the PR

**Comment by mrengstrom** [comment]
https://github.com/center-for-threat-informed-defense/caldera_pathfinder/pull/32

**Comment by mrengstrom** [comment]
The PR for resolving the messages you were seeing was pulled in, so if you pull the latest from pathfinder you should be able to resolve those debug messages you were seeing.  I will close this issue but feel free to re-open it or open a new one if you have any more issues.
