### ISSUE TITLE
Payloads caldera

### ISSUE THREAD

**Issue by veslo94** [mitre/caldera#2098]
Hello, caldera has payloads by default, what are these payloads in the documentation for each of them, it is not said anywhere?

**Comment by clenk** [comment]
Hi @veslo94, no they are not each described in the documentation. Each plugin may include payloads, but the main ones are found in the stockpile plugin. You can find all of these payloads [here](https://github.com/mitre/stockpile/tree/master/payloads), and there is an index with a description of each payload [here](https://github.com/mitre/stockpile/blob/master/data/payloads/70632d81-bb39-40dd-bfba-cfd1f8196eb6.yml)

You can also see the list of available payloads in the GUI in the payloads section when adding an ability to an adversary.

![Capture_1](https://user-images.githubusercontent.com/402940/113302057-b0f92100-92cd-11eb-8216-14fd714d4ac3.PNG)

If you search the abilities for one of the payloads you'll find the ability that uses it, with a description that gives an idea of what the payload does. For example, the `totallylegit.exe` payload:

![Capture_2](https://user-images.githubusercontent.com/402940/113302067-b35b7b00-92cd-11eb-99a6-62703b25279f.PNG)
