### ISSUE TITLE
Adding CraterMain.exe to OpenSuse

### ISSUE THREAD

**Issue by Zac-Taylor** [mitre/caldera#21]
Is there any documentation on installing CraterMain.exe to OpenSuse? If so can you please help me out.

Thank you

**Comment by dm-mitre** [comment]
Hi, we haven't ever tried to install CALDERA on OpenSuse, but the installation documentation should be relatively close to what you need: http://caldera.readthedocs.io/en/latest/installation.html#caldera-server-installation

As far as installation steps specific to CraterMain.exe, you just have to download it to a specific location on the server. It will be automatically copied and executed during the game.
