### ISSUE TITLE
User Training: Remote Agent Deployed but not showing as completed

### ISSUE THREAD

**Issue by dkoch144** [mitre/caldera#2109]
The second step for training for the User Cert is to deploy a remote agent on a different os than the host. I have caldera running on an ubuntu 20 vm and a windows 10 vm with the agent deployed and beaconing successfully but the step doesn't show as completed and I can't move on with the training. 

It might be worth while to at least expose the other training even if the cert can't be completed. As it stands, I can't even mess around with any of the other training until this is resolved.

**Comment by iguannalin** [comment]
If it helps, if you go and comment out [this line in the training plugin](https://github.com/mitre/training/blob/8336fa094a7ac09b21642d2b9c811940b48f1142/static/js/training.js#L122), I believe all the training flags should show.

**Comment by mohdalnahel** [comment]
I think I have the same issue. May be this is because the agent is not showing ander the agents list although it is alive. I can't figure out why it is giving me zero agents

**Comment by dkoch144** [comment]
> If it helps, if you go and comment out [this line in the training plugin](https://github.com/mitre/training/blob/8336fa094a7ac09b21642d2b9c811940b48f1142/static/js/training.js#L122), I believe all the training flags should show.

This is helpful, thank you. I would ideally like to complete the training, however I can't get any flags including the one mentioned in this issue to check off. I will just work through the training anyway and keep track myself of what I have completed.

**Comment by dkoch144** [comment]
I think this is solved, I connected my caldera VM to the internet and the flags were marked completed. It would be nice if this training could be completed entirely offline.
