### ISSUE TITLE
Regarding the issue of Thief in the adversary profile

### ISSUE THREAD

**Issue by wyc7** [mitre/caldera#2110]
I installed caldera 3.0.0 under kali linux, and the agent runs on wins10. I am running the Thief operation, and the sensitive file is a png format picture. The operation was completed without errors. But the compressed file sent back via HTTP failed to decompress, why? 

Screenshot：
![image](https://user-images.githubusercontent.com/48666541/113888979-6576d380-97f5-11eb-83cd-4dc42f6a2896.png)
![image](https://user-images.githubusercontent.com/48666541/113889052-73c4ef80-97f5-11eb-991c-f9fc92ef67e0.png)
![image](https://user-images.githubusercontent.com/48666541/113889104-7c1d2a80-97f5-11eb-9c6b-b70353fdee58.png)
![image](https://user-images.githubusercontent.com/48666541/113889188-8fc89100-97f5-11eb-9074-d8ba646635b0.png)
![image](https://user-images.githubusercontent.com/48666541/113889446-d3bb9600-97f5-11eb-93f8-d6475f2ddd24.png)

ERROR: /tmp/JPSA78P1B7IMXQF-ipilca/staged.zip : /tmp/JPSA78P1B7IMXQF-ipilca/staged.zip
Open ERROR: Can not open the file as [zip] archive

ERRORS:
Is not archive

can you help me?

**Comment by mrengstrom** [comment]
All files exfiltrated by caldera by default are encrypted.  There is a script in the utility folder that can be used to decrypt the files manually that are on the file system you can use here:
https://github.com/mitre/caldera/blob/master/app/utility/file_decryptor.py
this is explained in the documentation here:
https://caldera.readthedocs.io/en/latest/Exfiltration.html#unencrypting-the-files

Also, on the latest master code there is a feature implemented that you can view exfiltrated files on the UI and download the files, they are decrypted before staging for download in the browser being used.
https://github.com/mitre/fieldmanual/blob/master/sphinx-docs/Exfiltration.md

**Comment by wyc7** [comment]
The problem has been solved, thank you very much！

Command：
cd caldera/app/utility
python3 file_decryptor.py /tmp/JPSA78P1B7IMXQF-ipilca/staged.zip

Screenshot：
![image](https://user-images.githubusercontent.com/48666541/114036863-02e40d00-98b3-11eb-9281-843a6c39322b.png)
