### ISSUE TITLE
Chinese garbled

### ISSUE THREAD

**Issue by Difficultcl** [mitre/caldera#2121]
1.If there is Chinese in the data returned by the command line after the execution capability, a lot of garbled code will appear.
2.Collect ARP details，After this capability is implemented, the returned data is not saved as facts romete.host.ip.

for example：
![image](https://user-images.githubusercontent.com/38584419/114872862-4b5c7700-9e2d-11eb-9e76-4be290b4fde0.png)
![image](https://user-images.githubusercontent.com/38584419/114872948-616a3780-9e2d-11eb-9762-728b862e8417.png)

**Comment by garunagiri** [comment]
Hi Difficultcl,

Can you show us a screenshot of the `arp -a` command output when you run it in a native shell session please?

Additionally, can you paste the specific characters that are causing the trouble? We'd like to perform some additional testing in order to better understand the issue.

**Comment by Difficultcl** [comment]
hi,Thanks for your answer.The Chinese display is normal in the native shell session.
![image](https://user-images.githubusercontent.com/38584419/115110719-5d662300-9faf-11eb-89e9-ebe13f42b60c.png)

And here are the characters that caused the problem.

½Ó¿Ú: 192.168.10.137 --- 0x3
  Internet µØÖ·         ÎïÀíµØÖ·              ÀàÐÍ
  192.168.10.135        00-0c-29-15-ea-dc     ¶¯Ì¬        
  192.168.10.255        ff-ff-ff-ff-ff-ff     ¾²Ì¬        
  224.0.0.22            01-00-5e-00-00-16     ¾²Ì¬        
  239.255.255.250       01-00-5e-7f-ff-fa     ¾²Ì¬

**Comment by garunagiri** [comment]
I see. Could you paste the Chinese characters themselves from the PowerShell session please?

In order to best debug this, I need to reproduce the issue. What is the method you used to display Chinese characters within PowerShell? Did you install a new font? Or did you change the encoding that PowerShell uses?

**Comment by wbooth** [comment]
Duplicate, please see https://github.com/mitre/caldera/issues/2119 and continue with comments there
