### ISSUE TITLE
how to simulate an attack between the red team and the blue team on CALDERA

### ISSUE THREAD

**Issue by yasmine15** [mitre/caldera#2125]
hello, currently I am doing a research project to simulate an attack on caldera between the red team and the blue team, we would like to know how to make the scenario for this attack knowing full well that we create a plugin and we must use it to detect this attack, thank you very well

**Comment by wbooth** [comment]
Hey @yasmine15 , if you want to connect through caldera@mitre.org I'd be happy to set up a call to talk through this. There is the mock plugin but it hasn't been used much (https://github.com/mitre/mock) this will create fake agents with responses to simulate an attack.

**Comment by yasmine15** [comment]
@wbooth thank you so much for your help,Please do you have any articles on the caldera attack simulation, in fact we have a research project and we  must return it next week  but we are still encountering difficulties,thank you

**Comment by wbooth** [comment]
Of course, replied via email.
