### ISSUE TITLE
Multiple bugs for docker container 

### ISSUE THREAD

**Issue by t0-git** [mitre/caldera#2127]
**Describe the bug**
There are multiple bugs when deploying the caldera container (v 3.1.0) (command from the doc : `docker build . -t caldera:server` ) :
When it is running pip3 install :

![image](https://user-images.githubusercontent.com/52962854/115402057-59264980-a1eb-11eb-861d-57f527380c0a.png)

And another one :

![image](https://user-images.githubusercontent.com/52962854/115402219-8246da00-a1eb-11eb-92a4-3be1568cf984.png)
(This one was also present in 3.0.0 version)

Moreover, it seems upx is needed because sometimes, I have an error message on the GUI. Upx is not in the Dockerfile file, 

Finally, in the documentation, here is the command used to run the container :

`docker run -p 7010:7010 -p 7011:7011 -p 7012:7012 -p 8888:8888 caldera:server`

If people executes this command, the 7011 is open for tcp protocol, but 7011 is used by agents in UDP.  So the agents using UDP protocol will not work. This is my recommendation which works for me :

`docker run -p 7010:7010 -p 7011:7011/udp -p 7012:7012 -p 8888:8888 caldera:server`

**Comment by alexanderkent** [comment]
Thanks for taking the time capturing and reporting -- we are looking at bumping `reportlab` in the near future and will be updating the documentation to add `/udp` to the docker instructions accordingly.

UPX is an optional dependency and shouldn't affect CALDERA's core operation, but we are definitely curious regarding your mention of UPX related error messages in the GUI? Are you referring to `startup errors` in the GUI?

**Comment by t0-git** [comment]
Well I'm not able to reproduce the issue to have the error messge, so ignore the last part about UPX. I'll open another issue if it pops again. Thank you !
