### ISSUE TITLE
Agents implant name how change it?

### ISSUE THREAD

**Issue by 15w34r0n3D4y** [mitre/caldera#2146]
Hi.

First I need say it's perfect project, good job!

I have question about "agents.implant_name" because when I deploy agent and change agent name then save it everytime I run command it create file with default name and add firewall rules with default name (default name is splunkd). 
I see when I type in form IP address command code change it but name not and still $name.

Can I change $name in command code manually or can't?
Is it problem with browser because use Brave?

Thank you for answer.

**Comment by sunil-iyengar** [comment]
Not sure I understand the problem fully but you can check after changing the default name as shown in the screen grab below

![image](https://user-images.githubusercontent.com/20723092/119254105-78b1e880-bb82-11eb-8922-2d53f29d0a0b.png)

**Comment by blackwidow0616** [comment]
This may be a bug that I will continue looking into. In the meantime, there is a way to change it in the command you copy and paste to deploy the agent. The $name variable just grabs the filename from the server response, so when it's getting written to the system at the `[io.file]::WriteAllBytes("C:\Users\Public\$name.exe",$data) | Out-Null;` line, you can replace '$name' with whatever you want. Then when you execute it in `Start-Process -FilePath C:\Users\Public\$name.exe -ArgumentList "-server $server -group red" -WindowStyle hidden;` make sure to replace it there too. 
However, changing the Implant Name in the sidebar (like ghostpepper108 mentioned) is probably the easiest way to change it.

**Comment by copsahl** [comment]
We have come to the conclusion that this problem has something to do with the Brave browser itself. While it is based on Chromium it has some functionality that seems to mess with CALDERA. In our [READEME.md](https://github.com/mitre/caldera/blob/master/README.md) we do indicate that our only supported browser is Google Chrome, so we recommend using that for the best user experience.
