### ISSUE TITLE
access plugin: nmap scan (with scanner.sh) not working

### ISSUE THREAD

**Issue by bmelchorp** [mitre/caldera#2148]
I have deployed caldera and followed instructions in https://caldera.readthedocs.io/en/3.1.0/Initial-Access-Attacks.html
scanner.sh was already in folder /opt/caldera/plugins/access/data/payloads/scanner.sh with contents 
_#!/bin/bash

echo '[+] Starting basic NMAP scan'
nmap -Pn $1
echo '[+] Complete with module'__

access ability with same ID in /opt/caldera/plugins/access/data/abilities/technical-information-gathering/567eaaba-94cc-4a27-83f8-768e5638f4e1.yml with content
_- id: 567eaaba-94cc-4a27-83f8-768e5638f4e1
  name: NMAP scan
  description: Scan an external host for open ports and services
  tactic: technical-information-gathering
  technique:
    attack_id: T1254
    name: Conduct active scanning
  platforms:
    linux:
      sh:
        command: |
           ./scanner.sh #{target.ip}
        payloads:
           - scanner.sh
        cleanup: rm scanner.sh_

sandcat agent deployed in same caldera server under /opt/mysandcat and executing as:
root      6066  0.0  0.1 110040 13612 ?        Sl   17:10   0:00 ./splunkd -server https://172.24.240.35:8443 -group red -v
(spawned via crontab)

![Capture000](https://user-images.githubusercontent.com/20352654/117339753-648e9b80-aea0-11eb-86a5-b4060c373be3.JPG)

sandcat agent running would be PID 6066 and identifier xvkuzq.
I run the ability 
![Capture001](https://user-images.githubusercontent.com/20352654/117340433-2776d900-aea1-11eb-9f9d-2e1cd5e54405.JPG)
![Capture002](https://user-images.githubusercontent.com/20352654/117340448-2a71c980-aea1-11eb-9ee1-4a0d1abd312d.JPG)
![Capture003](https://user-images.githubusercontent.com/20352654/117340455-2c3b8d00-aea1-11eb-9a46-f980d00d6c17.JPG)

I can even see it tasked but nothing shows up in UI.  So I would appreciate to get to know what is wrong:
- scanner.sh ... Should it be executable in access plugin folder? how can I see payload is being fetched by agent?
- if command is ./scanner.sh ... Should I see the executable copied over to my sandcat folder?
- I am using haproxy. Should sandcat agent use port 8443? Can I use 8888?
- Should I use a payload with an id and reference it via {payloadid}?

Of course nmap is installed in caldera server and running shell script manually works as expected.

Thanks for your help in advance. Kindly tell me what else could you need

**Comment by mrengstrom** [comment]
So, going through your questions, here are a few answers, observations, and things to try:

1.  yes, abilities with payloads should be able to be executed from the abilities folder
2. all payloads should be copied down the the same working directory the agent is deployed in
3. Caldera can be setup to run on any port that you would like, and the default http C2 channel is setup to run on port 8888.  If you have a network configuration where you are forwarding ports or proxying the agent should point to the port that locally would resolve to the caldera server.  Depending on your haproxy configuration everything should be fine, and it looks like you were able to get your agent to beacon back and connect, so I don't see any big issues there.
4. the way the ability is currently setup should work without needing to change how the payload name is referenced.

- for nmap to work in the command, it will have to be installed where the agent is deployed, not on the caldera server.  All agent commends are ran locally on the system, so you are living off the land if no payload is pulled down to be executed or tools installed through the ability.

I also just went through and deployed an agent on my laptop and validated that I can execute that ability through access and I see the status update and it completes.

from the agent output you should see something like this (make sure the agent is started with the `-v` flag for verbose output):
```
[+] Beacon (HTTP): ALIVE
[+] Beacon (HTTP): ALIVE
[*] Running instruction cbcf7020-c2a0-42f4-b39c-e8570e8a602f
[*] Fetching new payload bytes via C2 channel HTTP: scanner.sh
[+] Beacon (HTTP): ALIVE
[*] Writing payload scanner.sh to disk at scanner.sh
[*] Submitting results for link cbcf7020-c2a0-42f4-b39c-e8570e8a602f via C2 channel HTTP
[+] Beacon (HTTP): ALIVE
```
The id in there is the link ID which will be different for each link, but you can see the payload being received there.  Also the agent deletes the payload after running the ability, so you would have to have a long running nmap scan or be quick to notice it for this ability.

in the UI you should see the command get tasked as a tile, the locked orange padlock is for commands not picked up by the agent yet and executed, once they are executed they go green and unlock.
<img width="1172" alt="Screen Shot 2021-05-20 at 2 38 16 PM" src="https://user-images.githubusercontent.com/59877971/119040278-d542b700-b97a-11eb-80a7-66c1a6de528d.png">

and clicking on the star you should have your command output:
```
./scanner.sh 127.0.0.1
[+] Starting basic NMAP scan
Starting Nmap 7.80 ( https://nmap.org ) at 2021-05-20 14:30 CDT
Nmap scan report for localhost (127.0.0.1)
Host is up (0.00096s latency).
Not shown: 969 closed ports
PORT      STATE    SERVICE
22/tcp    open     ssh
...
...
27356/tcp filtered unknown

Nmap done: 1 IP address (1 host up) scanned in 6.01 seconds
[+] Complete with module
```

I can see in your screenshot you do not have a tile for the link, so you may not have clicked 'run' after entering your IP address.  Also the bootstrap command to avoid logs has not been collected yet and executed, so you either just deployed the agent and it is waiting in the beacon interval to complete, or there could be a possible communications issue.

Let me know if any of this helps and if you can get anything working now.  If not let me know what your agent output looks like and we can try and see if there are any other issues.
