### ISSUE TITLE
Double quotes contained in commands in abilities are escaped and commands cannot be executed by sandcat

### ISSUE THREAD

**Issue by shinsugarfj** [mitre/caldera#2160]
**Describe the bug**

Double quotes contained in commands in abilities are escaped and commands cannot be executed by sandcat.

**To Reproduce**

1. Run the sandcat agent on the target Windows
2. Execute the following ability on the target.

https://github.com/redcanaryco/atomic-red-team/blob/65510577caa3139f401bbfd2b145b33a4bf892a6/atomics/T1562.001/T1562.001.yaml#L364-L365 
```
- name: Remove Windows Defender Definition Files
 : :
    command: |
      "C:\Program Files\Windows Defender\MpCmdRun.exe" -RemoveDefinitions -All
```

**Expected behavior**

The command runs successfully.

**Screenshots**

![image](https://user-images.githubusercontent.com/69222886/118898979-bcb9a900-b948-11eb-8809-956aef5622c3.png)

**Desktop (please complete the following information):**

 - OS: Server: Ubuntu 20.04, Target: Windows 10
 - Browser: Microsoft Edge(Chrome Ver)
 - Version: 3.1.0

**Additional context**

The probable cause is that the `exec.Command` used in the code below escapes the double quotes contained in the command string.

https://github.com/mitre/gocat/blob/fbb28a3ebfe1c305c6220c77c6ea20867bf25bb9/execute/shells/cmd.go#L28
```
	return runShellExecutor(*exec.Command(c.path, append(c.execArgs, command)...), timeout)
```

**Comment by blackwidow0616** [comment]
I am looking into this, and I will get back to you as soon as I have more information.

**Comment by uruwhy** [comment]
https://github.com/mitre/gocat/pull/57 This patch should take care of the issue. Please let us know if you come across anything else, thank you!
