### ISSUE TITLE
Training data is not retained after Caldera application restart (Python web server)

### ISSUE THREAD

**Issue by ghostpepper108** [mitre/caldera#2161]
**Describe the bug**
Training data is not retained after application restart.

**To Reproduce**
1. Open Caldera portal
2. Open "training" under Plugins
3. Select "User Certificate" in the drop down
4. Complete few CTFs
5. Restart the python application
6. Repeat step 1 to step 3 (both steps included)

**Expected behavior**
The completed CTFs should be shown

**Screenshots**
Completed CTFs

![image](https://user-images.githubusercontent.com/20723092/119253681-5d45de00-bb80-11eb-90bf-e5f0e1d58469.png)

After restart of Caldera application (python)
![image](https://user-images.githubusercontent.com/20723092/119253810-f543c780-bb80-11eb-9722-dbdc0b42cff4.png)

**Desktop (please complete the following information):**
 - OS: Mac
 - Browser Chrome
 - Version 90.0.4430.212

**Additional context**

**Comment by blackwidow0616** [comment]
CALDERA writes data to disk when the server is closed, generally using Ctrl+C. As long as the server is not being force killed, the data should be retained on the next startup. However, if the server is being started with the --fresh flag, the data will be cleared and therefore not persist.

**Comment by ghostpepper108** [comment]
@blackwidow0616 Understood. I start Caldera application as a background process hence ctrl+c is not an option. Killing the process seems an only option for me to restart. I am not sure why the certificate data is written to disk only when gracefully shutting down the server as against saving the data as when training is progressed. All other functionalities like adversaries, abilities etc. get saved right away.

**Comment by ghostpepper108** [comment]
@b17zr  Perfect, thank you. This helps.
