### ISSUE TITLE
Unable to get agent to beacon to C2 server

### ISSUE THREAD

**Issue by jasperosy** [mitre/caldera#2164]
I have simulated a network as such:

caldera-server ------- Windows VM 1(2 network interfaces, able to beacon directly back to C2 server)
                                           |
                                  Windows VM 2(different subnet, unable to beacon back directly)

I'm trying to get Windows VM 2 to beacon back to the C2 server via a proxy.
I have looked at the sandcat agent's functionality to perform peer-to-peer functionality. https://caldera.readthedocs.io/en/latest/Sandcat-Peer-to-Peer.html but the documentation was either lacking in details or not functioning as expected. 

I have added headers in the downloading of the agent from the C2 server, "$wc.Headers.add("gocat-extensions", "proxy_http")" and ran the agent with "-listenP2P" flag but the agent that has been deposited on Windows VM 2 is not able to proxy back to the C2 server. 

Simiarly, I have tried using smb pipe for peer-to-peer proxying using this header, "$wc.Headers.add("gocat-extensions", "proxy_smb_pipe") " but i got 404 not found when trying to download data from the caldera server. I have ensured proxy_smb_pipe.go is present in the gocat-extensions folder of the sandcat plugin. Furthermore, it shouldn't be a go language issue since proxy_http headers was added without an issue. 

If the peer to peer proxying is successful, should I be able to see the agent running on VM 2 on the caldera GUI?

Is there a specific step I am missing to allow the agent at Windows VM 2 to beacon back to the C2 server? If there is, I would greatly appreciate if you can help me out by explaining the steps to me. Thank you!

**Comment by blackwidow0616** [comment]
If the peer to peer proxying is successful, you should be able to see the agent from VM 2 in agent listing in the CALDERA GUI. 

I am looking into the specific steps for this and will get back to you once I have more information.

**Comment by jasperosy** [comment]
Thank you! I would greatly appreciate it if you are able to provide the commands and requirements to have this HTTP proxy working.

**Comment by uruwhy** [comment]
@jasperosy  Can you verify the following:
- Windows VM 2 has connectivity to Windows VM 1
- When starting an agent on Windows VM 1 with http proxy receiver, the receiver address/ports show up in the agent details ("Peer-to-Peer Proxy Receivers") in the GUI. If running the agent in verbose mode, the verbose output will indicate which local proxy receivers are active, if any.

If both conditions above are met, try running the agent on Windows VM 2 using the Windows VM 1 agent's local HTTP proxy receiver address as the `-server` value. For example, if the agent on Windows VM 1 is listening on port 12345 for HTTP proxy requests, then start the agent on Windows VM 2 with `-server` value `http://windowsvm1address:12345`. Let me know if this fails, and I can help investigate further.

**Comment by jasperosy** [comment]
I have verified that VM2 has connectivity to VM1. 

However, after having ran my agent with gocat-extensions of proxy_http and starting it with -listenP2P flag and -v, I realised that the agent only flashed some details right at the moment it was launched and all the details disappeared. Furthermore, when I checked the agent details, the peer-to-peer-proxy receiver row was not filled.

![image](https://user-images.githubusercontent.com/36022363/120570141-037bc880-c44a-11eb-8b5f-6e082424d689.png)

**Comment by uruwhy** [comment]
Regarding the details disappearing: the agent is configured to run "bootstrap" abilities upon initial connection to the server. These bootstrap abilities are user-configured commands to run whenever you get a new agent beacon - the default ability is to clear the terminal window/history (if running the agent via powershell, it'll clear the logs and the screen like you just saw). You can still capture the agent's verbose output by redirecting it to a file (e.g. `C:\Users\Public\splunkd.exe -server yourserveraddress > agentlogs.out`) and then tailing the log in a separate window (e.g. `Get-Content agentlogs.out -wait` for powershell).

There could be a few reasons why you have `-listenP2P` enabled, but the agent still isn't listening on any local ports for HTTP proxy requests. Can you verify again via your C2 server logs that your agent executable was compiled correctly? If your agent binary doesn't compile correctly in real-time, the server will default to the last-known pre-compiled agent binary that resides in the `payloads` directory within the sandcat plugin. For windows, this backup binary is typically found in `payloads/sandcat.go-windows`. I'm wondering if perhaps even though you are requesting a new agent binary with the http proxy extension, the server isn't compiling it correctly for whatever reason, and you get back a binary that doesn't have the extension compiled in (thus, no HTTP proxy listeners).  

Looking back, you did mention that the extension seems to have been added without any issue, so my guess is that your agent isn't able to listen on the local port for whatever reason (we'd have to see the verbose logs to determine exactly what's going on). For now, see if you can get the agent output redirected to a log file, and we can move forward from there.

**Comment by jasperosy** [comment]
It seems that the agent is able to compile correctly with the allow p2p receivers=true flag being set correctly. However, I still cannot see any ip address or port the proxy is receiving at in the GUI.

![image](https://user-images.githubusercontent.com/36022363/120967110-b2493d00-c799-11eb-9caf-b8ef616b2936.png)

**Comment by uruwhy** [comment]
Hi Jasper. Can you verify in your server logs that the proxy_http extension is being added correctly? Your agent log looks like the output I get when I run an agent with `-listenP2P` set, but without installing the `proxy_http` extension. When compiling an agent with that extension, your server logs should look like the following:

```
2021-06-07 08:56:03 - DEBUG (sand_svc.py:241 _obtain_extensions_from_headers) Using gocat variant: basic
2021-06-07 08:56:03 - DEBUG (sand_svc.py:193 _install_gocat_extensions) Installing gocat extension modules: proxy_http
2021-06-07 08:56:03 - DEBUG (sand_svc.py:135 _compile_new_agent) Dynamically compiling sandcat.go
2021-06-07 08:56:03 - DEBUG (sand_svc.py:203 _uninstall_gocat_extensions) Cleaning up files for gocat extension modules proxy_http
2021-06-07 08:56:04 - DEBUG (app_svc.py:123 retrieve_compiled_file) sandcat.go downloaded with hash=31f714a7e36d256168ab257e4d1d32aef3bd21c0e4116c68d96ce4a82a6f9897 and name=splunkd
```

**Comment by jasperosy** [comment]
I have checked the debug logs that it shows the same debug output.

![image](https://user-images.githubusercontent.com/36022363/121119516-568cbb80-c84e-11eb-92f9-3771db6c4b17.png)

**Comment by uruwhy** [comment]
Could you verify which git commit hashes you have for the sandcat and gocat github modules?

**Comment by jasperosy** [comment]
The git commit short hash is : b874da9
The version of caldera I am currently using is 2.9.0-796cbdc26559a50869d042e0a442f1c7

By the way, if the http proxy is working and I managed to drop an agent on VM2, then if I were to provide the C2 server and the agent cannot reach it, will the agent on VM2 automatically get the http proxy receiver address of http://vm1address:port ?

**Comment by uruwhy** [comment]
You will need to update the sandcat and gocat submodules accordingly - it looks like there's some version incompatibility between those two submodules. If you go into the `plugins/sandcat` and `plugins/sandcat/gocat` folders, can you verify which github commit hashes you have for those two submodules? 

Regarding your second question, more recent versions of the agent code will have agents automatically broadcast their peer-to-peer addresses for other agents to pick up periodically - that way, those agents that cannot connect directly to the C2 can attempt those peers. If I know which version of gocat you're running, then I can confirm whether or not you should expect this behavior. 

Regarding your original agent, are you running it with any sort of AV or firewall enabled? Something's preventing your agent from opening up local ports to listen for HTTP requests, and I'm curious to see what that might be.

**Comment by jasperosy** [comment]
The plugin details are for this caldera version: b874da9
This is for plugins/sandcat: 3e491a0
This is for plugins/sandcat/gocat: c096516

Oh for the original agent, I have tested with all firewalls off thus it should not affect any port usage.

**Comment by uruwhy** [comment]
I did try running an HTTP proxy agent with the plugin versions that you originally used, and I can confirm that the proxy does not initialize. The reason is that the gocat submodule was out of date for the 2.9.0 release, so the c096516 commit you were using is actually in the early stages of incorporating peer-to-peer (in other words, the full feature didn't exist). If you were to check out the https://github.com/mitre/gocat/commit/e30ee58e1a8d4b0eaeb8a5ddd0e739629060c221 commit for gocat (using the previous sandcat/caldera commit versions you were using), you should be able to use the proxy feature. 

It looks like you did try to update your caldera core and plugin versions, so the proxy features should definitely work there. Apologies for the inconvenience - let me know if you come across any other issues.

**Comment by jasperosy** [comment]
Just a quick question. For these agents:
plugins/sandcat: af31179
plugins/sandcat/gocat: fbb28a3

caldera-server ------- Windows VM 1(2 network interfaces, able to beacon directly back to C2 server)
|
Windows VM 2(different subnet, unable to beacon back directly) - VM3 - VM4

I have tried launching sandcat agents with http proxy extensions and listenP2P enabled for VM2, 3, 4. However, the agents at VM3 and VM4 are not able to proxy to VM1 if I do not give a specific address and port to beacon to. Should the beaconing be resolved automatically in the case where there are multiple agents with proxy extensions and listenP2P enabled?

**Comment by uruwhy** [comment]
If you check the verbose agent output for VM3 and VM4, are they receiving any peer-to-peer receiver addresses being broadcast by the agent on VM1? Sandcat agents will broadcast their p2p receiver addresses so that agents on the same network can see who can relay p2p messages. The beaconing should be resolved automatically. If you are having issues, please send me the agent output, and I can take a look

**Comment by jasperosy** [comment]
Oh it turns out the agents took quite some time to look for the correct broadcasting addresses. Thanks for all your help

**Comment by uruwhy** [comment]
You're very welcome! If I recall, the agent will first try reaching the specified server value. If it fails to beacon 3 times in a row, then it'll switch to peer-to-peer. I think it's ~15 seconds or so of wait-time in between each re-try, so it can take a while like you said.
