### ISSUE TITLE
Problems with killing agents

### ISSUE THREAD

**Issue by radioheado** [mitre/caldera#2171]
Hi Caldera team,

Thanks for the brilliant work!
I have problems when trying to kill the agents.
I saw that there is a closed issue [here](https://github.com/mitre/caldera/issues/1586), and I've checked the watchdog(0s) and sleep timers(30/60s). 
Please take a look at the following screenshot:
![image](https://user-images.githubusercontent.com/42974719/120726605-76b32800-c4a6-11eb-9257-57b9ec4eedf9.png)
These five agents were generated by MOCK plugin and I have no idea how to control their lifecycle.
I tried to click "Kill Agent" through web interface, the PID went yellow with value "0". Then I clicked the red cross to remove the agents from the panel. Several seconds later, these agents popped up again.
I repeated the procedure above, the agents just came back non-stoppably. 
I also have manually deployed agents and tried the same procedure. Initially they didn't get eliminated just like the MOCK agents. Then I tried the REST command like this curl -H "KEY:$API_KEY" -X DELETE http://localhost:8888/api/rest -d '{"index":"agents","paw":"$agent_paw"}', and it worked. So you won't see them from the screenshot. However, this command didn't work for the MOCK agents even if I got a "Delete action completed" output.
Thanks for reading this, and please pardon my language since I am not a native speaker.

**Comment by blackwidow0616** [comment]
I am looking into this, and I will get back to you as soon as I have more information.

**Comment by blackwidow0616** [comment]
I believe this is due to the Mock plugin creating the agents via the yaml file. So until the server restarts and the configuration changes, those agents will continue to keep appearing/respawing. If you wish to just not use those agents anymore, you can change the group by clicking on the PID and editing it there, so they won't be grouped with any other agents you're working with.

**Comment by blackwidow0616** [comment]
Hopefully this resolves your issue. If you’re still having any problems, please feel free to re-open or start a new ticket. Thanks!
