### ISSUE TITLE
Error deploying Sandcat agent on Windows XP machine.

### ISSUE THREAD

**Issue by isaaclittler** [mitre/caldera#2178]
I am trying to deploy the sandcat agent on a windows XP machine and when I run the given command it fails with the error 
![image](https://user-images.githubusercontent.com/39070468/121629087-1e4ccf00-ca40-11eb-91e6-fe5aabb65afb.png) . 
The splunkd.exe is being downloaded and I do not see any errors on download when the Caldera server is run with DEBUG.

I am curious if Windows XP is supported by Sandcat, or if there is just an issue with my deployment.

Thanks.

**Comment by mrengstrom** [comment]
@isaaclittler
Right now the windows sandcat agent that is built is for 64bit architecture machines.  Also from a language compiler standpoint, for go 1.11 and onwards win xp and vista are not supported.

The easiest way for you to try out something that might work, would be to deploy caldera on a machine that does not have golang installed, and compile the agents on a VM or another machine with this build command using these GOOS and GOARCH value (run it from the gocat folder).  If golang is not installed the agent will not be dynamically compiled when requested and it will be taken from the payloads folder in the sandcat plugin. (./plugins/sandcat/payloads)

```
GOARCH=386 GOOS=windows go build -o ../payloads/sandcat.go-windows -ldflags="-s -w" sandcat.go
```

After building take that output agent and replace the one in the payloads folder to have it be deployed by the server.  I am not guaranteeing it will work, but that would be your best bet to get a compiled agent for a 32-bit win xp deployment.

**Comment by blackwidow0616** [comment]
Hopefully this resolves your issue. If you’re still having any problems, please feel free to re-open or start a new ticket. Thanks!
