### ISSUE TITLE
Is it possible to segment agent and admin traffic?

### ISSUE THREAD

**Issue by initstring** [mitre/caldera#2191]
Currently, agent download and communications (i.e. Sandcat) terminate at port 8888 on the Caldera server. So does web administration. While this can be protected with a TLS proxy, it appears that it still eventually gets served by the local 8888.

We are working to harden our instance a bit, and are using an identity-aware proxy to protect all traffic to the management interface. Unfortunately, this breaks the ability for machines to download agents and communicate back with them.

Is it possible for the server to completely separate management and agent traffic?

In the meantime, we are configuring a second TLS load balancer to be be used for agents. But, technically, that could still be used to access the management UI (which we don't want).

Thanks again for such an awesome tool!

**Comment by uruwhy** [comment]
Good morning,

Glad you are enjoying the tool and making good use of it! And great question - it looks like we currently don't have any built-in easy ways to separate out the traffic based on port (i.e. assign port A for management traffic and port B for beacon traffic). The HTTP contact for agent communication uses the same socket as the management interface - the only difference being that the `/beacon` endpoint is reserved for agent traffic. Agents will also use the `/file/download` and `/file/upload` endpoints (unauthorized), which also reside on the same socket. If you're able to separate traffic based on URL endpoint, that's probably the easiest way without changing the current codebase. In other words, you can assume that traffic for `/beacon`, `/file/download`, and `/file/upload` is agent traffic, and anything else is API or management traffic (e.g. login, API requests)

**Comment by initstring** [comment]
@uruwhy -

Thank you so much for the thoughtful reply! This is very helpful. I believe the LB we are using can actually do some restrictions based on URL path, so this is probably enough to do the trick.

If I'm not mistaken, the URL to generate the agent and download initially is still `/`, but we might be able to add some logic on the POST parameters there.

Thanks again! I believe this can be closed now, so I'll close it out.

**Comment by uruwhy** [comment]
Hi @initstring,

Since the agent executable is considered a special payload, it is generated by sending a request to the `/file/download` endpoint. For example, a minimal Powershell snippet to download a dynamically compiled sandcat executable may look as follows:

```
$url="http://192.168.137.1:8888/file/download"; 
$wc=New-Object System.Net.WebClient;
$wc.Headers.add("platform","windows");
$wc.Headers.add("file","sandcat.go");
$output="C:\Users\Public\sandcat.exe";
$wc.DownloadFile($url,$output);
```

**Comment by initstring** [comment]
@uruwhy ,

Thanks for the updated info. Yes, of course you are correct. I was simply reading some console output incorrectly. This makes it much easier to filter for.

Have a great week!

**Comment by uruwhy** [comment]
Glad it's working out! Let us know if you run into any other issues or if you have any other questions. You have a great week, as well!
