### ISSUE TITLE
Long-last abilities cause an error "Resource temporarily unavailable"

### ISSUE THREAD

**Issue by ramus82** [mitre/caldera#2201]
**Describe the bug**
When an ability which requires some time to finish is executed, an error message "[Errno 11] Resource temporarily unavailable" appears in command output in Operations (after the ability is executed). The long-lasting ability is for example ability which invokes some scripts (like linenum.sh) which requires some time to finish. 

**To Reproduce**
1. create a script which contains some activity which requires some time to finish. Example:
`#!/bin/bash`
`echo "Starting sleeping ... chrrr" | tee /tmp/sleeping.out`
`sleep 5`
`echo "1st attempt to wake up ..." | tee -a /tmp/sleeping.out`
`sleep 5`
`echo "2nd attempt to wake up ..." | tee -a /tmp/sleeping.out`
`sleep 5`
`echo "... it's not worth it" | tee -a /tmp/sleeping.out`

2. store the script on the victim/agent (for example in /tmp) and assign the execution privileges (chmod +x /tmp/sleeping.sh)
3. create an ability which simply run the script on the path (e.g.: /tmp/sleeping.sh)
4. execute that ability (add it in adversary, create an operation and run it)
5. see the results of the executed ability in the Operations window

**Expected behavior**
The indicator (white/yellow star) can indicate when the script finished. After finishing the activity a result is displayed.

**Desktop:**
 - OS: Ubuntu 16.04, Centos 7 (tried on both OSs)
 - Browser: Firefox, Chrome, Edge
 - Caldera Version: 3.1.0
 - Python: 3.5, 3.9

I would appreciate if you can help me where to debug (which .py module of Caldera is take care about handling communication between agents/requestors).

**Comment by uruwhy** [comment]
@ramus82 Thank you for bringing up this bug! Just for my awareness, which agent did you use to produce this bug? Was it the Manx reverse-shell agent?

**Comment by ramus82** [comment]
Hi uruwhy, 
I used manx as well as sandcat.

If you, guys, help me where to enable some debugging info I can provide more details. In regular debug log is nothing.

Thanks

**Comment by uruwhy** [comment]
Hi @ramus82 , if you want to enable debugging on the server, you can run `server.py` with the `--log DEBUG` flags. However, that may not provide the information you're looking for. Let me see which files may be relevant - I'll also try to replicate this error with the manx and sandcat agents.

**Comment by uruwhy** [comment]
Hi @ramus82 . The sandcat agent didn't seem to have these issues. When using the manx agent, I did run into the problems that you described. I went ahead and put some fixes together via pull requests - however, they will only apply to the latest master branch of caldera. If you want to maintain your 3.1.0 version and avoid waiting for the PRs, you can change your `app/contact_tcp.py` file accordingly (github isn't letting me attach the file for some reason):

```
import asyncio
import json
import socket
import time

from app.utility.base_world import BaseWorld
from plugins.manx.app.c_session import Session


class Contact(BaseWorld):

    def __init__(self, services):
        self.name = 'tcp'
        self.description = 'Accept beacons through a raw TCP socket'
        self.log = self.create_logger('contact_tcp')
        self.contact_svc = services.get('contact_svc')
        self.tcp_handler = TcpSessionHandler(services, self.log)

    async def start(self):
        loop = asyncio.get_event_loop()
        tcp = self.get_config('app.contact.tcp')
        loop.create_task(asyncio.start_server(self.tcp_handler.accept, *tcp.split(':'), loop=loop))
        loop.create_task(self.operation_loop())

    async def operation_loop(self):
        while True:
            await self.tcp_handler.refresh()
            for session in self.tcp_handler.sessions:
                _, instructions = await self.contact_svc.handle_heartbeat(paw=session.paw)
                for instruction in instructions:
                    try:
                        self.log.debug('TCP instruction: %s' % instruction.id)
                        status, _, response = await self.tcp_handler.send(
                            session.id,
                            self.decode_bytes(instruction.command),
                            timeout=instruction.timeout
                        )
                        beacon = dict(paw=session.paw, results=[dict(id=instruction.id, output=self.encode_string(response), status=status)])
                        await self.contact_svc.handle_heartbeat(**beacon)
                        await asyncio.sleep(instruction.sleep)
                    except Exception as e:
                        self.log.debug('[-] operation exception: %s' % e)
            await asyncio.sleep(20)


class TcpSessionHandler(BaseWorld):

    def __init__(self, services, log):
        self.services = services
        self.log = log
        self.sessions = []

    async def refresh(self):
        index = 0

        while index < len(self.sessions):
            session = self.sessions[index]

            try:
                session.connection.send(str.encode(' '))
            except socket.error:
                self.log.debug('Error occurred when refreshing session %s. Removing from session pool.', session.id)
                del self.sessions[index]
            else:
                index += 1

    async def accept(self, reader, writer):
        try:
            profile = await self._handshake(reader)
        except Exception as e:
            self.log.debug('Handshake failed: %s' % e)
            return
        connection = writer.get_extra_info('socket')
        profile['executors'] = [e for e in profile['executors'].split(',') if e]
        profile['contact'] = 'tcp'
        agent, _ = await self.services.get('contact_svc').handle_heartbeat(**profile)
        new_session = Session(id=self.generate_number(size=6), paw=agent.paw, connection=connection)
        self.sessions.append(new_session)
        await self.send(new_session.id, agent.paw, timeout=5)

    async def send(self, session_id, cmd, timeout=60):
        try:
            conn = next(i.connection for i in self.sessions if i.id == int(session_id))
            conn.send(str.encode(' '))
            conn.send(str.encode('%s\n' % cmd))
            response = await self._attempt_connection(session_id, conn, timeout=timeout)
            response = json.loads(response)
            return response['status'], response["pwd"], response['response']
        except Exception as e:
            return 1, '~$ ', e

    """ PRIVATE """

    @staticmethod
    async def _handshake(reader):
        profile_bites = (await reader.readline()).strip()
        return json.loads(profile_bites)

    async def _attempt_connection(self, session_id, connection, timeout=60):
        buffer = 4096
        data = b''
        waited_seconds = 0
        time.sleep(0.1)  # initial wait for fast operations.
        while True:
            try:
                part = connection.recv(buffer)
                data += part
                if len(part) < buffer:
                    break
            except BlockingIOError as err:
                if waited_seconds < timeout:
                    time.sleep(1)
                    waited_seconds += 1
                else:
                    self.log.error("Timeout reached for session %s", session_id)
                    return json.dumps(dict(status=1, pwd='~$ ', response=str(err)))
        return str(data, 'utf-8')
```

**Comment by ramus82** [comment]
Hi @uruwhy ,
I tested the sandcat and it's really working fine. I was running it on older release of Caldera (on version 3.1.0 it works fine).

The new update of connect_tcp.py for manx works fine.

Thanks a lot.
