### ISSUE TITLE
Agent Deployment

### ISSUE THREAD

**Issue by Sivavamsiraju** [mitre/caldera#2209]
Any one please help me to deploy the agent. i am fcing issues with command when i am running the command it was not installing the agent

**Comment by Sivavamsiraju** [comment]
> 
> 
> Looks like your first issue -- we aim to respond to issues as quickly as possible. In the meantime, check out our documentation here: http://caldera.readthedocs.io/

Hi I am trying from this document only but i am facing the issue

**Comment by elegantmoose** [comment]
@Sivavamsiraju  - What agent were you trying to deploy and on what operating system? Can you paste the command you used? And the stacktrace?

**Comment by Sivavamsiraju** [comment]
Hi @elegantmoose i am trying to deploy the wondows agent with the code 

$server="";$wc=New-Object">localhost:8888;$url="$server/.../download";$wc=New-Object System.Net.WebClient;$wc.Headers.add("platform","windows");$wc.Headers.add("file","sandcat.go");$data=$wc.DownloadData($url);$name=$wc.ResponseHeaders["Content-Disposition"].Substring($wc.ResponseHeaders["Content-Disposition"].IndexOf("filename=")+9).Replace("`"","");get-process | ? {$_.modules.filename -like "C:\Users\Public\$name.exe"} | stop-process -f;rm -force "C:\Users\Public\$name.exe" -ea ignore;[io.file]::WriteAllBytes("C:\Users\Public\$name.exe",$data) | Out-Null;Start-Process -FilePath C:\Users\Public\$name.exe -ArgumentList "-server $server -group red" -WindowStyle hidden;


But it showinng error

Guide me to ressolve the issue

**Comment by elegantmoose** [comment]
Can you post the error/stacktrace?
