### ISSUE TITLE
Agent capabilities  - Rest API

### ISSUE THREAD

**Issue by BIGdeadLock** [mitre/caldera#2210]
Hello,

I'm running the CNC server on one of my VM machines and the agent is running in a different VM machine (for example
the server is running on 1.1.1.1 and the agent on 1.1.1.2).
When I query the REST API for the agent abilities (i.e /plugin/access/abilities)  I get the following error:

![image](https://user-images.githubusercontent.com/64005996/128026149-a194433b-dbf8-4016-908a-77d49ca87c8b.png)

The picture was taken from postman.
I tried running the command with curl as well like the documentation stated and got the same error:
![image](https://user-images.githubusercontent.com/64005996/128026384-c98d8cd8-a4d6-4c23-a74d-04663c46eb49.png)

other endpoints like the:
https://caldera.readthedocs.io/en/latest/The-REST-API.html#adversaries  works fine.
 

I'm expecting a json object with the abilities of the agent I deployed to return.

 - OS: Ubuntu 18.04 BIONIC

**Comment by elegantmoose** [comment]
@BIGdeadLock - What Caldera version are you running so I can try to recreate bug. Thanks.

**Comment by BIGdeadLock** [comment]
How can I know what version I'm working on?
I'm using the latest code that was on the master branch

**Comment by elegantmoose** [comment]
@BIGdeadLock - ah okay. Ill take a look when I have a moment. 

In the meantime, if you want, you could try downloading the last stable release of Caldera and seeing if that solves the problem for the short term.

To clone the stable release:
```
git clone https://github.com/mitre/caldera.git --recursive --branch 3.1.0
```

**Comment by elegantmoose** [comment]
@BIGdeadLock - got it, fix coming soon.

**Comment by BIGdeadLock** [comment]
@elegantmoose thank you. Will wait
