### ISSUE TITLE
Port Scanning cause general failure

### ISSUE THREAD

**Issue by BIGdeadLock** [mitre/caldera#2216]
**Describe the bug**
I'm trying to run a simple port scanning against a single ip address. I'm using the access plugin to try and use a single ability from the list of the Network Service Scanning technique.
After selecting one of the techniques (For example the Nmap scanning or Scan for Ip address) I get an "Internal Server Error".
After that the whole GUI stops working. For each tab, for example I press the agents tab on the navigator, I get a "Bad Request" Error. 
Refreshing does not help and neither existing the Chrome and reentering.
Only killing the process and running the docker again solves it.

After looking in the logs I'm getting the following error on the server side:

![image](https://user-images.githubusercontent.com/64005996/128717144-20e4e1c7-7591-41df-b633-1b14f917eeac.png)

and on the agent side:

![image](https://user-images.githubusercontent.com/64005996/128717045-7aa164dc-f402-4de0-a257-b42114e8bc15.png)

**To Reproduce**
1.  Run the sandcat agent on a linux machine.
2. Run the technique "Fingerprint network service".
3. Try running any "Network Services Scan" technique and hitting the other navigator's tabs like "agents".

**Expected behavior**
A successful network scan using nmap, scanner.py or any other tool Caldera is using.
The access plugin tab will display the attack and its result

**Desktop:**
 - OS: OS: Ubuntu 18.04 BIONIC
 - Browser chrome
 - Version 3.1.0

**Additional context**
- Nmap is installed on the local machine where the agent is running.
- Data that was sent to the endpoint via postman:
 {"paw":"$agent_paw","ability_id":"3a2ce3d5-e9e2-4344-ae23-470432ff8687","obfuscator":"plain-text", "facts": [{"trait":"remote.host.port", "value": "80"}, {"trait":"remote.host.ip", "value": "$ip_address"}]}

**Comment by alexanderkent** [comment]
Thanks for the detailed bug report -- it's very helpful. Unfortunately, we've not yet been able to reproduce this issue, but we will continue to further explore this. 

>`Only killing the process and running the docker again solves it.`

Are you running inside of a docker container`? If so, are you using the provided docker-compose.yml or how did you configure/run the container?

**Comment by BIGdeadLock** [comment]
@alexanderkent 

Hello, 

Yes I'm running the simulator on a docker container using the provided docker-compse.yml.

I have found out the I had misleaded you - I'm using the code cloned from the master branch and not from the 3.1.0 version.
I cloned the 3.1.0 version instead of the code I'm currently using and it fixed the problem.

**Comment by alexanderkent** [comment]
Perfect. Thanks for letting us know.
