### ISSUE TITLE
No GUI Component to this Plugin - Atomic

### ISSUE THREAD

**Issue by rafnexjm1234** [mitre/caldera#2217]
- OS: Kali
 - Browser Firefox

I tried to install the caldera but the atomic its not working in caldera even tho the atomic folder is already in the plugins folder also check in data.

![image](https://user-images.githubusercontent.com/42322468/128699512-5536fdda-3ecd-4b49-93a4-88399cc3b751.png)

![image](https://user-images.githubusercontent.com/42322468/128699719-6a0e903b-0e90-418c-b83f-9d5a16cd513d.png)

**Comment by wbooth** [comment]
Hey @rafnexjm1234 it likely is still working, the atomic plugin doesnt have any visual part to it. please check your adversaries to ensure that the plugin loaded properly

**Comment by iguannalin** [comment]
> * OS: Kali
> * Browser Firefox
> 
> I tried to install the caldera but the atomic its not working in caldera even tho the atomic folder is already in the plugins folder also check in data.
> 
> ![image](https://user-images.githubusercontent.com/42322468/128699512-5536fdda-3ecd-4b49-93a4-88399cc3b751.png)
> 
> ![image](https://user-images.githubusercontent.com/42322468/128699719-6a0e903b-0e90-418c-b83f-9d5a16cd513d.png)

This has been updated in a PR in May, [to add a GUI for the Atomic plugin](https://github.com/mitre/atomic/blob/bffeceaddc77c4c0f066a14b5bda32717b77d939/templates/atomic.html) to show the abilities. It's now in the latest version of the master branch.
