### ISSUE TITLE
Port Scan

### ISSUE THREAD

**Issue by BIGdeadLock** [mitre/caldera#2237]
Please notice there is a bug in one of your port scanning abilities:

![image](https://user-images.githubusercontent.com/64005996/130565313-5a27d751-3b33-4d5c-8d18-fa2b1a7d9714.png)

![image](https://user-images.githubusercontent.com/64005996/130565283-9ad1be65-76d9-4960-81f2-8ef326e2542b.png)

**To Reproduce**
1. Run the sandcat agent on a linux machine
2. Run the Port scan ability

**Expected behavior**
A successful port scan of all ports.

**Platform:**
 - OS: Ubuntu 18.4
 - Browser Chrome
 - Version 3.1.0

**Comment by uruwhy** [comment]
Thanks for bringing this up - it looks like it's an issue with how the atomic plugin imports abilities with multi-line commands, where extra semicolons are added unnecessarily.

**Comment by uruwhy** [comment]
The atomic PR at https://github.com/mitre/atomic/pull/32 should address this issue
