### ISSUE TITLE
ZSH Exec Error

### ISSUE THREAD

**Issue by hammjd** [mitre/caldera#2238]
Good Day,

I'm new to Caldera and I've installed it on a fresh version of Kali.  I've updated all packages including GoLang.  I continue to receive the error "zsh: exec format error: ./splunkd" when trying to perform the very first step of the training plugin.  I've ensured the file is executable (chmod +x).  It doesn't matter if I run the agent build command as su or user.  Any thoughts?

... I suspect this is an architecture issue.  I'm running a Mac with an M1 chipset and Kali in Parallels (VMWare doesn't support the M1 chipset yet).

BR,

Jeff

**Comment by uruwhy** [comment]
@hammjd When you compiled the agent executable, which operation system did you select? The executable must be compiled for the target operating system
