### ISSUE TITLE
How to incorporate YAML from MITRE's Adversary Emulation Library?

### ISSUE THREAD

**Issue by deetee1** [mitre/caldera#2241]
I would like to emulate FIN6's procedures in my home lab, how do we import the yaml file from
https://github.com/center-for-threat-informed-defense/adversary_emulation_library/blob/master/fin6/Emulation_Plan/yaml/FIN6.yaml into CALDERA?

**Comment by blackwidow0616** [comment]
Check out the CALDERA Emu plugin: https://github.com/mitre/emu
Enable Emu in your CALDERA configuration file, and this plugin should automatically pull in the yaml files from the Center for Threat Informed Defense Adversary Emulation Library.

**Comment by deetee1** [comment]
awesome, thanks a lot @blackwidow0616!
