### ISSUE TITLE
How to get adversary ids?

### ISSUE THREAD

**Issue by radioheado** [mitre/caldera#2253]
Hello,
I’m interested in controlling the agents via a programming method. And I was referring to this [page ](https://caldera.readthedocs.io/en/latest/The-REST-API.html) for official instructions. I tried to do some tests regarding REST API that provided either by the official documentation or some given example commands under Issues, it is still implicit to me of where to obtain the values of some required arguments, e.g., op_id, adversary_id, and so on. Would you mind giving some hints on this?

**Comment by alexanderkent** [comment]
Here's a curl / jq example how one could obtain adversary id's from the adversary endpoint. 
```
curl --silent --location --request POST 'localhost:8888/api/rest' \
--header 'KEY: ADMIN123' \
--header 'Content-Type: application/json' \
--data-raw '{"index":"adversaries"}' | jq -r ".[].adversary_id" | sort 
```
Outputs:
```
01d77744-2515-401a-a497-d9f7241aac3c
0b5636cf-f019-4ec9-aa7c-6e4f55505374
0b73bf34-fc5b-48f7-9194-dce993b915b1
0f4c3c67-845e-49a0-927e-90ed33c044e0
...
..
. // omitted for clarity 
```
Which are all the adversary id's -- one can check e.g. https://github.com/mitre/stockpile/search?q=01d77744-2515-401a-a497-d9f7241aac3c for good measure.

Hope this helps.

**Comment by radioheado** [comment]
> Here's a curl / jq example how one could obtain adversary id's from the adversary endpoint.
> 
> ```
> curl --silent --location --request POST 'localhost:8888/api/rest' \
> --header 'KEY: ADMIN123' \
> --header 'Content-Type: application/json' \
> --data-raw '{"index":"adversaries"}' | jq -r ".[].adversary_id" | sort 
> ```
> 
> Outputs:
> 
> ```
> 01d77744-2515-401a-a497-d9f7241aac3c
> 0b5636cf-f019-4ec9-aa7c-6e4f55505374
> 0b73bf34-fc5b-48f7-9194-dce993b915b1
> 0f4c3c67-845e-49a0-927e-90ed33c044e0
> ...
> ..
> . // omitted for clarity 
> ```
> 
> Which are all the adversary id's -- one can check e.g. https://github.com/mitre/stockpile/search?q=01d77744-2515-401a-a497-d9f7241aac3c for good measure.
> 
> Hope this helps.


Thank you so much for the quick response! My following questions might be stupid, I apologize in advance.
The current documentation of Caldera and the link you sent above are still implicit to us. The outputs only contain adversary ids, is there a way to also output the name? We want to manipulate the agents and operations in a programming way, so we'd really love to see a very detailed guide. 
I saw from other Issues that you are planning to make official documentation of the REST APIs used in Caldera. Can't wait to read it!! Could you please give an estimated date on when the documentation will be online?
