### ISSUE TITLE
How to query operation_ids

### ISSUE THREAD

**Issue by zan2-gmu** [mitre/caldera#2259]
Hello,
I was trying to change the status of an operation I just created through REST API via a programming method. Below is the command I was trying to use:

           curl -X POST -H "KEY:$MY_API_KEY" http://localhost:8888/api/rest -d '{"index":"operation", "op_id":123, "state":"finished"}'

But I found I have trouble in finding out the op_id. I don't know how to get the op_id of the operation I just created. Would you give me some suggestions on this? 

Thank you.

**Comment by uruwhy** [comment]
May I ask what version of CALDERA you are using? And how did you create the operation - did you create it via the GUI or via the REST API? If you made a `PUT` request via the REST API to create the operation, the returned JSON object should contain the operation ID. If you made the operation through the GUI, I don't think there's a built-in way to get the operation ID using the old version of the REST API or through the GUI.

**Comment by zan2-gmu** [comment]
> May I ask what version of CALDERA you are using? And how did you create the operation - did you create it via the GUI or via the REST API? If you made a `PUT` request via the REST API to create the operation, the returned JSON object should contain the operation ID. If you made the operation through the GUI, I don't think there's a built-in way to get the operation ID using the old version of the REST API or through the GUI.

Thank you for the response! I'm using version 3.1.0 of Caldera. I created the operation via REST API through a 'PUT' request. I go back to check the returned JSON message and find the id I want. It solves my question. Thank you.

**Comment by uruwhy** [comment]
Great! Glad to hear - let us know if you have any other questions. I'll close this issue out.
