### ISSUE TITLE
Human Plugin Error

### ISSUE THREAD

**Issue by ColeVan** [mitre/caldera#2284]
I've tried to correct the issue with human plugin. Not successful at the moment. Any suggestions?
Currently running  Caldera 3.1.0

![image](https://user-images.githubusercontent.com/70167373/134995132-a73d7d27-9ecf-432c-8769-cdefaf5211ff.png)
![image](https://user-images.githubusercontent.com/70167373/134995096-3bfeae24-b075-47d0-8f3c-dc269c8f092a.png)

**Comment by elegantmoose** [comment]
This is same as #2273
