### ISSUE TITLE
Documentation 2.0?  Presentation or Video

### ISSUE THREAD

**Issue by Rob3002** [mitre/caldera#229]
This is a significant enhancement and change of interface from the verion 0.3,

Is there documentation, presentation or you tube showing how this works.
Installation was straight forward but issues on steps on operating the new interface.

Thanks,

**Comment by privateducky** [comment]
100% agree. we have documentation in the works, which should be published publicly soon (next couple of weeks). hopefully, we'll get an updated youtube demo video published as well -- but while we're waiting from our end, if anyone wants to push a community video out, we'd definitely appreciate it!

**Comment by privateducky** [comment]
@Rob3002 I've added a first round of documentation through our GitHub Wiki. Would love feedback if you get a chance.

**Comment by privateducky** [comment]
closing as the wiki is pretty fully-fledged at this point.
