### ISSUE TITLE
 python3 caldera.py hangs

### ISSUE THREAD

**Issue by MumpekPumpa** [mitre/caldera#23]
I followed the documentation and am basically at the last step, running  python3 caldera.py, but it always hangs in this step:
INFO:app.updates:Updating logical definition of step: 'XCopy'

We're using an Ubuntu VM.

Any possible reason, logs to check?

**Comment by dm-mitre** [comment]
It's likely that it can't connect to the database. Try connecting to the database manually to make sure it is running correctly. https://docs.mongodb.com/v3.0/tutorial/getting-started-with-the-mongo-shell/

**Comment by MumpekPumpa** [comment]
Thank you for your reply. It seems to be running just fine:

MongoDB shell version: 2.6.10
connecting to: test
Welcome to the MongoDB shell.
For interactive help, type "help".
For more comprehensive documentation, see
        http://docs.mongodb.org/
Questions? Try the support group
        http://groups.google.com/group/mongodb-user
> db
test
>

**Comment by dm-mitre** [comment]
It looks like you're running MongoDB 2.6. I think we've only tested it on MongoDB 3, seems like there may be incompatibilities. If possible I would recommend upgrading to a more recent version of MongoDB.
