### ISSUE TITLE
Unable to pass the User Certification: Create ability

### ISSUE THREAD

**Issue by radioheado** [mitre/caldera#2315]
**Describe the bug**
Unable to pass the User Certification: Create ability.

**To Reproduce**
1. Open the `Navigate` menu.
2. Select `Campaigns > adversaries`.
3. In the drop-down, select the `Certifiable` adversary profile.
4. Press the `+ add` ability button on the right side of the window.
5. In the window that appears, enter the following information: Press the generate new id button.

Issue 1 here: there is no such button in 4.0.0-alpha. So I tried to make a new ability through the `abilities` tab before I move back to step 4. I made the ability according to the guide solution, 
1. Select `darwin `as the platform from the drop-down.
2. Select `sh` as the executor from the drop-down.
3. Select `sandcat.go-darwin` from the payloads box.
4. Enter `whoami `in the command text box.
5. Enter `ifconfig -a` in the cleanup command text box.

Currently, I also have to specify the `Technique Name` and `Technique ID` or it won't allow me to save. I filled in with `T1033` and `System Owner/User Discovery`. The above steps succeeded from step1 to step4. It failed every time when I wanted to add the cleanup command. No matter what I typed in the text box, it won't allow me to save the command.

**Expected behavior**
I expect to complete the flag.

**Screenshots**
![image](https://user-images.githubusercontent.com/42974719/136290416-d0a7a2d8-3020-4b03-8e5a-efee7c819a6d.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04.2 LTS
 - Browser: Firefox
 - Version 4.0.0-alpha

**Comment by TripleA98** [comment]
> @radioheado and @TripleA98 - we are working on patch.

thank you! it seems that it has been patched and fixed 🥇

**Comment by CDJellen** [comment]
The ability UI has been modified to enable cleanup commands in `4.0.0-alpha` as of #2321 .  Please consider updating to latest and creating the User Certificate training ability from the abilities tab.  Thank you for reporting the issue, and feel free to open a new issue if you run in to any further issues, we are always looking to improve as we approach the full release of version 4.
