### ISSUE TITLE
Error when running python server.py 

### ISSUE THREAD

**Issue by mariamalabkari** [mitre/caldera#2325]
I'm trying to install Caldera on Windows and I followed the following command lines:

git clone https://github.com/mitre/caldera.git --recursive --branch 4.0.0-alpha
cd caldera
pip install -r requirements.txt
python server.py --insecure

When I ran python server.py --insecure, I kept getting some errors. I'm able to open  http://localhost:8888, but I'm not able to access with the usernames & passwords provided (When I type the username and password it directed me to the same login page. 
I'm using python 3.10 

**Error**
“list index out of range” 

![image1](https://user-images.githubusercontent.com/55929646/137794227-5db18b17-886e-4e69-9511-d7e6a72228ef.jpeg)

![image0 (1)](https://user-images.githubusercontent.com/55929646/137794248-9bf01873-8606-479d-b822-6525792a77d9.jpeg)

**Comment by heatonk** [comment]
@mariamalabkari I'm taking a look at this issue; do you have any updates?

**Comment by heatonk** [comment]
Closing this issue, I can't replicate this with the provided information. If you can provide more information or updates, please let us know!
