### ISSUE TITLE
The full report and event logs for an operation are identical

### ISSUE THREAD

**Issue by radioheado** [mitre/caldera#2329]
Hi Caldera team,

I was exploring the newest version of Caldera and got some results after testing some defender profiles.
I tested all four defender profiles but only two of them generated results. 
I downloaded both the full report and event logs with agent output and found out they are identical (tested by Python program).
However, according to the documentation [here ](https://caldera.readthedocs.io/en/latest/Operation-Results.html#), the full report and event logs should not have the same content. 
I also tested a red profile when I tried to pass the User Certificate. The full report and event logs are not identical but are very similar with only minor differences. The keys like `operation_metadata` and `agent_metadata` are missing from the event logs.
Is this an update in 4.0.0 alpha? 
BTW, do you have a more detailed explanation on key `host_group` from the full report? Its value has vast information which I can't understand explicitly.

**Comment by heatonk** [comment]
@radioheado Update for you: thanks for submitting this ticket. The issues you brought up are bugs, so I am currently working on a fix for this, and should hopefully be fixed soon. Stay tuned for the update.

For your question about the `host_group`, my suggestion would be either the documentation that you linked or to reach out on the Caldera Slack so many more people can see your questions and provide help; here is the link to that: [Caldera Slack](https://join.slack.com/t/mitre-caldera/shared_invite/zt-m6n66uht-pxw8N5a~tNloYs5_EYuxog).
