### ISSUE TITLE
conf.yml

### ISSUE THREAD

**Issue by amonyphily** [mitre/caldera#233]
I tried to install CALDERA agent after CALDERA server Installation. But I can't find conf.yml at
https://@IP-myserver:8888/conf.yml.

CALDERA server is on centos and CALDERA agent is on Windows 10.
Visual C++ Redistributable for Visual Studio 2015 x64 is intalled. 

How can I fix it ?

**Comment by wbooth** [comment]
are you looking for the configuration file?
if so, the file is located in conf/local.yml

**Comment by amonyphily** [comment]
Hi thank you for your reponse !
I'm not looking for this file. I would like to find the one which can be download from the CALDERA server as explain  here, point 4 for the agent installation.

[https://caldera.readthedocs.io/en/latest/installation.html#caldera-agent-installation](url)

Without, it's not possible to connect both. 
I try to write it because this doc explain what contain the file
[https://caldera.readthedocs.io/en/latest/configuration.html#caldera-agent-configuration](url)

I've found cert.pem in  plugins/adversary/conf/cert.pem but it doesn't work when I start cagent.exe.

Any help ? :)

**Comment by ArtificialErmine** [comment]
Hey @amonyphily, sorry about the whole confusion here. The ReadtheDocs documentation is out of date, and we haven't had a chance to get it updated yet. The endpoint you should be hitting to get the configuration local.yml file for _adversary mode_ is 'http://@IP-myserver:8888/conf.yml'. Some minor changes were made to the way SSL works recently, so trying to reach it via HTTPS no longer appears to work. If it still doesn't seem to work, make sure the _adversary mode_ plugin is being loaded via the 'conf/local.yml' file in the main caldera repository [included in the list of plugins].

Let us know if you're still having issues after this, and we'll troubleshoot further!

**Comment by amonyphily** [comment]
Fine thanks, but it still doesn't work !
I think my issue is the same as the issue 41
[https://github.com/mitre/adversary/issues/41](url)

Thanks !
