### ISSUE TITLE
Agent report dead if server and agent are in diffrent timezone.

### ISSUE THREAD

**Issue by mirek186** [mitre/caldera#2331]
**Describe the bug**
Fresh 4.0.0-alpha deployment and noticed that if my server is in UTC and Target is in Europe/London then agent report dead. Is down to the code where agent just check last seen time and server is an hour behind client. I think is down to agent sending local time and not UTC.
`            getAgentStatus(agent) {
                let lastSeen = new Date(agent.last_seen).getTime();
                let isAlive = Date.now() - lastSeen < (agent.sleep_max * 1000);
`
Workaround: When I've moved the server to the same timezone, agent status is displayed correctly.

**To Reproduce**
1. Deploy caldera 4.0.0-alpha on a server with a clock different from the target. I had server UTC and Client Europe/London which in October is +1 hour.
2. Deploy agent on target and check the status in the GUI agent tab. It should show dead.

**Expected behavior**
An agent should report in UTC so targets machines could be deployed in different zones.

**Desktop (please complete the following information):**
 - OS: Manjaro Linux
 - Browser Firefox
 - Version 92.01

**Additional context**

**Comment by uruwhy** [comment]
@mirek186 The PR at https://github.com/mitre/caldera/pull/2355 should fix this issue. There is an associated gocat PR (https://github.com/mitre/caldera/pull/2355) if you want to make sure the agents are sending UTC time for execution results.
