### ISSUE TITLE
How can I let abilities that are subordinate to an operation run only once

### ISSUE THREAD

**Issue by zan2-gmu** [mitre/caldera#2339]
Hello Caldera team,

Thank you for your work. I'm happy with my update to Caldera 4.0.0.

I'm now interested in building my own defender profiles and use them to detect attacks. But I run into some problems on how I can let the abilities within an operation run only once. I know for a red agent operation, I can do this by setting auto_close = true. While this doesn't work for a blue agent operation. I tested it through Caldera web interface by selecting the auto_close option.

Thank you.

**Comment by zan2-gmu** [comment]
Thank you for your response.

1. I thought "auto_close = true" is used to automatically terminate an operation after every one of its abilities has been executed once. But this is not the case, right? In my current research, I want to use Caldera blue agents as "evidence collector". It helps collect artifacts produced by attackers during an intrusion for future analysis. I'm only looking for existing evidence but not interested in any future attack activities. So I think running the abilities only once if enough in my case.
2. No, I think it did not automatically terminate itself.
3. Upon running operations with "Incident Responder", abilities _Suspicious URLs in mail_ and _find atypical open ports_ are executed many times.

Thank you for your help.

**Comment by uruwhy** [comment]
So for abilities like "Suspicious URLs in mail", they're specifically set to be repeatable, so that they run more than once. From a defender's standpoint, this behavior makes sense since a defender may want to periodically run these checks multiple times. You can see this from the "repeatable" keyword in the ability yaml file within the `response` plugin: `response/data/abilities/detection/1226f8ec-e2e5-4311-88e7-378c0e5cc7ce.yml`

**Comment by uruwhy** [comment]
If you need to make an ability not repeatable, currently the only way to do that is to modify the ability yaml itself - either set `repeatable` to `False` or remove it entirely, and wait for up to a minute for the ability to reload in the server (or just restart the server itself). Hopefully this should address your use case

**Comment by zan2-gmu** [comment]
Thank you so much for your response. I will try this myself to see if it works for me.

**Comment by zan2-gmu** [comment]
I tested "repeatable = False" with ability _Suspicious URLs in mail_ and it works. Thank you.

**Comment by uruwhy** [comment]
Glad to hear! Let us know if you have any other questions
