### ISSUE TITLE
server does not use SSL

### ISSUE THREAD

**Issue by Kerat** [mitre/caldera#234]
Hello,
when I start server.py, I can't reach the server with HTTPS, only in clear HTTP.
Also when I connect myself to the web portail I can't see any menu to change my password has mentioned in the documentation.

What did I do wrong ?

**Comment by wbooth** [comment]
Hey karat, 
per https vs. http. out of the box it will now be http, you can use https via https://github.com/mitre/ssl plugin.

can you point me to the documentation you're looking at?

**Comment by Kerat** [comment]
Hi wbooth thanks for the response,
I'll try with this plugin then.
The documentation I use is this one : https://caldera.readthedocs.io/en/latest/installation.html

**Comment by wbooth** [comment]
those docs refer to adversary mode. Instructions to run this plugin can be seen https://github.com/mitre/adversary from there you can follow the docs to change account details.

for chain mode (the default mode) you can configure the user:password in the conf/local.yml file which loads on startup. In the config file the admin:admin user/pass is added by default.

**Comment by Kerat** [comment]
Ok thanks you, I'll dig in this direction then !
