### ISSUE TITLE
Unable to deploy an agent

### ISSUE THREAD

**Issue by anirtaka** [mitre/caldera#2347]
I am unable to deploy an agent.

I installed the latest release on Kali and the code is not generating anything

![image](https://user-images.githubusercontent.com/93640880/140021792-9f71c31a-b797-47a3-b9ba-15267a40314e.png)

**Comment by clenk** [comment]
Are there any errors from the server? If not, running the server with `--log debug` may yield some helpful messages. Is Go installed on the server?

**Comment by cyber-arsenull** [comment]
@anirtaka Is this the same issue as [#2348](https://github.com/mitre/caldera/issues/2348)? Try running with `--log debug` and see if you are getting the same errors.

**Comment by cyber-arsenull** [comment]
Closing this, as it is currently assumed it is the same as #2348 
@anirtaka feel free to open a new issue w/ debug log if it is not the same as the above mentioned.
