### ISSUE TITLE
Alpine name collision prevents adding ability to an adversary

### ISSUE THREAD

**Issue by cyber-arsenull** [mitre/caldera#2350]
**Describe the bug**
As mentioned in part of  #2348 you currently cannot add an ability to an adversary. 
This is due to the naming collision of `showAbilityModal` in `profiles.html` and `abilities.html`. Seems the abilities one always wins this fight, and you end up with the incorrect modal. 

**To Reproduce**

1. Click abilities
2. Click + Create an Ability
3. Fill out the needed information before + Add Cleanup Command
4. Click + Add Cleanup Command and the window will be closed immediately, as well as all the tabs already opened

**Expected behavior**
An ability selection screen (modal) should appear from `profiles.html`.

**Additional context**
Proof of issue's cause hypothesis: If you change the name of either the issue is resolved.

**Comment by radioheado** [comment]
Thank you so much for the quick update!

**Comment by cyber-arsenull** [comment]
No problem! Thanks for the good bug reports.
Seems like even prior to the naming collision, the `profiles.html` `showAbilityModal` was overwritten with the one from `abilities.html` 
@argaudreau 
I made a PR that reverts the `profiles.html` change, and changes the name in `profiles.html` to `showAbilityChoiceModal`:
https://github.com/mitre/caldera/pull/2351/commits/ff49573066fa5fab99017a4bfdbfb337d71e1132

I'm not sure if there were changes in the `profiles.html` commit that are separate from this issue and should stay in:
https://github.com/mitre/caldera/commit/13a246b3b54c51de52d785afe25edc1060fe5f1e

**Comment by clr2of8** [comment]
Just installed master today 11/8/21 and getting this same error

![image](https://user-images.githubusercontent.com/22311332/140819899-21fa6484-9447-49a6-bcc6-80874b7221e8.png)

**Comment by clr2of8** [comment]
any work arounds?

**Comment by cyber-arsenull** [comment]
@clr2of8 hey, try this branch: `bugfix/add_adversary_ability` for the related PR to this issue https://github.com/mitre/caldera/pull/2351
Feel free to comment if this does not work, or any other issues arise related to the PR solution.

**Comment by clr2of8** [comment]
Thanks @cyber-arsenull, I gave that a try and while it did fix the problem at hand, a new problem presented itself wherein I can't save the Adversary after adding any ability. I get "! Error saving profile" whenever I click the green "Save Profile" button. 

![image](https://user-images.githubusercontent.com/22311332/140858277-59eb250f-732c-4ef6-85d9-ed91dafb3d23.png)

**Comment by clr2of8** [comment]
OK, nevermind, it seemed to be a problem with only my custom built "Certifiable Adversary", I deleted and recreated and now it is saving.

**Comment by clr2of8** [comment]
Don't know if this is a problem with your branch specifically, but the "create ability" module doesn't get marked complete after adding the "My test ability" ability to the "Certifiable" adversary.  I started the training over completely and then found that the "Contact points" module won't complete either, tried to deploy sandcat as http protocol on remote windows vm but it says malformed request comes into the server.
