### ISSUE TITLE
solution guide for bootstrap abilities in Caldera 4.0 alpha

### ISSUE THREAD

**Issue by ChiefK6** [mitre/caldera#2352]
In solution guide, says to enter in ability ID but you need to select the name instead

**Comment by cyber-arsenull** [comment]
Hey @ChiefK6 thanks for the issue report.
Could you specific which challenge this is? 4 or 5 maybe? 
4 is 'Add new blue ability'
5 is 'Bootstrap abilities'

Thanks!

**Comment by ChiefK6** [comment]
Sorry about that. It was for 5 ‘Bootstrap Abilities’

**Comment by cyber-arsenull** [comment]
Ah I see

![image](https://user-images.githubusercontent.com/4370241/141009184-bd6860aa-e8c5-4744-b3e5-e4b39dccbf88.png)

**Comment by cyber-arsenull** [comment]
Added PR for this in the Training plugin. 
https://github.com/mitre/training/pull/141
Thank you @ChiefK6 for the issue report!

**Comment by wbooth** [comment]
PR merged !
