### ISSUE TITLE
Persistance object migration from v2.8

### ISSUE THREAD

**Issue by siisar** [mitre/caldera#2358]
Hi
Currently we are using Caldera v2.8 in our production env. 
We are working on an upgrade to v3.1, but the main drawback we have found is that the object where data is persisted is not compatible between both versions. Just copied our current object in a new fresh v3.1 instalation, and we got errors reading that object.

Is there any way to migrate the 2.8 object so it can be loaded in the latest versions? How can we proceed in this regard?

Best regards

**Comment by ArtificialErmine** [comment]
Hey @siisar - Unfortunately, there were few structural changes in various objects between 2.8.0 and 3.1.0, so there won't be a clean, easy way to migrate to the newer of the two. 

That being said, after some fiddling on my end, I was able to get the 3.1.0 instance to load a 2.8.0 object after making sure the salt and encryption keys in the config files matched, though that required filtering out some of the objects normally included in the `object_store`. Can you elaborate on specifically what you want to migrate between the two instances?

**Comment by siisar** [comment]
Hi @ArtificialErmine , thanks for your quick response,
The critical part we want to migrate are the TTPs, is there a way to handle them??

Regards

**Comment by ArtificialErmine** [comment]
Hey @siisar - Unfortunately, the data object format for both adversaries and abilities changed between those versions, so it'd take a bit of tweaking to just "transfer" the data store over. However, that may not be necessary, if the primary thing you want to migrate over are the adversaries and abilities. 

All abilities and adversaries either come from yaml files, or when created by the gui should be written to yaml files (typically located in `data/abilities` or `data/adversaries`. If you can locate these files (in `data/`, either in core or in the various plugins), and then place them in the appropriate locations for the new instance, the new 3.1.0 instance should ingest every ability and adversary your 2.8.0 instance had access to. 

Let me know if that doesn't make sense, or if it doesn't seem to be working. If so, we can look into other ways we might be able to potentially get the abilities and adversaries transferred over.

**Comment by siisar** [comment]
Thanks again @ArtificialErmine , I´ll try next week and I tell you, sounds good!

Regards

**Comment by siisar** [comment]
Hi again @ArtificialErmine 
We have successfully been able to migrate the abilities following your recommendations, copying the abilities yaml files and also the plugins.
The problem has been with adversaries, we could migrate them partially, because we found some references lost, as we can see in the logs when starting caldera:
2021-11-29 17:03:09 - WARNING (data_svc.py:393 _verify_adversary_profiles) Ability referenced in 114d6e3a-3165-4cb3-b2c6-6d12518086be but not found: 443b853ac50a79fc4a85354cb2c90fa2
2021-11-29 17:03:09 - WARNING (data_svc.py:393 _verify_adversary_profiles) Ability referenced in 114d6e3a-3165-4cb3-b2c6-6d12518086be but not found: 2bfafbee8e3edb25974a5d1aa3d9f431
2021-11-29 17:03:09 - WARNING (data_svc.py:393 _verify_adversary_profiles) Ability referenced in 207f2d41-aba3-4589-abb0-32ac889ef2f3 but not found: efa08918a92ed978dc45824c651e7f62

and so on
I happens with half of them... we cannot see any reference to the objects within the adversaries:
atomic_ordering:
- 985e6bbf0f1648f0ce9f02ae7c6ca40b
- 1cac00896661be81f2dd242c94bb84be

Some of those references are lost (but only some of them...), which are shown in the errors above...

Best regards

**Comment by siisar** [comment]
Hi again, we have found those references, seem to be in plugins/atomic/data/abilities/
We are going to copy them also, let´s see how it goes...

Regards

**Comment by ArtificialErmine** [comment]
@siisar - Did including the atomic abilities help with getting everything imported correctly?

**Comment by siisar** [comment]
Yes @ArtificialErmine , we did and most of the lost references were gone... only a few of them are left, and we cannot find where they are referencing to... (maybe to the object_store?), at least in the file system.
We guess they are new abilities created from scratch, anyway there are very few (about 10) and we can create them again in the new env. Still have to check how many lost references we have in the production env, hopefully very similar to the test env...

Thank you very much for your support @ArtificialErmine
