### ISSUE TITLE
Removing steps from adversary and hitting save doesn't save the changes

### ISSUE THREAD

**Issue by mgraf444** [mitre/caldera#2362]
**Describe the bug**
I removed steps from one of the adversaries (e.g. ransack) and hit save, but when I browse back to the adversary the steps re-appear.

**To Reproduce**
Delete steps from adversary and hit save.

**Expected behavior**
After hitting save, when browsing back on the adversary it should preserve my changes.

**Comment by wbooth** [comment]
@mgraf444 what version are you using?

**Comment by mgraf444** [comment]
4.0.0-alpha

**Comment by mgraf444** [comment]
Unless you aren't allowed to modify the default adversaries?

**Comment by alexanderkent** [comment]
> Unless you aren't allowed to modify the default adversaries?

One can modify the default adversaries, edit or delete abilities as needed.  

Can you check whether or not there are any errors in the `browser console` when you are attempting to persist your changes?
Press Command+Option+J (Mac) or Control+Shift+J (Windows, Linux, Chrome OS) to jump straight into the Console panel of Chrome DevTools. Or, navigate to More Tools > Developer Tools from Chrome menu, and click Console tab.

**Comment by mgraf444** [comment]
I don't see any, I wound up resorting to manually modifying the files
themselves.

**Comment by argaudreau** [comment]
Hi @mgraf444, are you experiencing this issue with a fresh pull from `master`?
