### ISSUE TITLE
Server running problem

### ISSUE THREAD

**Issue by abusabiha** [mitre/caldera#2364]
![Screenshot_2021-11-21_12_15_43](https://user-images.githubusercontent.com/86252592/142772509-2ef463a5-0371-429d-aeef-176b511bc41d.png)
See this image. 
After running this command  "python3 server.py --insecure" I saw this.

**Comment by clenk** [comment]
Hi @abusabiha, is your `~/caldera/plugins/manx` folder empty? When you cloned the Caldera repo did you use the `--recursive` flag? The plugins (such as manx, which is causing your error) are git submodules so the `--recursive` flag is required to pull down their contents.

**Comment by argaudreau** [comment]
Hi @abusabiha, are you still experiencing issues launching the server?
