### ISSUE TITLE
what's the  structure of caldera

### ISSUE THREAD

**Issue by Rookie-all** [mitre/caldera#2372]
I want to change the code structure and I think it would be quicker if I know the structure of the project. What's the code structure of caldera project.

**Comment by cyber-arsenull** [comment]
Hey @Rookie-all. 
Please let me know if you have specific questions on any of this below:

CALDERA has two primary pieces, the server and the agent. The server acts as the orchestrator and command and control, while the agent is what is deployed on remote machines and will perform abilities requested by the server.

## Server

### Services

The server is made up of several *service* modules found in `caldera/service/`. Here is a diagram outlining most of the service structure and organization.

![server_overview](https://user-images.githubusercontent.com/4370241/143947364-4b0b5f7c-71fd-4dfe-84a4-c9948a165fad.png)

### Objects

The *Data Service* manages a group of objects which act as the in-memory data storage. These are serializable via the `marshmallow` library for use by the RESTful API. 
See below the diagram for how these data objects interact with each other in HAS-A relationships.

![object_model](https://user-images.githubusercontent.com/4370241/143947458-e9bb1592-2a8c-4b69-8df8-1025c7d95d95.png)

These are loaded during initialization from YML files mostly found in `caldera/data` or a plugin's data directory `caldera/plugins/<plugin_name>/data`. 
Here is the breakdown for the `load_ability_file` function.

![ability_load](https://user-images.githubusercontent.com/4370241/143947419-7ae826b6-c5af-4d9f-8795-7fb8d9d7f57c.png)

### Initialization

The server's startup can be found in `caldera/server.py` with most of the initialization code being in the `run_tasks(services)` function. 

Please see this attached diagram for more information on each step of the init process. 

![server_init](https://user-images.githubusercontent.com/4370241/143947401-69a91ad8-5ab1-42be-b08f-339207fe3775.png)

## Agent

These are deployed onto remote targets. The most commonly supported agent is `sandcat` from the plugin of the same name. 
Here is a breakdown of the beacon / C2 communication at a high level.

![agent_c2_comm](https://user-images.githubusercontent.com/4370241/143947474-2ec6400d-595e-43fc-a5a6-ad53dc0f832c.png)

**Comment by cyber-arsenull** [comment]
Closing this for now, please let me know if you have any additional questions!

**Comment by Rookie-all** [comment]
Thanks for your answer！It is very helpfu!

**Comment by MANGLARAM** [comment]
I want to know how operation flows one by one and how it contact the agent with instruction and how it get response back in results please help me with this flow of caldera
