### ISSUE TITLE
Getting the report after testing an ability outside the scope of an operation

### ISSUE THREAD

**Issue by Gone12345** [mitre/caldera#2379]
Hello, i'm currently trying to run tests via REST/API, and i'm trying to execute an ability outside the scope of an operation. Everytime I try to execute it I get the output "complete", but no report or anything like that. I wanted to know if it is possible to get a report of the ability ran, like the command and the output. 
Thanks!

**Comment by BCHarrell** [comment]
Hi Gone12345.

If you're using the example provided [here](https://caldera.readthedocs.io/en/latest/The-REST-API.html?highlight=REST#post) pointed at the Access plugin endpoint, the answer is no - you cannot get the output via the API as the returned JSON precedes the ability being run.

This may not fully address your question, in which case I encourage you to submit a feature request, but if you're using API V2 as part of our current Alpha 4.0 release you can create an operation via the API with a default adversary. Simply do not supply `adversary.adversary_id` and a default adversary will be created for you, allowing you to add abilities to the operation (POST to `.../potential-links`) and then GET the link results while the operation is running and/or a full report after closing the operation. Set the operation to 'autonomous' to enable this.

For more info, you can read the Swagger Docs (http://localhost:8888/api/docs#/operations) in the alpha build.

Does that answer your question?

**Comment by Anth0rx** [comment]
I think that is a feature worth implementing. What would be needed to directly receive the results after the ability ran without creating an operation?

**Comment by clenk** [comment]
@Anth0rx can you help us understand the use case? Could you run an operation with just a single ability to get the same effect? The way it works currently is the server asynchronously directs the agent to run the ability. At some point after that the agent runs the ability and gets a result. If the ability was part of an operation, it will tell the server to tie the result to that link in that operation. With no operation, it has no way to find which run of the ability to tie the result to.

**Comment by Anth0rx** [comment]
A use case would be to to run an ability directly and synchronously beyond the scope of an operation: I want an agent to run an [active scan](https://github.com/mitre/access/blob/master/data/abilities/technical-information-gathering/567eaaba-94cc-4a27-83f8-768e5638f4e1.yml) and directly receive the results of the scan.

**Comment by clenk** [comment]
You might try the [manx plugin](https://github.com/mitre/manx), which provides a reverse-shell.

What are the downsides to running it as a single-ability operation you wish to avoid?
