### ISSUE TITLE
Agent options not loading

### ISSUE THREAD

**Issue by cyber-cyborg999** [mitre/caldera#2388]
**Describe the bug**
When i open agents tab from the new 4.0 alpha2 branch i am not see any options in the deploy agent tab.

**To Reproduce**
1. goto agents from sidebar
2. Click on deploy an agent.

**Expected behavior**
I believe there should be some options shown here like sandcat, manx etc

**Screenshots**
![Screenshot 2021-12-08 124148](https://user-images.githubusercontent.com/13641169/145165024-d2aee11e-0a81-4e57-a54f-c0db5927a8ed.png)

**Desktop (please complete the following information):**
 - OS: Docker
 - Browser: Chrome
 - Version: Version 96.0.4664.45 (Official Build) (64-bit)

**Comment by cyber-arsenull** [comment]
Very odd! I think something is odd with the Docker. Could you try to do without Docker? 

Here is what I see without docker: 
![image](https://user-images.githubusercontent.com/4370241/145330032-d609f297-0d15-4b8d-8df9-740c21206c91.png)

**Comment by yee-jonathan** [comment]
I deployed release `4.0.0-alpha.2` into a docker container, used Chrome version 96.0.4664.110 (Official Build) (x86_64) and cannot recreate this bug.

 Need more information from the original poster. Otherwise I propose moving to close this ticket.
