### ISSUE TITLE
Powershell issue return with Phishing

### ISSUE THREAD

**Issue by TripleA98** [mitre/caldera#2393]
I am trying to do spearphishing attack thorug caldera. 

This is the command: 
`if (-not(Test-Path HKLM:SOFTWARE\Classes\Excel.Application)){;   return 'Please install Microsoft Excel before running this test.'; }; else{;   $url = 'https://github.com/redcanaryco/atomic-red-team/raw/master/atomics/T1566.001/bin/PhishingAttachment.xlsm';   $fileName = 'PhishingAttachment.xlsm';   New-Item -Type File -Force -Path $fileName | out-null;   $wc = New-Object System.Net.WebClient;   $wc.Encoding = [System.Text.Encoding]::UTF8;   [Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12;   Invoke-WebRequest -Uri $url -OutFile $fileName; }`

this should be run on powershell.

I get this error:

```
else : The term 'else' is not recognized as the name of a cmdlet, function,
script file, or operable program. Check the spelling of the name, or if a path
was included, verify that the path is correct and try again.
At line:1 char:136
+ ... his test.'; }; else{; $url =
'https://github.com/redcanaryco/atomic-red-team/ra ...
+ ~~~~
+ CategoryInfo : ObjectNotFound: (else:String) [], CommandNotFoun
dException
+ FullyQualifiedErrorId : CommandNotFoundException
```

The agent is deployed on Windows 8 machine and caldera server is on kali linux.
Does anyone know what the problem might be? 
Is there a way or an ability that could allow running such script on powershell? 

Thank you!

**Comment by clenk** [comment]
Hi @TripleA98, sorry for the delayed response. From [this stackoverflow answer](https://stackoverflow.com/a/57479179/) it sounds like you can use `else` in a script file but not in a command. To do this in Caldera, you could put your command in a script file like [wifi.ps1](https://github.com/mitre/stockpile/blob/master/payloads/wifi.ps1) and then use it as the payload in your ability. For example, like how the wifi.ps1 script is used in the [Preferred Wifi ability](https://github.com/mitre/stockpile/blob/de13f249041c5a67ff772e522ba1acddc962ec8b/data/abilities/discovery/a0676fe1-cd52-482e-8dde-349b73f9aa69.yml#L32).

**Comment by cmagone** [comment]
Thank you for the example!
