### ISSUE TITLE
View adversaries with API. ERROR: "302: Found"

### ISSUE THREAD

**Issue by OscarJoverWalsh** [mitre/caldera#2395]
Hi, I am trying to view the skills for a specific adversary in CALDERA through the API, however, any query I do returns the following result "302: Found". Is there something I am executing wrong?

Ex: curl -H "KEY:1234" 'http://localhost:8888/api/rest' -H Content-Type: application/Json' -d "index":"adversaries","adversary_id":"f61e3fc0-43d8-b5d3-710610b92974"}'

If it helps, I'm running CALDERA locally, using ubuntu 20.04 in virtualBox, with python 3.8.10.

Thank you very much in advance.

**Comment by WhyNotPal** [comment]
Hey Oscar
As it happens, I get a similar problem with facts. 
Did you manage to solve your issue? 
Thanks

**Comment by OscarJoverWalsh** [comment]
Yes, I managed to fix the problem. Try this command and see if you have any more luck. It should work. You need to change the key to the one you have configured in the default.yml file named 'api_key_red'.

Hope it helps!

curl -H "KEY:1234" 'http://localhost:8888/api/rest' -H 'Content-Type: application/Json' -d "index":"adversaries","adversary_id":"0b73bf34-fc5b-48f7-9194-dce993b915b1"}'

**Comment by WhyNotPal** [comment]
Hey Oscar, 
Thanks for your message! Getting the abilities with the command you mentioned indeed works. However, running an ability outside of an operation does not seem to work for me.

**Comment by OscarJoverWalsh** [comment]
Hi, I'm sorry I can't tell you what you could do. I haven't run abilities on their own. 
You might want to open a new issue for this, I'm sure someone will be able to help you.
