### ISSUE TITLE
By default, blue team agent is assigned to red group

### ISSUE THREAD

**Issue by GSVSenseAmidMadness** [mitre/caldera#2396]
**Describe the bug**
When creating a windows agent with blue team cerdentials, the subsequent PS script will display following string: 
--$server -group red"--
Agent is not connected to blue team unless manually "red" is changed to "blue"

**To Reproduce**
1.  Deploy agent, select Windows
2. Observe the psh created
3. Execute psh, fail to see agent in blue. Shows up in red. 
4.  Change value to blue. Agent shows up in blue. 

**Desktop (please complete the following infor
![c18](https://user-images.githubusercontent.com/95069682/146002588-5b5601a4-6720-46f9-a0e5-36b50c331637.png)
mation):**
 - OS: Kali
 - Browser Firefox ESR /Edge
 - Caldera 4.0.0

**Comment by cmagone** [comment]
We added a new blue option for windows agents similar to the blue option for linux agents. If you pull the latest sandcat repo, you should be able to select the blue option.
