### ISSUE TITLE
Updated Functionalities on Creating Abilities 

### ISSUE THREAD

**Issue by radioheado** [mitre/caldera#2407]
Hi Caldera team,
I was so busy recently, and just came back to the Caldera project. I updated it and saw that there are two newly added boxes on `Ability Details`. Please see the following screenshot:
![image](https://user-images.githubusercontent.com/42974719/146462883-e1ee3356-5bd1-4a03-9740-87811068d8de.png)

I'm wondering what these two functionalities actually do. And I couldn't find explanation on the documentation.
Thank you!

**Comment by ArtificialErmine** [comment]
Hey @radioheado - thanks for pointing out these aren't documented yet, I'll try to make sure we do that in the near future.

For the moment, singleton abilities are abilities that should only be run until they have succeeded once. On the flip side, repeatable abilities are abilities that can be run repeatedly (and, depending on the planner, maybe run repeatedly until the server or operation is manually stopped).

Hopefully that clears things up a bit, but if not, let me know where I should elaborate further.

**Comment by radioheado** [comment]
> 

Thanks for the quick response! 
I want to make an operation where the abilities within it run only once. Should I set the abilities to not run repeatedly or just make the operation stop automatically?

**Comment by uruwhy** [comment]
Set them to not run repeatedly. 

Having the operation stop automatically only handles stopping the operation once all pending abilities have run - this doesn't affect whether or not abilities repeat.

**Comment by ArtificialErmine** [comment]
@radioheado I would suggest making the abilities singleton, then. The default behavior for an ability occurs when both singleton and repeatable are False, so setting singleton to True and repeatable to False should result in an operation where the abilities only run once (successfully).

**Comment by radioheado** [comment]
> @radioheado I would suggest making the abilities singleton, then. The default behavior for an ability occurs when both singleton and repeatable are False, so setting singleton to True and repeatable to False should result in an operation where the abilities only run once (successfully).

Thank you so much for the explanation! I'll try it later and make updates if necessary.
