### ISSUE TITLE
GET http://<ip>/campaign/profiles?null net::ERR_CONNECTION_RESET 200 (OK) with Chrome (caldera 3.1)

### ISSUE THREAD

**Issue by siisar** [mitre/caldera#2413]
Hi,

We are testing a new installation of the v3.1, and we have come across this error:

GET http://<ip>/campaign/profiles?null net::ERR_CONNECTION_RESET 200 (OK)

This error happens when clicking in the "advesaries" link, or in the "access" link within plugins. The rest of the links are right.
The effect in the browser is that after clicking, nothing happens. This errors appears in the browser console.
It´s very wierd, because it only happens when the connection is through our corporate VPN; when we are at office and don´t use VPN everything is fine. And with VPN only happens in the links mentioned above.
If I try to open that link in another tab, the content is loaded properly but without styles, as expected, so it seems that the resources are available.

In our former version 2.8 everything was working fine...

Do you have any clue about what is happening to us? I guess it is not easy for you to reproduce...

Chrome vesion 95.0.4638.69 (Build oficial) (64 bits)

Best regards

**Comment by siisar** [comment]
Hi again
We have been able to set up a workaround. Basically using the provided haproxy as reverse proxy, everything works fine...

Regards

**Comment by alexanderkent** [comment]
Thanks for the update; it would appear the VPN/NAT/firewall is blocking the connection, but glad it is working with haproxy.
