### ISSUE TITLE
I can't run

### ISSUE THREAD

**Issue by abusabiha** [mitre/caldera#2417]
Pls see this.
![Screenshot_2021-12-25_01_14_05](https://user-images.githubusercontent.com/86252592/147378813-f2416571-1188-4ddf-9799-b142bd8c3c89.png)

**Comment by yee-jonathan** [comment]
What branch did you install? Try recloning with either `--branch 3.1.0` or `--branch 4.0.0-alpha.2`.

**Comment by heatonk** [comment]
@abusabiha Hello!

The issue seems to be that the Manx plugin is not also downloaded. Can you try redownloading Caldera from Github with the --recursive flag? 

For more info, see [https://caldera.readthedocs.io/en/stable/Installing-CALDERA.html#installation](Here) for the docs on installation.

**Comment by heatonk** [comment]
@abusabiha 

I'm going to go ahead and close this issue since I haven't heard back from you, but if you are still having issues with this, feel free to reopen this issue.

Kyle
