### ISSUE TITLE
No options using drop down menu in blue operation

### ISSUE THREAD

**Issue by ChiefK6** [mitre/caldera#2421]
When using the blue login to complete the "Blue Operation" lab, there is no option to select the "Batch" choice in planner when creating an operation...
![2021-12-29 19_48_49-Window](https://user-images.githubusercontent.com/93936078/147717674-913c0353-83ab-4990-a29b-ff80b2f37472.png)

**Comment by argaudreau** [comment]
Hi @ChiefK6, thanks for bringing this to our attention. I was able to replicate the issue, so I'll update this issue as soon as I get a PR up. Planning on having that done sometime this week.

**Comment by argaudreau** [comment]
Scratch that -- the fix was easier than I thought. Turned out to be an issue in the stockpile plugin, I'll report back once it's merged.

https://github.com/mitre/stockpile/pull/542

**Comment by ChiefK6** [comment]
Adam!
youre the best! thank you for doing this! appreciate it


Chief

**Comment by argaudreau** [comment]
PR was merged -- if you do a fresh pull from master in `plugins/stockpile`, you should see planners show up as a blue user. We'll pin that submodule in a future release so it's pulled automatically

**Comment by argaudreau** [comment]
If the issue persists feel free to reopen this, but I'll close it out for now.

**Comment by argaudreau** [comment]
@clr2of8 Could you tell me what browser you're using? I have a fresh pull of master in the stockpile repo and I'm able to see all three default planners as a blue user.

**Comment by clr2of8** [comment]
I'm using Chrome on Windows 10.

**Comment by clr2of8** [comment]
If you want to chat with me via Slack, I'm in the Caldera workspace as @OrOneEqualsOne. I can also give you access to this VM in the cloud because it is a disposable student VM that I use for teaching classes on attack emulation.
