### ISSUE TITLE
Manual operation loop

### ISSUE THREAD

**Issue by metamorphisys** [mitre/caldera#2448]
Doing a manual operation in version 4.0.0 gets stuck in a single decision loop.
I've tried completing a manual operation using different adversary profiles and each attempt results in a loop of the first decision.
Example:
A manual operation using the discovery profile keeps repeating decision 1 - identify Active User

![Screenshot 2022-01-21 195401](https://user-images.githubusercontent.com/26992638/150617966-a30768d5-657a-4540-b5c1-b84bfeecd9cf.jpg)

**Comment by cyber-arsenull** [comment]
Thanks for the report @metamorphisys 
I think I have seen this as well, I will try to recreate and get back to you.

**Comment by cyber-arsenull** [comment]
I was able to recreate the issue. Seems like something that will need to be dug into a little further.

@argaudreau Have you seen anything like this in testing to help hint at what may be the culprit? 

### Recreate approach 1
![Pasted image 20220203182433](https://user-images.githubusercontent.com/4370241/152462536-cd5903d7-653c-4d0c-8610-ea39ced8bf90.png)
- Start directly in _Require Manual Approval_ mode
- Use an adversary

![Pasted image 20220203182535](https://user-images.githubusercontent.com/4370241/152462588-a0f91efb-1d00-44ea-b270-a8473d8532a1.png)
- Ability will get repeated, hitting "approve" doesn't seem to work correctly

### Recreate approach 2

![Pasted image 20220203182632](https://user-images.githubusercontent.com/4370241/152462663-556e3572-89cc-4cf1-911d-5a5046f21e41.png)
- Start in _Run autonomously_ mode with an adversary loaded

![Pasted image 20220203182824](https://user-images.githubusercontent.com/4370241/152462697-8f28a767-e2de-4e14-b0a8-72cfbca45263.png)
- Toggle to "Manual" approval at some point, and you will get a similar weirdness.

**Comment by cyber-arsenull** [comment]
Got word from the team that this is a part of an ongoing look at manual approvals.

**Comment by metamorphisys** [comment]
Excellent.

**Comment by cyber-arsenull** [comment]
Closing this as the team is working on it, will update when resolved. Thank you again!
