### ISSUE TITLE
Training: Update Agent - Flag 4 not clearing.

### ISSUE THREAD

**Issue by sjfigueroa** [mitre/caldera#2468]
Hello team Caldera,
I am trying to complete the training program and I have changed the group and sleep timer values to 60/80, 50/100, 100/200 and the training platform does not recognize the change. Is this an error on my behalf? Thanks for the support!

**Comment by wbooth** [comment]
@sjfigueroa Thanks for pointing this out -- what version of CALDERA are you using?

**Comment by sjfigueroa** [comment]
> @sjfigueroa Thanks for pointing this out -- what version of CALDERA are you using?

I am using 3.1.0

**Comment by mgonzcast** [comment]
I am experiencing a similar issue using caldera under kali 2024.2

The error that I am getting is that the system can´t kill the agent.

I am using a NAT network in Virtualbox under Windows and both machines (kali and windows 2016 Server) can ping each other and the agent shows as deployed
