### ISSUE TITLE
Mock plugin bug

### ISSUE THREAD

**Issue by juansanjose** [mitre/caldera#2476]
Hello,
When I try to run an operation using the mock puglin and the simulation group, I get the following error:
Traceback (most recent call last):
  File "/home/vagrant/caldera/app/objects/c_ability.py", line 87, in __getattr__
    return super().__getattribute__('additional_info')[item]
KeyError: 'parsers'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/vagrant/caldera/plugins/mock/app/simulation_svc.py", line 31, in run
    response, status = await self._generate_simulated_response(instruction.id)
  File "/home/vagrant/caldera/plugins/mock/app/simulation_svc.py", line 73, in _generate_simulated_response
    await ResultGenerator(ability.parsers).generate(words)
  File "/home/vagrant/caldera/app/objects/c_ability.py", line 89, in __getattr__
    raise AttributeError(item)
AttributeError: parsers

The agents seem to be running fine:
![image](https://user-images.githubusercontent.com/78904547/152984785-87811960-5777-4cb6-a193-d8487d59030b.png)

I run caldera with:
 - OS:  Linux vagrant 5.4.0-91-generic #102-Ubuntu SMP Fri Nov 5 16:31:28 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
 - go version go1.17.6 linux/amd64
 - Python 3.8.10
 - Browser chrome
 - Version 4.0.0-beta

**Comment by sjfigueroa** [comment]
Make sure to add "mock" to the plugins listed in default.yml

**Comment by heatonk** [comment]
@juansanjose I'm gonna be the person keeping an eye on this ticket, have you had a chance to doublecheck the default.yml that "mock" is listed. You can find default.yml in the base_directory/conf/default.yml.

Besides that, do you get any other errors on caldera startup or when you execute the operation?

**Comment by juansanjose** [comment]
When I ran caldera without the mock plugin I get this error on caldera startup
![image](https://user-images.githubusercontent.com/78904547/155213049-3ed29843-bdc9-4bbd-8801-cfb2c36eca47.png)

**Comment by heatonk** [comment]
Just so I'm understanding, when you run with the mock plugin installed and enabled, you get the error from your initial post, and when you run without mock enabled, you get that error?

**Comment by juansanjose** [comment]
yes

**Comment by heatonk** [comment]
@juansanjose Which version of caldera are you currently running? Are you using a specific release or the latest master commit? 

I'm trying to replicate your errors now.

**Comment by juansanjose** [comment]
I'm using 4.0.0 beta

**Comment by P0w3rChi3f** [comment]
I am getting the same error when I am attempting to complete the "Mock Plugin" training.  I was able to reproduce the error when I start the operations.  
<img width="959" alt="Screen Shot 2022-03-11 at 6 00 38 PM" src="https://user-images.githubusercontent.com/21298973/157986030-eff261f4-0a9e-4d95-843e-9e1cb76e88db.png">
<img width="1157" alt="Screen Shot 2022-03-11 at 6 00 53 PM" src="https://user-images.githubusercontent.com/21298973/157986041-1a3b49cb-6303-4c6e-8c1e-8c8b9e2b63f6.png">
<img width="1165" alt="Screen Shot 2022-03-11 at 6 01 11 PM" src="https://user-images.githubusercontent.com/21298973/157986053-0fee6f3f-4f8f-4d5e-a5fe-667c81c2a760.png">

**Comment by heatonk** [comment]
@juansanjose Please try pulling the latest mock plugin, this should fix the error you described above. If it doesn't, please feel free to reopen the issue.
