### ISSUE TITLE
v4.0.0-beta, Agent Configuration "Implant Name" doesn't take effect for new agents

### ISSUE THREAD

**Issue by clr2of8** [mitre/caldera#2485]
![image](https://user-images.githubusercontent.com/22311332/153930489-36aedf02-f4f2-4820-a44c-e4559b9b0cb1.png)
 
Then I choose "Deploy an agent", Manx for Windows ....

![image](https://user-images.githubusercontent.com/22311332/153930621-853124ce-9074-480e-b656-e538380d6f2b.png)

But the file download to c:\Users\Public still have the original/default filename instead of "super_scary"

**Comment by blackwidow0616** [comment]
I don't believe that the Windows agent deploy commands nor the Manx agent deploy commands take the custom Implant Name. However, I am looking into what we can do to change that.

**Comment by blackwidow0616** [comment]
Those two PRs should resolve the issue, but if you have any issues, feel free to reopen this ticket or start a new one!
