### ISSUE TITLE
Sandcat agent , changing privilege from User to Elevated

### ISSUE THREAD

**Issue by n40r1s** [mitre/caldera#2494]
HI , I just started using Caldera , my goal will be to create a pluggin. I started with the basics by doing the Blue Training.
However I struggle with the 2nd task , I can't create a Linux agent with Elevated privileges , it's automatically created with User privileges.
How can I change from User to Elevated ?

**Comment by alexanderkent** [comment]
Hi,  under Linux and Mac OS X you can use the `sudo` command to execute using the root context (elevated privilege).
For example, you can run `sudo -s` to create an elevated shell (enter your root password when prompted).

Once in the shell you can verify your current user's User ID groupings using the `id` command which will return something like `uid=0(root) gid=0(root) groups=0(root)`.

Note that an UID of 0 zero means root (elevated). 

Additionally `whoami` should return `root` as well. Next, once you have a root shell try deploying the CALDERA agent again.

**Comment by n40r1s** [comment]
@alexanderken  thank you , that was really helpful it solved my problem !
In my case I was using a Parrot machine , the root account was was not activated..
sudo didn't work , but switching the user directly to root did.
