### ISSUE TITLE
Plugin - Builder

### ISSUE THREAD

**Issue by b4b857f6ee** [mitre/caldera#2495]
Hello,

How many storage we need when activating the builder plugin?
I have a 100Go VM and it's full and it's still didn't download the full dockcross/windows-test etc ...

Any idea how much storage we need? I can't find the information.

Thank you :)

**Comment by b4b857f6ee** [comment]
I try 2OOGo... full too :/

**Comment by elegantmoose** [comment]
@b4b857f6ee - picking this up now.

**Comment by elegantmoose** [comment]
Is there an error output from the caldera server at all?

Also, looks like they have the dockcross image sizes enumerated here: https://github.com/dockcross/dockcross#cross-compilers
