### ISSUE TITLE
Need a button to test new ability

### ISSUE THREAD

**Issue by dickens88** [mitre/caldera#2503]
**What problem are you trying to solve? Please describe.**

When I created a new ability i need to test it first, but currently, it seems the only way i can test is clicking `save` button and add it to an `adversaries` and configure a `operations`. there are so many steps, especially you need to modify your ability again and again. 

**The ideal solution: What should the feature should do?**

I want to add a test button just at the bottom of `Create an Ability` dialog. it should just beside the `save` and `close` button. so that it will make testing earilier.

**What category of feature is this?**

- [ ] UI/UX

**Comment by wbooth** [comment]
This is great insight and I really like your idea.
