### ISSUE TITLE
Export/Share Adversary Profiles

### ISSUE THREAD

**Issue by wksim91** [mitre/caldera#2507]
**What problem are you trying to solve? Please describe.**

We are using Caldera 3.1 and we've created a few adversary profiles that (partially) emulates threat actors. 

Currently, we share the adversary profiles within the team by manually searching for:
1. Adversary in "/data/adversaries/".
2. Abilities in "/data/abilities/" and some in the "/plugins/atomic/data/abilities/" and "/plugins/stockpile/data/abilities/".
3. Payloads in similar folders as abilities above.

As this is a manual process, it can be error-prone. 

**The ideal solution: What should the feature should do?**
We've been looking for a better way to share adversary profiles between the team but this is the best we've come up with. Please advice if there is an existing feature that does this. Otherwise, we are request for feature that simplifies this process of importing & exporting of adversary profiles. This will be very helpful for sharing of adversary profiles across different teams.

**What category of feature is this?**

- [ ] UI/UX

**Comment by argaudreau** [comment]
Hi @wksim91, thank you for your feedback! This is a great idea for a feature and I've added it to our tracker. I can't promise any timelines just yet but we'll get started on an import/export adversary feature in the future.

The v4-beta adversary interface has been updated quite a bit. While there's no import/export feature there yet, you may find it easier to search for the abilities you need while creating an adversary.
