### ISSUE TITLE
Multiple Users Training at the same time

### ISSUE THREAD

**Issue by ddroege6** [mitre/caldera#2509]
**What problem are you trying to solve? Please describe.**
> Eg. I'm looking for a way to create accounts so that users can log in to Caldera and run their own operations. To ensure each user understands how to use Caldera I was going to have them complete the User and Blue certificates but I noticed if I completed some of the flags, they would show as completed for all other users as well. Just want that separation so users can do their own thing within each profile without the overlap.

**The ideal solution: What should the feature should do?**
> Users would be able to log into their respective RED/BLUE accounts, complete training plugins separately and show their completion codes when done. 

![Slack convo](https://user-images.githubusercontent.com/100710987/156211376-0b6787bd-148e-49b6-ac9b-63ea98c2c97b.PNG)

**What category of feature is this?**

- [ ] UI/UX
- [ ] API
- [x ] Other

**If you have code or pseudo-code please provide:**

none

```

- [x ] Willing to submit a pull request to implement this feature?

**Additional context**
Add any other context or screenshots about the feature request here.

Thank you for your contribution!

**Comment by uruwhy** [comment]
Multi-user training is an upcoming feature that's on our roadmap - I can't guarantee when this will roll out, but we'll definitely make sure it gets prioritized!

**Comment by ddroege6** [comment]
Thank you!
