### ISSUE TITLE
remove configuration file after the item deleted from web page

### ISSUE THREAD

**Issue by dickens88** [mitre/caldera#2511]
**What problem are you trying to solve? Please describe.**
Hi, I'm using 4.0.0-beta. I found that after I delete configurations from web page, such as abilities, operation etc, the items can not be found at web page but the related yaml file ware still under the directories. From my view, this will keep a lot of rubbish, bcos you always need to add new usecases, testing new one and delete the useless parts.

**The ideal solution: What should the feature should do?**
I suggest to remove all the related yaml file and directories after the configurations ware deleted from web page.

**What category of feature is this?**

- [x] UI/UX

**Comment by BCHarrell** [comment]
Thanks for the suggestion, I'm looking into this

**Comment by BCHarrell** [comment]
Added to the backlog. Part of this request is already implemented - abilities and adversaries do get removed based on testing. Operational files seem to remain.
