### ISSUE TITLE
Operation runs each ability multiple times after Fact Source updates

### ISSUE THREAD

**Issue by macmiranda** [mitre/caldera#2543]
**Describe the bug**
Updating a Fact Source and re-running an existing Operation or creating a new Operation configured to use it, causes the planner (independently of which one) to send multiple copies of each ability impacted by the facts that have been modified, e.g. if a fact is updated 4 times in a Fact Source, the ability that uses that fact in a given Operation will be sent 4 times to the target (each time with a different Fact value) . See the screenshot below
![image](https://user-images.githubusercontent.com/17923899/162031554-a71cf878-fc17-499c-885d-145d465ba2b2.png)
Duplicating the Fact Source and using the copy instead, yields the expected behavior, i.e. the ability is run only once per target.

**To Reproduce**
1. Run an Operation using any Fact Source
2. Modify one Fact in the Fact Source and Save it
3. Optionally, modify other Facts or the same one multiple times
4. Re-run the Operation or create a new Operation with the same Fact Source
5. Note that abilities that use the Facts that were modified are sent to the target multiple times

**Expected behavior**
The planner sends the ability only once to each target, no matter how many times the Facts in each Fact Source have been updated or modified.

**Screenshots**
See above

**Software Versions
Caldera 4.0.0
Python 3.6.8

**Additional context**
N/A

**Comment by macmiranda** [comment]
Just changing the value and saving it

**Comment by uruwhy** [comment]
Yes, it looks like updating a fact value through the GUI doesn't remove the old value in the backend. Thanks for bringing this up!

**Comment by argaudreau** [comment]
Hey @macmiranda, I apologize for the delay in getting back to you. We've got a new layout to the fact sources page in the works (https://github.com/mitre/caldera/pull/2546) that will include a fix to the duplicating fact values. We're looking to get that wrapped up in the next week or so, so stay tuned.

**Comment by argaudreau** [comment]
https://github.com/mitre/caldera/pull/2546 has been merged in. We were able to update a fact value via the GUI and have it overwrite the existing value instead of adding a new one. Feel free to re-open if you're not seeing the same behavior. Thanks again for bringing this to our attention!
