### ISSUE TITLE
Sandcat download request does not contain the correct implant name in the 'FILENAME' response headers of the request

### ISSUE THREAD

**Issue by cventour** [mitre/caldera#2551]
**Describe the bug**
When a script (like powershell) calls the /download/file endpoint on port 8888 to download a sandcat implant , the http response headers return a Content-Disposition header that should contain the configured Implant name as data. Instead , that header contains the "sandcat.go-windows" data which is the default. 

**To Reproduce**
1.  Agents -> Configuration -> Enter a custom "implant name" , let's say "ABC123"
2. Agents -> Deploy Agent -> Sandcat -> Windows
3. Choose the powershell script. 
4. Run the script step-by-step
5. Read the $wc.ResponseHeaders['Content-Disposition'] value
6. It will read  attachment; filename="sandcat.go-windows" 

**Expected behavior**
The content disposition header should  be : attachment; filename="ABC123.exe"

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 
 - Browser : Not Applicable.

**Additional context**
This is needed In scenarios where custom scripting is used to grab the Implant Name from the header responses and save the filename accordingly.  That was working as expected in Caldera v3

**Comment by uruwhy** [comment]
https://github.com/mitre/sandcat/pull/410 should have addressed this. Try using a more updated version of the sandcat plugin
