### ISSUE TITLE
Windows Sandcat starts and dies with  "Failed to decode HTTP response: illegal base64 data at input byte 3"

### ISSUE THREAD

**Issue by cventour** [mitre/caldera#2552]
**Describe the bug**
The windows sandcat client on Windows 10 keeps creating and killing beacons with message  Failed to decode HTTP response: illegal base64 data at input byte 3.

Sandcat started in verbose mode -v

Beacon API=/beacon
[*] Set communication channel to HTTP
[*] Updated agent's destination address to proxy peer address: http://192.168.1.28:8888
[*] Valid peer proxy receivers used so far:
        HTTP : http://192.168.1.28:8888
[*] Valid peer proxy receivers left to try out:
[-] Failed to decode HTTP response: illegal base64 data at input byte 3
[-] beacon: DEAD

On each beacon attempt server returns

2022-04-25 09:27:36 - ERROR (contact_http.py:38 _beacon) Malformed beacon: 'NoneType' object is not iterable

**To Reproduce**
1. Create script for sandcat beacon
2. Execute on windows 10 device (tested on Windows 10 20H2)

**Desktop (please complete the following information):**
 - OS: Windows 10 20H2 , Caldera running on Docker container.

**Comment by cventour** [comment]
Caldera Client was started using -server http://192.168.1.28:8888 -group red -v

**Comment by uruwhy** [comment]
What version of CALDERA are you using? And are you using an older sandcat agent binary, or a freshly compiled one?

**Comment by cventour** [comment]
That was on Cadera 4 latest. The sandcat agent was created using the powershell script so I take it it was created on the fly.

**Comment by SarguelUnda** [comment]
If at any point you added the plugin emu to caldera in the config file there use to be an issue until really recently where emu was overriding sandcat payload with a sandcat from caldera v2 which was then producing the kind of error you are describing. I think the problem was solved in emu but caldera was referencing an older version of emu until recently ( 7bd85b1100737d79b331417fbea7d201be8e8f71 ).

**Comment by cventour** [comment]
No, I just launched caldera from a docker container I created on the same host and tried to create an agent using powershell

**Comment by elegantmoose** [comment]
@cventour What go version is found on the Caldera server host? (post output to `go version`)

**Comment by arty-hlr** [comment]
@uruwhy I'd like to reopen this issue as I get the exact same error on a fresh docker build on ubuntu, trying to get a linux sandcat agent to beacon.

Caldera logs:
```
2025-11-10 22:51:57 DEBUG    First time HTTP beacon from       contact_svc.py:85
                             ubucgo
                    ERROR    Malformed beacon: list index out contact_http.py:38
                             of range
2025-11-10 22:52:12 DEBUG    First time HTTP beacon from       contact_svc.py:85
                             ptkjfr
                    ERROR    Malformed beacon: list index out contact_http.py:38
                             of range
```

Sandcat logs:
```
./test -server http://localhost:8888 -group red -v
Starting sandcat in verbose mode.
[*] No tunnel protocol specified. Skipping tunnel setup.
[*] Attempting to set channel HTTP
Beacon API=/beacon
[*] Set communication channel to HTTP
initial delay=0
server=http://localhost:8888
upstream dest addr=http://localhost:8888
group=red
privilege=Elevated
allow local p2p receivers=false
beacon channel=HTTP
available data encoders=base64, plain-text
[-] Failed to decode HTTP response: illegal base64 data at input byte 3
[-] beacon: DEAD
[-] Failed to decode HTTP response: illegal base64 data at input byte 3
[-] beacon: DEAD
^C
```

Caldera version is 5.3.0, for sandcat the version pinned that is cloned recursively seems to be https://github.com/mitre/sandcat/tree/0a35cd525f1cfabfcf602282428055c41f144513

**Comment by arty-hlr** [comment]
Also tried with the same go version (I had 1.25.0 in the container and 1.22.0 on the host trying to beacon before, I upgraded to 1.25.0 on my host), just in case it would make a difference, although I don't really understand why it would.
