### ISSUE TITLE
Python 3.10 on Ubuntu:Latest within Docker file

### ISSUE THREAD

**Issue by Thisnturalias** [mitre/caldera#2560]
Dockerfile uses Ubuntu:latest which installs python3.10 causing websocket loop errors.
ubuntu:focal pulls 3.8
"As of 3.10, the *loop* parameter was removed from Lock()" - This is with SSL and Mock plugins enabled
Seeing as requirements.txt recently was modified to specify  3.7 I don't know if the preferred method would be to add a repo and pull 3.7 or compile 3.7 within the container.

Thanks!

**Comment by elegantmoose** [comment]
I believe #2583 will address the websockets error.
