### ISSUE TITLE
ERROR: Could not build wheels for multidict, which is required to install pyproject.toml-based projects

### ISSUE THREAD

**Issue by fadymarkram** [mitre/caldera#2564]
i have tried to install caldra on kali with this aspics 5.16.0-kali7-amd64 with python 3.10 i got this error 
ERROR: Could not build wheels for multidict, which is required to install pyproject.toml-based projects

**Comment by cmagone** [comment]
Are you seeing any errors in the stack related to `gcc` ? If so, please install gcc on your server.
