### ISSUE TITLE
ERROR: manx  agent reported error time format 

### ISSUE THREAD

**Issue by aeifkz** [mitre/caldera#2568]
**Describe the bug**
caldera commit 374fad7c54746fd7113cd63e458cd3f3a1360808 use manx bug version [manx@4b6d216](https://github.com/mitre/manx/tree/4b6d2163f7e3808b4b6c955620d2e81dca317e04)

**To Reproduce**
1. Deploy an agent with Manx | A reverse-shell agent which communicates via the TCP contact
2. Run operations with any Manual Command. (ex: pwd)
3. Link Output show 'No output.' and Server log show time data format error information.

**Expected behavior**
Link Output should show results instead of 'No output.'

**Screenshots**
![12q3](https://user-images.githubusercontent.com/2063610/167284170-a8fa1158-677d-4d92-acdc-64205ed9eef8.JPG)
![test](https://user-images.githubusercontent.com/2063610/167284168-616eeaff-d5dc-4b01-888a-df222a292432.JPG)

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04.2 LTS
 - Browser Chrome 101.0.4951.54
 - Version Caldera v4.0.0

**Additional context**
Plugin manx  fix this bug in commit [manx@d8dfac727](https://github.com/mitre/manx/tree/d8dfac727c57b17e345dbcd8432d54a81adf13e9),  caldera needs refer the correct version.

**Comment by clenk** [comment]
@Purpl3Lynx Could you open a new issue please? OP's issue will be fixed when the plugins are pinned to their latest versions, which should be soon.

When you post the new issue, could you provide some additional details:
 - Can you run stockpile (non-custom) abilities in Manx?
 - When you updated the project did you also update the submodules/plugins?

Thanks!
