### ISSUE TITLE
Bucket name inconsistent when creating custom planner

### ISSUE THREAD

**Issue by LouisHacklaender** [mitre/caldera#2571]
**Describe the bug**
When creating a custom planner the bucket names defined in the planner's state machine (e.g. `lateral_movement`) that have to comply with the respective bucket method names in the planner do not match the bucket names defined in the stockpile plugin.

**To Reproduce**
1. Create new Planner including state machine and respective bucket methods (including underscores, e.g. `lateral_movement`)
2. In the bucket method, use `links = await self.planning_svc.get_links(self.operation, agent=agent, buckets=[bucket])`
3. Print/log the returned `links`
4. Run an operation with an adversary and agent that should support abilities from the given bucket

**Expected behavior**
The `get_links()` method returns ability links for all bucket names including those with underscores.

**Screenshots**
No screenshots but example output.

Using `buckets=[bucket]`:
```
-> Enter bucket: command_and_control
2022-05-10 07:54:12 - DEBUG (planning_svc.py:179 get_links) Generated 0 usable links
--> Got link: []
<- Exit bucket: command_and_control
```

Using `buckets=[bucket_name.replace("_", "-")]`:
```
-> Enter bucket: command_and_control
2022-05-10 07:55:37 - DEBUG (planning_svc.py:179 get_links) Generated 2 usable links
--> Got link: [<app.objects.secondclass.c_link.Link object at 0x7fb2593bdad0>, <app.objects.secondclass.c_link.Link object at 0x7fb2593ded50>]
---> Link ability name: Install PowerShell Core 6
---> Link ability name: Install PSTools
<- Exit bucket: command_and_control
```

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Browser: not relevant
 - Version 4.0.0-beta

**Additional context**
I was implementing a custom planner that wants to pick some of the generated links at random and noticed that for some buckets (i.e. those containing an underscore) the planning service did not return any ability links. After looking further into this, I noticed the problem. Replacing `buckets=[bucket]` with `buckets=[bucket_name.replace("_", "-")]` fixed the problem and I do not think this is the intended way.

Renaming the bucket names in the planner's state machine does not fix the problem because the bucket methods names no longer match the bucket names. Renaming the bucket methods (using `-` instead of `_` is not possible).

**Comment by pierregi** [comment]
It is not a bug, it is due to a limitation on python that does not allow function to be named with ` - `. So there is 2 names, the first one with ` _ `, listed on `self.state_machine = ["lateral_movement"]`, is the function name on which you will choose the ability bucket name (`await self.do_bucket('lateral-movement')` which is, by default, the tactic name (defined on the Attack matrix with ` - `).

**Comment by LouisHacklaender** [comment]
Thank you for your answer!

I am aware of the fact that python functions cannot contain `-`. 

Although one might not consider this a bug, I still think the behavior is not as expected, since when calling a function with the bucket name as you would expect it to be (i.e. `lateral_movement`) it does not work as expected.

Also I would like to mention here, that the way it is described in the [documentation](https://caldera.readthedocs.io/en/latest/How-to-Build-Planners.html) (`await self.planning_svc.get_links(self.operation, buckets=['privilege escalation'])` it returns no abilities as well.
