### ISSUE TITLE
How to determine/generate ID for custom planners and adversaries?

### ISSUE THREAD

**Issue by LouisHacklaender** [mitre/caldera#2584]
Hello everyone,

while implementing some custom planners and adversaries I was wondering how one should set the IDs for custom elements. Is it determined using the elements name or is it completely random? If so, how do you make sure two planners do not have the same ID? 
I checked the docs but did not find anything about ID generation.

I know you can basically determine and pick the IDs yourself, but I was wondering if there is some logic behind it.

Thank you for your time! :)

**Comment by CDJellen** [comment]
Hello @LouisHacklaender 

CALDERA uses a `uuid-v4` to register unique objects such as planners and adversaries.  For planners, as well as for adversaries added directly as `.yml` files, it suffices to generate a new `uuid` outside of CALDERA and include it in the `id` field of the `.yml` file.

New adversaries created through the UI will automatically have a `uuid` assigned to them, which will not conflict with any `uuid` elsewhere (abilities, adversaries, planners, etc.)

The purpose of the `id` is only to act as a unique key, but for consistency we recommend using the `uuid-v4` format.  These `id`s in themselves do not convey additional information nor do they have additional, undocumented requirements.

We're happy to hear that you're expanding CALDERA with new planners and adversaries, please feel free to open new issues as needed.  Thank you!

**Comment by LouisHacklaender** [comment]
Hello @CDJellen,

thank you for your detailed answer!
