### ISSUE TITLE
4.0.0-beta Operations not working on Ubuntu 22.04

### ISSUE THREAD

**Issue by notclement** [mitre/caldera#2596]
Hi,

I am trying to use the Operations function that Caldera offers but I can't seem to get the feature to work as intended

Here I have a an agent that I want to run some Operations on
<img width="687" alt="msedge_PPfMeKYbeg" src="https://user-images.githubusercontent.com/19283318/171538690-68eed272-141c-4a5c-a608-b2561269b6c4.png">

This is the settings that I use to create a new Operation
<img width="252" alt="msedge_OnZkCqGppG" src="https://user-images.githubusercontent.com/19283318/171538826-0f21cfc6-e096-4b95-a223-ec4b1e1cebf9.png">

This is what is displayed when I click on 'Start' in the Operations creation window
<img width="685" alt="msedge_3wm8Uzp3Nx" src="https://user-images.githubusercontent.com/19283318/171538903-04d224e6-90ce-4e80-830a-7ee176b0d028.png">

I am running on ```Linux caldera-server 5.15.0-33-generic #34-Ubuntu SMP Wed May 18 13:34:26 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux``` or ```Ubuntu 22.04 LTS```

I have tested this function on 3.1.0 and it works.

I followed the same installation process shown in the README of this repository.

Please let me know if I have made a mistake somewhere.

EDIT 15/06/22:
Tried a clean install again today and still encountering this issue

**Comment by Esklona** [comment]
Hi, im having same exact problem running caldera on the last Kali version
