### ISSUE TITLE
How to use JSON file with Caldera ??

### ISSUE THREAD

**Issue by iPlayC** [mitre/caldera#2598]
Hi everybody,

I have been using Caldera software for a short time, I want to use the full power of this software! 
I can launch operations and create adversaries, but I don't know how to put malware and see how it reacts on my test PC.

Thank you for your answer.

Sincerely

IPlayC

**Comment by CDJellen** [comment]
Hello @iPlayC ,

CALDERA supports this testing primarily through custom payloads, copied to the target machine and executed using a deployed agent.

If you have a malicious executable you'd like to execute on your test PC, you can add this executable to the `/plugins/stockpile/payloads/` directory.  Once you launch the CALDERA server, you can add this new payload to a custom ability and add an executor command to this ability, such as `start my_malicious_executable.exe`.  This should allow you to:
1. Autonomously transfer the malicious executable to your test PC using a CALDERA agent, and
2. Autonomously execute this executable.  By default, the stdout and stderr will be captured and sent back to the C2 server / CALDERA UI.

Please let me know if you need any help in creating a custom ability with your payload!
