### ISSUE TITLE
Manx agent not executing custom abilities

### ISSUE THREAD

**Issue by Purpl3Lynx** [mitre/caldera#2601]
**Describe the bug**
Manx agent not executing custom abilities. It fails right after I start the operation. Then it enters in some kind of buggy mode because I cannot kill it from the Caldera UI and it doesn't respond to any action.

**To Reproduce**

1. Deploy an agent with Manx | A reverse-shell agent which communicates via the TCP contact
2. Run operations with custom abilities
3. Abilities fail

**Expected behavior**
The same abilities work with Sandcat agent. Maybe is a problem with payloads?
I am getting the error pasted below from the server. 

![image](https://user-images.githubusercontent.com/28339167/172815947-5e902758-e900-4da6-a5cc-d30022bf797e.png)

**Desktop (please complete the following information):**

- OS: Ubuntu 20.04.4 LTS
- Browser Chrome Version 100.0.4896.127 (Official Build) (64-bit)
- Version Caldera v4.0.0

**Additional context**
Not-custom abilities DO work with Manx. 
To make sure I have everything up to date I cloned the whole Caldera repository yesterday again.

**Comment by apalmeirim** [comment]
Is there a solution to this problem? I am encountering the same, running 4.2.0
