### ISSUE TITLE
unexpected keyword argument 'loop

### ISSUE THREAD

**Issue by AC-WhiteGlint** [mitre/caldera#2611]
While deploying Caldera version 4 as a docker container, I get this error message

2022-06-22 13:44:29 - ERROR (base_events.py:1744 default_exception_handler) Task exception was never retrieved
future: <Task finished name='Task-20' coro=<start_server() done, defined at /usr/lib/python3.10/asyncio/streams.py:53> exception=TypeError("BaseEventLoop.create_server() got an unexpected keyword argument 'loop'")>
TypeError: BaseEventLoop.create_server() got an unexpected keyword argument 'loop'

**Comment by MichaelPak** [comment]
I have the same issue

**Comment by clenk** [comment]
Are you using Caldera 4.0.0 proper or one of the alpha/beta releases? I think https://github.com/mitre/caldera/pull/2583 was supposed to fix this issue.

**Comment by chenporian** [comment]
I have the same issue. I cloned the project yesterday...

**Comment by nilivingston** [comment]
I'm also seeing the same error using 4.0.0. Cloned the repo on 25 July 2022.

**Comment by elegantmoose** [comment]
@chenporian @nilivingston Noted. Looking into.
