### ISSUE TITLE
manx plugin receiving connection refused, server netstat not showing listening on port 7010

### ISSUE THREAD

**Issue by jennifergates** [mitre/caldera#2620]
**Describe the bug**
After a fresh install of version 4.0 and attempting to use the manx plugin, the agent receives a connection refused. Running netstat on the server does not show port 7010 is open.  pcap of the connection shows the server sending a RST.

**To Reproduce**
1. Install the manx agent on a client or even the server itself as per the Training plugin flag.

**Expected behavior**
The agent should be able to connect to the server and appear in the list of agents.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: kali
 - Browser chrome
 - Version 4.0

**Additional context**

**Comment by jasonmull** [comment]
I can confirm having this issue as well.

**Comment by chenporian** [comment]
I can confirm having this issue as well.

**Comment by Cy-Beard** [comment]
I am experiencing the same issue.....port 7010 is not open after running the server.py and therefore getting **connection refused** errors.

**Comment by Cy-Beard** [comment]
@wbooth will you handle this ticket or will it be assigned to someone else?

**Comment by wbooth** [comment]
@Cy-Beard thanks, @elegantmoose will take from here

**Comment by Cy-Beard** [comment]
@elegantmoose 
According to this article I found: https://wiki.kopacko.us/doku.php?id=resources:security:red:caldera
seems like after the installation you should enable the firewall?
That wasn't in the docs, I thought that had to be disabled but I can go ahead and enable and open the port if need be.
Suggestions?

**Comment by elegantmoose** [comment]
@Cy-Beard looking into.

**Comment by elegantmoose** [comment]
@jennifergates @Cy-Beard  Confirmed bug on 4.0.0.

I tested on master and the bug was not found. Can you try pulling master and see if that mitigates the bug?

**Comment by jennifergates** [comment]
I just tried it and it does work.  The changes made 3 days ago to the contact_tcp must have fixed it. Thank you!

**Comment by chenporian** [comment]
> I just tried it and it does work. The changes made 3 days ago to the contact_tcp must have fixed it. Thank you!

same :)
