### ISSUE TITLE
Caldera Test Scope

### ISSUE THREAD

**Issue by Rhymtester** [mitre/caldera#2624]
Can we assess network devices such as Routers, Switches & Access points using Caldera?

**Comment by elegantmoose** [comment]
Currently, there are not public abilities and agents that would identify and fingerprint network middle boxes in the manner (I think) you are referring to. 

We do have abilities for network scanning (nmap) and packet capture.  You may be able to extend these abilities and/or process returned information to a greater extent to glean network middle boxes.
