### ISSUE TITLE
Can't Install agent.

### ISSUE THREAD

**Issue by legendZE** [mitre/caldera#2648]
**Describe the bug**
When executing the installation script on the device, the server console log with "Get "https://proxy.golang.org/github.com/google/shlex/@v/v0.0.0-20191202100458-e7afc7fbc510.zip": dial tcp 142.251.43.17:443: i/o timeout" issue., the client console show "The Operation has timed out"

**To Reproduce**
1. 

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/87748068/186641379-3a2664b6-7faa-4791-b282-ef635b58bfd4.png)

**Desktop (please complete the following information):**
 - OS: [e.g. Mac, Windows, Kali]
 - Version [e.g. 2.8.0]

**Additional context**

**Comment by yee-jonathan** [comment]
This does not appear to be a CALDERA issue, rather a networking/firewall issue on your end. I believe a network configuration in your environment is preventing golang from making the proper tcp requests.
