### ISSUE TITLE
Pathfinder Plugin not rendering correctly within Caldera

### ISSUE THREAD

**Issue by scoobyduo** [mitre/caldera#2650]
Hi, should mention I am new here.

Pathfinder Plugin not rendering correctly within Caldera

1. Select Pathfinder from Plugin
2. Select nmap from drop-down
3. An alter pops us stating 'Error Setting up the Scanner'

Screenshots
![Caldera_Pathfinder_Error_Setting_Up_Scanner](https://user-images.githubusercontent.com/4652620/186885023-fcf2666e-ef7d-4c2a-b2ae-ed3f8bd898df.png)

Windows 10 with Chrome

Additional context
```
pathfinder.js:222 ReferenceError: validateFormState is not defined
 at pathfinder.js:207:9
(anonymous) @ pathfinder.js:222
```

```
function setupScannerSection(){
.....
.....
        validateFormState(response.enabled, '#startScan')
```

Would appear the validateFormState function is not defined when invoked by Pathfinder plugin

I also raised https://github.com/center-for-threat-informed-defense/caldera_pathfinder/issues/56 as not sure where the issue is

**Comment by elegantmoose** [comment]
@scoobyduo I believe this is due to the pathfinder plugin not being updated along side core UI changes.

@argaudreau is that correct?

**Comment by argaudreau** [comment]
@elegantmoose Correct, we have not updated the Pathfinder plugin to UI v4 which can cause some instability. Let's discuss if it's within scope for us to update it, or just have it updated for v5.

**Comment by argaudreau** [comment]
The pathfinder plugin is being updated to work with the new UI version, stay tuned in the next week or so for a fix for this.

**Comment by argaudreau** [comment]
Thanks for being patient -- Pathfinder's UI has been updated to work with v4. Please try a fresh pull of master in Pathfinder and let me know if you run into any issues.

**Comment by L015H4CK** [comment]
Not OP. Thanks for the quick update!

After updating, I encountered another (small) error using the "nmap" scanner with script "nmap-vulners".

When running a scan with the Pathfinder plugin for the first time, the "pingless" field in the config is empty. This results in the following error: 
`Scan ID: b853c028-db15-4c77-878d-b1b21d2105b4 failed. Error output: exception encountered when scanning, ValueError("invalid literal for int() with base 10: ''")`.

After checking the box "No Ping (-Pn)" the scan is successful (pingless: true).
Un-checking the box results in another successful execution (pingless: false).

Same behavior for Firefox and Chrome.

**Comment by argaudreau** [comment]
Did you leave the port fields blank by chance? You'll get a similar error if all the fields aren't filled out, but we should make those errors a bit more clear.

**Comment by L015H4CK** [comment]
I tested with empty port field and with filled-in port values.
The error stays the same whether I enter a port value or not.

**Comment by elegantmoose** [comment]
@L015H4CK Still having trouble?

**Comment by L015H4CK** [comment]
I opened a new issue for the above problem - https://github.com/center-for-threat-informed-defense/caldera_pathfinder/issues/60.

It was fixed in https://github.com/center-for-threat-informed-defense/caldera_pathfinder/commit/ed4ed7db8e12342763c811492999d0048dffa08f.

So far, everything seems to work great. Thanks for reaching out!
