### ISSUE TITLE
show the UUID in adversary profile

### ISSUE THREAD

**Issue by zrquan** [mitre/caldera#2654]
**What problem are you trying to solve? Please describe.**
There doesn't seem to be a normal way to see the UUID of the adversary, I can only find it in the html code.

**The ideal solution: What should the feature should do?**
Maybe show it in adversary profile.

**What category of feature is this?**

- [x] UI/UX
- [ ] API
- [ ] Other

**Comment by argaudreau** [comment]
Thanks for the recommendation! I've made a quick PR that adds the ID to the adversary page: https://github.com/mitre/caldera/pull/2672

**Comment by argaudreau** [comment]
Closing as PR addresses issue.
