### ISSUE TITLE
ERROR (c_plugin.py:70 enable) Error enabling plugin=ssl, [Errno 2] No such file or directory: 'haproxy'

### ISSUE THREAD

**Issue by Aledangelo** [mitre/caldera#2655]
When I start Cladera I get this error, I don't know how to resolve it (maybe it's a stupid question), but i need help. :'(

**Comment by clenk** [comment]
Hi @Aledangelo, do you have HAProxy installed?
> `brew install haproxy` (MacOS) or `sudo apt-get install haproxy` (Linux)
(see https://github.com/mitre/ssl#requirements)

**Comment by Aledangelo** [comment]
I thought I had it installed during caldera setup, but it didn't install correctly. Now I have installed it correctly and this error no longer appears. The only problem that still is not solved for me is that some techniques that involve using TLS (HTTPS) are missing.

**Comment by clenk** [comment]
Great, glad it's working. Which techniques are missing? Do we just not provide abilities for those techniques, or are there abilities for those techniques in the [stockpile](https://github.com/mitre/stockpile/tree/master/data/abilities) plugin but they aren't appearing in your UI?

**Comment by Aledangelo** [comment]
I can see the techniques of the "stockpile" plugin.
I was trying to reproduce the "poison ivy" malware and I realized that caldera is missing some sub-techniques, such as: Encrypted Channel: Symmetric Cryptography (T1573.001), Boot or Logon Autostart Execution: Active Setup (T1547.014), ....
I am a student, I do not consider myself an expert in these things. I don't know if they are missing or I did something wrong in the configuration

**Comment by clenk** [comment]
Caldera does not have abilities for every technique out there. The [atomic plugin](https://github.com/mitre/atomic) has an Encrypted Channel ability and several Boot or Logon Autostart Execution abilities (though not the specific one you mentioned). If you can't find what you're looking for in either atomic or stockpile, you will need to [create the abilities yourself](https://caldera.readthedocs.io/en/latest/Basic-Usage.html#abilities).

**Comment by Aledangelo** [comment]
OK! I got it. Thanks so much for the support
