### ISSUE TITLE
caldera communication api structure

### ISSUE THREAD

**Issue by MANGLARAM** [mitre/caldera#2665]
I want to  understand the api flows so i want to know how operation flows one by one and how it contact the agent with instruction and how it get response back in results please help me with this flow of caldera.

**Comment by L015H4CK** [comment]
Hi, I am not sure if I understood your question correctly. 

Also I am only using CALDERA focusing on different areas (planners) but I might help you to find the right direction. If you want to find out how the communication between the CALDERA server and an agent is working, you might want to look into the following files:
- `app/service/contact_svc.py`
  - lines 57+ `handle_heartbeat()`
- `app/contacts/contact_tcp.py`
  - lines 35-39 (`operation_loop()`)
  - lines 84+ (`send()`)

**Comment by MANGLARAM** [comment]
hi there, i got something regarding the flow of operation data but what i would like to know is how one is loading data from like i have created a agent where is it loading the agent data from and moreover i get what contact_http is , but what is contact_tcp , udp in relation to sandcat agent if i am using that
 
help would be really appriciated

**Comment by MANGLARAM** [comment]
> Hi, I am not sure if I understood your question correctly.
> 
> Also I am only using CALDERA focusing on different areas (planners) but I might help you to find the right direction. If you want to find out how the communication between the CALDERA server and an agent is working, you might want to look into the following files:
> 
> * `app/service/contact_svc.py`
>   
>   * lines 57+ `handle_heartbeat()`
> * `app/contacts/contact_tcp.py`
>   
>   * lines 35-39 (`operation_loop()`)
>   * lines 84+ (`send()`)

is this helpful in case of sandcat agent which uses http contact
