### ISSUE TITLE
Where is the "upload payload" button?

### ISSUE THREAD

**Issue by zrquan** [mitre/caldera#2676]
There is a "upload payload" button in version 3.1, but not found in version 4.x. Has it been deleted? Why?

![Screenshot_20221021_093218](https://user-images.githubusercontent.com/33086594/197090427-f3142be2-c06a-45c4-89fd-35484b3f6042.png)

**Comment by argaudreau** [comment]
Hi @zrquan, thanks for the good question. When we moved over to v2 of the API, we didn't add an endpoint for the uploading of payloads so it may have been overlooked during the UI redesign. It's a useful feature however, so I'll add it to our backlog and get this implemented.

**Comment by elegantmoose** [comment]
@zrquan closing as added to backlog

**Comment by cln-io** [comment]
🙈 it’s marked as completed, but I can’t find a trace of any upload feature anywhere, I could be overlooking it though 🤕
