### ISSUE TITLE
install caldera via pip3 error

### ISSUE THREAD

**Issue by x0341** [mitre/caldera#2678]
**Describe the bug**
Caldera cannot be installed

pip3 install -r requirements.txt
ERROR: Could not find a version that satisfies the requirement websockets>=10.3

**To Reproduce**
1. 

git clone https://github.com/mitre/caldera.git --recursive
cd caldera
pip3 install -r requirements.txt
ERROR: Could not find a version that satisfies the requirement websockets>=10.3

**Expected behavior**
Cannot run caldera last version

**Screenshots**

![image](https://user-images.githubusercontent.com/1771943/197645312-3bb6a23b-9e9f-4355-ba9f-5c1c922f65b2.png)

**Desktop (please complete the following information):**
 - OS: [e.g. Mac, Windows, Kali] 
 Kali Linux
 Python 3.6.9

 - Version [e.g. 2.8.0]

**Additional context**
pip3 install -r requirements.txt
ERROR: Could not find a version that satisfies the requirement websockets>=10.3

**Comment by x0341** [comment]
upgrade python to 3.8 and now is ok.

**Comment by yee-jonathan** [comment]
Issue resolved per reporter's comments
