### ISSUE TITLE
Go Lang version error

### ISSUE THREAD

**Issue by Lavisha97** [mitre/caldera#2685]
**Describe the bug**
Facing an error in GO Lang version despite the version being more than the minimum requirement mentioned.

Min Version needed: 1.11
Version Installed : go1.19.3
------
ERROR (app_svc.py:173 validate_requirement) go does not meet the minimum version of 1.11

**Comment by yee-jonathan** [comment]
@Lavisha97 What directory do you have go installed in? CALDERA checks for go being installed in `/usr/local/go/bin`. Please double check your environmental variables and report back.

**Comment by Lavisha97** [comment]
Hi @yee-jonathan,
It is in the same directory. PFA the screenshot as well
![image](https://user-images.githubusercontent.com/32261530/203037260-717597e5-95bd-4f45-9b1d-01d187d3bde1.png)

**Comment by yee-jonathan** [comment]
@Lavisha97 Can you also verify the proper $PATH variable is set? I cannot recreate this error.

**Comment by elegantmoose** [comment]
@Lavisha97 reopen if still issues
