### ISSUE TITLE
can not delete a fact source from web page

### ISSUE THREAD

**Issue by dickens88** [mitre/caldera#2689]
in 4.1.0 version. After I click the `delete` button in `fact sources` page, the instance of the fact source i deleted will dispear from the list on the page. But after i restart the server, the deleted fact source will come back again. It seems it didn't really remove the config, bcos when I check the files under `caldera/data/sources` I can see that the files of the fact source are always there, it will keep on adding new files but never been reduced.

I'm using 4.1.0, but i suppose 4.0.0 have the same issue. please check.

**Comment by elegantmoose** [comment]
@dickens88 What is the command you are using to restart the server?

**Comment by dickens88** [comment]
@elegantmoose thank you for the reply. I kill the process directly with `kill -9`. cloud you pls inform me what is the right way to restart server ?

**Comment by yee-jonathan** [comment]
@dickens88 Please see -> https://caldera.readthedocs.io/en/latest/Troubleshooting.html?highlight=restart#stopping-caldera

Using `kill -9` interrupts the backup and save features in CALDERA. Please use SIGINT or CTRL + C to safely shutdown CALDERA

**Comment by dickens88** [comment]
@yee-jonathan thank you for the info, it's very helpful. I run caldera server as a service, which means i will run it at backend. it also means that we can not use CTRL + C. But i suppose if caldera can be run as a service then it will be easier for use. just like `service caldear stop/start`. 

anyway, thank you very much for the answer.

**Comment by yee-jonathan** [comment]
@dickens88 Instead of `kill -9`, you can try `kill -sigint -<pid>` instead. That's the 'ctrl + c' equivalent.
