### ISSUE TITLE
Issue with psexec_move

### ISSUE THREAD

**Issue by qjerome** [mitre/caldera#27]
First of all, thank you very much for this nice project.
I open a issue because the psexec_move operation was not working for me and I somehow figured out how to fix the issue.
I saw in the logs that psexec module was looking for the RAT at ../dep/crater/crater/cratermain.exe and that file was missing.
The issue is that my caldera instance does not accept to start unless it finds the RAT at ./dep/crater/crater/CraterMain.exe, so I cannot simply rename it to cratermain.exe
What I did instead is to symlink CraterMain.exe to cratermain.exe, but I think a better solution would be to fix this name consistency directly in the code, maybe through a configuration variable.

Regards,

**Comment by dm-mitre** [comment]
@qjerome thanks for reporting this. this is definitely a bug.

**Comment by forensic65x** [comment]
I am seeing the same issue.  Has the bug been fixed?

**Comment by qjerome** [comment]
On my side I did not update since a while so I cannot help you.
Sorry!

**Comment by hf-mitre** [comment]
I've corrected the capitalization of `CraterMain.exe`.  Thanks for finding this and letting us know!
