### ISSUE TITLE
After restart caldera the deleted Fact Sources will come back again

### ISSUE THREAD

**Issue by dickens88** [mitre/caldera#2705]
Hello guys,

Sorry, but this is the second time I open this topic, the first time is here https://github.com/mitre/caldera/issues/2689.

I tried to use `CRTL+C` to stop caldera server, but this result is all the same. 

**To Reproduce**
1. I run some operations and they generated serveral Fact Sources automatically.
2. I click to `fact sources` page and saw the new items
![image](https://user-images.githubusercontent.com/8390209/208705207-bb6d9bc8-5cb6-4aed-acbb-440b4c5eb2f4.png)
3. I delete all those items one by one. it seems success when i click `Delete Source`. because it just disappear from the list then.
4. I restart the server by press `CRTL+C` or `kill -2 pid`, but after that all those deleted fact sources appears again.

I saw all the generated fact sources ware keep in `/opt/caldera/data/sources` that ware never been deleted ...

the caldera version is v4.0 release

**Comment by elegantmoose** [comment]
@dickens88 Apologies have not had time to look into. As a temporary fix could you restart Caldera with the '--fresh' flag that tosses the past saved data?

**Comment by dickens88** [comment]
> 

Hi @elegantmoose thank you for the reply. I tried restart with '--fresh' but it will remove all the things inside of `data` folder. It looks like a 'Force Initialization'. Fortunately, I found the archived files in the `backup` directory, otherwise I would have lost the test cases I added myself.

anyway, If i would like to delete the fact source which generated by operations automatically, i have to find the file under `data/sources` before I restart caldera.

**Comment by elegantmoose** [comment]
@dickens88 Looking into. (apologies for late response)

**Comment by elegantmoose** [comment]
@dickens88 I couldnt reproduce. What Caldera version and OS are you using?

**Comment by elegantmoose** [comment]
@dickens88 - I also just tested on Ubuntu 22 and couldnt reproduce.

Can you try to pulling Caldera v4.1 or the master branch and see if that fixes.

**Comment by elegantmoose** [comment]
@dickens88 Pull master branch and LMK if issue resolved for you.

**Comment by elegantmoose** [comment]
@dickens88 Reopen if issue still present.
