### ISSUE TITLE
Not Loading Agents, Abilities and Adversaries

### ISSUE THREAD

**Issue by scipi0n** [mitre/caldera#2715]
I believe there is a bug with Caldera since maybe two weeks ago. Nothing is currently working right now.

![imagen](https://user-images.githubusercontent.com/90568604/211504069-c3714663-ba46-45a2-9f42-600af96aba93.png)
The agents aren't loading.

![imagen](https://user-images.githubusercontent.com/90568604/211504593-84d79d73-5800-4ab9-a177-7958cb0e9ff0.png)
The abilities aren't loading.

![imagen](https://user-images.githubusercontent.com/90568604/211504800-a362a7dc-9f94-4dba-9d62-1865d69beaca.png)
As for the adversaries, it seems that the description of the adversary is there but I can't see the name and I can't click on them.

 I installed Caldera a few months ago and I've never experienced an issue like this. 

I thought this was a problem of my enviroment but a friend tried to install Caldera using Docker and he ran into the same problem as me. 

I am running Caldera on a Ubuntu 22.04.1 LTS system.
 
Like I said I still don't know for sure if its just a problem from my side or if its common.

**Comment by elegantmoose** [comment]
@scipi0n Any error output when you launch Caldera?

Try deleting your browser history as well. There might be some cached objects affecting UI.

**Comment by scipi0n** [comment]
No errors, some warnings what even with those errors the server worked well but one day it all failed.
The browser history is not the problem as I have tried switching browser and the problem still remains.

**Comment by scipi0n** [comment]
In the end it was an issue regarding our AV.

**Comment by elegantmoose** [comment]
Ah yep it was quarantining the agent files when you cloned them down. Definitely been there, glad you found root cause.
