### ISSUE TITLE
How to create a BootStrap ability

### ISSUE THREAD

**Issue by IGNFIfortrue** [mitre/caldera#2716]
hello who might concern,

I tired to create the BoostStrap, but failed to do that, it seems that not all abilities can be used as BootStrap ability, can you tell me the condition of creating a BootStrap ability?

thanks in advance.

**Comment by elegantmoose** [comment]
@IGNFIfortrue - Still having issue? Can you post some more details on what you tried to do specifically?

**Comment by elegantmoose** [comment]
@IGNFIfortrue Feel free to reopen with more details.
