### ISSUE TITLE
Manual Approve Function bug

### ISSUE THREAD

**Issue by IGNFIfortrue** [mitre/caldera#2717]
**Describe the bug**
as screenshots show, when I choose 'manual approve' before launching an oepration, the commands/links will be paused after I run the operation, and there is no button or choice to manually approve the commands

**To Reproduce**
1. start the operation with 'require manual approval' in advance function -> autonomous,
2. the commands will auto pasue and no reaction any longer

**Screenshots**
![image](https://user-images.githubusercontent.com/122549520/212115038-5f53e2bf-8cb1-44af-b81b-e14687a13db6.png)

![image](https://user-images.githubusercontent.com/122549520/212115326-052a90e6-0359-453b-9197-cf5be66a48ac.png)

**Desktop (please complete the following information):**
 - OS: kali linux
 - Browser firefox

**Comment by L015H4CK** [comment]
Hello, I just tried running an operation with the "Require manual approval" option.
After starting the operation, a button "Review Command" appeared in the "Link Command" column where I could successfully discard or approve a command.

I tested with Caldera 4.1.0 on Kali Linux and Firefox browser.

Did you check the server logs (server.py using `-l DEBUG`)? Maybe something went wrong?
I also wonder, why your second agent has a number as identifier?

PS: I am no caldera official - just a user.

**Comment by IGNFIfortrue** [comment]
> Hello, I just tried running an operation with the "Require manual approval" option. After starting the operation, a button "Review Command" appeared in the "Link Command" column where I could successfully discard or approve a command.
> 
> I tested with Caldera 4.1.0 on Kali Linux and Firefox browser.
> 
> Did you check the server logs (server.py using `-l DEBUG`)? Maybe something went wrong? I also wonder, why your second agent has a number as identifier?
> 
> PS: I am no caldera official - just a user.

Hello L015H4CK，

Thank you for your reply, I guess I truly meet a bug since there is no  "Review Command" button on my side, I will try your suggestion later.
For the second agent with a number-identifier, I guess it is because that I deploy it using udp instead of HTTP.

**Comment by L015H4CK** [comment]
Someone also already mentioned this three weeks ago (in discussion https://github.com/mitre/caldera/discussions/2710).
I still could not replicate the problem.

Have you tried using `--fresh` when starting the server to see if the error persists?

**Comment by pbmilley** [comment]
I'm having this exact same problem.  I've tried using Firefox on Kali (the same host running the Caldera server) and another Linux system with a Chromium browser (Vivaldi).  Both had the same result as above - the operation starts and pauses on the first task, and there is no "Review Command" button to be found anywhere on the page.

I've run the server with "-l DEBUG" option, and could not see any relevant errors.  I've also re-installed Caldera in a fresh directory doing a new git clone command - same result.

Please let me know if I can provide any other information that would be useful for reproducing or troubleshooting this issue.  I'm trying to complete the training and I'm stuck on this step.

**Comment by Quickswitches** [comment]
Same thing here, also using kali and firefox so guess the issue is there somewhere?

**Comment by Quickswitches** [comment]
Also just tried installing and using chrome but no change so doesn't seem to be the browser but kali itself?

**Comment by Quickswitches** [comment]
Just installed Caldera on a Ubuntu VM and it works fine there so guessing an issue with kali somehow

**Comment by heyquentin** [comment]
Same issue here. No button. I'm running Parrot 5.2 with Firefox 102.7. I'll try a Ubuntu build

**Comment by heyquentin** [comment]
Spun up a new Ubuntu Server 22.04 vm and installed Caldera via git. Same issue, there's no button in the Manual mode. Tried different browsers and there's no change, button still missing.

**Comment by heyquentin** [comment]
Tried the Docker build. Button still missing.

**Comment by elegantmoose** [comment]
Looking into.

**Comment by elegantmoose** [comment]
Yep, was able to replicate bug.

**Comment by elegantmoose** [comment]
@heyquentin @Quickswitches @pbmilley @IGNFIfortrue - Patched. Pull down master branch, check if fix works for you.

**Comment by pbmilley** [comment]
Yes, it's working for me now.  Thanks!
