### ISSUE TITLE
Offline Build Fails. Workaround?

### ISSUE THREAD

**Issue by kwasibb** [mitre/caldera#2723]
I am trying to install caldera offline but when I do it fails when I try to run the pip install. 

`(venv) dude@deep-pc:~/caldera$ pip3.8 install -r requirements.txt --no-index --find-links python_deps
Ignoring cryptography: markers 'python_version <= "3.7"' don't match your environment
Ignoring aioftp: markers 'python_version < "3.7"' don't match your environment
Looking in links: python_deps
Processing ./python_deps/aiohttp_jinja2-1.5-py3-none-any.whl
Processing ./python_deps/aiohttp-3.8.1-cp38-cp38-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_12_x86_64.manylinux2010_x86_64.whl
Processing ./python_deps/aiohttp_session-2.9.0-py3-none-any.whl
Processing ./python_deps/aiohttp_security-0.4.0-py3-none-any.whl
Processing ./python_deps/aiohttp-apispec-2.2.3.tar.gz
  Installing build dependencies ... error
  ERROR: Command errored out with exit status 1:
   command: /home/dude/caldera/venv/bin/python3.8 /home/dude/caldera/venv/lib/python3.8/site-packages/pip install --ignore-installed --no-user --prefix /tmp/pip-build-env-4p4yxt_5/overlay --no-warn-script-location --no-binary :none: --only-binary :none: --no-index --find-links python_deps -- 'setuptools>=40.8.0' wheel
       cwd: None
  Complete output (4 lines):
  Looking in links: python_deps
  Processing ./python_deps/setuptools-40.8.0-py2.py3-none-any.whl
  ERROR: Could not find a version that satisfies the requirement wheel (from versions: none)
  ERROR: No matching distribution found for wheel
  ----------------------------------------
ERROR: Command errored out with exit status 1: /home/dude/caldera/venv/bin/python3.8 /home/dude/caldera/venv/lib/python3.8/site-packages/pip install --ignore-installed --no-user --prefix /tmp/pip-build-env-4p4yxt_5/overlay --no-warn-script-location --no-binary :none: --only-binary :none: --no-index --find-links python_deps -- 'setuptools>=40.8.0' wheel Check the logs for full command output.
`

Pip version: `pip 20.0.2 from ~/caldera/venv/lib/python3.8/site-packages/pip (python 3.8)`

**Comment by Lolstroop** [comment]
Same here. Fails at Processing ./python_deps/aiohttp-apispec-2.2.3.tar.gz

**Comment by elegantmoose** [comment]
Looking at error output, this is an upstream issue with aiohttp package and its installation packages:

**Processing ./python_deps/aiohttp_session-2.9.0-py3-none-any.whl
Processing ./python_deps/aiohttp_security-0.4.0-py3-none-any.whl
Processing ./python_deps/aiohttp-apispec-2.2.3.tar.gz
Installing build dependencies ... error**
