### ISSUE TITLE
Deleted values for facts keeps being used by caldera

### ISSUE THREAD

**Issue by Florablia** [mitre/caldera#2725]
**Describe the bug**
Facts values somehow stay in memory and are used by caldera even thought they're no more in the source.

**To Reproduce**
1. Create a fact source with some facts and value, for example: fact: username, value: admin
2. Launch an operation with this fact source, with an ability using this fact. Wait for the operation to finish: the ability has successfully launched with the value "admin" for the fact "username"
3. Change the fact source to modify the value of fact "username" to something else, for example "administrator".
4. Relaunch the operation. The ability is now launched two times, once for the value "admin" - which should no longer exist - and a second time for the value "administrator"

**Expected behavior**
The ability should launch only once, with the updated value of the fact. If a fact value is no more in the fact source, it should not be used by the operation. 

**Screenshots**
I got a fact source with facts user.name and user.password containing only one value
![image](https://user-images.githubusercontent.com/104207345/217041516-48d5743e-3e55-46f6-b320-b9771a1c2aad.png)
But I have changed this value (user.name was root, and user.password was something else). First time, the operation was running well, with only one instance of the ability using those facts. But after I've changed the value, I now have 4 instance of the same ability running, with all possible combinations of user.name and user.password values:
![image](https://user-images.githubusercontent.com/104207345/217041109-bc49b7e4-6e4c-4999-9c8f-ad1f02cafe43.png)
here we got the one I actually want (updated values):
![image](https://user-images.githubusercontent.com/104207345/217041249-f33e16c8-ce38-4ed7-96bc-8a361f7df23a.png)
and here we got a combination with "root" as user.name, even thought it is no more in the fact source:
![image](https://user-images.githubusercontent.com/104207345/217041387-3b6db27a-bb81-461a-976e-1c7d3a8ebb16.png)

Fact source contains no relationship, so the value isn't kept for a relationship either. It's like a ghost value. 
I have found no other way than to make an entirely new fact source each time I wanna test new values. Which is counterproductive.

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Browser : firefox v105.0
 - Caldera Version : 4.0

**Comment by elegantmoose** [comment]
@Florablia Still having this issue?

Just checking, there is no abilities running before the ability you noted that is re-picking up the fact that you deleted? (i.e. you are running only that ability in the operation)

**Comment by Florablia** [comment]
Hi, 
Still having the issue and no other ability is launch in that operation. 
PI we're using Caldera as a docker, with a mounted volume for our abilities (I think we mount the whole data directory, will be able to confirm tomorrow).
