### ISSUE TITLE
How to prepare my victim machine env

### ISSUE THREAD

**Issue by gen3111620** [mitre/caldera#2728]
Hi, Thanks this awesome repo, it's helpful to understand TTPs for me.

I use some windows ability then met some error
this is some example as below,

1. Disable Defender with Defender Control (T1562.001)
command : cmd /c $env:temp\DefenderControl\DefenderControl\DefenderControl.exe
error : The system cannot find the path specified.

2. Port Scan NMap for Windows (T1046)

nmap : The term 'nmap' is not recognized as the name of a cmdlet, function, script file, or operable program. Check 
the spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:1
+

so I want to ask when I install windows 10 in my VM, How can I prepare for this environment then cover all windows ability? such as I need to enumerate all tool or all command install

Thanks in advance

**Comment by elegantmoose** [comment]
@gen3111620 There is a lot of online resources for building vulnerable machines, youll have to find setups that fit your target. From a 2-sec google:
- https://kavigihan.medium.com/creating-vulnerable-machines-beginner-guide-fbddc835949d
-https://www.reddit.com/r/hacking/comments/f4kpvr/building_a_vulnerable_vm/
- https://medium.com/@srisailam099/how-to-create-a-vulnerable-machine-bfc1031c72fb
