### ISSUE TITLE
KeyError when creating a fact source

### ISSUE THREAD

**Issue by zrquan** [mitre/caldera#2738]
**Describe the bug**
When using the correct content-type header **application/json** to create a fact source, a 500 Server Error is returned due to KeyError.

It seems that because `apispec_request_validation_middleware` isn't bound to the `create_fact_source` function.

![Screenshot_20230317_165915](https://user-images.githubusercontent.com/33086594/225859175-8ea153e4-7014-4b35-9021-a79303ee3f81.png)

```
500 Internal Server Error

Traceback (most recent call last):
  File "/home/zrquan/.pyenv/versions/caldera/lib/python3.10/site-packages/aiohttp/web_protocol.py", line 435, in _handle_request
    resp = await request_handler(request)
  File "/home/zrquan/.pyenv/versions/caldera/lib/python3.10/site-packages/aiohttp/web_app.py", line 504, in _handle
    resp = await handler(request)
  File "/home/zrquan/.pyenv/versions/caldera/lib/python3.10/site-packages/aiohttp/web_middlewares.py", line 117, in impl
    return await handler(request)
  File "/home/zrquan/code/python/caldera/app/api/v2/responses.py", line 37, in apispec_request_validation_middleware
    return await handler(request)
  File "/home/zrquan/.pyenv/versions/caldera/lib/python3.10/site-packages/aiohttp_apispec/middlewares.py", line 33, in validation_middleware
    data = await request.app["_apispec_parser"].parse(
  File "/home/zrquan/.pyenv/versions/caldera/lib/python3.10/site-packages/webargs/asyncparser.py", line 90, in parse
    result = schema.load(parsed)
  File "/home/zrquan/.pyenv/versions/caldera/lib/python3.10/site-packages/marshmallow/schema.py", line 722, in load
    return self._do_load(
  File "/home/zrquan/.pyenv/versions/caldera/lib/python3.10/site-packages/marshmallow/schema.py", line 844, in _do_load
    processed_data = self._invoke_load_processors(
  File "/home/zrquan/.pyenv/versions/caldera/lib/python3.10/site-packages/marshmallow/schema.py", line 1092, in _invoke_load_processors
    data = self._invoke_processors(
  File "/home/zrquan/.pyenv/versions/caldera/lib/python3.10/site-packages/marshmallow/schema.py", line 1224, in _invoke_processors
    data = processor(data, many=many, **kwargs)
  File "/home/zrquan/code/python/caldera/app/objects/c_source.py", line 49, in fix_adjustments
    self._fix_loaded_object_origins(in_data)
  File "/home/zrquan/code/python/caldera/app/objects/c_source.py", line 66, in _fix_loaded_object_origins
    y['source'] = input_data['id']
KeyError: 'id'
```

**Comment by L015H4CK** [comment]
Hi, to me it looks like your input data is missing an "id" field. Looking at the API documentation (http://{caldera_server_ip}:8888/api/docs#/sources/post_api_v2_sources) the example data for posting to api/v2/sources is:

```
{
  "relationships": [
    {
      "target": {
        "relationships": [
          "string"
        ],
        "value": "string",
        "collected_by": [
          "string"
        ],
        "trait": "string",
        "technique_id": "string",
        "score": 0,
        "source": "string",
        "links": [
          "string"
        ],
        "origin_type": "string",
        "limit_count": 0
      },
      "score": 0,
      "source": {
        "relationships": [
          "string"
        ],
        "value": "string",
        "collected_by": [
          "string"
        ],
        "trait": "string",
        "technique_id": "string",
        "score": 0,
        "source": "string",
        "links": [
          "string"
        ],
        "origin_type": "string",
        "limit_count": 0
      },
      "edge": "string",
      "origin": "string"
    }
  ],
  "facts": [
    {
      "relationships": [
        "string"
      ],
      "value": "string",
      "collected_by": [
        "string"
      ],
      "trait": "string",
      "technique_id": "string",
      "score": 0,
      "source": "string",
      "links": [
        "string"
      ],
      "origin_type": "string",
      "limit_count": 0
    }
  ],
  "rules": [
    {
      "action": "string",
      "trait": "string",
      "match": "string"
    }
  ],
  "adjustments": [
    {
      "offset": 0,
      "trait": "string",
      "value": "string",
      "ability_id": "string"
    }
  ],
  "id": "string",
  "name": "string",
  "plugin": null
}
```

In my experience one does not have to use every field in the used input data, but I would try setting the "id" field (simply use an online UUIDv4 generator for id generation).

**Comment by zrquan** [comment]
I think that when the id field is not set, it should be randomly generated and returned, just like the behavior of posting to /api/v2/operations.

And when you posting to /api/v2/sources but the content-type header is not "application/json", an id will be randomly generated, so I feel this is more like a bug :thinking:

**Comment by L015H4CK** [comment]
Yes, if I remember correctly the ID is randomly generated when it is not set when posting adversary profiles (the only case that I used so far). It was just an idea to find the source of the error.. when setting the ID fixes the error we know that the ID generation is missing somewhere - if not we can continue the search..

**Comment by L015H4CK** [comment]
More info: When posting an "empty" fact source, i.e. only setting the "name" field, it works as well. In this case a new ID is randomly generated and inserted in the ID field. The bug/problem seems to be that the caldera server tries to access the ID field in the input data in order to set the source of the facts to create _before_ generating and setting the id field of the fact source.

**Comment by L015H4CK** [comment]
> > I just tested it using curl instead of httpx. I got a "500 Internal Server Error. Server got itself in trouble" when not setting ID. After setting ID to "1234" for testing purposes, curl successfully pushed the fact source and it was visible in the web ui.
> 
> You can set the PYTHONASYNCIODEBUG environment variable to 1 to enable debug mode of asyncio, then post to /api/v2/sources without ID to get the traceback.

I do not understand your comment.

All I meant to say was, that I was able to reproduce the error and found a way to fix it.

After that, I added some additional information about where to problem might originate from.
