### ISSUE TITLE
aiohttp errors in version 4.1.0

### ISSUE THREAD

**Issue by nov3mb3r** [mitre/caldera#2742]
**Describe the bug**
ERROR: Could not build wheels for aiohttp, which is required to install pyproject.toml-based projects    

**To Reproduce**
1. Download stable release 4.10
2. pip3 install -r requirements.txt 
3. python3 server.py --insecure  

**Expected behavior**
Normal installation

**Screenshots**
![image](https://user-images.githubusercontent.com/10418973/230077219-233b51e4-fe0f-43b7-a522-9b15e130a471.png)
![image](https://user-images.githubusercontent.com/10418973/230077090-8463ba59-ecfc-46f0-8062-78bdbb95d549.png)

**Desktop (please complete the following information):**
 - OS: Kali Purple (6.1.0-kali5-amd64) / 6.1.0-kali5-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.1.12-1kali2 (2023-02-23) x86_64 GNU/Linux
 - Browser [e.g. firefox]
 - Python: Python 3.11.2

**Comment by L015H4CK** [comment]
Have you tried using another Python version? If I remember correctly, I encountered the same error using Python 3.10. Currently I am working with Python 3.9.13 and the installation of aiohttp_apispec as well as CALDERA work fine.

**Comment by dkorzhevin** [comment]
It looks, like python 3.11.x not supported yet, 3.10.x should be used.

```pip3.10 install -r requirements.txt``` did the trick.

**Comment by ventrova** [comment]
I'm currently on Python 3.11 and have caldera working.

Initialize a python virtual environment in your caldera directory. 
cd path/caldera
python3 -m venv venv3
source venv3/bin/activate
This is my currrent Requirements.txt file -> 
[requirements.txt](https://github.com/mitre/caldera/files/11326088/requirements.txt)

or you can just replace these two: 1)aiohttp==3.8.2 and 2) reportlab==3.6.12.

A few other things I did prior to that, which may not be necessary is:
1)pip3 install aiohttp_apispec
2)sudo apt install python3-dev

**Comment by amtzespinosa** [comment]
I had caldera running with Python 3.11 as well. Just update requirements.txt. Here it is:
[requirements.txt](https://github.com/mitre/caldera/files/11370783/requirements.txt)
