### ISSUE TITLE
CALDERA Qradar plugin

### ISSUE THREAD

**Issue by 00gxd14g** [mitre/caldera#2748]
https://github.com/00gxd14g/caldera/tree/master/plugins/qradar_integration can anyone help with this issue?

**Comment by L015H4CK** [comment]
Hi, what exactly is your issue? The link only shows your plugin.

**Comment by 00gxd14g** [comment]
Hello, I tried to create an extension but I'm not sure if everything is okay, it may need to be checked. I used the extension development documentation, but there may be some missing parts. I might need some help with this.

**Comment by L015H4CK** [comment]
I am sorry, but  I cannot look into your plugin and check "if everything is okay"..

If you have any specific questions I will gladly try to help you.
