### ISSUE TITLE
404 is received after finishing training

### ISSUE THREAD

**Issue by timbrigham-oc** [mitre/caldera#2751]
**Describe the bug**
On completion of the training module, a 404 is received clicking "Get your certificate". 

**To Reproduce**
1. Complete the training.
2. Click "Get your certificate", which goes to https://forms.office.com/g/mEeuSUBTda
3. Receive a 404 error 

**Expected behavior**
A Microsoft form should open, allowing submission of the completed training

**Desktop (please complete the following information):**
Tested on Chrome and Edge.

**Additional context**
Tested on the latest release of the Caldera framework.

**Comment by dkorzhevin** [comment]
I can confirm same issue. URL does not exist, or its access rights do not allow to open it.

**Comment by elegantmoose** [comment]
@timbrigham-oc @dkorzhevin Apologies. It should be fixed now. 

You will need to re-pull the Training plugin repo (master branch).

```
cd caldera/plugins/training
git checkout master
git pull origin master
```

OR just navigate directly to new form: https://forms.office.com/g/sYRNDuxCjC

**Comment by dkorzhevin** [comment]
Thank you, @elegantmoose !
