### ISSUE TITLE
Include option to export operation logs in ATTiRe format

### ISSUE THREAD

**Issue by ari-wein** [mitre/caldera#2759]
**What problem are you trying to solve? Please describe.**
I would love the ability to export operation logs in ATTiRe logging format.
The specification is here: https://github.com/SecurityRiskAdvisors/ATTiRe

**Comment by elegantmoose** [comment]
@ari-wein Not a bad idea. We will have to see if we can work it into a sponsor deliverable at some point.

**Comment by tklauw** [comment]
Very useful log format. Atomic Red Team already able to do ATTiRe logging. Any idea when it would be available in CALDERA? Thanks! :-)
