### ISSUE TITLE
'Kill Agent' errors for Manx agent deployed on Localhost - CTF

### ISSUE THREAD

**Issue by Jallnutt1** [mitre/caldera#2766]
Hello, 

I am new to Caldera and was going through the built-in CTF. In the "Contact points" challenge it has you create a Manx agent on your localhost (same host I am using to run Caldera). In the next challenge, "Kill agent" it has you kill the agent and I seem to always get an error when I try that. I get the "! Error Killing the Agent" little red box in the bottom right of the browser. I don't get any additional information. I tried killing a Manx agent deployed to a different linux machine and it died just fine. I rebooted my localhost machine and still the same issue. Any idea why this is? 

Thank you

**Comment by clenk** [comment]
Hi @Jallnutt1 apologies for the delayed response. The first things I would check are if you get any errors in the browser's console, in the commandline where you are running the manx agent, or in the commandline where you're running the Caldera server (you can run it with `--log DEBUG` for more logs, too).
