### ISSUE TITLE
Caledra with https

### ISSUE THREAD

**Issue by 0xWix** [mitre/caldera#2767]
Hi,
am trying to run caldera with https not with http but it's not working anyone have a solution for this !!??

**Comment by elegantmoose** [comment]
@0xWix Any more details, logs, stacktraces?

**Comment by 0xWix** [comment]
am trying to send and receive traffic by https not http

**Comment by alonsobsd** [comment]
> am trying to send and receive traffic by https not http @elegantmoose

Did you look at ssl plugin? it is used for ssl support and it needs haproxy https://caldera.readthedocs.io/en/latest/Plugin-library.html#ssl

**Comment by 0xWix** [comment]
@alonsobsd  i did this but am still having a same problem

**Comment by BuildAndDestroy** [comment]
By chance, are you using the Docker install? There was a PR for this a while back that does work with HTTPS:
https://github.com/mitre/caldera/pull/2661

**Comment by BuildAndDestroy** [comment]
Just noticed there was an issue with default.yml and local.yml. At some point, local.yml is now added to the docker build. Updated and merged to my master branch. Lines 21-46 should help you get there.
https://github.com/BuildAndDestroy/caldera/blob/master/Dockerfile
