### ISSUE TITLE
aiohttp-jinja2==1.0.0

### ISSUE THREAD

**Issue by etaylor77** [mitre/caldera#277]
When running `pip install -r requirements.txt`

Collecting aiohttp-jinja2==1.0.0 (from -r requirements.txt (line 1))
Could not find a version that satisfies the requirement aiohttp-jinja==1.0.0

No matching distribution found for aiohttp-jinja2==1.0.0

**Comment by wbooth** [comment]
ensure you're running pip for python3
one way to be sure it to execute like:
python3 -m pip install ...

**Comment by etaylor77** [comment]
Perfect! That worked. Thanks for the help.

**Comment by ana122128** [comment]
Thanks wbooth..!!!

I has same issue.

**Comment by santoah** [comment]
10

Try this, 
I solved by updating pip via Python, like this:

python2 -m pip install --user --upgrade pip

python3 -m pip install --user --upgrade pip
Hope it works for u. 

and then i ran 
python3 -m pip install -r requirements.txt

**Comment by 12306Bro** [comment]
Thank you for your help, I successfully solved this problem.
