### ISSUE TITLE
Not working SSL plugin

### ISSUE THREAD

**Issue by muyuka** [mitre/caldera#2774]
I want to add HTTPS to Caldera and I followed every single step on https://caldera.readthedocs.io/en/latest/Plugin-library.html?highlight=https#ssl but it is not working. After apply those steps, I restarted the caldera server and the error below is occurred. Is there any idea for solution?

**Error:**
2023-06-19 14:47:25 - ERROR (base_events.py:1771 default_exception_handler) Task exception was never retrieved
future: <Task finished name='Task-41' coro=<_check_using_default_cert() done, defined at /home/kali/Desktop/caldera/plugins/ssl/hook.py:24> exception=ConnectionRefusedError(111, 'Connection refused')>
Traceback (most recent call last):
  File "/home/kali/Desktop/caldera/plugins/ssl/hook.py", line 26, in _check_using_default_cert
    server_cert = get_server_certificate(('127.0.0.1', 8443))
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/ssl.py", line 1527, in get_server_certificate
    with create_connection(addr, timeout=timeout) as sock:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/socket.py", line 851, in create_connection
    raise exceptions[0]
  File "/usr/lib/python3.11/socket.py", line 836, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

**Comment by muyuka** [comment]
I fixed this problem by deleting "**nbproc 1**" line in haproxy.conf file. I think the latest version of HaProxy is not supporting that. 
But right now, Although the HTTPS connection is established, the certificate I use is not considered reliable because it is self-signed and I cannot communicate with the caldera agent over https. 
In the caldera docs, it says I can use **openssl req -x509 -newkey rsa:4096  -out conf/certificate.pem -keyout conf/certificate.pem -nodes** command to create a certificate but that certificate is useless. How can I solve it?

**Comment by clenk** [comment]
You can either add an exception for that self-signed cert or buy a real cert from a cert provider.
