### ISSUE TITLE
TypeError: __init__() missing 1 required positional argument: 'log'

### ISSUE THREAD

**Issue by behold3r** [mitre/caldera#278]
Traceback:

`Traceback (most recent call last):
  File "server.py", line 87, in <module>
    operation_svc = OperationService(data_svc=data_svc, utility_svc=utility_svc, planning_svc=planning_svc, planner=cfg['planner'])
  File "/home/administrator/caldera/app/service/operation_svc.py", line 17, in __init__
    self.planner = getattr(planning_module, 'LogicalPlanner')(self.data_svc, planning_svc)
TypeError: __init__() missing 1 required positional argument: 'log'`

When running on latest build.

**Comment by privateducky** [comment]
do a fresh recursive clone on the repo and retry-- this error appears to be a mis-alignment of the plugins with the latest core/master code. I've confirmed a fresh clone has no problems.

**Comment by behold3r** [comment]
Thanks David! That solved the issue.
