### ISSUE TITLE
Unable to create a customize agent

### ISSUE THREAD

**Issue by claperson** [mitre/caldera#2784]
Hi.
I am facing an issue whiile creating a custom agent. Please find the below script details:

profile=$(echo '{"server":"http://10.2.222.60:8888", "platform": "linux", "executors":["sh"]}' | base64 -w O)
curl -S -X POST -d $profile http://10.2.222.60:8888/beacon | base64 --decode

Can someone kindly guide me as to what mistake I am making at this point?

**Comment by clenk** [comment]
Hi, thanks for reaching out. The beacon needs to contain a `paw` key with a value that is an id string unique to the instance of the agent that is sending the beacon. With the default agent, this value is randomly generated.

What error message were you seeing?

**Comment by claperson** [comment]
![image003](https://github.com/mitre/caldera/assets/138789278/23e3e3df-6a88-4816-9bc1-aacf58ab536b)
Please refer to the attached snapshot. I tried as you mentioned but  still not able progress.
