### ISSUE TITLE
Deleted Facts Being Re-used

### ISSUE THREAD

**Issue by heyquentin** [mitre/caldera#2788]
**Describe the bug**
I set up an adversary and a Facts page to go along with the adversary. In one of the facts I put the value in as "Red Team" and used this in an ability. An operation was run and Caldera didn't like the space so I changed the value to "Red_Team". When I run an operation a second time the operation is doubled and in the command there's "Red Team" and "Red_Team" despite the Fact Source value only being "Red_Team". 

**To Reproduce**
1. Set up an operation that uses a fact
2. Run the operation
3. Change the fact
4. Re-run the operation

**Expected behavior**
The updated fact and only that fact should be used during the operation

**Screenshots**
Ability. Fact in question is #{fin6_reg_run_name}
![vmware_Nk7WvVuJ6U](https://github.com/mitre/caldera/assets/25093410/1b149f77-5a5a-4cd3-bd6e-83d44dc3d7b4)

Fact Source. Note the content of fin6_reg_run_name
![juoposEg6v](https://github.com/mitre/caldera/assets/25093410/62b76a34-7150-40ca-b1bc-c5975519b910)

Operation is run and ability is executed twice
![6F5PdCW6Cn](https://github.com/mitre/caldera/assets/25093410/b1949ed5-ceb9-4230-a4ed-f578d433a661)

One command with the updated fact
![vmware_1QxNpii5vT](https://github.com/mitre/caldera/assets/25093410/734d2656-7b69-4a65-97bc-833cb0f5b0ed)

And one with the old fact
![Qm2X0EL0k5](https://github.com/mitre/caldera/assets/25093410/dea5dae0-3ec0-4afc-9148-00a1ea26522e)

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04
 - Browser: Firefox
 - Version: latest

**Additional context**
It looks like this problem was reported here https://github.com/mitre/caldera/issues/2725 and nothing was done. Can you please address the issue?

**Comment by dan-kir** [comment]
I have also experienced this bug.

**Comment by elegantmoose** [comment]
Fix coming soon.

**Comment by elegantmoose** [comment]
#2811

**Comment by dan-kir** [comment]
Bump.
Appears this was recently fixed?

**Comment by elegantmoose** [comment]
@dan-kir Correct. Would help if we close the issue. :)
