### ISSUE TITLE
Unable to Connect to Caldera Server from another host.

### ISSUE THREAD

**Issue by BlakeHensleyy** [mitre/caldera#2794]
**Describe the bug**
I am unable to connect to my Calder server GUI from a different host. The Caldera server will go through the setup command with no issues. When I try to connect from a different host then I cannot connect, regardless of port used. 

**To Reproduce**
1. Not sure.

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - Server: RHEL 8.8 
 - Connecting host: Windows 10
 - Chrome
 - Version 4.2.0 or 4.1.0 (Neither work)

**Additional context**
 I have tried installing Caldera using the concise instructions and I have tried the Step-by-Step. I use python/pip 3.8. The Calera server and the connecting host have all needed ports open and there is no firewall between the two.
[caldera_error.txt](https://github.com/mitre/caldera/files/12163193/caldera_error.txt)

**Comment by clenk** [comment]
Hi @hashcab, thank you for including the log. It looks like the connection was made before the server reported "All systems ready." which might be a problem. Are you able to connect from the local host?

**Comment by hashcab** [comment]
Yes, when I curl the IP:8888 from the local host I get the Caldera logon screen HTML returned.

**Comment by hashcab** [comment]
> Hi @hashcab, thank you for including the log. It looks like the connection was made before the server reported "All systems ready." which might be a problem. Are you able to connect from the local host?

Yes, when I curl from local host then the webpage is returned. What do you think the cause of the connection could be? Thanks for the help! @clenk

**Comment by hashcab** [comment]
All I had to do was allow the port in my firewall ):
