### ISSUE TITLE
Exec Format Error - Installing a linux agent

### ISSUE THREAD

**Issue by yaweffah0** [mitre/caldera#2796]
Hi people. 
I am trying to install a linux agent on a target Linux machine. However whenever i try to execute the splunkd file on the target machine. I get an exec format error. Snippet shown below:

`./splunkd -server "http://10.0.2.15:8888" -group red -v                                                                      
ResourceUnavailable: Program 'splunkd' failed to run: An error occurred trying to start process '/home/automobile/splunkd' with working directory '/home/automobile'. Exec format errorAt line:1 char:1    `

**Comment by clenk** [comment]
Hi @yaweffah0, can you show the command used to download splunkd? Specifically, did it include `-H "platform:linux"` in the `curl` command? Also what architecture is the linux machine? Any chance it is ARM?
