### ISSUE TITLE
How to add payloads to caldera using the UI

### ISSUE THREAD

**Issue by cln-io** [mitre/caldera#2805]
Similar to #2676 

How does one upload payloads from the Caldera interface?
The swagger file doesn't seem to have any details on uploading it over API's either :(

I did locate documentation for exfil stuff https://caldera.readthedocs.io/en/latest/The-REST-API.html#file-upload (but POST'ing into that replies with 500, server got itself into trouble)

What am I missing here? 🙁

**Comment by elegantmoose** [comment]
As in to add a payload to Caldera so that it can then be used in operation?

**Comment by cln-io** [comment]
> As in to add a payload to Caldera so that it can then be used in operation?

Yes indeed!

for example: upload a custom binary to caldera to be used in an operation (by an ability)

**Comment by clenk** [comment]
Caldera doesn't currently have an API endpoint for adding additional payloads. It expects new payloads to be provided via new plugins. It expects payload executables to be in a `payloads` directory under the plugin (eg. https://github.com/mitre/stockpile/tree/master/payloads), and then a yaml file referencing the payload to be `data/payloads` under the plugin (eg. https://github.com/mitre/stockpile/blob/master/data/payloads/70632d81-bb39-40dd-bfba-cfd1f8196eb6.yml). The yaml file will enable the payload to be used in an operation. See https://github.com/mitre/skeleton for a quickstart for a new plugin that you can add additional payloads to.
