### ISSUE TITLE
Spaces in fact traits are being prefixed with backslashes

### ISSUE THREAD

**Issue by dan-kir** [mitre/caldera#2814]
**Describe the bug**
Spaces in fact traits are being prefixed with backslashes when used in abilities.

This is causing problems when trying to seed an operation with a fact source that includes such traits.

**To Reproduce**
1. Create a fact trait with spaces.
2. Use the fact in an ability
3. Any spaces are prefixed with backslashes.

**Expected behavior**
1. Create a fact trait with spaces.
2. Use the fact in an ability.
3. The trait can be used as is without the backslash prefix.

**Screenshots**
Example fact trait:
![Screenshot_2023-09-05_16-05-21](https://github.com/mitre/caldera/assets/92664495/8eb03610-aad4-4315-bda9-ad932e1bacd9)

Example command being executed:
![Screenshot_2023-09-05_16-14-18](https://github.com/mitre/caldera/assets/92664495/35086ddf-ba5b-4776-a221-3176da424b16)

**Desktop (please complete the following information):**
 - OS: Kali
 - Browser: Chrome
 - Version: Caldera latest

**Additional context**
Don't think the issue is with the agents. Tested both Sandcat and Ragdoll agents.

**Comment by idleninja** [comment]
I came to check if this had been previously reported as i too am experiencing the same unexpected behavior.

**Comment by dan-kir** [comment]
Bump. 
I would still like to see a solution to this. Can draft a PR when I have the time to investigate.

**Comment by d3vco** [comment]
@dan-kir what ability / plugin were you using when you encountered this issue?

I was not able to replicate when testing on an arbitrary ability (spaces were retained from fact to command), which makes me think it may be related to the ability or plugin that you are using.

**Comment by dan-kir** [comment]
> @dan-kir what ability / plugin were you using when you encountered this issue?
> 
> I was not able to replicate when testing on an arbitrary ability (spaces were retained from fact to command), which makes me think it may be related to the ability or plugin that you are using.

In the provided screenshots, I am using a custom ability that simply sends a GET request using curl.

**Comment by elegantmoose** [comment]
@dan-kir Still having issue?

**Comment by dan-kir** [comment]
@elegantmoose Yes still seeing spaces in facts being escaped when used in abilities. I can provide more examples if it will help.

**Comment by dan-kir** [comment]
Here is a simple example using modified ability 'Leave note (T1491)'

![image](https://github.com/mitre/caldera/assets/92664495/bec06f3b-cf9d-409f-bb8e-64f7b16a54f9)
![image](https://github.com/mitre/caldera/assets/92664495/010159b2-466e-4ccd-b780-9122b86c7a0c)
![image](https://github.com/mitre/caldera/assets/92664495/e3c0bb26-0052-41c5-b6d0-b143f04fe998)
![image](https://github.com/mitre/caldera/assets/92664495/284cd1e7-a820-4789-8632-519a19709fde)

**Comment by d3vco** [comment]
I still cannot replicate. I modified the Leave note ability as shown in your screenshots @dan-kir and I did not experience the space escaping behavior.

![Screenshot 2024-01-12 175902](https://github.com/mitre/caldera/assets/935806/b0f5c9a3-df19-4714-b8a1-738b45a68c6e)


I will add that `Fact`s do [have a method](https://github.com/mitre/caldera/blob/1c944c612862d7941bb4125cf45f0d055482dc49/app/objects/secondclass/c_fact.py#L94) that *allows them to be* escaped, but nothing you are doing should be calling that method.

**Comment by dan-kir** [comment]
That's it! That function is being called because I'm using a 'sh' executor.

I confirmed this was my problem by updating the 'escaped' function like so:
```python
def escaped(self, executor):
        #if executor not in escape_ref:
        return self.value
        escaped_value = str(self.value)
        #for char in escape_ref[executor]['special']:
        #    escaped_value = escaped_value.replace(char, (escape_ref[executor]['escape_prefix'] + char))
        return escaped_value
```

This works for me in the short-term. Unsure what a long-term fix looks like. Could spaces be removed from the 'escape_ref' dictionary?

**Comment by gitonglue** [comment]
Thank you @dan-kir for providing the fix by commenting out the lines. 

Will there be future feature to allow user specifying whether to escape special characters or not? Even better, to allow user to define the list of characters for escaping. Thank you :)
