### ISSUE TITLE
Caldera - Missing Payloads

### ISSUE THREAD

**Issue by TheLiberator0101** [mitre/caldera#2821]
Is anyone else missing these 4 payloads in their Caldera instance? I would really like to use these, but they don't seem to be available. I've already run the download script in the plugins/emu folder, but I noticed the script doesn't include the four highlighted in the screen grab. 

![image](https://github.com/mitre/caldera/assets/45983566/73a88c5a-720b-41ca-b76b-61ff4ebe2eca)

**Comment by elegantmoose** [comment]
@TheLiberator0101 Did you run the download script in the Emu plugin for all the plugins the Emu abilities need?

https://github.com/mitre/emu#installation

**Comment by elegantmoose** [comment]
@TheLiberator0101 Any luck?
