### ISSUE TITLE
Problem with installation

### ISSUE THREAD

**Issue by ic32k** [mitre/caldera#2847]
Hello,

I'm trying to learn how to use Caldera, and I'm facing some problems with the installation, tried both deployments methods, docer and local installation, started with docker deployment as though it will be easyer but it is worst dependencies not met, basic programs (curl, apt-tools, lsb_release) not installed in the base image making install scripts fail, etc also tried to install several versions cloning different branches (4.2.0, 4.1.0, 4.0.0) of the program....

The first problem was after running the download_payloads.sh from emu plugin, this contains a bug as ADFind.zip is password protected ("NotMalware") and the unzip script hasn't provided it... in the emu plugin directory still some payloads was missing (m64.exe, ryuk.exe, dumpwebbrowsercreds.exe, rubeus.exe, etc)

And some errors from dependencies not met from oter plugins
![imagen](https://github.com/mitre/caldera/assets/45407347/3f6bf681-d131-4756-ba77-7b5d3f6d1b94)
![imagen](https://github.com/mitre/caldera/assets/45407347/762eff9c-5a46-4448-a7c1-7cd7441b7c96)

Managed to solve that installing manually and searching the binnaries in the wild (all except ryuk)

Still some error I didn't manage to solve:
![imagen](https://github.com/mitre/caldera/assets/45407347/0ae6ead0-fa52-4047-8d5a-11a312778ace)

And got some error trying to solve the certificates:
![imagen](https://github.com/mitre/caldera/assets/45407347/83f2c3ee-a2ec-4875-84cf-c73e376e8492)

**Comment by elegantmoose** [comment]
@ic32k

Unfortunately a lot of the payloads and scripts from the Emu plugin (and really CTID emulation plans) have their URLs change so it sometimes required to go out and find where they live now.

For the other plugin errors, some plugins require additional requirements. Its a good idea to read the README of any of the plugins you are using. In the case above, the Human plugin requires some additional libraries that can be installed via:

```
pip install -r caldera/plugins/human/requirements.txt
```

**Comment by elegantmoose** [comment]
reopen if still having trouble
