### ISSUE TITLE
High CPU Usage on Caldera TAB

### ISSUE THREAD

**Issue by OppressionBreedsResistance** [mitre/caldera#2849]
**Describe the bug**
High CPU usage of Caldera TAB in various browsers 

**To Reproduce**
1. Browse Caldera Web GUI
2. Select Operations or Adversaries from the left panel
3. Run Shift+Esc to analyze CPU, Memory and Network usage of browser
4. Observe 100% CPU usage

**Expected behavior**
Smooth browsing

**Screenshots**
![caldera_CPU](https://github.com/mitre/caldera/assets/60150959/c0a10b73-ab17-4100-9ad9-43e5f62fcdf6)
Red square indicates CPU usage

![caldera_CPU2](https://github.com/mitre/caldera/assets/60150959/4d881fb8-c622-4726-a340-4e9fbc31e861)
CPU and Memory usage on virtual machine server and docker container are minimal. I believe its a client-side problem. 

**Desktop (please complete the following information):**
 - OS: Windows 11 latest
 - Browser: Edge, Chrome, Firefox
 - Caldera Version: 4.2.0
 - CPU: Intel Core i5-9500 3 GHZ
 - RAM: 32 GB

**Additional context**
Network usage is very low, as well as memory and cpu consumption on the Caldera Server. I can only see high CPU usage on the client side.

**Comment by clenk** [comment]
Hello @OppressionBreedsResistance, thank you for the detailed report. Unfortunately we haven't been able to reproduce this yet. Is this happening on a brand-new instance of Caldera, or one that has several operations and/or custom adversaries created? Any non-standard Caldera plugins in use?

**Comment by OppressionBreedsResistance** [comment]
Hi, thank you for your reply
We have got a multiple plugins which i think most important is atomic. We have as well 

- access
- compass
- debrief
- emu
- fieldmanual
- gameboard
- human
- manx
- sandcat
- stockpile
- training
Whats interesting here, the problem with CPU is only when accessing  "operations", "adversaties" or "abiligies" from "Campaigns" submenu. 

There is almost no long-term running operations, maybe one-two per day. I have noticed that problem arises when im accessing "adversaries" tab. Maybe high number of configured adversaries is the cause? What`s the "standard" adversaries 
number in Caldera?

**Comment by elegantmoose** [comment]
@OppressionBreedsResistance We were not able to reproduce. Any update from your end?

**Comment by OppressionBreedsResistance** [comment]
Hi 
Right now its working much better. My devops team have made some reconfigurations recently, so maybe wait a couple days (new year I guess) - I will ask them what have they done and I will update you, just in case anyone has similar problem. 
Another question - maybe, just maybe there is a little bit fewer adversaries. How many adversaries are considered "normal" amount?
