### ISSUE TITLE
Operation in state Running and not accepting any commands

### ISSUE THREAD

**Issue by borutlape** [mitre/caldera#2853]
Hi,

I am using latest Caldera on latest Kali.
When I start an operation, it does not end, (e.g. Discovery stops at step 10 of 12).
More over the operation does not accept any commands (stop, pause, manual/automatic....) and displays red error:  
"Error updating operation. Operation may have already finished running."

Any ideas?

Thanks,
Borut

**Comment by elegantmoose** [comment]
Borut, can you provide the full stack trace?
