### ISSUE TITLE
Access credentials for Docker image are missing

### ISSUE THREAD

**Issue by d3zit** [mitre/caldera#2854]
None of the credentials available online in the documentation grant access to the web ui.

**Comment by d3zit** [comment]
I also checked the conf file, but unfortunately nothing happens with those credentials. `requirements:
  go:
    command: go version
    type: installed_program
    version: 1.19
  python:
    attr: version
    module: sys
    type: python_module
    version: 3.8.0
users:
  blue:
    blue: admin
  red:
    admin: admin
    red: admin
`

**Comment by AnkurYogi** [comment]
same here doesn't seem to find UI creds after docker install

**Comment by clenk** [comment]
What command are you using to start the server and which conf file are you looking in?

If you start the server with the `--insecure` option it will use `default.yml`, but if you don't use that option it will generate and use a `local.yml` which will contain different credentials.

**Comment by kotaksempit** [comment]
@d3zit , @AnkurYogi 

If you are using docker deployment. The credential file (conf/local.yml) is generated inside the container. You need to enter the container to retrieve it. 

1) List out your running docker containers. Keep note of the name of the container.
`docker ps` 

2) Enter the container using exec command. 
`docker exec -it your_container_name bash`

3) Once you entered the container terminal, run this to view the credentials
`cat conf/local.yml`

**Comment by elegantmoose** [comment]
reopen if still having trouble
