### ISSUE TITLE
docker build image on arm64 servers failed when deploying golang

### ISSUE THREAD

**Issue by gh503** [mitre/caldera#2860]
**Describe the bug**
docker build image on arm64 servers failed when deploying golang.

**To Reproduce**
1. run `docker build` on an arm64 server;

**Expected behavior**
1.docker build success with arm64.

**Screenshots**
![image](https://github.com/mitre/caldera/assets/65324074/c978adb3-bee4-41f4-b4dc-23c526227cfd)

**Desktop (please complete the following information):**
 - OS: openEuler
 - Version 22.03 LTS

**Additional context**
finally I built success with go1.17.6-arm64.tar.gz

**Comment by elegantmoose** [comment]
@gh503 Did you find workaround?

**Comment by gh503** [comment]
@elegantmoose Yeah, thanks!
