### ISSUE TITLE
not asset directory error

### ISSUE THREAD

**Issue by recepbuyukfirat** [mitre/caldera#2876]
Hello,

When i was build caldera, it wasn't build because not found directory asset folder. please help

**Comment by clenk** [comment]
Hi, when you ran `server.py` did you include the `--build` flag? When you cloned the repository did you use `--recursive`? You should have a `plugins/magma` directory that is not empty. Is that the case?

**Comment by bjeffries** [comment]
@clenk can we catch the error that is thrown when --build isn't used and produce better logging. (i.e. make sure you use the --build option with the new release)
I think this will reduce pain points of users upgrading to 5.0 who didn't read the new start requirements. [raises hand, that's me too]

**Comment by elegantmoose** [comment]
Yes, we can add a warning message.
