### ISSUE TITLE
Unable to login with default users

### ISSUE THREAD

**Issue by ManuPH** [mitre/caldera#2881]
Hi Team,

When you run caldera's new version with default yml configuration file:
`python3 server.py --insecure --build`

It's not posible to login with default users/password pairs included in default.yml file:

![image](https://github.com/mitre/caldera/assets/12954137/97d8c8e7-2dca-4486-812f-b0499a123b46)

**Comment by activeshadow** [comment]
I can confirm that I am seeing this behavior as well.

**Comment by elegantmoose** [comment]
When did you pull v5? What browser are you using?

*We just fixed an issue on Firefox browser that was preventing the login form from working.

**Comment by activeshadow** [comment]
I pulled branch 5.0.0 an hour ago, and I tested in Firefox.

**Comment by activeshadow** [comment]
@elegantmoose is the fix for Firefox in a separate branch that I can test?

**Comment by elegantmoose** [comment]
Try:
- Deleting browser history
- If using '127.0.0.1:8888', try 'localhost:8888', or vice versa.

**Comment by activeshadow** [comment]
I tested from a fresh VM that I had just built, so no browser history to speak of.

**Comment by elegantmoose** [comment]
@activeshadow It was merged in Magma plugin yesterday -> https://github.com/mitre/magma/pull/40

**Comment by elegantmoose** [comment]
Oh try pulling master not v5.0.0

**Comment by activeshadow** [comment]
@elegantmoose this worked for me. I can now login from Firefox. Thanks!

**Comment by elegantmoose** [comment]
@ManuPH How about for you?

**Comment by ManuPH** [comment]
It works now!, thank you!

**Comment by Unleashedmen** [comment]
I have the same problem, i cannot login with the default credentials, the difference here is that I installed using docker , when running the application i saw that there is not local.yml created and default.yml credentials do not work, any ideas?
![image](https://github.com/mitre/caldera/assets/16200949/85dce4f3-074c-443d-aa13-00208feca2b0)

**Comment by MuhammadEissa** [comment]
the latest is not working, same issue cant log in no matter what

**Comment by decyphertek-io** [comment]
Solution Using Python Method:
-----------------------------------------
I ran into a similar issue and decided to provide some more detail on how to solve the problem. 
* --insecure flag uses default.yml
*  Not using --insecure will autogenerate a local.yml
```
# first setup nodejs , golang , & git caldera:
cd caldera
python3 server.py --build 
# This will autogenerate a local.yml
# Once finished, then exit
ctrl + c

npm audit fix --force
vim  /caldera/conf/local.yml

# change all 0.0.0.0 AND localhost to your Server IP . 

vim /caldera/plugins/magma/.env
VITE_CALDERA_URL=http://SERVER-IP:8888

python3 server.py --build --fresh

cat /caldera/conf/local.yml
# find passwords to login.
```
* If you are having issues, you can delete caldera directory and git clone caldera again.
* If you made many changes, sometimes there can be build errors. This will solve that.

**Comment by t3rmin8r** [comment]
@decyphertek-io Thank you! I spent a solid day troubleshooting according to the docs. This got it working for me.
