### ISSUE TITLE
Error "Template 'index.html' not found" when connecting to localhost 

### ISSUE THREAD

**Issue by rbpn4** [mitre/caldera#2882]
Hi everyone,

I hope someone can help with this issue. Whenever I connect to the localhost via a browser I get the following error  "Template 'index.html' not found". 

Is there a place to download this from or it's something that should be created during the deployment? 

I am getting a few errors and warnings (screenshots) but I didn't think it would affect this - but I could be very wrong. Any help would be highly appreciated. 

Cheers! 

Full output:
![Screenshot 2024-02-16 112830](https://github.com/mitre/caldera/assets/157497155/f68c0d53-301c-4ec5-851c-11819dbf67c0)

update:

This is what I get in the browser when trying to access 
![image](https://github.com/mitre/caldera/assets/157497155/3e0f7e37-aa31-46d4-8fe7-45ced266fcdc)

**Comment by elegantmoose** [comment]
Are you running v5 or v4.2. (Looks like v4.2)

I also dont see any errors in the output.

**Comment by rbpn4** [comment]
> Are you running v5 or v4.2. (Looks like v4.2) 

I  think it might be v4.2. I did forget to put the '--branch x.x.x' operator and mention the version.

> I also dont see any errors in the output.

There are two on lines 14&15 and a couple of warnings but not sure what impact they have

![image](https://github.com/mitre/caldera/assets/157497155/50eac504-e5b9-4d54-a688-f7cb21f0fc21)

**Comment by elegantmoose** [comment]
Did you configure the port to be 10888 or is that typo? (Caldera's normal port is 8888)

**Comment by rbpn4** [comment]
Yes I configured it to port 1088

**Comment by elegantmoose** [comment]
Hmm, not sure what the issue is as those errors would not be causing the UI files to be missing.

Were you able to make progress? If not, I might say repull master branch and give that a try.

**Comment by rbpn4** [comment]
No... I'm still stuck with the same issue... I tried to pull it again, tried versions 5.0,4.2 and 4.0 and also in a new VM - all seem to have the same issue

**Comment by rbpn4** [comment]
Thanks for your help so far elegantmoose! I managed to resolve the issue just now. 

This is what fixed it for me:

running the following command in the caldera folder: `git submodule add https://github.com/mitre/magma`

Then running - `cd plugins/magma && npm install`

And finally - `sudo python3 server.py --build`
