### ISSUE TITLE
Cannot start ability manually

### ISSUE THREAD

**Issue by kacvinsky-tom** [mitre/caldera#2887]
**Describe the bug**
When I set the operation to require manual approval, the operation starts, but I cannot run the first ability. The status of the ability is "paused". The button "View Command" only shows the command on hovering but does nothing after I click on it (In the older version, this button showed the approval window where I could approve the command and run the ability). 

**To Reproduce**
1. Start an operation with the attribute Autonomous set to "Require manual approval".
2. Try to start the paused ability.

**Expected behavior**
There should be a button to review the command and run the ability.

**Desktop (please complete the following information):**
 - OS: Ubuntu 22.04
 - Browser: Firefox/Chromium 
 - Version: 122.0.1 (64-bit)/121.0.6167.184

This happens with the new Caldera web UI (v5.0.0).

**Comment by elegantmoose** [comment]
@kacvinsky-tom Confirmed bug. On the queue, will get to ASAP. Apologies.

**Comment by elegantmoose** [comment]
@JamieScottC For reference, started operation in manual mode, no way to change status of first link, set in "paused" state.

![Screenshot from 2024-02-20 23-04-37](https://github.com/mitre/caldera/assets/7109639/7acaa1c9-1706-4a69-8f74-16673bfb666a)
