### ISSUE TITLE
Any agents for ARM? 

### ISSUE THREAD

**Issue by koncentrat11** [mitre/caldera#2888]
I was looking to use an ARM-based OS as the agent, but deploying an agent results in:

> -bash: ./splunkd: cannot execute binary file: Exec format error

I assume this is due to the architecture not being x86_64, but do ARM agents exist?

Thanks!

**Comment by elegantmoose** [comment]
@koncentrat11 What was the command you used to drop the agent?

Did none of these work:
<img width="763" alt="Screenshot 2024-02-19 at 11 42 09 AM" src="https://github.com/mitre/caldera/assets/7109639/ba7a136c-b581-4519-82a2-bb2c706e29e5">

**Comment by elegantmoose** [comment]
Reopen if still having issues.
