### ISSUE TITLE
Operation never finishes after a link/ability has failed

### ISSUE THREAD

**Issue by stipemd** [mitre/caldera#2897]
**Describe the bug**
Sometimes when running an operations, when an ability has filed, the operation never finishes. Even after hours, its sitting in the "running" state and no new abilities run.

For my operations, I always use a "basic" fact source and the issue reoccurs (90% of time) no matter which adversary I select. I've confirmed that the agent is still checking in.

**To Reproduce**
1. Run an operation.
2. Wait for an ability to fail.

**Expected behavior**
Expected behavior is that the next ability runs even after the current one fails.

**Screenshots**
![image](https://github.com/mitre/caldera/assets/126610718/5be9dbb2-06dd-4c95-85ac-c984979b55bf)
Current time after above screenshot is 12:19 PM.

![image](https://github.com/mitre/caldera/assets/126610718/6acc539c-fac6-4a1d-817f-2dadac889fff)

![image](https://github.com/mitre/caldera/assets/126610718/33f989af-beec-46d5-aa31-0e63b0467474)

![image](https://github.com/mitre/caldera/assets/126610718/303abba3-10d0-4a5d-b902-777188d59d01)
Server logs show nothing.

**Desktop (please complete the following information):**
 - OS: RHEL 9
 - Browser: Firefox
 - Version 115.3.1 ESR

**Additional context**
n/a

**Comment by elegantmoose** [comment]
Was there more actions for the operation to execute?

If not, the operation should either finish or will stay open indefinitely depending on whether you set the operation to auto-close or not.
