### ISSUE TITLE
py2exe to build cagent

### ISSUE THREAD

**Issue by 0xebfehat** [mitre/caldera#29]
Hi, Thank your sharing great tool. 

I tried to build cagent at my side at my side, however I cannot find modified version of py2exe. 
I thought  py2exe-0.9.2.2-py3.5.egg was in CALDERA repository, but I have no luck to find it. 
Can you advise me where I can get it?

**Comment by dm-mitre** [comment]
Hi yes, the modified version is https://github.com/mitre/caldera-py2exe 
Be sure to install the Microsoft build tools 2015-2017 or Visual Studio 2015-2017 to get the appropriate C Compiler.

**Comment by 0xebfehat** [comment]
Thank you! 
I will try again.
