### ISSUE TITLE
Template 'index.html' not found

### ISSUE THREAD

**Issue by Kaide0521** [mitre/caldera#2905]
docker run -p 7010:7010 -p 7011:7011/udp -p 7012:7012 -p 8888:8888 caldera:server

then, visit http://127.0.0.1:8888 , response:  "Template 'index.html' not found"

**Comment by dougjpsantos1981** [comment]
Having the same issue here, Kali Linux  release 2024.1, mitre caldera pulled from github today.

**Comment by fxschaefer** [comment]
Having the same issue in Ubuntu 22.04LTS after installing caldera. Pulled from GitHub today.

**Comment by fxschaefer** [comment]
Hey... just found out why. Please check if you have nodejs and npm installed. Did you receive any errors when executing "python3 server.py --build" ? If so, check if it's npm related...

**Comment by elegantmoose** [comment]
@Kaide0521 @dougjpsantos1981 Any luck?
