### ISSUE TITLE
Not being able to login in when using HTTPS?

### ISSUE THREAD

**Issue by koncentrat11** [mitre/caldera#2906]
I am trying to use HTTPS instead of HTTP, and I've followed this guide: https://www.blackhillsinfosec.com/how-to-install-mitre-caldera-and-configure-your-ssl-certificate/, however when I try to access the panel at https://localhost:8443 I get to the login screen, but when I try to log in nothing happens. I can still use the HTTP just fine. Any idea?

**Comment by aut0exec** [comment]
@koncentrat11 Have you had a look [Here](https://github.com/mitre/caldera/issues/2901#issuecomment-1971807074)? Myself and others have had the same issue recently.

**Comment by elegantmoose** [comment]
@koncentrat11 Any luck?
