### ISSUE TITLE
Incomplete installation instructions

### ISSUE THREAD

**Issue by daanraman** [mitre/caldera#2908]
**Describe the bug**
The installation instructions on a fresh Ubuntu machine are incomplete

**To Reproduce**
1. Follow the 4 commands in the readme
2. The installation fails during the build phase

**Expected behavior**
A running instance :)

**Desktop (please complete the following information):**
Ubuntu 22.04.4 LTS

**Additional context**
The steps I had to take to fix it:
- Update node to the latest version (v21.6.2)

After updating node, I was able to build Caldera. However, after launch, it was impossible to login (nothing happens clicking "login").
I fixed this with information from another support ticket:

- Copy over & edit the env file in 
- Create & update plugins/magma/.env and update it with following info:
VITE_CALDERA_URL=http://<IP>:8888

After this Caldera is running great.
Thanks for all the work on this project!

**Comment by elegantmoose** [comment]
Yes we need to add it to docs. 

*We were trying to think of potential other fix that doesnt require this workaround.

Appreciate the feedback.
