### ISSUE TITLE
Untrimmed whitespaces in tab names triggers 404 error

### ISSUE THREAD

**Issue by Guil33** [mitre/caldera#2909]
**Describe the bug**
Switching from and to "fact sources" as well as "exfilled files" tab using the tab button returns a 404 error. Example below.

TLDR: looks like the issue comes from the spaces in "fact sources" and "exfilled files" not being trimmed in the URL when clicking on the corresponding tab. This does not occur when clicking on the corresponding link in the left menu.

**To Reproduce**
1. Click on "fact sources" from the "Resources" section (this opens a "tab").
2. Click on "fact sources" from the tab section.
3. Get 404 Error

**Expected behavior**
The behavior should be the same when clicking from the left menu or when clicking on the tab, i.e. going to "/factsources"

**Screenshots**
Here's what the error looks like:
![image](https://github.com/mitre/caldera/assets/71752071/f94570f5-2802-4601-9946-86f51b52ae94)

Click on "fact sources" from the left menu:
![image](https://github.com/mitre/caldera/assets/71752071/3de1be14-8937-4cd0-bdb3-815a85a7ac28)

Click on "fact sources" from the top menu (tab):
![image](https://github.com/mitre/caldera/assets/71752071/a6ad47b9-4f5d-44b2-80e7-6e17d649a2e3)

Identical behavior with "exfilled files", which is most likely coming from the space within the name.

The 4 steps in the following image are:
- red 1: Click on "fact sources" from the left menu
- green 1: Click on "agents" from the left menu
- red 2: Click on "fact sources" from the top menu (tab)
- green 2: Click on "agents" from the top menu (tab)
(Basically, the red 2 part looks abnormal to me, which is where the bug occurs).
![image](https://github.com/mitre/caldera/assets/71752071/ee3a4127-db75-448e-8043-2b363f403a4e)

**Desktop**:
- OS: Windows
- Browser: Firefox
- Version: 123.0.1

**Server**
- OS: Ubuntu Server 22.04.4
- Python: Python 3.10.12

**Comment by elegantmoose** [comment]
Looking into.
