### ISSUE TITLE
Reliance on non-static IDs for third-party abilities triggers Warnings at every startup

### ISSUE THREAD

**Issue by Guil33** [mitre/caldera#2917]
**Describe the bug**
The adversary ef4d997c-a0d1-4067-9efa-87c58682db71 ("Defense Evasion") includes abilities' IDs that no longer exist or have never existed, which triggers warnings upon booting up the server.

**Update (2024-03-28): the IDs not being found is because they are hashes of the abilities taken from the atomic repo, which may change at any time; thus changing the final IDs. A permanent fix needs to remove the reliance on the fact that a hash would be static over time. (see comment below)**

**To Reproduce**
1. Boot up the Caldera server

**Expected behavior**
The adversary should include the current and correct IDs.

**Screenshots**
Warnings at startup:
![image](https://github.com/mitre/caldera/assets/71752071/6e3e5ce4-06db-430b-917c-caa4043e3a3b)
_Don't mind the last 2 Warnings with "string" which come from a test I did at some point and forgot about_

Undefined abilities in the adversary:
![image](https://github.com/mitre/caldera/assets/71752071/b6485439-afc1-4ecc-bc5f-bf29464e0582)

**Additional context**
Although the ids no longer exist, there are very clear replacements for each missing ability (corresponding name and platform).
PR incoming for this.

**Comment by elegantmoose** [comment]
@Guil33 Might have to be a temporary fix for now unfortunately. Im not keen on keeping another versioned set of ART's abilities.
