### ISSUE TITLE
Builder plugin error upon server startup: "Error enabling plugin=builder, 'function' object has no attribute 'list'"

### ISSUE THREAD

**Issue by redAngel9012** [mitre/caldera#2922]
**Describe the bug**
I'm running Caldera on a Kali Linux 2023.4 VM (non-GUI), and I ran server.py with the --build switch, which resulted in an error with the Builder plugin: **"Error enabling plugin=builder, 'function' object has no attribute 'list'"**. I'm using Python v3.11. Running server.py without any switches still resulted in the error. The other plugins work with no issues. 

The error is then followed by saying the plugin builder is enabled. 

Navigating to the builder section in Caldera returns a blank screen. 

**To Reproduce**
1. Run **python3 server.py --build** 
2. Run **python3 server.py**

**Expected behavior**
Run python3 server.py --build and then python3 server.py with no error to the builder plugin, then see the builder view in Caldera. 

**Screenshots**
<img width="862" alt="Screenshot 2024-03-19 at 9 56 33 AM" src="https://github.com/mitre/caldera/assets/164023545/565a41db-f8ac-41ea-8df4-3d8b7b1dff6e">
<img width="1170" alt="Screenshot 2024-03-19 at 10 23 22 AM" src="https://github.com/mitre/caldera/assets/164023545/03bf52fa-195c-44c7-918f-ca9ac9186645">

**Desktop (please complete the following information):**
 - OS: macOS Sonoma 14.3.1
 - Browser: Firefox 
 - Version: 124.0 (64-bit)

**Comment by younggod69** [comment]
Hello! Try to enter in caldera/plugins/builder and run "install.sh" script and pip3 install -r requirements.txt file from builder folder. 
This solved my issues with the builder plugin.

**Comment by redAngel9012** [comment]
> Hello! Try to enter in caldera/plugins/builder and run "install.sh" script and pip3 install -r requirements.txt file from builder folder. This solved my issues with the builder plugin.

Thanks for the update. I found out why it failed after reviewing the c_python.py script, which the error was referencing (line 70). It turns out there's no "data" folder in my builder directory:

<img width="588" alt="Screenshot 2024-03-19 at 10 56 10 AM" src="https://github.com/mitre/caldera/assets/164023545/997d4643-d781-4d3e-82ed-47e1f571de62">

<img width="456" alt="Screenshot 2024-03-19 at 10 55 10 AM" src="https://github.com/mitre/caldera/assets/164023545/a77ab484-5d51-49ba-9048-f772e7cf397e">

**Comment by redAngel9012** [comment]
I re-ran the server.py script with --build, same problem.

**Comment by redAngel9012** [comment]
[debug.txt](https://github.com/mitre/caldera/files/14726168/debug.txt)
I've attached the output of the debug log. I'm not sure what else to check.

**Comment by redAngel9012** [comment]
No worries. Thanks for your help. I will try the Docker installation of Caldera and see if that works out.

**Comment by redAngel9012** [comment]
Thanks for the assistance. I'll go ahead and try the Docker installation of Caldera and see if that works out for me.
