### ISSUE TITLE
Is there a way to execute abilities only on the new agent?

### ISSUE THREAD

**Issue by kacvinsky-tom** [mitre/caldera#2923]
Hello,

I am creating an adversary profile with a bunch of abilities, which should be executed on two victim machines. 

I deploy an agent on the first one and run the operation. However, the adversary profile consists of an ability that deploys the agent on a second machine with PsExec. From that point, the planner runs abilities on both agents, but I want to use only the new one.

I've read through the documentation but couldn't find any straightforward answer to this problem. Can you suggest me some easy solution, so from that point I can only run link of abilities only on the second agent?

I thought about either killing the first agent or adding the ability right after deploying the agent, which will fail on the first machine but succeed on the other.

Thanks!

**Comment by elegantmoose** [comment]
@kacvinsky-tom Late to the party but the preferred solution here is to use a custom planner. You could essentially see what candidate actions are on the queue, filter out the actions for preferred agent, and then apply those actions to the operation.

Its not a simple solution, as you would need to write some code, but it also is not overly hard.

https://caldera.readthedocs.io/en/latest/How-to-Build-Planners.html
