### ISSUE TITLE
HTML contact point /weather does not work in 5.0.0

### ISSUE THREAD

**Issue by LwsChlds** [mitre/caldera#2932]
**Describe the bug**
The endpoint `/weather` that is used by the ragdoll agent doesn't work in the new UI

**To Reproduce**
1. Clone and build latest version
2. Open `http://localhost:8888/weather` or try and run a ragdoll agent
3. See `Template 'weather.html' not found` as a response

**Expected behavior**
The endpoint to work the same as in 4.2.0

**Desktop (please complete the following information):**
 - OS: Ubuntu 22.04
 - Browser: Chrome
 - Version: 5.0.0

**Comment by elegantmoose** [comment]
working on fix, will push soon.
