### ISSUE TITLE
signs in then loops back to sign in page whenever you click on anything else

### ISSUE THREAD

**Issue by polymorphikx** [mitre/caldera#2944]
**Describe the bug**
I have spend days trying to still the latest version 5.0 of caldera on a virtual machine on azure running Ubuntu 22.04. The farthest ive gotten has been building the docker which has allowed me to view the caldera webpage and sign in...but here is where the issue starts.

**To Reproduce**
i build the docker and run it...same issue.

**Expected behavior**
i expect for it to sign in and to function not to kick me back to the login page each and every single time i click on anything in the page after sign in. its a loop.

**Screenshots**
there is no error so screenshot wouldnt help...its the sign in page, i sign in (red:admin) then once in any link i click it just kicks me back to the sign in page.

**Desktop (please complete the following information):**
 - OS: ubuntu 22.04 on azure virtual machine
 - Browser : tried it on chrome, edge, firefox and safari
 - Version 5.0

**Additional context**
i made sure to be at all the correct versions on "Go", "Node", "Python", and anything else that was needed.

**Comment by polymorphikx** [comment]
thank you...yet, i've read that link for help top to bottom.

**Comment by Greyes904** [comment]
I am curently having the same issue and have ran it in debug mode to make sure there aren't any errors that would cause it. Did you find a solution?

**Comment by elegantmoose** [comment]
Are you doing v5.0 or Master branch?

**Comment by Greyes904** [comment]
Doing v5.0. I’ve checked all dependencies. Only one that the server won’t
seem to pick up is GoLang. I’m using 1.19 but caldera doesn’t seem to
detect it. Don’t think that should affect it though right?

**Comment by elegantmoose** [comment]
@Greyes904  We believe we fixed the login issue with https://github.com/mitre/caldera/pull/2977.

(pull master and retry)

Reopen and let us know if not.
