### ISSUE TITLE
hardcoded URL localhost:8888

### ISSUE THREAD

**Issue by elruedas-ops** [mitre/caldera#2946]
**Describe the bug**
by default all work fine. After change the bind port in conf/production.yml (my conf file):
app.contact.http: http://caldera:9999
port: 9999

when I  get http://10.0.4.6:9999/login and introduce user/pass nothing happened. If I debug the requesta made by de browser I find a js (index246d96ad.js) asking for http://localhost:8888/api/v2/config/main net::ERR_CONNECTION_REFUSED

the JS has this code inside:
let g = `${{}.VITE_CALDERA_URL || "http://localhost:8888"}/file/download_exfil?file=${btoa(v)}`
const d = (await r.get(`http://localhost:8888/plugin/${e.pluginName}/gui`)).data

I tried to find references in all files for VITE_CALDERA_URL and change all to point the port 9999. for example:
./plugins/magma/.env.template:VITE_CALDERA_URL=http://localhost:9999

**To Reproduce**
1. install in a docker following the oficial gide
2. chage the 
conf/production.yml (my conf file):
app.contact.http: http://caldera:9999
port: 9999

docker-compose.yml:
version: '3'

services:
  caldera:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        TZ: "UTC" #TZ sets timezone for ubuntu setup
        WIN_BUILD: "true" #WIN_BUILD is used to enable windows build in sandcat plugin
    image: caldera:server-v2.2
    ports:
       - "8888:8888"
       - "8443:8443"
       - "9999:9999"
      # - "7010:7010"
      # - "7011:7011/udp"
      # - "7012:7012"
      # - "8853:8853"
      # - "8022:8022"
      # - "2222:2222"
    volumes:
      #- ./:/usr/src/app
      - ./conf/production.yml:/usr/src/app/conf/production.yml
      - ./plugins/ssl/conf/haproxy.conf:/usr/src/app/plugins/ssl/conf/haproxy.conf
    command: --log DEBUG --environment production

4. docker compose build --no-cache
5. docker compose up
**Expected behavior**

**Screenshots**
![image](https://github.com/mitre/caldera/assets/77004701/af9edc77-c33e-47b4-b21b-bc35e0377579)

![image](https://github.com/mitre/caldera/assets/77004701/3753fca4-c123-4caa-8237-5bf3e690a840)

![image](https://github.com/mitre/caldera/assets/77004701/57f03af2-89e2-4192-93e2-40f465b8f318)

**Desktop (please complete the following information):**
 - OS: Ubuntu + docker (lasts versions)
 - Browser chrome
 - Version Versión 123.0.6312.122 (Build oficial) (64 bits)

**Additional context**
I think that there are certain lines hardcoded with the port 8888

**Comment by plaskur-365-bank** [comment]
solution for me:
`find . -type f -exec grep -l "http://localhost:8888" {} \; | xargs -I {} sed -i "s/http:\/\/localhost:8888/http:\/\/192.168.0.10:8888/g" {}`
