### ISSUE TITLE
FileNotFoundError: [WinError 2] Le fichier spécifié est introuvable

### ISSUE THREAD

**Issue by lastrat** [mitre/caldera#2950]
I'm having python 3.11.7

This is the error I get when I want to start Caldera on my windows PC

![image](https://github.com/mitre/caldera/assets/110492857/580c87b6-31d6-4d6c-aff7-45a699d768fb)

**Comment by elegantmoose** [comment]
We do not support Caldera server for Windows, only Linux or MacOS. (Apologies)

This error looks like a missing plugin directory but even still you may get further errors with Windows.
