### ISSUE TITLE
psh executor for Windows agent not working

### ISSUE THREAD

**Issue by clod81** [mitre/caldera#2954]
I tried both the Docker version, as well as stand alone on Ubuntu, both version 4.2.0 and 5.0.0 versions, all with the same results.

In all these setups, I get the sandcat agent connecting without any issues to the caldera server. Any ability that relies on `cmd` executor runs with no issues.

Anything that requires the `psh` feature, doesn't seem to run, and in the operation detailed result I can see: `Executor not available`.

According to the documentation (https://caldera.readthedocs.io/en/latest/Plugin-library.html#extensions) the `psh` executor should be present by default for the Windows agent.

**Comment by guillaume-duong-bib** [comment]
Can confirm that the psh executor should work by default. On what os version is your agent running?

**Comment by clod81** [comment]
windows 10, up to date

**Comment by elegantmoose** [comment]
Hmm this is a new one I dont think we have seen before. 

@deacon-mp  Have you by chance seen this on any windows operations?
