### ISSUE TITLE
Not able to login

### ISSUE THREAD

**Issue by morpheuslord** [mitre/caldera#2955]
**Describe the bug**
I had installed the tool via docker and I have taken all necessary steps to ensure it correctly installed `like using the --recursive option` but it won't go past the login screen
**To Reproduce**
Steps to reproduce the behaviour:
1. clone the repo
2. create a docker instance
3. make sure all of it is installed properly.
4. try logging in

**Expected behaviour**

I enter the password and it will log in to the user panel

**Screenshots**
https://github.com/mitre/caldera/assets/70637311/0bea5011-6cab-496e-96fb-85499ddba01a

**Desktop (please complete the following information):**
 - OS: Windows and Deployed in Kali WSL
 - Browser: Brave
 - Version: 1.65.114

**Additional context**
I tried all the suggested fixes from other issues but none worked.

**Comment by elegantmoose** [comment]
Whats the URL/IP you are using to access it?

If deploying locally, try `localhost:8888`

**Comment by morpheuslord** [comment]
I tried both 127.0.0.1 and localhost

**Comment by Jycreyn** [comment]
Hello, 

I have exactly same issue . with master or 5.0.0 same issue

**Comment by Jycreyn** [comment]
![image](https://github.com/mitre/caldera/assets/94803198/5b54ed84-b99a-4149-af0e-5ddf8cef10b0)

**Comment by morpheuslord** [comment]
hmmm shell I just shift cause I want to really try this tool 😅

**Comment by elegantmoose** [comment]
Dang, this one is hounding us. And I cant duplicate locally. Let me try to get other team members with some slack on it. 

Very sorry for the hold up!

**Comment by gent79reid** [comment]
Same issue here. 
What I have done:
* Running in WSL2 Ubuntu22.04
* install requirement.text and requirement-dev.txt

**Comment by morpheuslord** [comment]
> Same issue here. What I have done:
> 
> * Running in WSL2 Ubuntu22.04
> * git clone https://github.com/mitre/caldera.git --recursive --branch 5.0.0
> * install requirement.txt and requirement-dev.txt
> * python3 server.py --insecure --build

Yup, that is whats whats happening to all of us. Can you provide any logs or screenshots to give a better view on this from your end maybe we can determine something via that?

**Comment by elegantmoose** [comment]
@morpheuslord @gent79reid @Jycreyn We believe we fixed this issue with https://github.com/mitre/caldera/pull/2977.

Reopen issue if not the case.

*Also, DONT pull down `--branch 5.0.0`, pull down master as has all the fixes. We will mint 5.1.0 when issues stabilize.

**Comment by decyphertek-io** [comment]
Solution Using Python Method:
-----------------------------------------
I ran into a similar issue and decided to provide some more detail on how to solve the problem. 
* --insecure flag uses default.yml
*  Not using --insecure will autogenerate a local.yml
```
# first setup nodejs , golang , & git caldera:
cd caldera
python3 server.py --build 
# This will autogenerate a local.yml
# Once finished, then exit
ctrl + c

npm audit fix --force
vim  /caldera/conf/local.yml

# change all 0.0.0.0 AND localhost to your Server IP . 

vim /caldera/plugins/magma/.env
VITE_CALDERA_URL=http://SERVER-IP:8888

python3 server.py --build --fresh

cat /caldera/conf/local.yml
# find passwords to login.
```
* If you are having issues, you can delete caldera directory and git clone caldera again.
* If you made many changes, sometimes there can be build errors. This will solve that.
