### ISSUE TITLE
No review command button during empty operation Training Module

### ISSUE THREAD

**Issue by ansiballZ** [mitre/caldera#2962]
**Describe the bug**
v5.0.0
Going step by step in the empty operation solution guide, I am able to add manual commands and potential links.  However, when I click run or run link button nothing seems to happen and there is no "Review Command" button nor the ability to "Approve."

**To Reproduce**
1. Fresh install of Caldera 5.0.0 on Rocky Linux 8.7
2. Log into the web UI
3. Deployed a Sandcat agent to a Linux target 
4. Operations -> New Operation
    - Gave operation a name
    - "No Adversary" was set for Adversary
    - Fact source = basic
    - Autonomous = Require manual approval
    - Run State = Pause on start
4. Hit Start
5. Added 4 basic commands (ie whoami, ps, etc.) and 1 potential link (access passwd file)
6.  Clicked "Play"

**Expected behavior**
After clicking play, a "Review Command" button should appear and be able to approve each command

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Mac, Windows, Kali]
   Rocky Linux
   Chrome
 - Version
    5.0.0

**Additional context**

**Comment by guillaume-duong-bib** [comment]
You are right, the manual approval of links doesn't work, see #2887.
It should work if you set the operation to automatic.

**Comment by ansiballZ** [comment]
Unfortunately I am unable to test.  As soon as I create an operation and add a command it disappears

**Comment by guillaume-duong-bib** [comment]
You should probably wait for the PR (and the linked one) above and try again after. What you're explaining seems to work for me after these, a.k.a. when I add a potential link or a manual command to an empty manual operation, I am able to approve or discard them.

**Comment by ansiballZ** [comment]
I was able to apply your fix, run the --build flag and was able to get it working.  Thanks
