### ISSUE TITLE
fact_store's lifecycle?

### ISSUE THREAD

**Issue by guillaume-duong-bib** [mitre/caldera#2971]
I'm still trying to figure out #2930, and I noticed that every fact I ever created, directly through a Fact Source, or indirectly through a link's parser, is stored in `fact_store` (after some tests, only the facts that have been "loaded", e.g. through an operation, are in this case).
Even though 99% of the "sources" of these facts, i.e. either operations or Fact Sources, have been deleted since.

I see no call to `_delete_fact` from `base_knowledge_svc.py`, so it makes sense that they remain, but I would expect these facts to disappear when their source disappears, e.g. when I delete a Fact Source or an operation.

Is this a desired behavior, or an oversight? If this is desired, what are the reasons for it?

**Comment by clenk** [comment]
It looks like an oversight to me.

**Comment by guillaume-duong-bib** [comment]
Thanks for your answer.
So can I work on a PR for the issue on #2930 plus these, assuming that:
- deleting a Fact Source should delete all the facts originating from that Source from the `fact_store`? (I'll check again that they are indeed not removed already)
- deleting an operation should delete all the learned facts of that operation from the `fact_store`? (same note)

**Comment by guillaume-duong-bib** [comment]
(And while you're there, any idea on whether #2930 is a mistake on my end or indeed a bug of the same kind?)
