### ISSUE TITLE
Abilities' changes in adversaries' views are not updated consistlently, leading to potential loss

### ISSUE THREAD

**Issue by guillaume-duong-bib** [mitre/caldera#2985]
**Describe the bug**
When editing abilities from the adversaries's view, switching to and from other tabs (e.g. operations) makes the view "forget" about the changes (it's loading the same data as before the edit) and may cause an unintended override of the changes. 

**To Reproduce**
1. Go to the adversary tab and select an adversary.
2. Edit something (tests done with the command section) and save.
3. Clicking directly on the ability again, you can see the changes without issue.
4. Click on another tab, and come back to the adversary tab.
5. The adversary previously opened is still opened. Click on the edited ability: **the changes are gone.** If you edit anything (or not) and save, the changes made at **2** are overriden.

**Expected behavior**
The data at **5** should be the same as at **3**, i.e. updated with the changes. Otherwise, not being aware of this may cause the user to destroy their previous edits when switching from another tab, changing something else and then saving the ability again (which happens often in testing phases).

**Screenshots**
See the video:
https://github.com/mitre/caldera/assets/168103052/e9f29d4e-2e1c-4f4e-8e9c-fca3d73165ed

**Desktop (please complete the following information):**
 - OS: Win 10
 - Browser: Firefox 126.0

**Additional context**
It looks like clicking on the same adversary from the drop-down list makes the ability update, BUT only after another tab switch (see the video), so I am confused as to what is not loading properly:
https://github.com/mitre/caldera/assets/168103052/3ab025f9-6498-487d-a5d1-4d01025fc6c3

**Comment by timbrigham-oc** [comment]
I have seen this same behavior, Windows 11, Chrome 124
