### ISSUE TITLE
crater doesn't support Linux?

### ISSUE THREAD

**Issue by J4son** [mitre/caldera#3]
I saw build.bat in git, but seems that Linux can't use it.

**Comment by dm-mitre** [comment]
Crater might be able to be built on Linux, our current build method is on Windows with Mono, Mono is cross platform so it may work to build on Linux but we haven't tried it.

If you mean does crater run on Linux, the answer is no. The only part of CALDERA that runs on Linux is the server, the agent and crater run on Windows. We released our docs over the weekend with a lot more information about CALDERA runtime requirements and setup. Feel free to take a look at http://caldera.readthedocs.io/en/latest/

**Comment by zacoker** [comment]
Good morning, I am having some issues with setting up Caldera.

Here's the command I used:
'
sudo python36 -m pip install -r requirements.txt
'

And here's the error
`
  Running setup.py install for pyyaml ... done
  Running setup.py install for MarkupSafe ... done
  Running setup.py install for pycparser ... done
  Running setup.py install for itsdangerous ... done
  Running setup.py install for mongoengine ... done
  Running setup.py install for pyDatalog ... done
  Running setup.py install for ujson ... error
    Complete output from command /usr/bin/python3.6 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-n1_09aia/ujson/setup.py';f=getattr(                tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-5v                kfgkvm-record/install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    running build_ext
    building 'ujson' extension
    creating build
    creating build/temp.linux-x86_64-3.6
    creating build/temp.linux-x86_64-3.6/python
    creating build/temp.linux-x86_64-3.6/lib
    gcc -pthread -Wno-unused-result -Wsign-compare -DDYNAMIC_ANNOTATIONS_ENABLED=1 -DNDEBUG -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions                 -fstack-protector --param=ssp-buffer-size=4 -m64 -mtune=generic -D_GNU_SOURCE -fPIC -fwrapv -fPIC -I./python -I./lib -I/usr/include/python3.6m -c                 ./python/ujson.c -o build/temp.linux-x86_64-3.6/./python/ujson.o -D_GNU_SOURCE
    unable to execute 'gcc': No such file or directory
    error: command 'gcc' failed with exit status 1
`

I was also confused about Crater on Nix since it is listed on the server install instructions.

Thanks much!

**Comment by zacoker** [comment]
Figured it out:

sudo yum install python36-devel

**Comment by dm-mitre** [comment]
also, see #2 for precompiled crater/cagent binaries

**Comment by J4son** [comment]
@dm-mitre Uh, I think the doc should modify about system support. I can install all components except crater. I can't start caldera without crater. But you know, crater can't run in Linux. It's terrible, I waste much time on Linux.

**Comment by hf-mitre** [comment]
I've made some small updates to the documentation that hopefully make things clearer so that others don't run into the same issues. 
e5d18f0fdeb65eb21c151d5f3901f7692ef1910c 
344b2bd74262df49e251328fc3bd7125bfa05915
9ceed09f51ab9382f6ef66e2f21edd0324d440d8

**Comment by shawndwells** [comment]
Was tipped off about CALDERA, and it looks really interesting! Given how much infrastructure is Linux based, is there intention to port the agents?

**Comment by bstrom** [comment]
We're open to the idea. It would take quite a bit of work beyond an agent port to define platform specific techniques for it as well and update the logic to support them.

**Comment by dm-mitre** [comment]
@zacoker, glad you figured it out, we updated the docs to list python-dev as an install dependency for linux
