### ISSUE TITLE
Graph view errors

### ISSUE THREAD

**Issue by elegantmoose** [mitre/caldera#3004]
**Describe the bug**

Relaying from @timbrigham-oc  and this thread.
https://github.com/mitre/magma/pull/53#issuecomment-2173740794

1. Filters view of table not updating correctly to selected table.
2. Operation view not changing when selecting new operation

**To Reproduce**
1. 

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Mac, Windows, Kali]
 - Version [e.g. 2.8.0]

**Additional context**

**Comment by elegantmoose** [comment]
@timbrigham-oc  Pull this branch from Magma and let me know if works well for you.

https://github.com/mitre/magma/tree/fix/operation_filters

i.e.
```
cd caldera/plugins/magma
git fetch --all
git checkout origin fix/operation_filters
```

**Comment by timbrigham-oc** [comment]
@elegantmoose, I've merged that locally and recompiled. It looks good.
