### ISSUE TITLE
Cannot find defender profile, where should it be?

### ISSUE THREAD

**Issue by cfzq088** [mitre/caldera#3029]
Choose a defender profile
    Navigate to the Defenders page
    Select a defender from the dropdown and review abilities. The “Incident responder” defender is a good starting profile.
In getting-started.html, It was said that after logging in to Caldera blue, I can choose a defender profile, but in fact, I can not see anything about defender, the view just same as red, what's wrong with my operation? 
![image](https://github.com/user-attachments/assets/1e808743-dd1a-4da4-a2c0-4fa7a2e60c52)

**Comment by elegantmoose** [comment]
tagging @clenk

**Comment by uruwhy** [comment]
@cfzq088 can you confirm that your `response` plugin is enabled and started up successfully? That plugin contains the [incident responder profile](https://github.com/mitre/response/blob/8ea6ab5e0f341aba8facf29ba0301643e3d6a3b4/data/adversaries/7e422753-ad7a-4401-bc8b-b12a28e69c25.yml)

**Comment by elegantmoose** [comment]
reopen if need to
