### ISSUE TITLE
Caldera v5 in docker, how to enable other plugins?

### ISSUE THREAD

**Issue by zinwelzl** [mitre/caldera#3050]
Caldera v5 in docker, how to enable other plugins?
I can't see it anywhere in web GUI.
When change (in docker container) local.yml, after restart, new local.yml is created.
And if I delete local.yml, new one is created.

**Comment by zinwelzl** [comment]
I did read everything.

Anywhere is GUI I can enable plugins?

This I get when start docker
2024-09-17 11:36:22 INFO     Using main config from conf/local.yml server.py:235
2024-09-17 11:36:24 INFO     Invalid Github Gist personal API contact_gist.py:70
                             token provided. Gist C2 contact                    
                             will not be started.                               
                    INFO     Generating temporary SSH private   tunnel_ssh.py:26
                             key. Was unable to use provided                    
                             SSH private key                                    
                    INFO     Creating SSH listener on 0.0.0.0,     logging.py:92
                             port 8022                                          
                    INFO     Enabled plugin: access               app_svc.py:116
                    ERROR    Error importing plugin=builder, No   c_plugin.py:91
                             module named 'docker'                              
                    ERROR    Error loading plugin=builder,        c_plugin.py:59
                             'NoneType' object has no attribute                 
                             'description'                                      
                    INFO     Enabled plugin: compass              app_svc.py:116
                    INFO     Enabled plugin: debrief              app_svc.py:116
                    INFO     Enabled plugin: fieldmanual          app_svc.py:116
                    INFO     Enabled plugin: magma                app_svc.py:116
                    INFO     Enabled plugin: manx                 app_svc.py:116
                    INFO     Enabled plugin: response             app_svc.py:116
                    INFO     Enabled plugin: sandcat              app_svc.py:116
                    INFO     Enabled plugin: stockpile            app_svc.py:116
                    INFO     Enabled plugin: training             app_svc.py:116
                    INFO     serving on 0.0.0.0:2222               server.py:741
                    WARNING  Unable to properly load .donut for  data_svc.py:436
                             payload                                            
                             plugins.stockpile.app.donut.donut_h                
                             andler due to failed import                        
2024-09-17 11:36:25 WARNING  upx does not meet the minimum        app_svc.py:171
                             version of 0.0.0. Upx is an optional               
                             dependency which adds more                         
                             functionality.                                     
2024-09-17 11:36:34 WARNING  Ability referenced in adversary   c_adversary.py:90
                             ef4d997c-a0d1-4067-9efa-87c58682d                  
                             b71 but not found:                                 
                             df94858e92a23d274ac1d70133d9150f                   
                    WARNING  Ability referenced in adversary   c_adversary.py:90
                             ef4d997c-a0d1-4067-9efa-87c58682d                  
                             b71 but not found:                                 
                             06d6ac81dae5c0f49dd3d5641eb2c81e                   
                    WARNING  Ability referenced in adversary   c_adversary.py:90
                             ef4d997c-a0d1-4067-9efa-87c58682d                  
                             b71 but not found:                                 
                             5b93df032e230056c21a3e57334f77d1                   
                    WARNING  Ability referenced in adversary   c_adversary.py:90
                             ef4d997c-a0d1-4067-9efa-87c58682d                  
                             b71 but not found:                                 
                             20277ce46ffe7d08083f8b5ca524b317                   
                    WARNING  Ability referenced in adversary   c_adversary.py:90
                             ef4d997c-a0d1-4067-9efa-87c58682d                  
                             b71 but not found:                                 
                             0424ccb447bfa66b94162266f55ecd52                   
                    WARNING  Ability referenced in adversary   c_adversary.py:90
                             ef4d997c-a0d1-4067-9efa-87c58682d                  
                             b71 but not found:                                 
                             2f32a5c66db68b291469a3ab49be9261                   
                    WARNING  Ability referenced in adversary   c_adversary.py:90
                             ef4d997c-a0d1-4067-9efa-87c58682d                  
                             b71 but not found:                                 
                             f1222384fe40cc71e7dea9d182014eaf                   
                    WARNING  Ability referenced in adversary   c_adversary.py:90
                             ef4d997c-a0d1-4067-9efa-87c58682d                  
                             b71 but not found:                                 
                             d9c1b1283c1ad6fdda27be021c4737d3                   
                    WARNING  Ability referenced in adversary   c_adversary.py:90
                             ef4d997c-a0d1-4067-9efa-87c58682d                  
                             b71 but not found:                                 
                             9d2e91b9241ae43b517be2be98bddfd9                   
                    WARNING  Ability referenced in adversary   c_adversary.py:90
                             ef4d997c-a0d1-4067-9efa-87c58682d                  
                             b71 but not found:                                 
                             dedfa0a54c9c13ce5714a0dc2e1f5d1a                   
                    WARNING  Ability referenced in adversary   c_adversary.py:90
                             ef4d997c-a0d1-4067-9efa-87c58682d                  
                             b71 but not found:                                 
                             18348573c1f989a6cca9e9bf10809700                   
                    WARNING  Ability referenced in adversary   c_adversary.py:90
                             ef4d997c-a0d1-4067-9efa-87c58682d                  
                             b71 but not found:                                 
                             a9c0234156994cab384418b43da52da4                   
                    WARNING  Ability referenced in adversary   c_adversary.py:90
                             ef4d997c-a0d1-4067-9efa-87c58682d                  
                             b71 but not found:                                 
                             d5ac8f5ec45224dc36453a9490845f23                   
                    WARNING  Ability referenced in adversary   c_adversary.py:90
                             ef4d997c-a0d1-4067-9efa-87c58682d                  
                             b71 but not found:                                 
                             80e752c5fc69a56ccb86bc90efc5eff6                   
                    WARNING  Ability referenced in adversary   c_adversary.py:90
                             ef4d997c-a0d1-4067-9efa-87c58682d                  
                             b71 but not found:                                 
                             8478297ebb155b34c412a0fde335eccd                   
                    WARNING  Ability referenced in adversary   c_adversary.py:90
                             ef4d997c-a0d1-4067-9efa-87c58682d                  
                             b71 but not found:                                 
                             683115a2ceeb045e6ffbf4487322b220                   
                    WARNING  Ability referenced in adversary   c_adversary.py:90
                             ef4d997c-a0d1-4067-9efa-87c58682d                  
                             b71 but not found:                                 
                             8a60db80ab6f4a6b1db758c95bacfafa                   
                    WARNING  Ability referenced in adversary   c_adversary.py:90
                             ef4d997c-a0d1-4067-9efa-87c58682d                  
                             b71 but not found:                                 
                             0aaebed766f7120873d5ad90c23355f8                   
                    WARNING  Ability referenced in adversary   c_adversary.py:90
                             ef4d997c-a0d1-4067-9efa-87c58682d                  
                             b71 but not found:                                 
                             854e480af3b5e2946bb3ae44916e951a                   
                    WARNING  Ability referenced in adversary   c_adversary.py:90
                             ef4d997c-a0d1-4067-9efa-87c58682d                  
                             b71 but not found:                                 
                             2929fac2296bf1041ba33c86d42d9a5a                   
                    WARNING  Ability referenced in adversary   c_adversary.py:90
                             ef4d997c-a0d1-4067-9efa-87c58682d                  
                             b71 but not found:                                 
                             c8e46a29cac614806da56b0be6b0e454                   
                    WARNING  Ability referenced in adversary   c_adversary.py:90
                             ef4d997c-a0d1-4067-9efa-87c58682d                  
                             b71 but not found:                                 
                             6401e9fc7007569199a38703f0aa0f0f                   
                    WARNING  Ability referenced in adversary   c_adversary.py:90
                             ef4d997c-a0d1-4067-9efa-87c58682d                  
                             b71 but not found:                                 
                             8e7c28877a9c7826fece190f185b534c                   
                    WARNING  Ability referenced in adversary   c_adversary.py:90
                             ef4d997c-a0d1-4067-9efa-87c58682d                  
                             b71 but not found:                                 
                             23dafb943f2f1a3e21e8204826c7b271                   
                    WARNING  Ability referenced in adversary   c_adversary.py:90
                             ef4d997c-a0d1-4067-9efa-87c58682d                  
                             b71 but not found:                                 
                             379509c4b83f252bc779446f0512e936                   
                    WARNING  Ability referenced in adversary   c_adversary.py:90
                             ef4d997c-a0d1-4067-9efa-87c58682d                  
                             b71 but not found:                                 
                             80be956df11e4a384333150807c3ccd9                   
                    WARNING  Ability referenced in adversary   c_adversary.py:90
                             ef4d997c-a0d1-4067-9efa-87c58682d                  
                             b71 but not found:                                 
                             d38cba2905e62b4c1a7e5c88137ce485                   
                    WARNING  Ability referenced in adversary   c_adversary.py:90
                             ef4d997c-a0d1-4067-9efa-87c58682d                  
                             b71 but not found:                                 
                             326a9797b0d59b8f6d5a3c384c564b9f                   
                    WARNING  Ability referenced in adversary   c_adversary.py:90
                             ef4d997c-a0d1-4067-9efa-87c58682d                  
                             b71 but not found:                                 
                             5ffa5b3b330848d39dc1728365dad61c                   
                    WARNING  Ability referenced in adversary   c_adversary.py:90
                             ef4d997c-a0d1-4067-9efa-87c58682d                  
                             b71 but not found:                                 
                             db8c6ba84f796a2f1fa1497b8dc1aae2                   
                    WARNING  Ability referenced in adversary   c_adversary.py:90
                             ef4d997c-a0d1-4067-9efa-87c58682d                  
                             b71 but not found:                                 
                             4d4b29abb6b1e580e33c0035c1fc37ad                   
                    WARNING  Ability referenced in adversary   c_adversary.py:90
                             ef4d997c-a0d1-4067-9efa-87c58682d                  
                             b71 but not found:                                 
                             93127a8c6cdb05fd84f871a5faa9d7c7                   
                    INFO     Docs built successfully.                 hook.py:58
2024-09-17 11:36:35 INFO     All systems ready.                    server.py:104

 ██████╗ █████╗ ██╗     ██████╗ ███████╗██████╗  █████╗
██╔════╝██╔══██╗██║     ██╔══██╗██╔════╝██╔══██╗██╔══██╗
██║     ███████║██║     ██║  ██║█████╗  ██████╔╝███████║
██║     ██╔══██║██║     ██║  ██║██╔══╝  ██╔══██╗██╔══██║
╚██████╗██║  ██║███████╗██████╔╝███████╗██║  ██║██║  ██║
 ╚═════╝╚═╝  ╚═╝╚══════╝╚═════╝ ╚══════╝╚═╝  ╚═╝╚═╝  ╚═╝

**Comment by uruwhy** [comment]
If you're editing the config yml file, any edits must be done when the CALDERA server is not running. When the server is shut down, settings are saved to the config file, which would overwrite any edits you just made. Stop the server, make whatever changes you want to the configuration (adding/removing plugins), and restart the server. You should be good to go from there

**Comment by zinwelzl** [comment]
How to stop caldera server inside running docker container and not stop docker caldera container?

**Comment by elegantmoose** [comment]
Do you mean like getting command line access to docker container? (i.e. https://stackoverflow.com/questions/30172605/how-do-i-get-into-a-docker-containers-shell)

**Comment by zinwelzl** [comment]
i know how to get shell in docker container, but then can't stop caldera
whatever i try it doesn't work
id you know how to do this

**Comment by zinwelzl** [comment]
ok, i will try.
but i now have local installation, no docker.
