### ISSUE TITLE
Adversary payload folder missing

### ISSUE THREAD

**Issue by wietze** [mitre/caldera#309]
In commit 816e8a4af53848d067ad333c3bbd64fdc4e1ef67 the `plugins/adversary/payloads` payload folder was removed from `conf/local.yaml`, which means that any requests to `/file/download` won't check this directory anymore.

The Adversary plugin needs this directory to be present for the [Install-Agent.ps1](https://github.com/mitre/adversary/blob/master/templates/Install-Cagent.ps1#L7) file: it throws ambiguous errors when the line 
```
- plugins/adversary/payloads
```
is missing from the config file. 

Now that the Adversary plugin is disabled by default, I'd suggest either enabling the plugin will somehow automatically add the above folder to the search path, a warning is displayed next to the PowerShell script in the web interface, or the script itself gives a more meaningful error.

**Comment by privateducky** [comment]
agreed. I just made the change to auto-fill in the payloads directory for every plugin that has one, negating the need to define them in local.yml. let me know if that works for you.

**Comment by wietze** [comment]
That worked, good solution. Thanks
