### ISSUE TITLE
Installation instructions don't work - pip

### ISSUE THREAD

**Issue by workandresearchgithub** [mitre/caldera#315]
I've installed CentOs 7.x, and then installed python 3.6, including python pip:
--
yum -y install python36.x86_64 python36-devel.x86_64 python36-pip.noarch 
--

[root@localhost caldera]# pwd
/opt/caldera
[root@localhost caldera]# ls
app  conf  docker-compose.yml  LICENSE  logs  plugins  README.md  requirements.txt  server.py  tests
[root@localhost caldera]# pip install -r requirements.txt
-bash: pip: command not found

What is missing?

**Comment by workandresearchgithub** [comment]
Ok...did some googling and found this seems to get things going:
--
python3.6  -m pip install -r requirements.txt
--

However, it leads to another error as it doesn't complete successfully:
--
    unable to execute 'gcc': No such file or directory
    error: command 'gcc' failed with exit status 1

    ----------------------------------------
Command "/usr/bin/python3.6 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-kf5rp809/cryptography/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-vinmn140-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-build-kf5rp809/cryptography/
You are using pip version 8.1.2, however version 19.1.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
--

Are you expecting the folks who install this to have Python developer experience and knowledge?
If so, please let the reader know that up front.

**Comment by workandresearchgithub** [comment]
ok, so I installed gcc (also not listed in your requirements):
--
yum install gcc.x86_64
--

Now I'm getting this error:
--
gcc -pthread -Wno-unused-result -Wsign-compare -DDYNAMIC_ANNOTATIONS_ENABLED=1 -DNDEBUG -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic -D_GNU_SOURCE -fPIC -fwrapv -fPIC -I/usr/include/python3.6m -c build/temp.linux-x86_64-3.6/_openssl.c -o build/temp.linux-x86_64-3.6/build/temp.linux-x86_64-3.6/_openssl.o -Wconversion -Wno-error=sign-conversion
    build/temp.linux-x86_64-3.6/_openssl.c:498:30: fatal error: openssl/opensslv.h: No such file or directory
     #include <openssl/opensslv.h>
--

It appears to also require openssl?

**Comment by workandresearchgithub** [comment]
Looks like it's already there:
--
# yum install openssl.x86_64
Loaded plugins: fastestmirror
Loading mirror speeds from cached hostfile
 * base: repo.ialab.dsu.edu
 * epel: fedora-epel.mirrors.tds.net
 * extras: repo.ialab.dsu.edu
 * updates: repo.ialab.dsu.edu
Package 1:openssl-1.0.2k-16.el7_6.1.x86_64 already installed and latest version
Nothing to do
--

Maybe it needs an openssl development environment?

**Comment by workandresearchgithub** [comment]
well, installing the ssl development package seems to have addressed the issue:
--
yum install openssl-devel.x86_64
--

Output of python3.6 -m pip install -r requirements.txt
--

Installing collected packages: cryptography
  Running setup.py install for cryptography ... done
Successfully installed cryptography-2.3.1
--

Now all I should have to do to get things working is run this, correct?:
--
python server.py
--

**Comment by workandresearchgithub** [comment]
Once again, something appears to be missing here:
--
# python server.py
  File "server.py", line 23
    async def background_tasks(app):
            ^
SyntaxError: invalid syntax
--

maybe if I change it to python3.6?
--
# python3.6 server.py
DEBUG:root:Loading plugin: stockpile
DEBUG:root:Loading plugin: sandcat
DEBUG:root:Loading plugin: gui
DEBUG:root:Loading plugin: chain
DEBUG:root:Uploaded files will be put in /tmp
DEBUG:root:Serving at http://127.0.0.1:8888
--

Hey, success !

So I'm curious...is the incomplete documentation meant to be some type of test?
i.e. "only the worthy shall pass" or perhaps, "only those who persist are granted entry to the club"  ?

**Comment by privateducky** [comment]
Looks like you worked your way through it!

No, this is not a test. Depending on your operating system, especially some basic/light versions of CentOS, there could be extra dependencies as you saw. The main ones revolve around if Python 3 is installed in the OS by default - or if your OS requires you to compile/install Python from some external repository (as you saw in your CentOS 7 build).

The README instructions for CALDERA will work out of the box for:

- Any Ubuntu version 16.04+ (probably 12.04 as well, just untested)
- Any modern MacOS
- Most Raspberry Pi builds
- Most Debian builds

Because there is such a variance of operating systems (just on Linux alone!) our instructions assume Python 3.5.3+ is installed by default on the operating system. I think recording installation instructions for other more minimal builds would be great though - if you can package up instructions in a way that we can post them in our Wiki section, let me know and I'd be happy to add them (and credit you). 

Welcome to CALDERA!

**Comment by workandresearchgithub** [comment]
Will this work?
--
[Caldera 0.X.0 - Installation.docx](https://github.com/mitre/caldera/files/3414991/Caldera.0.X.0.-.Installation.docx)

--

**Comment by privateducky** [comment]
Yes; that looks good. If you write this in Markdown, I'll get it uploaded ASAP otherwise I'll ensure one of developers formats it in Markdown in the next few days. Thanks!

**Comment by mikeyijdskfhsd** [comment]
FYI: I had issues with a missing function when using Python 3.5  and adversary (the datetime module didn't have fromisoformat). Using Python 3.7 fixed this.

**Comment by Ramikan** [comment]
Install pip3 and then use pip3 install -r requirements.txt

**Comment by 12306Bro** [comment]
File "server.py", line 25
    async def background_tasks(app):
            ^
SyntaxError: invalid syntax

Why does this happen?
Referring to the suggestion of workandresearchgithub, I solved this problem using python3.7 server.py.
DEBUG:root:Loading plugin: stockpile
DEBUG:root:Loading plugin: sandcat
DEBUG:root:Loading plugin: gui
DEBUG:root:Loading plugin: chain
