### ISSUE TITLE
API Documentation

### ISSUE THREAD

**Issue by SpaceAether** [mitre/caldera#33]
Hello,
First of all congratulation for this great tool, I'm just scratching the surface of it but it seems promising.
I wanted to know if you plan on releasing the API documentation soon because I was beginning to take a look at it to play with but without the documentation it make it a bit more complicated to understand.
Thanks in advance for the answer

**Comment by dm-mitre** [comment]
Hi, have you seen our documentation here: https://caldera.readthedocs.io/en/latest/index.html
Anything that we have documented will show up there.

**Comment by SpaceAether** [comment]
Yes, I have seen it, but the last parts about the API (Planner API and Operation API) are empty and I'm wondering if you plan on filling these blanks in the near future.

**Comment by hf-mitre** [comment]
If you're interested in controlling CALDERA HTTP this may be closer to what you're looking for https://github.com/mitre/caldera/blob/master/caldera/api.md .  That's actually a very dated file that we should update and make part of the actual docs site.  For now, you might be better off just looking at https://github.com/mitre/caldera/blob/master/caldera/app/api.py .

**Comment by hf-mitre** [comment]
For adding new techniques and getting familiar with the internals, this is probably the best resource we have right now https://caldera.readthedocs.io/en/latest/add_technique.html .

**Comment by SpaceAether** [comment]
Thanks for these files, I hadn't seen https://github.com/mitre/caldera/blob/master/caldera/api.md before, and for https://github.com/mitre/caldera/blob/master/caldera/app/api.py, it is the one I was looking to understand it but you are right, you should make it a part of the docs site, it would be easier to browse.
