### ISSUE TITLE
introduction of "private" facts

### ISSUE THREAD

**Issue by EmilioPanti** [mitre/caldera#332]
I would like to know if an introduction of "private" facts is envisaged, whose collection during an operation does not end up in the "global" knowledge available to all the agents of this operation but which is usable exclusively from the collector agent

**Comment by wbooth** [comment]
We don't have anything for private facts in the roadmap at the moment. There is currently a higher score given for facts collected together, but nothing is exclusive. We have just given facts a priority ranking/score. We are absolutely open to this idea and we welcome a pr if you want to submit something
