### ISSUE TITLE
Get Adversary Data/Techniques on Client Side

### ISSUE THREAD

**Issue by paulsimvient** [mitre/caldera#349]
is there a way to get Adversary Data/Techniques on Client Side?  Would that come through the agent?

**Comment by privateducky** [comment]
yep; so "links" are sent to the agents during an operation. each link contains a command, a cleanup command, a payload name and a link_id. The agent receives this "link" and runs the command.

**Comment by paulsimvient** [comment]
Outstanding thank you. I’ll give it a try tonight.

**Comment by paulsimvient** [comment]
Hi David,

Let me tell you what I'm interested in doing. I'd like to try using the
basic framework for a training exercise but this will all occur within a
simulated environment so I don't actually need to execute the commands,
only to know what they are and simulate the attack. Given this, is there a
fairly easy way to simply say "Here's what this particular agent is doing..
i.e. here's the action".  I see this running on the server (see below) but
not on the client side. I'd like to see where I can pull this information
in text/json or equivalent format so each trainee can be tested on what to
do next. Make sense?

Host #1... Identify active user⤓★
Description:

Find user running agent
Technique:
T1033
Collected:

2019-08-06 16:12:09
Finished:

2019-08-06 16:12:09
Command:

whoami

**Comment by privateducky** [comment]
i think i see what you're looking for: from the agent, you want to see what commands are sent to it.

if that's right, you can go into plugins/sandcat/gocat/execute/execute.go (this is the module of code that the agent actually executes per command). You can append a log line in the function in this module, which would log the command to the agent's terminal (you could log or write to a JSON file, etc). 

If you simply want to view/log the command, the execute.go module would look like (note the changes):
```
package execute

import (
    "fmt"
	"runtime"
	"os/exec"
)

// Execute runs a shell command
func Execute(command string) ([]byte, error) {
    fmt.Println(command)
	if runtime.GOOS == "windows" {
		return exec.Command("powershell.exe", "-ExecutionPolicy", "Bypass", "-C", command).CombinedOutput()
	}
	return exec.Command("sh", "-c", command).CombinedOutput()
}
```

**Comment by privateducky** [comment]
Keep in mind, if you change agent code, you'll need to ensure that GoLang is installed on the same machine as the CALDERA server. This is because - if GoLang is installed - the agent code will be compiled in real-time every time it is downloaded.

**Comment by paulsimvient** [comment]
Thanks kindly David - let me check in to that and get back to you.

Very very much appreciated!!

Paul

**Comment by paulsimvient** [comment]
Oh I meant to ask you - am I working from Caldera 2.0?

And how would you rate this compared to let's say the SimSpace system
that's using MIT's LARIAT.

(For the record I'm really enjoying Caldera!!!)

Paul

**Comment by privateducky** [comment]
yes-- if you're using the bleeding-edge (latest master code) you're using CALDERA 2.x. You can alternatively download one of the release versions (from the GitHub releases tab) to get a stable copy of version 2.0, 2.1 or 2.2 (2.3 is being cut soon). 

per SimSpace; I'm familiar with that product but haven't used it. From what I know: we have a similar goal of simulating realistic threats.
