### ISSUE TITLE
ERR_CONNECTION_REFUSED

### ISSUE THREAD

**Issue by etemcitil** [mitre/caldera#350]
As we can see below everything looks working but i am not able to first display the caldera gui from remote host in same network.
I have disabled firewalld on server.

from local host
 wget http://127.0.0.1:8888
--2019-08-02 21:44:12--  http://127.0.0.1:8888/
Connecting to 127.0.0.1:8888... connected.
HTTP request sent, awaiting response... 302 Found
Location: /login [following]
--2019-08-02 21:44:12--  http://127.0.0.1:8888/login
Reusing existing connection to 127.0.0.1:8888.
HTTP request sent, awaiting response... 401 Unauthorized
Authorization failed.

from remote host,
telnet 192.168.140.135 8888
Connecting To 192.168.140.135...Could not open connection to the host, on port 8888: Connect failed

i can see my syn packet from server it doesnt look connection issue.

 python server.py
DEBUG:root:Loading plugin: stockpile
DEBUG:root:Loading plugin: sandcat
DEBUG:root:Loading plugin: gui
DEBUG:root:Loading plugin: chain
DEBUG:root:Using an in-memory database: True
DEBUG:root:Uploaded files will be put in /tmp
DEBUG:file_svc:Downloaded files will come from ['plugins/stockpile/payloads', 'plugins/sandcat/payloads']
DEBUG:root:Serving at http://127.0.0.1:8888

**Comment by privateducky** [comment]
you'll need to update the conf/local.yml to use 0.0.0.0 instead of 127.0.0.1.

This wiki page is a good one to ensure you grasp: https://github.com/mitre/caldera/wiki/The-local.yml-file
