### ISSUE TITLE
Error while trying to load caldera

### ISSUE THREAD

**Issue by Doron-droid** [mitre/caldera#353]
I've pulled the latest Caldera changes, and now I got the following error while trying to run server.py:

Traceback (most recent call last):
  File "server.py", line 100, in <module>
    main(services=services, host=cfg['host'], port=cfg['port'], users=cfg['users'])
  File "server.py", line 65, in main
    loop.run_until_complete(init(host, port, services, users))
  File "/usr/lib/python3.6/asyncio/base_events.py", line 484, in run_until_complete
    return future.result()
  File "server.py", line 57, in init
    await attach_plugins(app, services)
  File "server.py", line 42, in attach_plugins
    await plugin(app, services)
  File "/home/ubuntu/caldera/plugins/stockpile/hook.py", line 8, in initialize
    await data_svc.reload_database(adversaries='plugins/stockpile/adversaries.yml',
AttributeError: 'DataService' object has no attribute 'reload_database'

any idea?

**Comment by privateducky** [comment]
Yep-- this is due to plugins getting updated, so the core code is out of sync with the plugins. You can either go through each plugin (and core code) and do a hard/reset git pull - or just reclone the caldera repository from scratch.

**Comment by Doron-droid** [comment]
magic thank you

**Comment by Doron-droid** [comment]
I re-cloned the repository from scratch and added abilities facts and adversaries. the service is up and running but I cannot run operations from the gut, the "start" button just stops from working.

Any idea what could be the reason?

**Comment by privateducky** [comment]
I just did a sanity check on the latest code & can't reproduce that issue. 

from the debug message you posted though, my guess is you're running the server in a VM or have swapped the local.yml IP address to a local IP address on your network. 

I would start by running the server under the default IP (127.0.0.1) or swap it to all interfaces (0.0.0.0). When you select a specific IP address on your network (like 172.21.0.10) the NAT/network could require some tweaking.

**Comment by Doron-droid** [comment]
Thanks for the help, it was configured for all interfaces. I changed it to default IP and then back to all interfaces and it somehow worked.

Thanks a lot

**Comment by privateducky** [comment]
no problem!
