### ISSUE TITLE
Troublesome Error in Version 1.6.2! After Update, the Conditions in Auto Responder are Blank!

### ISSUE THREAD

**Issue by black-eye** [mitre/caldera#36]
The title says it all.

After rollback to v 1.6.1.1 everything is back to normal. But you've lost most of the settings if you saved the form in the meantime. If you haven't saved the template in v 1.6.2, the settings seems to be back completely.

Not sure, wheather the condition actualy worked on fontend (until saving the form, it might be just UI problem). Didn't have the nerve to test it more, it happened to me on live site.

BTW: not sure, what version it actually is: the changelog says 1.6.2, WP says 1.6.3.

**Comment by dm-mitre** [comment]
Hi @black-eye we think you may have meant to post here: https://github.com/CalderaWP/Caldera-Forms

**Comment by black-eye** [comment]
Oh, I'm sorry, wrong Caldera! 
I should have paid more attention where I post - I was actually bit surprised there are so little issues here... ;)
Please close the issue. Thanks.
