### ISSUE TITLE
Creating new adversaries in the GUI

### ISSUE THREAD

**Issue by tobesr** [mitre/caldera#368]
Hi,

Might be me missing something, but I can't seem to create Adversaries in the GUI / Chain at the moment - the slider button is missing?  Used to work, but not with the latest code. I can create them fine in the folder. I have included a screenshot to help.

![VirtualBox_Caldera server_13_08_2019_14_59_36](https://user-images.githubusercontent.com/54070629/62947871-2f443f00-bddb-11e9-89db-161deeefb770.png)

**Comment by privateducky** [comment]
creating adversaries can be done by selecting an existing adversary and cloning it ('save new'). I'd like to re-add a "create" button which is more explicit but haven't gotten around to it (hint, hint, if you want to give it a shot!)

**Comment by tobesr** [comment]
I'll take a look (not great at js / html but we shall see) - you got any of the old code for me to use as a start? / a plan of how you want it to look / work?

**Comment by privateducky** [comment]
yeah, the toggle button would look good/consistent. no special look though-- as long as it's functional and the code is (relatively) clean, I'm all ears.

one place to look: when you "clone" an existing adversary (by viewing one and clicking "save as"). you should be able to piggyback on this logic, so it should be a pretty minimal change -- only touching chain.html and sections.js files.

**Comment by tobesr** [comment]
Got some work done this afternoon on it - couple of little bugs to work out but getting there.

Can I be added as a collaborator so I can create a branch for it? or is there a better easier way - yes I am a Github novice!

**Comment by privateducky** [comment]
sounds great! the easiest way would be to fork the project (chain) and submit a pull request from there. let me know if you have questions along the way (even simple ones)!

**Comment by tobesr** [comment]
Pull request done.... Hopefully correctly!

**Comment by privateducky** [comment]
great work! I just reviewed the code-- it looks pretty clean, just a handful of small fixes to put in place.

**Comment by privateducky** [comment]
I just took your PR and adjusted a few things I had commented on and bundled it into a change I just merged into the code base. adding adversaries is now explicit - let me know of any questions/comments and thanks for your help!
