### ISSUE TITLE
server.py and '_sqlite3'

### ISSUE THREAD

**Issue by Reakt1** [mitre/caldera#372]
Fresh Ubuntu 16.04LTS
Fully updated,
Got there Python3.7.4 installed,
Pip did his magic and done all requirements, but when I try to start server.py 
`$ python3.7 server.py`
I get this error :

> Traceback (most recent call last):
>   File "server.py", line 14, in <module>
>     from app.database.core_dao import CoreDao
>   File "/home/lokalac/caldera/app/database/core_dao.py", line 1, in <module>
>     from app.database.memory import Memory
>   File "/home/lokalac/caldera/app/database/memory.py", line 1, in <module>
>     import sqlite3
>   File "/usr/local/lib/python3.7/sqlite3/__init__.py", line 23, in <module>
>     from sqlite3.dbapi2 import *
>   File "/usr/local/lib/python3.7/sqlite3/dbapi2.py", line 27, in <module>
>     from _sqlite3 import *
> ModuleNotFoundError: No module named '_sqlite3'

Any help and suggestions are welcome, 
Thank you.

**Comment by privateducky** [comment]
closing, as answer should do the trick. please re-open if it doesn't.
