### ISSUE TITLE
Caldera-Agent Missing Module: multiprocessing.SimpleQueue

### ISSUE THREAD

**Issue by jpsec** [mitre/caldera#4]
Windows 10 64 Bit, Same Problem on Win7 64 Bit
Py2Exe cannot find module multiprocessing.SimpleQueue

Totally clueless after hours of search :(
Will now try with Win 8.1 :(

PS C:\Users\Mallory\caldera-agent\caldera_agent> .\make.bat

C:\Users\Mallory\caldera-agent\caldera_agent>python setup.py clean --all
running clean
removing 'build\temp.win-amd64-3.5' (and everything under it)
removing 'build\lib.win-amd64-3.5' (and everything under it)
'build\bdist.win-amd64' does not exist -- can't clean it
'build\scripts-3.5' does not exist -- can't clean it
removing 'build'

C:\Users\Mallory\caldera-agent\caldera_agent>del _foster3*.pyd

C:\Users\Mallory\caldera-agent\caldera_agent>python setup.py build_ext --inplace
running build_ext
building '_foster3' extension
creating build
creating build\temp.win-amd64-3.5
creating build\temp.win-amd64-3.5\Release
C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\x86_amd64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -IC:\Use
rs\Mallory\AppData\Local\Programs\Python\Python35\include -IC:\Users\Mallory\AppData\Local\Programs\Python\Python35\incl
ude "-IC:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\INCLUDE" "-IC:\Program Files (x86)\Windows Kits\10\include
\10.0.10240.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\8.1\include\shared" "-IC:\Program Files (x86)\Windows Kits\8.
1\include\um" "-IC:\Program Files (x86)\Windows Kits\8.1\include\winrt" /Tc_foster3.c /Fobuild\temp.win-amd64-3.5\Releas
e\_foster3.obj
_foster3.c
_foster3.c(326): warning C4133: 'function': incompatible types - from 'STARTUPINFOEXW *' to 'LPSTARTUPINFOW'
_foster3.c(495): warning C4133: 'function': incompatible types - from 'STARTUPINFOEXW *' to 'LPSTARTUPINFOW'
creating C:\Users\Mallory\caldera-agent\caldera_agent\build\lib.win-amd64-3.5
C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\x86_amd64\link.exe /nologo /INCREMENTAL:NO /LTCG /DLL /MANIFE
ST:EMBED,ID=2 /MANIFESTUAC:NO /LIBPATH:C:\Users\Mallory\AppData\Local\Programs\Python\Python35\libs /LIBPATH:C:\Users\Ma
llory\AppData\Local\Programs\Python\Python35\PCbuild\amd64 "/LIBPATH:C:\Program Files (x86)\Microsoft Visual Studio 14.0
\VC\LIB\amd64" "/LIBPATH:C:\Program Files (x86)\Windows Kits\10\lib\10.0.10240.0\ucrt\x64" "/LIBPATH:C:\Program Files (x
86)\Windows Kits\8.1\lib\winv6.3\um\x64" advapi32.lib /EXPORT:PyInit__foster3 build\temp.win-amd64-3.5\Release\_foster3.
obj /OUT:build\lib.win-amd64-3.5\_foster3.cp35-win_amd64.pyd /IMPLIB:build\temp.win-amd64-3.5\Release\_foster3.cp35-win_
amd64.lib
_foster3.obj : warning LNK4197: export 'PyInit__foster3' specified multiple times; using first specification
   Creating library build\temp.win-amd64-3.5\Release\_foster3.cp35-win_amd64.lib and object build\temp.win-amd64-3.5\Rel
ease\_foster3.cp35-win_amd64.exp
Generating code
c:\users\mallory\caldera-agent\caldera_agent\_foster3.c(564) : warning C4700: uninitialized local variable 'target_handl
e' used
Finished generating code
copying build\lib.win-amd64-3.5\_foster3.cp35-win_amd64.pyd ->

C:\Users\Mallory\caldera-agent\caldera_agent>python setup.py py2exe
Building self-contained .exe
running py2exe
running build_ext

  1 missing Modules
  ------------------
? multiprocessing.SimpleQueue         imported from concurrent.futures.process
Building 'dist\cagent.exe'.
Copy DLL C:\Users\Mallory\AppData\Local\Programs\Python\Python35\VCRUNTIME140.dll to dist
PS C:\Users\Mallory\caldera-agent\caldera_agent> python -V
Python 3.5.4
PS C:\Users\Mallory\caldera-agent\caldera_agent>

**Comment by hf-mitre** [comment]
@jpsec I'm going to try to reproduce this. First though, can I ask if you are installing py2exe from PyPI or from our fork https://github.com/mitre/caldera-py2exe ? 

Also, there is a pre-built copy of cagent if you'd rather use it in the meantime:  https://github.com/mitre/caldera-agent/releases .

**Comment by jpsec** [comment]
AHHHH DAMN didn't see that, I'll provide the rest of the info tonight. Thanks a lot for the quick feedback!
