### ISSUE TITLE
Can't get iohttp==2.3.9 via pip3

### ISSUE THREAD

**Issue by DpoBoceka** [mitre/caldera#40]
Requirements.txt has iohttp==2.3.9 which can't be detected by pip. Perhaps, that specific version was removed from the repository, so what should I replace it with?

**Comment by dm-mitre** [comment]
I think you've misspelled the package, it is `aiohttp` (note the "a"). The easiest way to install all the dependencies is with the command `pip install -r caldera/requirements.txt` (when run from the root folder of the project) which will read in the requirements file without having to type each dependency in by hand.

**Comment by DpoBoceka** [comment]
yeah, you're right, silly of me, thank you!
