### ISSUE TITLE
Impact of running Caldera on a Win Server 2012 R2

### ISSUE THREAD

**Issue by Fortesqueu** [mitre/caldera#41]
Hi to everyone,

I've installed Caldera Agent in two Windows Server 2012 R2 and at first glance, seems to work the same way as using Windows 10 machines.

I'd like to know the risks, limitations or impact of running Caldera Agent in a server instead of a regular win10 image. The documentations say that the cagent.exe works in Win7, 8 and 10, but why not to mention servers as well?

**Comment by dm-mitre** [comment]
I can't think of a reason why the agent wouldn't work on Windows Server 2012 R2, but we don't really test that use which is why its not in the docs.
