### ISSUE TITLE
[Improvement] Selecting step while creating adversary

### ISSUE THREAD

**Issue by SpaceAether** [mitre/caldera#42]
Hello,

While testing Caldera I found that when creating an adversary and selecting the steps, it could be difficult to know easily what are the steps that can fulfill the preconditions for each step without juggling between the steps description and the adversary creation.

So I was thinking it might be useful to add a message or a way to indicate what are the steps that can fulfill the preconditions for a selected step when creating an adversary.

**Comment by hf-mitre** [comment]
@SpaceAether, thanks for the feedback!  I believe we have a team member that is working on something like this, but I'm not quite the current status of it; I'll check with him.

**Comment by cl-mitre** [comment]
We've been testing a local version that implements a warning system that indicates which preconditions aren't filled, and what steps can fill those preconditions. It should be included in the next update we push, though we sadly don't have an exact timeline for that at the moment.
