### ISSUE TITLE
Help needed: Creating domain in Caldera server

### ISSUE THREAD

**Issue by secure0** [mitre/caldera#43]
Dears,

I have installed Caldera server on Ubuntu. To create a network, there is a drop-down menu to select "Domain". Is this meant to be Windows AD Domain ? If yes, does it need to be created in Windows DC server and then we get that Ubuntu joined to the Windows server ? IF no, what is meant by domain ?

Thanks in advance.

**Comment by hf-mitre** [comment]
Domain refers to the  windows domain that the target boxes are joined to.  The machine being used as the caldera server does not need to be part of the domain.  

After installing the caldera service on the target machines, the domain should automatically populate as an option in the Create Network domain dropdown.  
More detailed steps for installation and running operations can be found here https://caldera.readthedocs.io/en/latest/index.html .  

Hope this helps!

**Comment by omergunal** [comment]
@hf-mitre i created active directory but caldera didnt find it. machines  can sending ping each other
