### ISSUE TITLE
Traceback error

### ISSUE THREAD

**Issue by entwinedgerm** [mitre/caldera#44]
Receiving the following error when trying to run caldera.py

![calderaerror](https://user-images.githubusercontent.com/40652661/42014150-f563ad1e-7a5d-11e8-8ace-220da7cafef9.PNG)

Can someone point me in the right direction?

**Comment by dm-mitre** [comment]
Hi, have you tried following the installation steps: https://caldera.readthedocs.io/en/latest/installation.html

**Comment by entwinedgerm** [comment]
I have and when I go to start the caldera server it receive the error above. Initially I was getting a ujson module not found and Visual C++ library error but I was able to correct that.

**Comment by dm-mitre** [comment]
it sounds like `pip install -r requirements.txt` did not complete correctly you may need to try again and make sure it finishes without error

**Comment by entwinedgerm** [comment]
That appeared to correct some issues 

![replset error](https://user-images.githubusercontent.com/40652661/42062714-a8536332-7aeb-11e8-8d41-42cecec136bd.PNG)

Mongo was started with the command in the installation document.

**Comment by ronwalf** [comment]
Can you post your mongodb command line? It looks like it's missing the "--replSet caldera" option

**Comment by entwinedgerm** [comment]
![mongocommand](https://user-images.githubusercontent.com/40652661/42063854-f288325c-7af0-11e8-902d-be7de139e30d.PNG)

The struggle is real

**Comment by entwinedgerm** [comment]
Any ideas? Has it been tested on Mongodb 4.0 or am i missing something?

**Comment by dm-mitre** [comment]
hmm looks like it is running as a replset. we may need to upgrade pymongo. to support MongoDB 4.0 
Try installing an earlier version of mongoDB if possible. Alternatively you can try upgrading pymongo to the latest version, but there may be compatibility issues.

**Comment by entwinedgerm** [comment]
What version of Mongo do you recommend

**Comment by dm-mitre** [comment]
Definitely works with mongo 3.4. I believe 3.6 should also be good.

**Comment by entwinedgerm** [comment]
It works with 3.4.10 but does not with 3.6. Do you have the specific cmd line instructions for the Windows version of OpenSSL?

**Comment by entwinedgerm** [comment]
I had to muck around with openssl since it was missing some of the cert file names . I have access to the console now. Thanks for all of the help
