### ISSUE TITLE
terminating blocking commands in a step

### ISSUE THREAD

**Issue by TheMinz** [mitre/caldera#45]
Greetings,

I have seen your product and let me tell you that you guys have done an amazing job coding such a project. I was trying to extend its functionality by add a step. The step is supposed to emulate abnormal RDP behavior, namely I want my step to be able to connect to several RDP servers (lets say 10 for example) in quick succession. I have been able to utilize the **operation.execute_shell_command** to run native shell command and my plan was to utilize it to run mstsc.exe to connect to the RDP server and closing it after 10-20 seconds multiple time. My problem was the fact that mstsc blocks the execution of the remaining of the action. So I was wondering is there a way to kill the mstsc process after a set amount of time.

Below is the code of the step class to show you the progress im at

```
class MultiRDP(Step):
    """
    Description:
        This step connects to multiple machines using RDP
    Requirements:
        This step requires: - the existance of a RAT on a host
							- creds to connect with
							- the subnet to connect to
    """
    attack_mapping = [] #TODO
    display_name = "multi_RDP"
    summary = "Connect to multiple machines using RDP"
    preconditions = [('rat', OPRat),
                     ('host', OPHost(OPVar("rat.host")))]

    postconditions = [('file_g', OPFile({'host': OPVar('rat.host')}))]
    significant_parameters = ['host']

    @staticmethod
    def description(host):
        return "Connecting using RDP"

    @staticmethod
    async def action(operation, rat, host):
        username = "admin"
        password = "admin"
        ipaddress ="x.x.x.x"
        await operation.execute_shell_command(rat, command.CommandLine(['reg', 'add', '"HKLM\Software\Microsoft\Terminal Server Client"','/v AuthenticationLevelOverride','/t REG_DWORD','/d 0']), lambda x: x == '')
        await operation.execute_shell_command(rat, command.CommandLine(['cmdkey /generic:TERMSRV/'+ipaddress+' /user:'+username+' /pass:'+password]), lambda x: x == '')
        await operation.execute_shell_command(rat, command.CommandLine(['mstsc /v:'+ipaddress]), lambda x: x == '')
        await operation.execute_shell_command(rat, command.CommandLine(['timeout /T 10 /NOBREAK']), lambda x: x == '')
        await operation.execute_shell_command(rat, command.CommandLine(['taskkill /im mstsc.exe /F']), lambda x: x == '')
        await operation.execute_shell_command(rat, command.CommandLine(['cmdkey /delete:TERMSRV/'+ipaddress]), lambda x: x == '')
        await operation.execute_shell_command(rat, command.CommandLine(['reg', 'delete', '"HKLM\Software\Microsoft\Terminal Server Client"','/v AuthenticationLevelOverride','/f']), lambda x: x == '')
        return True

    @staticmethod
    async def cleanup(cleaner, file_g):
        for fileg in file_g:
            await cleaner.delete(fileg)
```

**Comment by dm-mitre** [comment]
Looking good @TheMinz. 

You can use the windows command `start` to run a program and return immediately (see https://stackoverflow.com/questions/28212148/how-to-run-a-command-from-a-batch-file-and-immediately-return ). 

A few other helpful tips. You shouldn't need the `cleanup` function unless you're actually leaving files and it looks like you're cleaning up after yourself already. Likewise with the `file_g` postcondition; you would only use that if you were creating files that you left on the host. Also it may be easier to do the sleep within python via `time.sleep(10)`. And finally, you may find some of our built in command line utilities useful ( https://github.com/mitre/caldera/tree/master/caldera/app/commands ). We won't have commands for everything you need, but some of them help with formatting and have built in parsers for the result of a command that will also detect common errors.
