### ISSUE TITLE
OS Command Injection  in sandcat plugin

### ISSUE THREAD

**Issue by 1c3z** [mitre/caldera#462]
login the caldera

open the url
http://127.0.0.1:8888/plugin/sandcat/gui 

Enter a url, click clone button
```
`touch /tmp/pwn`
```

![image](https://user-images.githubusercontent.com/9052484/64106984-f41aa780-cdab-11e9-81d5-2d0e0478d9c4.png)

![image](https://user-images.githubusercontent.com/9052484/64106913-c59ccc80-cdab-11e9-9af9-5547d04f98fc.png)

**Comment by khyberspache** [comment]
Good catch. That makes sense considering how we clone the site... appears to truncate the wget command to allow arbitrary shell command execution. If you have a PR to fix this, feel free to submit.

**Comment by privateducky** [comment]
This appears fixed - closing (thanks @ajunlee)
