### ISSUE TITLE
sand_gui_api.py: invalid syntax error

### ISSUE THREAD

**Issue by ohmygord** [mitre/caldera#463]
Hi,

On trying to load server.py I see an issue with invalid syntax within the sand_gui_api.py file. 

![image](https://user-images.githubusercontent.com/51379445/64113065-31b60b00-cd81-11e9-8da8-550460b6f8bf.png)

If I remove sandcat from the local.yml file the server starts. Is there anything I can modify within the sand_gui_api.py script to fix this?

thanks

**Comment by khyberspache** [comment]
Can you check which minor version of python3.5 you're on? I cannot reproduce this error.

**Comment by privateducky** [comment]
I updated the line of code that appeared to be the culprit -- let me know if the latest code solves it!

**Comment by ohmygord** [comment]
Thank you @privateducky this looks to have done the trick. Your help is very much appreciated!!

**Comment by privateducky** [comment]
Great!
