### ISSUE TITLE
Terminal plugin wont load/compile

### ISSUE THREAD

**Issue by wearenotsecure** [mitre/caldera#466]
Installed Caldera on an Ubuntu 18.04 server and got it running fine with the out of the box plugins. I enabled the plugin via local.yml file and then I ran pip3 install -r requirements.txt  the Terminal plugin folder which completed without any issues. When i then try to run server.py i get the following error : 
Traceback (most recent call last):
  File "server.py", line 93, in <module>
    plugin_modules = build_plugins(cfg['plugins'])
  File "server.py", line 39, in build_plugins
    Popen(['pip', 'install', '-r', 'plugins/%s/requirements.txt' % plug], stdout=DEVNULL)
  File "/usr/lib/python3.6/subprocess.py", line 729, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.6/subprocess.py", line 1364, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'pip': 'pip'

Any ideas on how to fix ?

**Comment by wearenotsecure** [comment]
Forgot to mention that i am running Python 3.6.8

**Comment by privateducky** [comment]
ah yes-- when plugins are loaded (in server.py), they install the pip requirements automatically through this line:
```
Popen(['pip', 'install', '-r', 'plugins/%s/requirements.txt' % plug], stdout=DEVNULL)
```
Since you're using 'pip3' instead of 'pip', this line will fail. You can change the word here- as a workaround- but in the meantime, I'll add a patch today to handle this case.

**Comment by privateducky** [comment]
patch merged. let me know if you still see issues.

**Comment by wearenotsecure** [comment]
Yep seems to work now .
Below is the output when starting the server :
root@caldera:/opt/caldera# python3 server.py
DEBUG:root:Loading plugin: stockpile
DEBUG:root:Loading plugin: sandcat
DEBUG:root:Loading plugin: gui
DEBUG:root:Loading plugin: chain
DEBUG:root:Loading plugin: caltack
DEBUG:root:Loading plugin: terminal
Problem installing PIP requirements automatically. Try doing this manually.
DEBUG:root:Using an in-memory database: True
DEBUG:root:Uploaded files will be put in /tmp
DEBUG:root:Agents will be considered untrusted after 180 seconds of silence
DEBUG:root:Serving at http://0.0.0.0:8888
DEBUG:data_svc:Loading data from plugins/stockpile/data
DEBUG:data_svc:Loading data from plugins/terminal/data

Not sure what the note is about pip requirements however they are all correctly installed ( manually installed them before hand using the pip3 install -r req.......  

Anyway seems to be working fine so thanks a lot.

**Comment by privateducky** [comment]
great! yeah that log line is sort of misleading.. every time you start CALDERA, it'll try to re-import the PIP requirements. that line is saying it failed to import them automatically, so you should try manually (which you already did, so it doesn't need to happen again).
