### ISSUE TITLE
Sandcat submodule - missing commit reference

### ISSUE THREAD

**Issue by spellanser** [mitre/caldera#483]
Hello! 
This repo is broken now: can't update sandcat submodule. 

```
~$ git submodule update

fatal: reference is not a tree: 637b3eb89f038fcf2ec76fe593deb8d986cee301
Unable to checkout '637b3eb89f038fcf2ec76fe593deb8d986cee301' in submodule path 'plugins/sandcat'
```

**Comment by privateducky** [comment]
I can't reproduce this (I just did a fresh clone and retried). Can you try re-cloning and see if the behavior continues?

**Comment by spellanser** [comment]
My apologies, seems like it was some network related problem. 
Thank you!
