### ISSUE TITLE
NATing caldera server

### ISSUE THREAD

**Issue by TheMinz** [mitre/caldera#49]
Greetings,

I was trying to deploy caldera server in a virtual machine, but due to some security mechanisms I didn't make the virtual machine bridged to the network. I used the combination of NATing and port forwarding. I have allowed the access to port 8888/tcp through the OS (Windows) firewall and have configured the port forwarding rule to forward any traffic going to the host machine on port 8888/tcp to go directly to caldera server port 8888/tcp. 

when I configured all of that, I managed to access the web interface and login, but I can't do anything else than that. I can't view operations, networks and adversaries. I also can't access any of the options in the "Debug" menu. When I click on any option nothing happens. Is there any other port I need to allow through the firewall and configure port forwarding for it in order to make the server work?

**Comment by hf-mitre** [comment]
@TheMinz , based on your description, it sounds like the networking is working OK.  Does the CALDERA server output any error messages.  My first guess is that the server having trouble communicating with MongoDB.  

Check if: 

1.  MongoDB is running on the same host the caldera server is running on. 

2. That it has been configured to use a replica set named "caldera" ( https://caldera.readthedocs.io/en/latest/installation.html#caldera-server-installation ). 

3. Check the MongoDB version -- lots of people are reporting problems with v4 which we haven't fixed yet, in the interim use v3.

**Comment by hf-mitre** [comment]
Closing this since it's been 3 weeks.  Hope you got it to work!
