### ISSUE TITLE
caldera REST API

### ISSUE THREAD

**Issue by kpm4** [mitre/caldera#498]
hello,

I am trying to build a REST API plugin with similar chain plugin features. I am stuked with the authentication, because it is implemented in the core. What do you suggest to build REST API auth in the plugin to run services API?

thanks

**Comment by privateducky** [comment]
if you look at chain_api.py, you'll see that it uses the auth_service from the core code, like this:
```
    @template('chain.html')
    async def landing(self, request):
        await self.auth_svc.check_permissions(request)
        abilities = await self.data_svc.explode_abilities()
...
```
Note the first line of the landing function. This is checking if the request is authenticated. You can do the same behavior in custom plugins as well. 

Let me know if this helps.

**Comment by spellanser** [comment]
Hello! 
This docs page https://github.com/mitre/caldera/wiki/Plugins-chain says, that REST API already ready for use in chain plugin. 

But there is no docs about the API. 
It takes more time to figure out how to work with API from the code. 
Could you please update the docs?

**Comment by kpm4** [comment]
there are partial REST APIs, the auth is still done with cookies ( https://github.com/mitre/caldera/blob/master/app/service/auth_svc.py#L36 ). 
So basically the only way to use the REST API is to send username and password to /enter endpoint and get the cookie, then send it to every APIs requests.
Could be nice to have a API key or a JWT token, IMHO.

**Comment by privateducky** [comment]
agreed. right now, our GUI/API auth is pretty basic, as it's not the focus of the application.. but, if you push up a pull request in this area, we'd love to take a look!

**Comment by privateducky** [comment]
@spellanser agreed-- yes, we'll update the docs with API details

**Comment by spellanser** [comment]
> @spellanser agreed-- yes, we'll update the docs with API details

Great, thank you!

**Comment by privateducky** [comment]
@spellanser it's not great & comprehensive (yet) but I took a first spin at adding REST API documentation on the Chain wiki page. I'm covering all the supported endpoints. Over time, we'll look to beef this up with more robust examples and descriptions.
