### ISSUE TITLE
server can't find cagent

### ISSUE THREAD

**Issue by cx0113** [mitre/caldera#51]
Hello,
  I setup a caldera server and agent following the installation steps. But i can't find it in caldera web interface. I can see the cagent service has started in Windows Task Manger.  Can someone point me in the right direction?
Thanks!

**Comment by trallgorm** [comment]
You can't see the agent in caldera's web interface? Do you have the correct conf.yml file in the same directory? Do you have connectivity between the caldera server and the machine with the agent on it?

**Comment by dm-mitre** [comment]
make sure you can ping/browse to the IP as listed in conf.yml sometimes the IP is not detected correctly and conf.yml points to the wrong IP.

**Comment by qq854051086** [comment]
I saw your problem, very similar to what I encountered. I modified my certificate and I saw the agent. Remember to keep the agent and server on the same network segment.
