### ISSUE TITLE
Unicode Decode Error on result of  windows worm(smb+winrm)

### ISSUE THREAD

**Issue by Iwatch31** [mitre/caldera#514]
Hello,

When i try to run the Collect ARP details scenario i have a none Utf-8 result so My second phase fail on the result parse of the first phase I think.

The traceback look like:

caldera_1  | Traceback (most recent call last):
caldera_1  |   File "/usr/src/app/app/service/operation_svc.py", line 56, in run
caldera_1  |     await planner.execute(phase)
caldera_1  |   File "/usr/src/app/plugins/stockpile/app/sequential.py", line 12, in execute
caldera_1  |     for l in await self.planning_svc.select_links(operation, member, phase):
caldera_1  |   File "/usr/src/app/app/service/planning_svc.py", line 24, in select_links
caldera_1  |     await self.get_service('parsing_svc').parse_facts(operation)
caldera_1  |   File "/usr/src/app/app/service/parsing_svc.py", line 31, in parse_facts
caldera_1  |     matched_facts = parsers.regex(parser[0], b64decode(result['output']).decode('utf-8'), self.log)
caldera_1  | UnicodeDecodeError: 'utf-8' codec can't decode byte 0xff in position 11: invalid start byte

thank

**Comment by privateducky** [comment]
@khyberspache can you take a look at this?

**Comment by khyberspache** [comment]
@Iwatch31 If I'm understanding you correctly, the operation fails after running the Collect ARP details (`arp -a`) command and never progresses on?

**Comment by Iwatch31** [comment]
my first phase (arp -a) is executed correctly but when caldera starts the second this error disappears in the logs and my overall scenario does not go to the end

**Comment by khyberspache** [comment]
I see you've tried to update line 31 of `parsing_svc.py` to remove the UTF-8 encoding - that won't work because the parser needs to run against UTF-8 encoded strings.  Make sure line 31 of `parsing_svc.py` is: `matched_facts = parsers.regex(parser[0], b64decode(result['output']).decode('utf-8'), self.log)`

Once you've done that, what does the output of your `arp -a` command look like? My guess is there's a weird character.

We have encountered encoding issues before with Caldera parsing and currently don't handle errors in that area well...

**Comment by Iwatch31** [comment]
exactly I tried this change but without result, I was wrong in the error it is this one:

DEBUG:agent_svc:HEARTBEAT (AD-Demo-SOC$DEMO\Victime)
caldera_1  | DEBUG:operation_svc:Operation 1 (test) phase 1: completed
caldera_1  | DEBUG:operation_svc:Operation 1 (test) phase 2: started
caldera_1  | Traceback (most recent call last):
caldera_1  |   File "/usr/src/app/app/service/operation_svc.py", line 56, in run
caldera_1  |     await planner.execute(phase)
caldera_1  |   File "/usr/src/app/plugins/stockpile/app/sequential.py", line 12, in execute
caldera_1  |     for l in await self.planning_svc.select_links(operation, member, phase):
caldera_1  |   File "/usr/src/app/app/service/planning_svc.py", line 24, in select_links
caldera_1  |     await self.get_service('parsing_svc').parse_facts(operation)
caldera_1  |   File "/usr/src/app/app/service/parsing_svc.py", line 31, in parse_facts
caldera_1  |     matched_facts = parsers.regex(parser[0], b64decode(result['output']).decode('utf-8'), self.log)
caldera_1  | UnicodeDecodeError: 'utf-8' codec can't decode byte 0xff in position 11: invalid start byte

In the result caldera retrieved for the command (arp -a) I actually have a special character that does not normally appear in the normal result of the pwsh command

**Comment by khyberspache** [comment]
Can you provide the `arp -a` output, not the stack trace?

**Comment by Iwatch31** [comment]
here is the command output seen in the caldera gui : 

Interfaceÿ: 192.168.140.185 --- 0xb
  Adresse Internet      Adresse physique      Type
  169.254.182.90        52-54-00-dd-c7-90     dynamique 
  192.168.140.1         52-54-00-b0-78-9d     dynamique 
  192.168.140.3         52-54-00-dd-c7-90     dynamique 
  192.168.140.5         44-a8-42-2b-7b-c7     dynamique 
  192.168.140.16        52-54-00-c9-09-32     dynamique 
  192.168.140.22        52-54-00-9b-9f-04     dynamique 
  192.168.140.30        52-54-00-99-3d-42     dynamique 
  192.168.140.40        52-54-00-e0-44-66     dynamique 
  192.168.140.50        34-17-eb-ed-08-1f     dynamique 
  192.168.140.71        52-54-00-de-ad-71     dynamique 
  192.168.140.99        52-54-00-dd-c7-90     dynamique 
  192.168.140.109       52-54-00-ac-16-ad     dynamique 
  192.168.140.110       52-54-00-9b-d6-5c     dynamique 
  192.168.140.113       52-54-00-9b-d6-5c     dynamique 
  192.168.140.115       52-54-00-e2-0c-54     dynamique 
  192.168.140.160       52-54-00-e2-0c-54     dynamique 
  192.168.140.250       00-11-32-66-9d-85     dynamique 
  192.168.140.254       70-4c-a5-36-89-28     dynamique 
  192.168.140.255       ff-ff-ff-ff-ff-ff     statique  
  224.0.0.22            01-00-5e-00-00-16     statique  
  224.0.0.252           01-00-5e-00-00-fc     statique  
  239.255.255.250       01-00-5e-7f-ff-fa     statique  
  255.255.255.255       ff-ff-ff-ff-ff-ff     statique

**Comment by rodkinal** [comment]
Hi, 

I am getting the same error while trying to perform a nosy neighbor attack (the operation fails during the ARP phase): 

```
Traceback (most recent call last):
  File "/caldera/app/service/operation_svc.py", line 56, in run
    await planner.execute(phase)
  File "/caldera/plugins/stockpile/app/sequential.py", line 12, in execute
    for l in await self.planning_svc.select_links(operation, member, phase):
  File "/caldera/app/service/planning_svc.py", line 24, in select_links
    await self.get_service('parsing_svc').parse_facts(operation)
  File "/caldera/app/service/parsing_svc.py", line 29, in parse_facts
    blob = b64decode(result['output']).decode('utf-8')
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xa2 in position 41: invalid start byte
```
Thanks!

**Comment by khyberspache** [comment]
@Iwatch31 @rodkinal 

Try changing `blob = b64decode(result['output']).decode('utf-8')` to `blob = b64decode(result['output']).decode('utf-8', errors='ignore')`. 

If that doesn't work, try forcing the encoding by changing that line to: 
`blob = b64decode(result['output']).decode('utf-8', errors='ignore').encode('windows-1252').decode('utf-8', errors='ignore')`

**Comment by Iwatch31** [comment]
ok thanks it's good for me this following solution works : blob = b64decode(result['output']).decode('utf-8', errors='ignore').
