### ISSUE TITLE
Caldera Server can't find visual c++

### ISSUE THREAD

**Issue by ericgatm4** [mitre/caldera#52]
When I attempt to start caldera on a Windows 2012 R2 server, I get the error Microsoft Visual C++ is required.  

However Visual C++ 14.0 Build Tools is installed

Can anyone provide some ideas/guidance?

Thx

**Comment by dm-mitre** [comment]
If you are having trouble starting the agent, you must install the Visual C++ redistributable. See instructions here: https://caldera.readthedocs.io/en/latest/installation.html#installation-instructions

**Comment by ericgatm4** [comment]
I’ve installed c++ but when I execute python caldera.py I get an error message that it’s missing

Thx

Eric G Steinberg
[/Users/EricSteinberg/Library/Containers/com.microsoft.Outlook/Data/Library/Caches/Signatures/signature_2131493194]<http://www.mantix4.com/>
Mobile  303.667.4045  |  Main 877.Mantix4  |  www.Mantix4.com
373 Inverness Parkway | Suite 110 | Englewood, CO 80112
Visit us on:
[/Users/EricSteinberg/Library/Containers/com.microsoft.Outlook/Data/Library/Caches/Signatures/signature_2129191799] [/Users/EricSteinberg/Library/Containers/com.microsoft.Outlook/Data/Library/Caches/Signatures/signature_168133501]  [/Users/EricSteinberg/Library/Containers/com.microsoft.Outlook/Data/Library/Caches/Signatures/signature_755935200]

[/Users/EricSteinberg/Library/Containers/com.microsoft.Outlook/Data/Library/Caches/Signatures/signature_1234811888][/Users/EricSteinberg/Library/Containers/com.microsoft.Outlook/Data/Library/Caches/Signatures/signature_828775388]

This E-mail message is covered by the Privacy Act 18 U.S.C. 2510-2521 the information contained in this E-mail message is personal and confidential and is intended for a specific individual (s) and purpose and therefore is protected from disclosure under the Gramm-Leach-Bliley H.R. 3723 on October 11, 1996, which has protected this document as a confidential and trade secret. If you are not the intended recipient of this communication, or the employee or agent responsible for delivering this message to the intended recipient, you are NOT authorized to read, print, retain, copy or otherwise disseminate this communication and are advised that any such dissemination, distribution or copy of this communication, or acting on the information contained herein, may be a violation of applicable law and is strictly prohibited. If you have received this communication in error, please notify the sender immediately by return e-mail and delete all copies of this communication.

**Comment by dm-mitre** [comment]
it sounds like `pip install -r requirements.txt` did not work correctly. Can you rerun that command in the installation documents and paste the output? 

Alternatively you may wish to try our new docker compose method which is much easier.

**Comment by dm-mitre** [comment]
http://caldera.readthedocs.io/en/latest/installation.html#option-1-install-with-docker-compose

**Comment by ericgatm4** [comment]
Thx  I’ll give this a try.

Where do I find the installation info on the Docker method?



Eric G Steinberg
[/Users/EricSteinberg/Library/Containers/com.microsoft.Outlook/Data/Library/Caches/Signatures/signature_1151060349]<http://www.mantix4.com/>
Mobile  303.667.4045  |  Main 877.Mantix4  |  www.Mantix4.com
373 Inverness Parkway | Suite 110 | Englewood, CO 80112
Visit us on:
[/Users/EricSteinberg/Library/Containers/com.microsoft.Outlook/Data/Library/Caches/Signatures/signature_288243895] [/Users/EricSteinberg/Library/Containers/com.microsoft.Outlook/Data/Library/Caches/Signatures/signature_1289383317]  [/Users/EricSteinberg/Library/Containers/com.microsoft.Outlook/Data/Library/Caches/Signatures/signature_1821086698]

[/Users/EricSteinberg/Library/Containers/com.microsoft.Outlook/Data/Library/Caches/Signatures/signature_1247861383][/Users/EricSteinberg/Library/Containers/com.microsoft.Outlook/Data/Library/Caches/Signatures/signature_2067438170]

This E-mail message is covered by the Privacy Act 18 U.S.C. 2510-2521 the information contained in this E-mail message is personal and confidential and is intended for a specific individual (s) and purpose and therefore is protected from disclosure under the Gramm-Leach-Bliley H.R. 3723 on October 11, 1996, which has protected this document as a confidential and trade secret. If you are not the intended recipient of this communication, or the employee or agent responsible for delivering this message to the intended recipient, you are NOT authorized to read, print, retain, copy or otherwise disseminate this communication and are advised that any such dissemination, distribution or copy of this communication, or acting on the information contained herein, may be a violation of applicable law and is strictly prohibited. If you have received this communication in error, please notify the sender immediately by return e-mail and delete all copies of this communication.

**Comment by dm-mitre** [comment]
http://caldera.readthedocs.io/en/latest/installation.html#option-1-install-with-docker-compose

**Comment by ericgatm4** [comment]
Should the containers be Windows or Linux?

Thx


Eric G Steinberg
[/Users/EricSteinberg/Library/Containers/com.microsoft.Outlook/Data/Library/Caches/Signatures/signature_671915732]<http://www.mantix4.com/>
Mobile  303.667.4045  |  Main 877.Mantix4  |  www.Mantix4.com
373 Inverness Parkway | Suite 110 | Englewood, CO 80112
Visit us on:
[/Users/EricSteinberg/Library/Containers/com.microsoft.Outlook/Data/Library/Caches/Signatures/signature_757347787] [/Users/EricSteinberg/Library/Containers/com.microsoft.Outlook/Data/Library/Caches/Signatures/signature_1638166078]  [/Users/EricSteinberg/Library/Containers/com.microsoft.Outlook/Data/Library/Caches/Signatures/signature_1525476225]

[/Users/EricSteinberg/Library/Containers/com.microsoft.Outlook/Data/Library/Caches/Signatures/signature_2128508850][/Users/EricSteinberg/Library/Containers/com.microsoft.Outlook/Data/Library/Caches/Signatures/signature_785075327]

This E-mail message is covered by the Privacy Act 18 U.S.C. 2510-2521 the information contained in this E-mail message is personal and confidential and is intended for a specific individual (s) and purpose and therefore is protected from disclosure under the Gramm-Leach-Bliley H.R. 3723 on October 11, 1996, which has protected this document as a confidential and trade secret. If you are not the intended recipient of this communication, or the employee or agent responsible for delivering this message to the intended recipient, you are NOT authorized to read, print, retain, copy or otherwise disseminate this communication and are advised that any such dissemination, distribution or copy of this communication, or acting on the information contained herein, may be a violation of applicable law and is strictly prohibited. If you have received this communication in error, please notify the sender immediately by return e-mail and delete all copies of this communication.

**Comment by hf-mitre** [comment]
`docker-compose up` will use the configuration outlined in the https://github.com/mitre/caldera/blob/master/docker-compose.yaml file.  Two containers are needed. One is created from a MongoDB image, this image is created by MongoDB and should be pulled down automatically by Docker from Docker Hub.  The container the CALDERA server runs in will use an image built by Docker.  The steps Docker uses to create the image are in the Dockerfile ( https://github.com/mitre/caldera/blob/master/Dockerfile ).  Our Dockerfile is based on an official Python image which should also automatically get pulled down from Docker hub.
