### ISSUE TITLE
Caldera unable to view on windows 10 webpage

### ISSUE THREAD

**Issue by sulaimanbale11** [mitre/caldera#522]
![IMG-20190921-WA0054](https://user-images.githubusercontent.com/50750136/65374204-e2953300-dcb9-11e9-9896-46aba528399f.jpg)

As seen in the image , after running the required services I am unable to view caldera webpage. 

Please help !!

**Comment by aapplebaum** [comment]
We'd need more information to help debug this. What is the output of the CALDERA server? What's in your local.yml file?

**Comment by aapplebaum** [comment]
I just noticed you're trying to access the server via 0.0.0.0:8888 -- I don't believe Chrome will resolve that to localhost. Try using 127.0.0.1 or the IP you used in your other screenshot.
