### ISSUE TITLE
Able to download agent , not able to run it!!

### ISSUE THREAD

**Issue by sulaimanbale** [mitre/caldera#524]
![image](https://user-images.githubusercontent.com/46603663/65385848-16c62d80-dd66-11e9-80ec-e7c42bf610b5.png)

As it can be seen agent has been downloaded, but Windows 10 does not know what program to run it with ? How do i overcome this ?

**Comment by privateducky** [comment]
This functionality only does the drive-by download (right now). You’ll need to manually add a .exe extension to the downloaded file to run it

**Comment by wbooth** [comment]
User appears to have run a successful operations https://github.com/mitre/caldera/issues/521#issuecomment-533936814
