### ISSUE TITLE
debian 10 clean install

### ISSUE THREAD

**Issue by kinomakino** [mitre/caldera#525]
Debian 10 clean install.
mongodb clean install last version.

Traceback (most recent call last):
  File "server.py", line 20, in <module>
    from app.service.parsing_svc import ParsingService
  File "/home/kinomakino/caldera/app/service/parsing_svc.py", line 1, in <module>
    import plugins.stockpile.parsers.standard as parsers
ModuleNotFoundError: No module named 'plugins.stockpile.parsers'

db version v4.2.0
git version: a4b751dcf51dd249c5865812b390cfd1c0129c30
OpenSSL version: OpenSSL 1.1.1c  28 May 2019
allocator: tcmalloc
modules: none
build environment:
    distmod: debian92
    distarch: x86_64
    target_arch: x86_64

thanks in advice

**Comment by privateducky** [comment]
What version of python3 are you using?

**Comment by privateducky** [comment]
on second thought - it looks like you didn't clone recursively. 

Double-check the installation instructions in the README to see an example of how to do this.
