### ISSUE TITLE
Unable to start the server

### ISSUE THREAD

**Issue by souhaiboudiouf** [mitre/caldera#526]
<br>This is the error i get when i try to run the server</br>

<br>caldera$python3 server.py</br>
<br>usage:CALDERA application [-h] -E ENVIRONMENT</br>
<br>CALDERA application: error: the following arguments are required: -E/--environment</br>

<br>Any help, please</br>

**Comment by privateducky** [comment]
It appears you’re using an older version of the code base (which predates our documentation). Try a fresh clone.

**Comment by souhaiboudiouf** [comment]
It works after a fresh clone.
Thank you
