### ISSUE TITLE
New video for caldera 2.0

### ISSUE THREAD

**Issue by sulaimanbale** [mitre/caldera#528]
Hi,

Could the team create a new video on how to use caldera 2.0 ? As i am not too sure on how to use Caldera 2.0.

I could see the older one on YouTube but it is totally different on caldera 2.0.
Thanks.

**Comment by privateducky** [comment]
We’re looking into updating the video but have no ETA. In the meantime, our GitHub wiki is our written documentation, so that would be a comprehensive source of information. Let me know what questions you have in the meantime.

**Comment by sulaimanbale11** [comment]
I would like to know how can I use caldera to use it against windows server 2012 for example !!

**Comment by sulaimanbale11** [comment]
Is there any way of contacting you ?

**Comment by sulaimanbale11** [comment]
Hi I've ping you on twitter!!

**Comment by privateducky** [comment]
sounds good. for running caldera with windows 2012, you follow the same steps. run a sandcat agent on the server and then you can run an operation from caldera against it. let us know how it goes.

**Comment by privateducky** [comment]
update on this-- we're working on getting a series of video tutorials out soon.

**Comment by privateducky** [comment]
closing - our first video is now online: https://www.youtube.com/watch?v=GukTj-i3UDg

keep an eye out for more.
