### ISSUE TITLE
Caldera asks to use microphone on Chrome?

### ISSUE THREAD

**Issue by MachLearnPort** [mitre/caldera#556]
Just installed Caldera server on Ubuntu, and was prompted by Chrome that Caldera was requesting access to my microphone. I declined it, and was wondering if anyone else received this message.

**Comment by privateducky** [comment]
Yes! In our bleeding-edge code, we've been toying around with adding voice-activated commands inside CALDERA... for example, you can navigate to the Sandcat tab in the GUI and say 'download the agent' and the agent will automatically download. 

I'm not sure how much of this will remain in our next stable release but if you're tracking our bleeding-edge code, you can toy around with the idea.

**Comment by MachLearnPort** [comment]
Ahhhh, very cool thanks.
