### ISSUE TITLE
Adversaries are not working

### ISSUE THREAD

**Issue by kpm4** [mitre/caldera#563]
just did a git clone of the latest caldera and all submodules, and I noticed that the built-in adversary are not working properly.

only "View admin shares" and "Collect ARP details" are running for Mission 1 and Worm. 
I can't find any error in the logs, and from the json report it says that everything is running.

can you reproduce it as well?

thanks

**Comment by kpm4** [comment]
I can reproduce it only with "cmd" agent, the powershell one is working properly.

**Comment by privateducky** [comment]
hi @kpm4 -- there are only a handful of 'cmd' capable abilities right now. 

when you look at an adversary, you can see the supported platforms for each ability they have. hover over the platforms to see which executor(s) are supported.

here is an example:
![Screen Shot 2019-10-08 at 7 31 55 AM](https://user-images.githubusercontent.com/49954156/66392396-bfe36980-e99d-11e9-9361-cd7afbbc9d37.png)

**Comment by kpm4** [comment]
I found the issue.
The Windows-cmd sandcat agent has a typo with the new version
https://github.com/mitre/sandcat/blob/136a2f88d19dc3631f67718f56beda950a42e1ab/templates/sandcat.html#L97

-executor is now -executors

**Comment by privateducky** [comment]
ah-- nice catch.

**Comment by privateducky** [comment]
I just pushed a fix to that in the sandcat repository now.
