### ISSUE TITLE
Network tab not available 

### ISSUE THREAD

**Issue by souhaiboudiouf** [mitre/caldera#582]
Hi there,

It's been a while now i am trying to use caldera but things stuck.
My issue is how to reach my targets in which an agent is install. I am using the latest version but the network tab is not showing. 
Is the network tab included in the new version?
I appreciate any direction that can help.

Regards

**Comment by privateducky** [comment]
network tab is not in caldera 2.0+. I would advise running the 2 missions listed in the README and see if that clears up any questions.

**Comment by souhaiboudiouf** [comment]
Thank you for your prompt response.

**Comment by souhaiboudiouf** [comment]
I tried mission 1 listed in the README this is what i get:
![Capture2](https://user-images.githubusercontent.com/37930849/66715745-1e0db380-edc7-11e9-9097-bb47377c8eaa.JPG)
![Capture](https://user-images.githubusercontent.com/37930849/66715747-2960df00-edc7-11e9-86d7-1e550ae8054e.JPG)

When i start the operation nothing shows up in the browser. 
I was struggling to find the start (*) icon  and the row mentioned but i didn't find them. Is this a normal behavior or am i missing something?

Thanks in advance
