### ISSUE TITLE
Agents Exception Error: Error on Bootstrap

### ISSUE THREAD

**Issue by chiraggoel95** [mitre/caldera#59]
Here is the output shown in the Jobs whenever i am trying to run any operation in Caldera.
[
  {
    "_id": "5b6d2142a15306000dfb195c",
    "agent": "5b69a87aa1530600012b7c34",
    "action": {
      "clients": {},
      "result": []
    },
    "create_time": "2018-08-10T05:23:14.553Z",
    "status": "success"
  },
  {
    "_id": "5b6d2142a15306000dfb195d",
    "agent": "5b69a87aa1530600012b7c34",
    "action": {
      "write_commander": {
        "path": "C:\\commander.exe"
      },
      "result": "\r\nSUCCESS: The file (or folder): \"C:\\commander.exe\" now owned by the administrators group.\r\n"
    },
    "create_time": "2018-08-10T05:23:14.758Z",
    "status": "success"
  },
  {
    "_id": "5b6d2143a15306000dfb195e",
    "agent": "5b69a87aa1530600012b7c34",
    "action": {
      "create_process": {
        "process_args": "C:\\commander.exe -f",
        "parent": null,
        "hide": true,
        "output": false
      },
      "error": "agents exception",
      "exception": "Traceback (most recent call last):\n  File \"C:\\Gitlab Runner\\builds\\f8e514af\\0\\caldera\\caldera-agent\\caldera_agent\\async_client.py\", line 117, in run_job\n  File \"C:\\Gitlab Runner\\builds\\f8e514af\\0\\caldera\\caldera-agent\\caldera_agent\\interfaces.py\", line 84, in run\n  File \"C:\\Gitlab Runner\\builds\\f8e514af\\0\\caldera\\caldera-agent\\caldera_agent\\interfaces.py\", line 159, in _create_process\n  File \"C:\\Gitlab Runner\\builds\\f8e514af\\0\\caldera\\caldera-agent\\caldera_agent\\foster3.py\", line 861, in __init__\n  File \"C:\\Gitlab Runner\\builds\\f8e514af\\0\\caldera\\caldera-agent\\caldera_agent\\foster3.py\", line 1153, in _execute_child\nOSError: [WinError 1392] The file or directory is corrupted and unreadable\n"
    },
    "create_time": "2018-08-10T05:23:15.955Z",
    "status": "failed"
  }
]

Also, Cant see the steps being executed by the caldera.

**Comment by omergunal** [comment]
I have the same problem, what is your agent's operating system?

**Comment by chiraggoel95** [comment]
I am currently running my Agent on Windows 10 with the server on kali linux ran using docker-compose up.

**Comment by hf-mitre** [comment]
I think this might originate from a problem in our `Dockerfile` when we `curl` down the RAT.  It looks like github is redirecting this request. This line needs 
 https://github.com/mitre/caldera/blob/master/Dockerfile#L11  `-L` option added to pull down the RAT.  

I'm really not sure how this got missed by us.  I'll push up a fix soon, but if you can, try this right away and see if it fixes the problem: 
1. Stop the running services: 
```
docker-compose down 
```
2. Change the `curl` line in the Dockerfile to 
```
curl $crater -L -k -o ../dep/crater/crater/CraterMain.exe
```

3. Re-Build the CALDERA Docker image: 
```
docker-compose build 
```
4. Re-create the services: 
```
docker-compose up 
```

**Comment by hf-mitre** [comment]
I've pushed the changed Dockerfile e52c1a62dce6765cbb31c8e0be86542f4aa1c201 . 

Would appreciate it if someone could comment back here on if this fixes the problem. 

Thanks.

**Comment by omergunal** [comment]
@hf-mitre it working now, thanks
