### ISSUE TITLE
Adding new techniques

### ISSUE THREAD

**Issue by CySHell** [mitre/caldera#6]
Is there any documentation available explaining how to add new tools and steps?
Looking at the code, it's fairly hard for me to fully understand the data model and configurations needed to add new stuff on my own.

**Comment by hf-mitre** [comment]
Unfortunately, there's not extensive documentation for that yet.  We do have a placeholder for it http://caldera.readthedocs.io/en/latest/add_technique.html, which basically refers you to the source code here: https://github.com/mitre/caldera/blob/master/caldera/app/operation/operation_steps.py.

Currently, the best reference for the data model are the definition's for the classes in the objects.py module: https://github.com/mitre/caldera/blob/master/caldera/app/engine/objects.py. 

At least one reason we haven't added a lot of documentation into how to develop new techniques yet is we want to change it to be easier.  Right now, it's pretty awkward with all the steps stuffed into a single file.  We've thought about breaking out each step into it's own module, and maybe allowing the steps to be edited via the web interface.  Although, I'm not sure how much those changes by themselves would really make it more approachable. 

We're definitely interested in feedback and suggestions on how to make adding new steps easier.  

In the meantime, we could probably put together a blog/tutorial for adding a new command-line utility and a Step that uses it if it would be helpful.  It could cover adding the methods used to generate command-lines for the RAT to run and parsing the output, as well as creating a step that would update the database with results of the command.

**Comment by albertfrates** [comment]
I would 2nd a blog/tutorial for adding a command line utility. I'm currently attempting to add several steps, and am a bit lost inside of the operation_steps.py file.

**Comment by dm-mitre** [comment]
@albertfrates We've got something almost ready. We'll try to push it out soon.

**Comment by dm-mitre** [comment]
@albertfrates @AshenLeet I've updated the documentation to explain a bit how adding techniques works. It still a working draft, but I wanted to get something out so people could take a look at it. Feel free to ask any questions or clarifications you have

**Comment by dm-mitre** [comment]
http://caldera.readthedocs.io/en/latest/add_technique.html

**Comment by delicedecerise** [comment]
> http://caldera.readthedocs.io/en/latest/add_technique.html

Hello,

This link does not seem to work anymore. Do you perhaps have an alternative?

**Comment by clenk** [comment]
Hi @delicedecerise, you may find this helpful: https://caldera.readthedocs.io/en/latest/Basic-Usage.html#abilities

However, starting up the server and going through the training plugin will teach you how to use Caldera, including creating a new ability. Just click on `training` under `PLUGINS` in the menu on the right hand side of the server GUI.
