### ISSUE TITLE
Help Needed: Writing a Step

### ISSUE THREAD

**Issue by korgull** [mitre/caldera#62]
I am making an effort to create a Step.  I thought creating a Step that creates a user account might be a simple one.  I have read through the documentation, but I'm still missing something.  The code I added to the operation_steps.py is shown below.  I'm leveraging the net.py module in the `/caldera/caldera/app/commands/` directory.   Does anyone have any suggestions on how to do this correctly?  I think I'm calling the 'net' function properly - based on the code, it looks like it just takes the variables after the command as a single string.  I get the step called, but it's flagging me for not using the parser positional argument, which I thought was optional - none of the other steps use it for the `execute_shell_command` call.  Adding a value just gives me a different error (I chose `net` as the positional value).

thanks

```
class NetUser(Step):
    """
    Description:
        This step creates a local account on the local target machine, using the 'net user' command.
    Requirements:
        Requires administrative access to the target machine.
    """
    attack_mapping = [('T1136', 'Persistence'), ('T1059', 'Execution')]
    display_name = "net_user_local"
    summary = 'Locally add a user using the command "net user"'

    preconditions = [("rat", OPRat({"elevated": True})),
                     ("host", OPHost(OPVar("rat.host")))]
    postconditions = [("user_g", OPUser)]

    significant_parameters = ['host'] #Host is the significant parameter so it runs once per host

    preproperties = ['rat.username']
    postproperties = ["user_g.username", "user_g.is_group", "user_g.sid"]

    @staticmethod
    def description(rat, host):
        return "Creating local user calderauser on {} with net user".format(host.hostname)

    @staticmethod
    async def action(operation, rat, host, user_g): #variables from pre- and postconditions go here
        cmd = 'user calderauser Password1 /ADD'
        await operation.execute_shell_command(rat, net.net(cmd))
        await user_g({'user_g': 'calderauser'})
        return True
```

**Comment by dm-mitre** [comment]
You're really close. The parser argument is actually not optional. A simple fix would be to change it to
```
        await operation.execute_shell_command(rat, net.net(cmd), lambda x: ())
```

Longer explanation: The other techniques actually do pass in a function although its hard to tell. If you [look closely at the definition of net.use()](https://github.com/mitre/caldera/blob/master/caldera/app/commands/net.py#L60) you'll see that it returns a tuple. Which is then [unpacked with the `*` operator](https://docs.python.org/3/tutorial/controlflow.html#unpacking-argument-lists) when passed into `execute_shell_command()`.

**Comment by korgull** [comment]
Thanks! 
However, I'll need to look closer at unpacking the function.  I used the line you suggested and now get the error: `TypeError: net() takes from 0 to 1 positional arguments but 2 were given` which is what I think I was getting before, leading me to believe the parser value wasn't needed (in addition to what I perceived in the code).

**Comment by dm-mitre** [comment]
I having some difficulty following your question. Could you post the code that you are using with the current modifications?

**Comment by korgull** [comment]
Sure.

This code produces `TypeError: net() takes from 0 to 1 positional arguments but 2 were given`

```
class NetUser(Step):
    """
    Description:
        This step creates a local account on the local target machine, using the 'net user' command.
    Requirements:
        Requires administrative access to the target machine.
    """
    attack_mapping = [('T1136', 'Persistence'), ('T1059', 'Execution')]
    display_name = "net_user_local"
    summary = 'Locally add a user using the command "net user"'

    preconditions = [("rat", OPRat({"elevated": True})),
                     ("host", OPHost(OPVar("rat.host")))]
    postconditions = [("user_g", OPUser)]

    significant_parameters = ['host'] #Host is the significant parameter so it runs once per host

    preproperties = ['rat.username']
    postproperties = ["user_g.username", "user_g.is_group", "user_g.sid"]

    @staticmethod
    def description(rat, host):
        return "Creating local user calderauser on {} with net user".format(host.hostname)

    @staticmethod
    async def action(operation, rat, host, user_g): #variables from pre- and postconditions go here
        cmd = 'user calderauser Password1 /ADD'
        await operation.execute_shell_command(rat, net.net(cmd), lambda x: ())
        await user_g({'user_g': 'calderauser'})
        return True
```

And before I looked back at the net.net definition inside net.py, I just added an asterisk to the net.net function:

```
class NetUser(Step):
    """
    Description:
        This step creates a local account on the local target machine, using the 'net user' command.
    Requirements:
        Requires administrative access to the target machine.
    """
    attack_mapping = [('T1136', 'Persistence'), ('T1059', 'Execution')]
    display_name = "net_user_local"
    summary = 'Locally add a user using the command "net user"'

    preconditions = [("rat", OPRat({"elevated": True})),
                     ("host", OPHost(OPVar("rat.host")))]
    postconditions = [("user_g", OPUser)]

    significant_parameters = ['host'] #Host is the significant parameter so it runs once per host

    preproperties = ['rat.username']
    postproperties = ["user_g.username", "user_g.is_group", "user_g.sid"]

    @staticmethod
    def description(rat, host):
        return "Creating local user calderauser on {} with net user".format(host.hostname)

    @staticmethod
    async def action(operation, rat, host, user_g): #variables from pre- and postconditions go here
        cmd = 'user calderauser Password1 /ADD'
        await operation.execute_shell_command(rat, *net.net(cmd))
        await user_g({'user_g': 'calderauser'})
        return True
```

Which obviously won't work - which provides the error `ypeError: execute_shell_command() argument after * must be an iterable, not CommandLine` because the definition just outputs `CommandLine`, not a tuple as net.use and the other do.  Should `net.net` be rewritten to output a tuple?

**Comment by korgull** [comment]
Wait.. scratch that.. I may have have a typo.. Sorry.. I'm trying this again.

**Comment by korgull** [comment]
Bingo.  It ran, but put spaces between all the characters.  I can look into it and see what I did wrong.

```
Hostname: win10caldera1
Command Line: net u s e r   c a l d e r a u s e r   P a s s w o r d 1   / A D D
StdOut: 
The syntax of this command is: 
[SNIP]
```

**Comment by hf-mitre** [comment]
Hi @korgull , 

Try changing ` await user_g({'user_g': 'calderauser'})` to ` await user_g({'username': 'calderauser'})`

The allowed fields for ObservedUsers (users that CALDERA discovers -- or creates -- during an operation) are here: https://github.com/mitre/caldera/blob/master/caldera/app/engine/objects.py#L255

**Comment by dm-mitre** [comment]
Great! It is expected that the user account will be there until you clean it up ;) I encourage you to look through the existing steps and see if you can figure out how to write a cleanup method on your own. And of course if you run into trouble feel free to message us.

**Comment by korgull** [comment]
Awesome.  I was thinking that I might need an extra step to clean up the use account.  If I gather correctly, "cleanup" in Caldera simply means that it takes the rats off the machines with agents on them.

Thanks!  You can mark this issue as "closed" :)

**Comment by dm-mitre** [comment]
After all the steps are finished running, there is an extra phase called cleanup that occurs during which everything is undone... A few things happen automatically, (e.g. rats are automatically stopped and deleted) but each step can have a `cleanup` function which will be run during this phase. The cleanup function is expected to undo anything that the step may have done. In this case you would want your cleanup function to delete the user account that your step made. 

The arguments for the cleanup function are the same as the arguments for your `action()` function which lets you re-use them to perform cleanup.

Here's an example of a cleanup function that does some interesting things: https://github.com/mitre/caldera/blob/master/caldera/app/operation/operation_steps.py#L1392

**Comment by dm-mitre** [comment]
Glad we could help
