### ISSUE TITLE
Parsing problems

### ISSUE THREAD

**Issue by EmilioPanti** [mitre/caldera#625]
If during an operation already started a new agent joins the operation, the parsing of the abilities performed by the new agent does not take place correctly if those abilities  have already been executed and parsed by the "old" agents.

Eg: just start the Hunter adversary profile on an agent and, at the second / third phase, start a new agent who joins the same group.

I tried to figure out where the error is but with all the recent new introductions (used/relationship/requirements) it is difficult for me o fully understand the code.

**Comment by privateducky** [comment]
PR merged. Thanks @EmilioPanti !
