### ISSUE TITLE
Operation just finished without running.

### ISSUE THREAD

**Issue by sulaimanbale** [mitre/caldera#643]
![image](https://user-images.githubusercontent.com/46603663/67451979-8032a800-f654-11e9-95c9-947041dffa44.png)

Hi everyone, after using the operations, it does not run. I am not sure why.

**Comment by privateducky** [comment]
looking at your screenshot, it looks like your agent is "untrusted". An agent is trusted by default and then moves to untrusted if there is an interruption to it's normal beaconing time. 

you can either:

1. restart your agent to restore it's trust
2. mark the agent as trusted in the chain mode GUI (agent section)
3. start your operation, allowing it to use untrusted agents

**Comment by privateducky** [comment]
closing as solution is posted
