### ISSUE TITLE
Mimikatz

### ISSUE THREAD

**Issue by sulaimanbale** [mitre/caldera#644]
I bellive that the mimikatz attack is not working. Kindly help. Alredy placed a mimikataz in the c:/user/  directories.

![image](https://user-images.githubusercontent.com/46603663/67470039-b5a0bb00-f67f-11e9-851a-07e867bd6c14.png)

**Comment by privateducky** [comment]
can you click the star icon (in your screenshot) to show the error message?

**Comment by privateducky** [comment]
it looks like the command (in the ability) is "invoke-mimikittenzmimikatz.exe" and what it should be is "invoke-mimikittenz". Can you try changing the ability file to this?

**Comment by sulaimanbale** [comment]
ok sure ill update

**Comment by sulaimanbale** [comment]
May i know where is the directory to find this mimikatz so that i can change ?

**Comment by sulaimanbale** [comment]
![image](https://user-images.githubusercontent.com/46603663/67613132-a420f580-f7dc-11e9-8726-912b5c17d6b0.png)

**Comment by sulaimanbale** [comment]
Is it this?

**Comment by khyberspache** [comment]
You're trying to run two different tools.  MimiKatz != MimiKittenz

**Comment by sulaimanbale11** [comment]
Okay thank you, any chances of you knowing which module to use to dump credentials from a windows server ?

**Comment by privateducky** [comment]
credential dumping can occur through a lot of different mechanism. we don't want to give too much advice in which module to use, as there is such variance based on your objectives ;) 

Closing this ticket as it seems the main solution is solved.
