### ISSUE TITLE
Need Help: Using parameters from a previous step

### ISSUE THREAD

**Issue by korgull** [mitre/caldera#66]
I am writing a step that will perform a password spray attack on computers that are found in the domain using the `GetComputers` step.  The postproperties of the `GetComputers` step is the `host_g` variable and the `os_version`.  I've been grepping the codebase for some insight, but it's not yet clear to me what all is available.  In this case, I want the netbios names so I can perform `net use` password spray attacks on the other computers in the domain.  

How would I go about passing parameters created from `GetComputers` to the password spraying attack step?

Thanks

**Comment by korgull** [comment]
I figured this one out.  As it turns out, supplying:

```
preconditions = [("rat", OPRat),
                     ("dest_host", OPHost),
                     ('host', OPHost(OPVar("rat.host")))]
```

Allows me to send Net Use commands to the hosts identified from `GetComputers`.  Simply by using the top level `dest_host` variable in the code

```
    @staticmethod
    def description(rat, host, dest_host):
        return "Launching password spray attack on {}'s C$ network share via net use from {}".format(dest_host.hostname, rat.host.hostname)
```

Showed me which database value to use - which was `hostname`.

This ticket is closed for me.

**Comment by dm-mitre** [comment]
Glad you figured it out @korgull . One followup item, the objects and properties that are available are listed in caldera/app/engine/objects.py For example The `OPHost` object schema is here; https://github.com/mitre/caldera/blob/e52c1a62dce6765cbb31c8e0be86542f4aa1c201/caldera/app/engine/objects.py#L211 

The classes with the `Observed` prefix are the ones that you can access from the steps (replace `Observed` with `OP`)

**Comment by korgull** [comment]
Ah.  Replacing Observed with OP clarifies a lot.  Thanks!
