### ISSUE TITLE
EXPLODE operation: list index out of range

### ISSUE THREAD

**Issue by sunaeb** [mitre/caldera#681]
Hi 
Could you please check this issues, I'm getting this error very often when I want to use "Chain".

500 Internal Server Error
Server got itself in trouble

And local server logs look like that:

ERROR:data_svc:[!] EXPLODE operation: list index out of range
Traceback (most recent call last):
  File "/opt/caldera/caldera/app/service/operation_svc.py", line 52, in run
    planner = await self._get_planning_module(operation[0])
TypeError: 'NoneType' object is not subscriptable
ERROR:data_svc:[!] EXPLODE operation: list index out of range
DEBUG:root:[!] rest_core: 'NoneType' object is not iterable
DEBUG:root:[!] rest_core: 'NoneType' object is not iterable
ERROR:data_svc:[!] EXPLODE operation: list index out of range
ERROR:data_svc:[!] EXPLODE operation: list index out of range
ERROR:data_svc:[!] EXPLODE operation: list index out of range

**Comment by privateducky** [comment]
closing as solution is above.
