### ISSUE TITLE
I can't find conf.yml

### ISSUE THREAD

**Issue by soph2** [mitre/caldera#70]
I tried to install CALDERA agent after CALDERA server Installation. But I can't find conf.yml at 
`https://my-caldera-server:8888/conf.yml`.
If I connect this page, there is this error.
![image](https://user-images.githubusercontent.com/44008261/46704080-f05acf80-cc85-11e8-8c30-d5b1f8e35e13.png)

1. How can I do connect this page?
CALDERA server is on Ubuntu, CALDERA agent is on Windows7 ultimate.

2. Is it possible to install Visual C++ Redistributable for Visual Studio 2015 x86 on 64-bit windows?

**Comment by qq854051086** [comment]
1. Perhaps you can try replacing "my-caldera-server" with "192.168.1.50" addresses like this. Here's the caldera server IP address, such as "https://192.168.1.50:8888/conf.yml".

2. And "caldera agent" is best installed on win8.1, the ISO image can be downloaded from Microsoft official, the specific process is more cumbersome. But it will be more convenient than win7.

The agent needs three things to run, the first two I listed, and the third (framework 3.5) needs to be installed with an ISO image
![image](https://user-images.githubusercontent.com/38556416/46721035-b0efab80-cca4-11e8-8ae5-41be56d65e97.png)

**Comment by cl-mitre** [comment]
As qq854051086 pointed out, the url for the conf.yml page needs to have the IP address of the target server in place of "my-caldera-server",  unless you have DNS set up (if you don't know what this is, you do not have DNS set up). 

To answer your second question, yes, it is possible to install any version of the VS C++ redistributable on any recent version of Windows, though some dependencies may be required before doing so depending on your chosen flavor of Windows. If you are running into a specific issue with setting up agents, @spoh2, reply back and I'll try to help you further.

**Comment by workandresearchgithub** [comment]
Recommend for closure.
