### ISSUE TITLE
Powerkatz

### ISSUE THREAD

**Issue by sulaimanbale** [mitre/caldera#713]
After running successfully powerkatz, in the json report there is no hash found. Is this a problem?

**Comment by sulaimanbale** [comment]
![image](https://user-images.githubusercontent.com/46603663/68181818-a0a71e80-ffd3-11e9-9d13-c758c777258f.png)

**Comment by sulaimanbale** [comment]
Where are the hashes ?

**Comment by privateducky** [comment]
when you download a report, you'll want to include 'agent output' as part of the download to see the actual shell output for each command. 

alternatively, you can click the star icon next to the corresponding row (in the timeline that populates during a running operation) to see the output from the mimikatz ability.

**Comment by sulaimanbale** [comment]
![image](https://user-images.githubusercontent.com/46603663/68239076-52326800-0045-11ea-84d5-d6a761506841.png)
Where can i get 'agent output' ?

**Comment by wbooth** [comment]
@sulaimanbale you can get the output in the downloadable report, just click 'Download' on the left side

**Comment by wbooth** [comment]
also ensure that you are on the latest code as it was in and out and back in during the recent refactor

**Comment by sulaimanbale** [comment]
okay thank you! However, downlaoding does not give me the hashes of passwords.

**Comment by privateducky** [comment]
when you downloaded the operation report (after the operation completed), you should see an output for every ability that was run. if you look at the output related to the PowerKatz ability, what do you see?

**Comment by sulaimanbale** [comment]
![image](https://user-images.githubusercontent.com/46603663/68352833-ac652300-0142-11ea-9914-d63c4372a79e.png)


There is no output as seen.

**Comment by privateducky** [comment]
you'll want to download with agent output (when you're on the reports modal, you'll see that option when you download). by default, the report will not include the output from each command.

**Comment by sulaimanbale** [comment]
okay thank you!
