### ISSUE TITLE
How can i download scripts from local host instead of github scripts.

### ISSUE THREAD

**Issue by sulaimanbale** [mitre/caldera#717]
![image](https://user-images.githubusercontent.com/46603663/68263902-2c778400-0082-11ea-90c4-d5fe5457eb57.png)

Since my agent does not have an internet connection, i wish to host the scripts on my local server. How can i do it ? Kindly help. Currently it is fetching scripts from github, wish i dont wish to do it.

**Comment by privateducky** [comment]
Read the "What is an ability?" documentation page: https://github.com/mitre/caldera/wiki/What-is-an-ability

In here, pay specific attention to the payload option you can put inside an ability file.

**Comment by sulaimanbale** [comment]
Thank you ! Manange to make it work. Closing issue.

**Comment by zorovj** [comment]
Hello,
I have been facing the same issue and I did not understand the documentation part for it. Can you please explain clearly how to store the payloads on the server and download it from there. Can I do it from the GUI? Currently I don't see any payloads in the 'payloads' directory on my server so how does it work if I add a payload from the GUI option into an ability. Where does it get it from?

Thanks!

**Comment by clenk** [comment]
Hi @zorovj, you can put your own payloads in the payloads directory, but the built-in payloads come from plugins, mostly [stockpile](https://github.com/mitre/stockpile/tree/master/payloads).

The documentation information referenced above has moved here (scroll down to the `Payload` section): https://caldera.readthedocs.io/en/latest/Basic-Usage.html#abilities
