### ISSUE TITLE
Running error 0 abilities

### ISSUE THREAD

**Issue by sulaimanbale** [mitre/caldera#718]
![image](https://user-images.githubusercontent.com/46603663/68268114-eb866c00-008f-11ea-96ab-5c21002ee1a0.png)

Kindly help ! Installed on local host using guide provided by did not work.

**Comment by privateducky** [comment]
it looks like your plugins are out of date. 

we did quite a bit of refactoring of the data store last weekend, so if you're trying to follow the bleeding-edge code, you should get a fresh clone of the code base. 

otherwise, I'd recommend using the latest stable release (2.3.2).

**Comment by sulaimanbale** [comment]
okay thank you
