### ISSUE TITLE
Sandcat / caagent.exe

### ISSUE THREAD

**Issue by sulaimanbale11** [mitre/caldera#745]
Hi,

Is there any way to hide this process as i shows IOC in process explorer or such ? The main reason is to not give any IOCs to blue team

**Comment by sulaimanbale** [comment]
or how can we allow caldera to leave traces/IOCs in the victim machines ?

**Comment by privateducky** [comment]
deploying Sandcat into an environment to hide from the defense is out of scope for what we do in this project. There are a number of techniques out there to assist with hiding processes on machines, which is a field of study in itself. These concepts tend to be agnostic to any command-and-control system (like CALDERA). 

good luck!

**Comment by sulaimanbale** [comment]
Thank you !! Can you close the issue.

**Comment by sulaimanbale11** [comment]
Thank you !!
