### ISSUE TITLE
error when running pip install -r requirements.txt

### ISSUE THREAD

**Issue by bilzerian** [mitre/caldera#747]
Traceback (most recent call last):
       File "usr/bin/pip", line 11, in <module>
           sys.exit(main())
TypeError:'module' object is not callable 

Attempting the install on kali.
I have rebooted a few times and tried going thru the file and installing manually. please advise

**Comment by brianedmonds90** [comment]
This is a python issue vs a Caldera issue. What version of python are you using? Also sometimes it's helpful to try `python -m pip install -r requirements.txt` when pip isn't working the way you think.

**Comment by bilzerian** [comment]
Got a different error,  but i was messing with a few files going to try from scratch and follow up. was giving me a pip message saying i needed to update

**Comment by bilzerian** [comment]
This is resolved but getting error when building cryptography. able to install manually. going to close this and see if others had this issue
