### ISSUE TITLE
Negative time.sleep() value resulting from jitter > delay

### ISSUE THREAD

**Issue by an4tman** [mitre/caldera#75]
```
[...]
  file "/usr/local/bin/caldera/app/operation/operation.py", line 605, in job_delay
    time.sleep(wait_time / 1000)
ValueError: sleep length must be non-negative
```

I haven't had a chance to dig into the code yet, but my guess is that there's no check for `wait_time` becoming negative if the "jitter" value is greater than the "delay" value.

**Comment by cl-mitre** [comment]
Good catch, you're exactly right. The change you made in your MR should work as a stop gap, thought I'm hesitant to merge it into the repository at large due to an upcoming major update. Once that update comes through, we should be able to implement a fix for everyone.

**Comment by an4tman** [comment]
👍 cool, looking forward to the update!

**Comment by privateducky** [comment]
closing but @an4tman feel free to submit an MR against the adversary plugin if this continues to persist.
