### ISSUE TITLE
caldera discovering new devices and performing attacks on them

### ISSUE THREAD

**Issue by sulaimanbale** [mitre/caldera#756]
Hi,

Is caldera able to find new devices eg; from the same domain, IP address and plant agents into them so that attacks can be performed on those devices?

An example is initial access in a  client PC, I will lateral move to the DC, may I know how to do this in caldera and then perform credential dumping on the dc. Agent is only installed on pc , not DC. How can I lateral move to DC using Caldera?

Please explain if yes how to do it.

**Comment by privateducky** [comment]
you would need to build an adversary profile that has abilities to discover information and then laterally move. 

a good example of this is our built-in "worm" adversary, which discovers information through a variety of abilities, then it uses those abilities to laterally move.

**Comment by sulaimanbale** [comment]
thank you
