### ISSUE TITLE
CALDERA copy sandcat file failed to beacon - lateral movement

### ISSUE THREAD

**Issue by sulaimanbale** [mitre/caldera#762]
![image](https://user-images.githubusercontent.com/46603663/68742905-37a35480-062c-11ea-94e0-57ffe9d19f7e.png)

After doing the following command - becon failed and show it is dead ? any fixes ?

**Comment by sulaimanbale** [comment]
Another solution tried

![image](https://user-images.githubusercontent.com/46603663/68744924-9e2a7180-0630-11ea-9ecf-e58b338c48bd.png)


This sandcat was origanlly downlaoded by the server and was working. When i try invoking using PsExec it failed.

**Comment by khyberspache** [comment]
You need to provide a `-server <target_ip` flag to sandcat

**Comment by sulaimanbale** [comment]
okay thank you!!
