### ISSUE TITLE
attack.py API issue

### ISSUE THREAD

**Issue by atg53** [mitre/caldera#79]
Line 8 of https://github.com/mitre/caldera/blob/master/caldera/app/attack.py references an outdated API url. I noticed Issue #75 referenced a major update, is there a predicted release date of the update, and will that incorporate the new API?

**Comment by hf-mitre** [comment]
Hi @atg53 ,  

Unfortunately, we don't have a planned specific release data for the update.  The timeframe is probably sometime in the next few weeks. 

The good news: the update will address the API changes for the new ATT&CK site.  In the meantime, we can point https://github.com/mitre/caldera/blob/master/caldera/app/attack.py#L8 at https://attack-old.mitre.org and it should work again.  I'd change the url myself right now, but I'm not in the position to easily try it out and make sure it works.

**Comment by hf-mitre** [comment]
Temp fix of using attack-old.mitre.org should be addressed by: 
13ebab8e97c3ba0e6c86ffc967d4c9e1bf292cfb and 63e50b9629b9a78b5a279891300721d5dd4311ea

Looks like this and #85 were duplicates.
