### ISSUE TITLE
launching sandcat.exe

### ISSUE THREAD

**Issue by sulaimanbale** [mitre/caldera#790]
Hi,

I am able to download sandcat file and edit its file type as a exe.  After clicking it it shows not established.

![image](https://user-images.githubusercontent.com/46603663/69219798-9299f600-0bae-11ea-90f1-737470635632.png)

How do i allow it to connect to my server?

**Comment by privateducky** [comment]
to start Sandcat by double-clicking, you'll need to download the agent by passing in the correct server as a header.

check out the section titled "Customizing Default Options & Execution Without CLI Options" on the sandcat Wiki page:

https://github.com/mitre/caldera/wiki/Plugins-sandcat

**Comment by sulaimanbale11** [comment]
Yes, how do I do it on a windows GUI level ?

**Comment by sulaimanbale** [comment]
The current scenrio i am seeing is that a user clicks the sandcat.exe and it automatically connect to Caldera C2. Any helps ?

**Comment by ramus82** [comment]
> The current scenrio i am seeing is that a user clicks the sandcat.exe and it automatically connect to Caldera C2. Any helps ?

You can compile the sandcat from updated source file. There is a default values hardcoded. If you change them the execution of the sandcat.exe without arguments might work.

**Comment by sulaimanbale11** [comment]
How do I do it?

Thank you. 

Regards,
Sulaiman

**Comment by privateducky** [comment]
checkout the link I posted earlier-- you just need to download an agent with the right server location included as the defaultServer header:
```
curl -sk -X POST -H 'file:sandcat.go' -H 'platform:windows' -H 'defaultServer:http://localhost:8888' http://localhost:8888/file/download
```

**Comment by privateducky** [comment]
closing - answered above.
