### ISSUE TITLE
operation error

### ISSUE THREAD

**Issue by J4son** [mitre/caldera#8]
DEBUG:app.operation.operation:starting operation
INFO:app.operation.operation:Writing commander to: 'C:\commander.exe'
WARNING:app.operation.operation:Error on bootstrap: ('AgentExceptionError', 'Tra
ceback (most recent call last):\n  File "C:\\Users\\lpc\\Desktop\\caldera\\calde
ra-agent\\caldera_agent\\async_client.py", line 117, in run_job\n    success, re
sult = await self.interface.run(action, args)\n  File "C:\\Users\\lpc\\Desktop\\
caldera\\caldera-agent\\caldera_agent\\interfaces.py", line 64, in run\n    outp
ut = await self._write_commander(args[\'path\'])\n  File "C:\\Users\\lpc\\Deskto
p\\caldera\\caldera-agent\\caldera_agent\\interfaces.py", line 111, in _write_co
mmander\n    return await self._run_in_caldera_subprocess("takeown /F {} /A".for
mat(path))\n  File "C:\\Users\\lpc\\Desktop\\caldera\\caldera-agent\\caldera_age
nt\\interfaces.py", line 120, in _run_in_caldera_subprocess\n    return stdout.d
ecode()\nUnicodeDecodeError: \'utf-8\' codec can\'t decode byte 0xb3 in position
 2: invalid start byte\n', <Job: {'status': 'failed', 'action': {'write_commande
r': {'path': 'C:\\commander.exe'}, 'exception': 'Traceback (most recent call las
t):\n  File "C:\\Users\\lpc\\Desktop\\caldera\\caldera-agent\\caldera_agent\\asy
nc_client.py", line 117, in run_job\n    success, result = await self.interface.
run(action, args)\n  File "C:\\Users\\lpc\\Desktop\\caldera\\caldera-agent\\cald
era_agent\\interfaces.py", line 64, in run\n    output = await self._write_comma
nder(args[\'path\'])\n  File "C:\\Users\\lpc\\Desktop\\caldera\\caldera-agent\\c
aldera_agent\\interfaces.py", line 111, in _write_commander\n    return await se
lf._run_in_caldera_subprocess("takeown /F {} /A".format(path))\n  File "C:\\User
s\\lpc\\Desktop\\caldera\\caldera-agent\\caldera_agent\\interfaces.py", line 120
, in _run_in_caldera_subprocess\n    return stdout.decode()\nUnicodeDecodeError:
 \'utf-8\' codec can\'t decode byte 0xb3 in position 2: invalid start byte\n', '
error': 'agents exception'}, 'agent': ObjectId('5a38dc49344fa2139ca6638b'), 'cre
ate_time': datetime.datetime(2017, 12, 19, 9, 37, 26, 111000, tzinfo=<bson.tz_ut
il.FixedOffset object at 0x00000000042BADA0>), '_id': ObjectId('5a38ddd6344fa20a
08c04c46')}>)
INFO:app.operation.operation:Operation complete: Error on bootstrap: ('AgentExce
ptionError', 'Traceback (most recent call last):\n  File "C:\\Users\\lpc\\Deskto
p\\caldera\\caldera-agent\\caldera_agent\\async_client.py", line 117, in run_job
\n    success, result = await self.interface.run(action, args)\n  File "C:\\User
s\\lpc\\Desktop\\caldera\\caldera-agent\\caldera_agent\\interfaces.py", line 64,
 in run\n    output = await self._write_commander(args[\'path\'])\n  File "C:\\U
sers\\lpc\\Desktop\\caldera\\caldera-agent\\caldera_agent\\interfaces.py", line
111, in _write_commander\n    return await self._run_in_caldera_subprocess("take
own /F {} /A".format(path))\n  File "C:\\Users\\lpc\\Desktop\\caldera\\caldera-a
gent\\caldera_agent\\interfaces.py", line 120, in _run_in_caldera_subprocess\n
  return stdout.decode()\nUnicodeDecodeError: \'utf-8\' codec can\'t decode byte
 0xb3 in position 2: invalid start byte\n', <Job: {'status': 'failed', 'action':
 {'write_commander': {'path': 'C:\\commander.exe'}, 'exception': 'Traceback (mos
t recent call last):\n  File "C:\\Users\\lpc\\Desktop\\caldera\\caldera-agent\\c
aldera_agent\\async_client.py", line 117, in run_job\n    success, result = awai
t self.interface.run(action, args)\n  File "C:\\Users\\lpc\\Desktop\\caldera\\ca
ldera-agent\\caldera_agent\\interfaces.py", line 64, in run\n    output = await
self._write_commander(args[\'path\'])\n  File "C:\\Users\\lpc\\Desktop\\caldera\
\caldera-agent\\caldera_agent\\interfaces.py", line 111, in _write_commander\n
  return await self._run_in_caldera_subprocess("takeown /F {} /A".format(path))\
n  File "C:\\Users\\lpc\\Desktop\\caldera\\caldera-agent\\caldera_agent\\interfa
ces.py", line 120, in _run_in_caldera_subprocess\n    return stdout.decode()\nUn
icodeDecodeError: \'utf-8\' codec can\'t decode byte 0xb3 in position 2: invalid
 start byte\n', 'error': 'agents exception'}, 'agent': ObjectId('5a38dc49344fa21
39ca6638b'), 'create_time': datetime.datetime(2017, 12, 19, 9, 37, 26, 111000, t
zinfo=<bson.tz_util.FixedOffset object at 0x00000000042BADA0>), '_id': ObjectId(
'5a38ddd6344fa20a08c04c46')}>)
DEBUG:app.api:websocket connection closed

Is caldera run correct？

**Comment by dm-mitre** [comment]
This is definitely a bug. In the operation view there should be a tab called "Jobs", can you find that and paste the content here?

**Comment by J4son** [comment]
[
  {
    "_id": "5a38e666344fa20a08c04c4b",
    "agent": "5a38dc49344fa2139ca6638b",
    "action": {
      "clients": {},
      "result": []
    },
    "create_time": "2017-12-19T10:13:58.036Z",
    "status": "success"
  },
  {
    "_id": "5a38e666344fa20a08c04c4c",
    "agent": "5a38dc49344fa2139ca6638b",
    "action": {
      "write_commander": {
        "path": "C:\\commander.exe"
      },
      "error": "agents exception",
      "exception": "Traceback (most recent call last):\n  File \"C:\\Users\\lpc\\Desktop\\caldera\\caldera-agent\\caldera_agent\\async_client.py\", line 117, in run_job\n    success, result = await self.interface.run(action, args)\n  File \"C:\\Users\\lpc\\Desktop\\caldera\\caldera-agent\\caldera_agent\\interfaces.py\", line 64, in run\n    output = await self._write_commander(args['path'])\n  File \"C:\\Users\\lpc\\Desktop\\caldera\\caldera-agent\\caldera_agent\\interfaces.py\", line 111, in _write_commander\n    return await self._run_in_caldera_subprocess(\"takeown /F {} /A\".format(path))\n  File \"C:\\Users\\lpc\\Desktop\\caldera\\caldera-agent\\caldera_agent\\interfaces.py\", line 120, in _run_in_caldera_subprocess\n    return stdout.decode()\nUnicodeDecodeError: 'utf-8' codec can't decode byte 0xb3 in position 2: invalid start byte\n"
    },
    "create_time": "2017-12-19T10:13:58.123Z",
    "status": "failed"
  }
]
This is "Jobs" info. 
"Cleanup Log" always show error.

**Comment by dm-mitre** [comment]
I think this may be related encoding types. @J4son Is your computer set to a language that is not english?

**Comment by J4son** [comment]
@dm-mitre Uh, I use windows with Chinese. Maybe this reason?

**Comment by J4son** [comment]
@dm-mitre I change language and test again, still same error

**Comment by dm-mitre** [comment]
That might be the reason. We'll have to look into this.

**Comment by J4son** [comment]
@dm-mitre I check your code, maybe you can modify code about "decode". I also try to modify code to ignore this error!

**Comment by darl0ck** [comment]
@J4son hi! How you have solve this problem ?

**Comment by dm-mitre** [comment]
@darl0ck I can't speak for J4son but I think he set his computer language to english. You're free to try this. I will also try to get a fix out that supports this better.

**Comment by darl0ck** [comment]
@dm-mitre Hi!
thx for your response
but i wanna test your utill domain with a lot of hosts and on each of it russian set's as default

**Comment by dm-mitre** [comment]
@darl0ck feel free to try this beta release https://github.com/mitre/caldera-crater/releases/tag/v0.2.0-beta

**Comment by darl0ck** [comment]
@dm-mitre the same 
  {
    "_id": "5a6ff63d1a8ace07c997ed04",
    "agent": "5a6ad2f81a8ace073e2debdb",
    "action": {
      "write_commander": {
        "path": "C:\\commander.exe"
      },
      "error": "agents exception",
      "exception": "Traceback (most recent call last):\n  File \"C:\\Gitlab Runner\\builds\\f8e514af\\0\\caldera\\caldera-agent\\caldera_agent\\async_client.py\", line 117, in run_job\n  File \"C:\\Gitlab Runner\\builds\\f8e514af\\0\\caldera\\caldera-agent\\caldera_agent\\interfaces.py\", line 64, in run\n  File \"C:\\Gitlab Runner\\builds\\f8e514af\\0\\caldera\\caldera-agent\\caldera_agent\\interfaces.py\", line 111, in _write_commander\n  File \"C:\\Gitlab Runner\\builds\\f8e514af\\0\\caldera\\caldera-agent\\caldera_agent\\interfaces.py\", line 120, in _run_in_caldera_subprocess\nUnicodeDecodeError: 'utf-8' codec can't decode byte 0x93 in position 2: invalid start byte\n"
    },
    "create_time": "2018-01-30T04:36:13.354Z",
    "status": "failed"
  }

**Comment by dm-mitre** [comment]
@darl0ck thanks, I looked a little more at this and couldn't find anything obviously wrong. I don't have a good way of testing this so I don't expect to make any progress on this soon. I'll post here if I do.

**Comment by darl0ck** [comment]
@dm-mitre mayBe it raising an error because you reading information by bytes
maybe you can youse hard decoding to text

**Comment by rtl4k** [comment]
@dm-mitre Same here, with spanish language.

  {
    "_id": "5ac37ac7c19b1946f7a6b7bf",
    "agent": "5ac338c7c19b1942053d06d8",
    "action": {
      "execute": {
        "command_line": "taskkill /pid 2360 /f"
      },
      "exception": "Traceback (most recent call last):\n  File \"C:\\Gitlab Runner\\builds\\f8e514af\\0\\caldera\\caldera-agent\\caldera_agent\\async_client.py\", line 117, in run_job\n  File \"C:\\Gitlab Runner\\builds\\f8e514af\\0\\caldera\\caldera-agent\\caldera_agent\\interfaces.py\", line 58, in run\n  File \"C:\\Gitlab Runner\\builds\\f8e514af\\0\\caldera\\caldera-agent\\caldera_agent\\interfaces.py\", line 120, in _run_in_caldera_subprocess\nUnicodeDecodeError: 'utf-8' codec can't decode byte 0xa2 in position 19: invalid start byte\n",
      "error": "agents exception"
    },
    "create_time": "2018-04-03T12:59:51.415Z",
    "status": "failed"
  }

**Comment by dm-mitre** [comment]
@rtl4k good to know there is interest in fixing this issue. I think we may have some idea of what is going on underneath the hood. I'll try to keep things updated here if we make any progress

**Comment by iMightLikeOrange** [comment]
I also have this issue, but my computer is already in English.  Is there any notable progress?

**Comment by dm-mitre** [comment]
I can't announce anything right now but we are making progress. Stayed tuned.

**Comment by DengyigeFeng** [comment]
@dm-mitre 
I also have this problem. Is there any solution now?thx

**Comment by felipetorquato** [comment]
Hey, i'm with the same issue. Is there any solution now?

**Comment by perra22** [comment]
Hi, i have this issue too. Is there any solution now? (my computer is already in English) Thanks!

**Comment by privateducky** [comment]
resolved in latest code.
