### ISSUE TITLE
tools downloading into main folder users\admin instead of given directory.

### ISSUE THREAD

**Issue by sulaimanbale** [mitre/caldera#800]
![image](https://user-images.githubusercontent.com/46603663/69325052-808a8700-0c84-11ea-9300-43c600f10a00.png)

![image](https://user-images.githubusercontent.com/46603663/69325211-c0ea0500-0c84-11ea-9689-b068e6da08e3.png)

Tools are being dropped in C:\Users\Administrator but not at the given location. How to fix ?

**Comment by khyberspache** [comment]
Payloads will only download to the directory the agent is running in. You can use a `mv` or `Move-Item` command to move it to the directory you want to execute from.

**Comment by sulaimanbale** [comment]
okay thank you
