### ISSUE TITLE
Server.py issue when starting caldera.py

### ISSUE THREAD

**Issue by dnice77** [mitre/caldera#84]
Traceback (most recent call last):
  File "caldera.py", line 16, in <module>
    from app import server
  File "/home/dbohatec/caldera/caldera/caldera/app/server.py", line 139
    async def heartbeat_init():
            ^
SyntaxError: invalid syntax

**Comment by omergunal** [comment]
Which python version are you using? Please try with Python version greater than 3.0

**Comment by hf-mitre** [comment]
Specifically 3.5+.   The `async` keyword was added to Python in 3.5.

**Comment by dnice77** [comment]
root@ubuntu:/home/dbohatec/caldera/caldera/caldera# python3.6 caldera.py 
Traceback (most recent call last):
  File "caldera.py", line 16, in <module>
    from app import server
  File "/home/dbohatec/caldera/caldera/caldera/app/server.py", line 315
    © 2018 GitHub, Inc.
    ^
SyntaxError: invalid character in identifier

**Comment by omergunal** [comment]
There is no line like that "© 2018 GitHub, Inc." in server.py.  Are you sure you downloaded it correctly?

**Comment by blakehooks** [comment]
> root@ubuntu:/home/dbohatec/caldera/caldera/caldera# python3.6 caldera.py
> Traceback (most recent call last):
> File "caldera.py", line 16, in 
> from app import server
> File "/home/dbohatec/caldera/caldera/caldera/app/server.py", line 315
> © 2018 GitHub, Inc.
> ^
> SyntaxError: invalid character in identifier

That issue would occur if you copied the file contents directly from the page, and accidentally copied the GitHub copyright onto a 315th line. (server.py should only be 314 lines long)

**Comment by workandresearchgithub** [comment]
Recommend you close this issue.
