### ISSUE TITLE
Help needed - xored files

### ISSUE THREAD

**Issue by fakoh** [mitre/caldera#869]
Hi,
under `caldera\plugins\stockpile\payloads` there are files `powerview.ps1.xored` and `invoke-mimi.ps1.xored`. 

Also, `.gitignore` in stockpile contains section:
```
# ignore bc av will wipe
payloads/PowerView.ps1
```
To me, this means you have already implemented a way to load files to Sandcat in-memory so that they do not get flagged by AV. But I have not found any piece of documentation on this feature.

My questions:
- if I specify a file named `FILE` in `payloads:` section of an ability, then I can supply `FILE.xored` in `/payloads` and it will work, right?
- how to convert a file (script/executable) to this .xored version?

Thanks.

**Comment by privateducky** [comment]
good questions. 

I just went ahead and appended some documentation around this XOR utility on our ability wiki page: https://github.com/mitre/caldera/wiki/What-is-an-ability. Check out the section on payloads.

Let me know what questions you have after reading that.
