### ISSUE TITLE
cmd.move uses the wrong slashes, causing steps like service_manipulation(sc file replace) to fail

### ISSUE THREAD

**Issue by trallgorm** [mitre/caldera#88]
Just wanted to let you know of an issue I've found, the service_manipulation(sc file replace) step kept failing for me on a Windows 10 victim because it said the path could not be found. Digging into it, it creates the .bak file by moving the old service binary file to it using cmd /c move but it uses \ instead of / in the path which for some reason doesn't work with the move command. 

I fixed it by going to cmd.py and changing the slashes in the move method as well as the delete method which has the same issue. I can submit a pull request if you'd like.

**Comment by privateducky** [comment]
@trallgorm that would be great!
