### ISSUE TITLE
About host discover

### ISSUE THREAD

**Issue by J4son** [mitre/caldera#9]
Hey,bro!
I changed my system with English region, and caldera run well. But another problem troubled me. I have one agent and one "client computer" for test, all computer join the same AD. When I create network, I just find agent, "client computer" is miss. Was my operation wrong?

**Comment by dm-mitre** [comment]
Computers that you install an agent on should appear in the create network page. If there is a computer that is missing, the agent may not be installed properly, or there may be a communication problem between the agent and the caldera server.

**Comment by J4son** [comment]
@dm-mitre I'm confused. Is "caldera" can test enterprise network? If I want to test defenses and security configurations, should I install agent to all computers in network?

**Comment by dm-mitre** [comment]
Install the agent on the computers that you want to test. At this time we only suggest testing 10-15 computers in a network.
