### ISSUE TITLE
Multiple hosts networks

### ISSUE THREAD

**Issue by RalucaPreda** [mitre/caldera#906]
Hi, while using Adversary mode in v. 2.1, can't seem to be able to run operations on networks with multiple hosts, as steps only get run on the start host.

**Comment by privateducky** [comment]
we're no longer actively supporting adversary mode-- this plugin will soon be deprecated. I would advise you to start using our main operational mode (chain) instead. we're getting ready to cut our 2.4.0 release in a few days, which will have some of the same adversaries from adversary mode available in chain mode.

**Comment by RalucaPreda** [comment]
Thank you for your answer, but considering this version was tagged not so long ago, do you remember this being an issue or a reason why that would happen?

**Comment by privateducky** [comment]
I don't recall that being an issue-- but let me tag @cl-mitre and @unkempthenry to see if they recall. Have you tried reverting to 2.0 and seeing if that worked? Since we did 2.0, we haven't done a significant amount of work on adversary mode, mainly small bug fixes/tweaks.

**Comment by RalucaPreda** [comment]
Thank you. No, I reverted to 2.1 since 2.2 was not tagged at the moment and I had some issues running the plugin.
