### ISSUE TITLE
Add a phase to a new adversary after creating it without phases

### ISSUE THREAD

**Issue by w4rguy** [mitre/caldera#972]
I was running some testing with caldera. I created a new adversary through the web interface and did not at a phase to the adversary yet. It's impossible to add a phase to the adversary if it does not yet have any phases defined to it.

I think it would be useful as a feature if that could be added to the frontend.

**Comment by privateducky** [comment]
Agreed. We’ll add that in.

**Comment by privateducky** [comment]
@w4rguy I made the change to allow this:" https://github.com/mitre/caldera/pull/973/files

I ran a couple of tests and it seems to work ok. let me know if you notice any issues.
