### ISSUE TITLE
suggestions for auto-installer.sh information improvment

### ISSUE THREAD

**Issue by Karlosse** [mitre/caldera#987]
Hi,
I find there is an inconsistency in the auto-installer.sh information which get displayed.
Indeed, at the Go installation step, I got:
**[-] Checking for GO**
which: no go in (/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/root/bin)
[-] Installing GO
#[..] Updating the OS: OK
--timestamp-- https://dl.google.com/go/go1.13.linux-amd64.tar.gz
Connection to <my_proxy>... connected.
Proxy tunneling failed: ForbiddenUnable to estalblish SSL connection.
**[+] GO installed**

As I was not reading things properly, I obviously just saw "GO installed" and didn't understand at first what was wrong then with go.
Maybe an improvement could be made to prompt an error when the installation steps doesn't go properly.
I was even running server.py and not getting that I had an error with completing the requirements.
I was not understanding what was wrong ill I restarted installation process.

Anyway, thanks for your work.
It is great.

**Comment by wbooth** [comment]
Thanks for the feedback. We’ll take a look at improving the auto installer messaging. If you have ideas for changes feel free to open a PR even if it’s a WIP type suggestion. Glad you are enjoying it.

**Comment by privateducky** [comment]
@Karlosse I'd second what @wbooth said -- I think you have a good point. if you can, fork CALDERA then submit a pull request with these changes.

**Comment by privateducky** [comment]
now merged.
